### ISSUE TITLE
Splitting the project into different DLLs and NuGet packages

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#10]
The idea of splitting up MonoGame.Extended into a few different DLL's and NuGet packages has come a up a few times. I think this is a good idea in principle, but it's also a complex issue. 

Let's discuss how the project should be split up and the pros and cons of each option. Initially the primary goal is to keep 3rd party dependencies out of the core library.

Currently, the project is structured like this:

- `MonoGame.Extended.dll` is the core PCL library and has dependencies on the PCL version of MonoGame and Newtonsoft.Json.
- `MonoGame.Extended.Content.Pipeline.dll` is a normal .NET 4 DLL that has dependencies on MonoGame.Extended, Newtonsoft.Json and TiledSharp. This DLL is intended to be referenced by the MonoGame Pipeline tool.

**Comment by WardBenjamin** [comment]
I personally agree that there should be no more additional DLL's to manage apart from these two unless we add some feature-set (outside of the content DLL) that uses code external to our project or depends on such code, in which case it should be separated into it's own optional DLL. This would maintain a very clean DLL structure, rather than having to worry about a DLL for each and every section of MonoGame.Extended.

**Comment by craftworkgames** [comment]
Thanks @WardBenjamin. I can see how this issue might cause some polarity so I'm hoping a few more people weigh into the discussion.

**Comment by craftworkgames** [comment]
I've been thinking a bit about how to structure the project into different namespaces. The approach I've  been tossing around is to break the code up into *feature* based namespaces. For example:

`MonoGame.Extended.Sprites`
`MonoGame.Extended.BitmapFonts`
`MonoGame.Extended.ViewportAdapters`
`MonoGame.Extended.InputListeners`

etc.

This approach works pretty well for the most part. I'm not sure if every class fits into that structure though. Some classes like `Camera2D` might simply fall into the root namespace `MonoGame.Extended` perhaps.

The other thing I've been thinking about is how some features can have multiple *variations* so to speak. For example, there could be 2 flavors of tile based maps (Tiled and tIDE). Since these *might* share some code, they probably belong in sub-namespaces of a `Maps` namespace.

`MonoGame.Extended.Maps`
`MonoGame.Extended.Maps.Tiled`
`MonoGame.Extended.Maps.Tide`

@WardBenjamin @ClassicThunder Thoughts?

**Comment by craftworkgames** [comment]
I'm pretty happy with the way the project is structured in the version 0.2 release. This is always open for discussion, but I'm going to close this issue.
