### ISSUE TITLE
Sprite Extension not working as extension when called from Visual Basic

### ISSUE THREAD

**Issue by beppe9000** [craftworkgames/MonoGame.Extended#101]
MonoGame.Extended/Source/MonoGame.Extended/Sprites/SpriteExtensions.cs 

The extension methods here are not seen/recognized as extension methods, forcing me to call SpriteExtensions.Draw(myspritebatch, mysprite) instead of mysprite.draw(myspritebatch)...

Is there any workaround/solution?

**Comment by craftworkgames** [comment]
It works the other way around. The extension method is on `SpriteBatch` not `Sprite`. It's intended to work like this:

    myspritebatch.Draw(mysprite);

I guess the name of the `SpriteExtensions` class is a little misleading. We should probably rename it to `SpriteBatchExtensions` to make it clear. Obviously it'll still live in the `Sprites` namespace so it won't clash with other extensions.

**Comment by beppe9000** [comment]
Thanks! Wow, it seemed so natural to ask a sprite to draw itself that i didn't even double check it... I think you should mirror those extensions to the Sprite class, just in case :)

**Comment by craftworkgames** [comment]
> I think you should mirror those extensions to the Sprite class, just in case :)

I guess there's no harm in this if there's simply another extension method that reverses the parameters.

        public static void Draw(this Sprite sprite, SpriteBatch spriteBatch)
        {
            Draw(spriteBatch, sprite);
        }

        public static void Draw(this SpriteBatch spriteBatch, Sprite sprite)
        {
            if (sprite == null) throw new ArgumentNullException(nameof(sprite));

            if (sprite.IsVisible)
            {
                var texture = sprite.TextureRegion.Texture;
                var sourceRectangle = sprite.TextureRegion.Bounds;

                spriteBatch.Draw(texture, sprite.Position, sourceRectangle, sprite.Color, sprite.Rotation, sprite.Origin,
                    sprite.Scale, sprite.Effect, 0);
            }
        }

**Comment by beppe9000** [comment]
Cool! You fixed a spot for dumb errors!
