### ISSUE TITLE
[Tiled] Tiled Map support for "Collection of Images"

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#102]
This issue came about because of a bug [raised on the forums](http://community.monogame.net/t/content-pipeline-cant-build-tmx-files/6941/3).
### The Problem

The good news is that I managed to reproduce the issue and I understand the problem now :smile:

It turns out that MonoGame.Extended doesn't currently support "Collection of Images" for tilesets.

![image](https://cloud.githubusercontent.com/assets/3201643/12739235/4c0b3c6c-c9b3-11e5-9cf6-5d929af20c3b.png)

The workaround for the moment is to change your tilesets to be "Based on Tilset Image". Something like this:

![image](https://cloud.githubusercontent.com/assets/3201643/12739237/4f30f0da-c9b3-11e5-9d39-096fca28dce7.png)

Unfortunately, you'll also need to delete the broken tilsets and this will mean you'll have to recreate the map.
### So what's happening under the hood?

When you save a "Collection of Images" tilset the XML looks like this:

```
<tileset firstgid="2" name="basictile" tilewidth="32" tileheight="32" tilecount="1" columns="0">
  <tile id="0">
   <image width="32" height="32" source="basictile.png"/>
  </tile>
</tileset>
```

When you save a "Based on Tileset Image" tileset the XML looks like this:

```
 <tileset firstgid="1" name="basictile" tilewidth="32" tileheight="32" tilecount="1" columns="1">
  <image source="basictile.png" width="32" height="32"/>
 </tileset>
```

The differences are fairly subtle at first glance but the actual cause of the issue is the way the importer is handling the "source" property.

```
if (!string.IsNullOrWhiteSpace(tileset.Source))
{
    // import tileset
}
```

The importer is expecting the "source" property to always have a value but in the case of the "Collection of Images" it will be null.
### Other issues

That explains that particular issue and points us in the right direction to fix the bug but there's a few other things that bothered me while I was investigating this.
1. The importers don't really do any logging. It's pretty difficult to debug these things as it is.
2. If something is not supported by the importer it should throw an error and fail.
3. It's still unclear to me why the MonoGame Pipeline tool is hanging.

**Comment by LithiumToast** [comment]
Does MG.Ex use some sort of logging library? Would probably be a good idea to change the Tiled map importer to throw or log a descriptive error if it can't find an expected XML property.

**Comment by craftworkgames** [comment]
> Does MG.Ex use some sort of logging library?

Not currently. I think logging has it's place, but it also carries a cost. I'm hesitant to introduce a dependency into the core library.

However, the content importers do have built in logging on the context object.

        public override TmxMap Import(string filename, ContentImporterContext context)
        {
            context.Logger.LogMessage($"Importing {filename}");

At the very least the importers should output messages to this so that they can be seen in the output window of the Pipeline tool.

> change the Tiled map importer to throw or log a descriptive error if it can't find an expected XML property.

Yes, absolutely. The importers especially should fail fast if something goes wrong. There's nothing worse than a subtle annoying bug with very little bad error messages.

**Comment by LithiumToast** [comment]
> Not currently. I think logging has its place, but it also carries a cost. I'm hesitant to introduce a dependency into the core library.

Fair enough.

> However, the content importers do have built in logging on the context object.

I didn't know about that. That's perfect for this situtation.

**Comment by craftworkgames** [comment]
I remember someone was working on this. Does it work already?

**Comment by LithiumToast** [comment]
Since this can be worked around by using tileset images I think this not really worth the time to implement correctly, especially with new rendering since this was posted. One solution would be to combine all tiles into one large texture atlas automatically using the content pipeline.

**Comment by craftworkgames** [comment]
Agreed.

**Comment by buttsj** [comment]
This thread is quite old, so my apologies for digging up an old topic. However I wanted to say that this was a huge pain to troubleshoot with the current error messages MG.Ex outputs from the Content pipeline. I had to attach the MG.Ex projects to my game in order to debug and find what the right thing was to Google search...

Not suggesting this Issue is reopened or anything, but maybe somewhere on the MG.Ex docs this issue should be highlighted. Thanks!

**Comment by craftworkgames** [comment]
> Not suggesting this Issue is reopened or anything, but maybe somewhere on the MG.Ex docs this issue should be highlighted. Thanks!

Please open a new issue with the details:
 - What where you trying to do when you had the issue?
 - What error messages are you getting?
 - What error message would you prefer?
 - How did you do to workaround the issue? (this helps other people that come across the issue)
