### ISSUE TITLE
Tiled tilesets must be in the same folder as the .tmx file

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#103]
Another issue raised on [the forums](http://community.monogame.net/t/content-pipeline-cant-build-tmx-files/6941/4?u=craftworkgames)

### Problem
I would like to place the tileset image into a different folder.

### Workaround
To make it work I just placed the tileset image at the same folder of the .tmx file.

**Comment by rafaelalmeidatk** [comment]
I solved this issue changing the tileset image path in the .tmx file, but after I figured out that the Tiled already do this automatically. So, with this simple folder structure:

![Folder structure](http://i.imgur.com/rZW0EBm.png)

You select the `basictile.png` as tileset in Tiled and the path is automatically changed to `../imgs/tilesets/basictile.png`, like that:

    <image source="../imgs/tilesets/basictile.png" width="64" height="32"/>

**Comment by craftworkgames** [comment]
Okay. So do we need to do anything or can this issue be closed?

**Comment by rafaelalmeidatk** [comment]
Can be closed, the process is all made by Tiled.

**Comment by Trebor777** [comment]
Hum be careful with this. I add the issue (and fixed it) using Nez (and it seems to be using the same code as here). The issue also occurs when you use an external tileset as the image path will be stored relative to the tileset (tsx) file and not to the map.
Also 1st GID isn't passed correctly in that case too.

If you look here : https://github.com/Trebor777/Nez/blob/master/PipelineImporter/Tiled/TiledMapImporter.cs
and here: 
https://github.com/Trebor777/Nez/blob/master/PipelineImporter/Tiled/TmxTileset.cs

You'll see it's an easy fix. I simply rebuild the path relative to the map location. Then the loader is able to get the correct image and tile information.

**Comment by LithiumToast** [comment]
@craftworkgames Is there support for Tiled tilesets as `.tsx` (Tile Set XML)?

**Comment by craftworkgames** [comment]
@Trebor777 Thanks for the heads up.

@LithiumToast I believe we do, but I'm not entirely sure.

**Comment by Trebor777** [comment]
@LithiumToast: Not directly, the tsx file is read and imported when the map file is parsed by the content builder :) But some tiny features are missing :p

**Comment by LithiumToast** [comment]
@Trebor777 Ah, well. If you want to add a pull request to add the missing features I'm sure @craftworkgames would appreciate it.

**Comment by craftworkgames** [comment]
@Trebor777 or if you could at least list the missing features here that would be great.

**Comment by Trebor777** [comment]
I didn't go through them all, but the collision objects for tiles are not imported and get completely dismissed. They are stored in the tileset as objectgroups. (they can be set in tiled with the collision editor)

**Comment by craftworkgames** [comment]
Oh right. Yeah, we have been working on Object Groups #125 lately. It's nearly finished I believe.
