### ISSUE TITLE
Release early, release often

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#105]
One of motto's is ["Release early, release often"](https://en.wikipedia.org/wiki/Release_early,_release_often). My plan has always been to do a release every month or so.

So far we've had [4ish releases](https://www.nuget.org/packages/MonoGame.Extended/) (not counting minor bug fixes).
    
    Version	                                    Downloads	Last updated
    MonoGame.Extended   0.4.64 (this version)	294	        13 December 2015
    MonoGame.Extended   0.3.44-alpha	        271	        23 September 2015
    MonoGame.Extended   0.2.7-alpha	            126	        26 August 2015
    MonoGame.Extended   0.1.1-alpha	            34	        02 August 2015

This is okay. It's certainly a lot better than MonoGame's release cycle :stuck_out_tongue_winking_eye: 

But I think we can do a lot better. 

Pushing a release is easy. I've got an automated build to push a NuGet package from `master` in one click. The real problem is that it's difficult to get the code ready for release. To make sure that nothing makes it into the release that shouldn't be there.

I'm guilty of checking all my stuff into `master`. It seemed like the right thing to do at the time, but it's not working very well now. `master` is getting dirty, with half finished features.

So I propose we start doing [feature branching](http://martinfowler.com/bliki/FeatureBranch.html) and push a release *every* time we pull a completed* feature into `master`.

* Of course, the definition of *completed* is going to vary. We're not looking for perfection, just something that looks pretty good from an API point of view.

**Comment by craftworkgames** [comment]
Before we can do this properly I think we need to cleanup `master` and remove anything that shouldn't be there. Fortunately, the project namespaces organized nicely into features.

![image](https://cloud.githubusercontent.com/assets/3201643/12768613/8c24d7e6-ca5c-11e5-8a4f-76c050bb4a33.png)

The features marked with a red dot are my candidates for removal. Here's why:

 **Animations** - the animations feature was kind of an experiment to write a [sprite sheet animation tool](http://dylanwilson.net/introducing-astrid-animator). It kinda works but the code is a mess and probably shouldn't have been released as is. At the very least this feature needs a cleanup before the 0.5 release.

**Collisions** - the collision detection code is really rough and should have also existed in a feature branch before it made it into the release. @LithiumToast is planning to do some work on #74 to make this a lot better.

**Gui** & **Screens**  - is what I'm currently working on. There's still a lot to do so I'm going to move it into a feature branch.

**Shapes** - I recently added some sprite batch extensions for drawing shapes (#31). This is working pretty well for drawing debug shapes and could probably go out as v0.5. However, there has been some discussion about either replacing this with or adding a `PrimitiveBatch` approach as well.

**Comment by LithiumToast** [comment]
I hoping to get the software design for collisions finished and boilerplate code finished by 1st of next month, but no promises.

**Comment by craftworkgames** [comment]
@LithiumToast No problem. How much have you done?  Do you think i'll be difficult to move it into a feature branch?

**Comment by LithiumToast** [comment]
@craftworkgames You might as well just create a branch for me if you want, I won't be able to work on it until this weekend.

**Comment by craftworkgames** [comment]
@LithiumToast Okay I'll do that and let you know. Before I create any branches though I'm going to do some code cleanup.

**Comment by craftworkgames** [comment]
Okay so I've been thinking about how to manage the first round of feature branches.

## First round of feature branches

The first thing I did was move the **Gui** & **Screens** code into a branch called `gui-system`. This has already been done and `master` no longer has this code.

I thought about removing **Animations** and **Collisions** from master also, but I think that's a bad idea until we have something concrete to replace them with. I'm still in favor of creating branches for these features when someone gets around to refactoring them. For the moment though, they can stay.

@LithiumToast I already created a branch called `collision-detection` to work on replacing the **Collisions** feature when you get to it.

I think the changes to **Shapes** is releasable enough to stay in `master`. I may even do a release with just this one new feature to start the process of releasing more often.

## Feature demos

Another thought that came out of this was getting rid of the "Sandbox" project. Instead, I think each feature should have a "Demo" project included in the solution. This way, we have a reproducible way to test features when they change and a much cleaner way to show off the library.

I've already started this in the `gui-system` branch. 

![image](https://cloud.githubusercontent.com/assets/3201643/12782072/8ab25754-cac4-11e5-80e0-8fef4830c72e.png)

**Comment by LithiumToast** [comment]
For collisions I will eventually get around to implementing algorithms for finding convex hulls for a "soup" of vertices. (The convex hull will be the collision geometry). It would be awesome if could setup a testing playground to watch the algorithm work in action. The demo idea could work well for this if use the gui library to have game screen menu for selecting tests, kinda like how Farseer Physics does their demo project.
