### ISSUE TITLE
[Documentation] VSIX Project Templates

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#106]
Turns out I create new MonoGame.Extended projects fairly often these days. Something that gets really annoying is all the setup code, like:
-  adding a reference to the NuGet packages (for both MG and MG.E). 
- configuring the `Content.mgcb` and MonoGame Pipeline.
- cleaning out and possibly renaming the `Game1` class.
- setting up the camera and viewport adapters.
- creating a `SpriteBatch` and a test sprite

Then I thought, wait a second, maybe I can automate some of this process. It turns out, creating Visual Studio Project Templates is fairly easy.

![image](https://cloud.githubusercontent.com/assets/3201643/12779233/97363958-cab2-11e5-8a4e-42ca816bef33.png)

![image](https://cloud.githubusercontent.com/assets/3201643/12779242/a46965b4-cab2-11e5-8c9c-2e5218bf8a4a.png)

This is awesome. But it only gets us half of the way there. I think it would be great if we shipped Visual Studio Project templates as part of each release.

Enter [Visual Studio Extensions (VSIX)](https://msdn.microsoft.com/en-us/library/ff363239.aspx). I think. They seem to be the way to create an _installer_ for project templates and give a little more control over creating them. Although, I haven't really looked into it much yet.

Of course, MonoGame already has [project templates](https://github.com/mono/MonoGame/tree/develop/ProjectTemplates) so it shouldn't be too difficult to figure this out.

Off the top of my head I would like to solve these problems that I haven't already figured out yet:
- the templates should install in the MonoGame category alongside the MonoGame templates.
- they should be installed with the same blue logo as the NuGet package.
- we need to be able to build the templates and VSIX as part of the automated build.
- the template should always reference the latest version MG.E NuGet package.
- we'll update the readme to make this the preferred way to install MG.E into Visual Studio

**Comment by cupstudio** [comment]
Would love this!

**Comment by craftworkgames** [comment]
This looks like a tutorial for exactly what we want to do here:

https://msdn.microsoft.com/en-us/library/dd997148.aspx

I've also created [a project template for developers](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/ProjectTemplates) working on the library to create Demo projects. I used this to bring all the demos over from the samples repo. I think this is easier to manage and helps when developing new features.

**Comment by bsimser** [comment]
Quick question, can we not get everything done with the install.ps1 file you can add to the nuget package?

**Comment by craftworkgames** [comment]
> can we not get everything done with the install.ps1 file you can add to the nuget package?

I dunno, can we?  How would that work?

**Comment by lithiumtoast** [comment]
Closing due to age. I believe VSIX is not the appropriate tool in today's world of .NET Core / 5.
