### ISSUE TITLE
[Documentation] Generate API documentation

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#108]
At some point we may want to start generating some MSDN style documentation for the library. 

I'm not really sure which [documentation generator](http://stackoverflow.com/questions/641364/c-sharp-documentation-generator) we should use? Anyone have experience with this stuff? One that's not mentioned on that list is [sharpDox](https://github.com/Geaz/sharpDox) which I've used, but it was only kind of okay.

My only requirement would be that we can automate this stuff through the build system. In other words, it should be generated from the command line and spit out HTML or some equivalent.

I'd probably host it on a github pages website and have the build system upload it automatically with each release.

**Comment by LithiumToast** [comment]
I would use Sandcastle.

**Comment by LithiumToast** [comment]
DOxygen, Doc-O-Matic, NDoc look good too.

**Comment by craftworkgames** [comment]
There's also [MonoDoc](www.mono-project.com/docs/tools+libraries/tools/monodoc/). I don't know much about it but I thought I'd add it to the list.

So here's the thing. I don't really want to spend a lot of time on this. We need something that can:
 - produce API documentation as HTML (or other format) for hosting on a website
 - can be run via our TeamCity build system on a Windows box (i.e. from the command line)
 - needs to be either free or very affordable.

That's about it.

If anyone is interested in evaluating some of these tools and finding one that does these things I'll set it up on the build server and find a place to host them. Github pages perhaps?

**Comment by bsimser** [comment]
The entire documentation for NuGet is done via Markdown (as was a lot of the .NET Framework documentation). There are some API generation tools that will output Markdown but it seems to me the simplest thing is to setup a documentation project (maybe as a branch on here or turn this into an organization with it's own repo) and do it that way. https://github.com/NuGet/NuGetDocs

**Comment by vinzBad** [comment]
I generated a html-documentation with doxygen for Monogame.Extended -> [html.zip](https://github.com/craftworkgames/MonoGame.Extended/files/815054/html.zip) . If you want to generate the config yourself, you can download it from [here](https://gist.github.com/vinzBad/ef374c549d64c36588a1d74b385cc0fc), place it in the Source-Folder and run `doxygen doxygen.conf`

Cheers,
Vinzenz

**Comment by craftworkgames** [comment]
@vinzBad Thanks man. It looks really nice.

Of course the next step is figuring out where to host it and generating it on the build server for each build. I guess it wouldn't be super difficult but it might take some time to get that up and running.

**Comment by vinzBad** [comment]
It looks like there's a bridge between doxygen and readthedocs / sphinx, I'll take a look into it. If it works -> free documentation hosting on readthedocs.io

**Comment by vinzBad** [comment]
[This](http://stackoverflow.com/a/41199722) works. But I thinks it's a bit to complicated for my taste. I can host the generated html on https://distractionco.de ,when there's no other option.

**Comment by craftworkgames** [comment]
We can probably use [github pages](https://pages.github.com) since it's all static content.

**Comment by craftworkgames** [comment]
The other night I was playing with mkdocs.

It was relatively easy to get the ["hello world" onto github pages](http://craftworkgames.github.io/MonoGame.Extended/). I'm thinking we'll make this our main source of documentation and maybe host the generated API docs in the same place.

**Comment by bsimser** [comment]
Looks good and is pretty straight forward. Do we have a branch then to pull and put some documentation in yet. Would like to do some contributing.

**Comment by craftworkgames** [comment]
I haven't got far with it yet but the process is fairly simple.

There's a `Docs` folder in the main `develop` branch. To create documentation pages you simply add markdown files into that directory.

On the build server I'll setup an automated process to run `mkdocs gh-deploy` and it'll publish the documentation to github pages. Simple.

**Comment by bsimser** [comment]
Sounds like a plan. I'll grab the branch and see what's there and either build on or create a TOC of sorts (based on the various documentation there is). I know if the files are in a  /docs folder github pages just works, no publishing needed (anything that's committed to that folder is published). The old way used to be forcing a branch named gh-pages but the /docs folder works now and just needs to be configured to look at that folder instead of a branch for the contents. The jekyll backend takes care of the rest. Thanks.

**Comment by craftworkgames** [comment]
>  I know if the files are in a /docs folder github pages just works, no publishing needed (anything that's committed to that folder is published).

Where did you read that?  As far as I was aware this is [feature of mkdocs](http://www.mkdocs.org/user-guide/deploying-your-docs/) *not* github pages?

> The old way used to be forcing a branch named gh-pages

I think it still works that way.

The difference is that mkdocs is taking control of the gh-pages branch, we shouldn't be manually changing that branch at all. The only branch we need to worry about is `develop`.

**Comment by bsimser** [comment]
The gh-pages branch still works if you want but the new way [documented here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) lets you use a /docs folder on the master branch. Might be a problem because we're working on the develop branch so the gh-pages branch might be a better option here (unless you want everyone committing to master in the docs folder then merge develop to master for releases).

**Comment by craftworkgames** [comment]
Cool. I didn't know about that.

One "benefit" of that approach is that we could keep the published documentation in line with the latest release. That way the "official" documentation will line up with the `master` branch and the files in the `docs` folder will line up with the `develop` branch.

I'm not sure if that's the way we want to go yet but I'll keep it in mind.

**Comment by craftworkgames** [comment]
Okay. The new [documentation site](http://craftworkgames.github.io/MonoGame.Extended/) is up and running.
