### ISSUE TITLE
Load content on monogame-UWP

### ISSUE THREAD

**Issue by Kserol** [craftworkgames/MonoGame.Extended#109]
Hi,

i can't load custom content (tileMap, animation) in a monogame-Uwp project. 
I catch : "ContentLoadException: Could not load Tilesets/level01 asset as a non-content file! "

I build content with MonoGame Pipeline GUI:
![image](https://cloud.githubusercontent.com/assets/2233539/12821548/2083fe00-cb64-11e5-9e60-1138d74592bb.png)

how do I debug this?

**Comment by LithiumToast** [comment]
@Kserol If I remember correctly there should be an inner exception to the `ContentLoadException` which is more informative of what went wrong exactly. Could you check to see if there is an inner exception, and if so, post it here?

**Comment by craftworkgames** [comment]
Are you getting the error from the MonoGame Pipeline tool or from your own code when you call `Content.Load<TiledMap>`?

**Comment by Kserol** [comment]
@craftworkgames on Content.Load<TiledMap>(...)
@LithiumToast Thanks ! i can fix it with the InnerExecption.

It's all my fault. 
Like Monogame.Extended nuget package isn't compatble with UWP project, I create  a new project  "MonoGame.Extended.**Uwp**" targeting  Universal Windows.
When Content.Load() try to load  "MonoGame.Extended" (by reflection) he fail. Can't find assembly.
Rename  the ouput of my UWP project solve this.

Thanks, sorry for the inconvenience caused

**Comment by craftworkgames** [comment]
No problem. I'm glad you got it working. It's always good to know how people are using the library.
