### ISSUE TITLE
Tiled map editor support

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#11]
I've been working on [Tiled](http://www.mapeditor.org/) map loading recently. It's working at a bare minimum level loading the TMX map files with the MonoGame Pipeline tool and rendering the map using `SpriteBatch`'s for each map layer. 

There's still lots of things to do:

 - Rendering just the visible tiles in the camera's rectangle
 - There seems to be an issue with gaps between tiles "tearing", it could be a bug in MonoGame?
 - Not all Tiled options are support (e.g. isometric or staggered maps)
 - The map renders, but there's no support for "querying" the map (e.g. find tile properties)
 - What code can be shared with tIDE maps?
 - Should the Tiled code be split into another project? (e.g. MonoGame.Extended.Tiled)
 - Probably many other things?

This issue is here to discuss how it should work and how we can split up the workload.

**Comment by craftworkgames** [comment]
So I have very basic support for Tiled maps working but there's still a lot of things to do. The [TMX map format spec](http://doc.mapeditor.org/reference/tmx-map-format/) is a good reference. Here's a list of things that haven't been implemented yet.

 - Support for isometric and staggered orientations
 - Background color of the map
 - Render order: The order in which tiles on tile layers are rendered. (right-up, left-down and left-up)
 - Tileset source: If the tileset is stored in an external TSX (Tile Set XML) file.
 - tileoffset: to be applied when drawing a tile from the related tileset.
 - Image trans: Defines a specific color that is treated as transparent.
 - Terrain types: Defines an array of terrain types, which can be referenced from the terrain attribute of the tile element.
 - Animations: Contains a list of animation frames.
 - compression: The compression used to compress the tile layer data. Tiled Qt supports "gzip" and "zlib".
 - Tile flipping: the highest two bits of the gid store the flipped state.
 - objectgroup: The object group is in fact a map layer, and is hence called "object layer" in Tiled
 - imagelayer: A layer consisting of a single image.
 - properties: Wraps any number of custom properties. Can be used as a child of the map, tile (when part of a tileset), layer, objectgroup and object elements.

If we implement all of that stuff we'd have feature parity with the Tiled editor I believe. Although, some things have more value than others. Even basic Tiled support is pretty useful.

The other thing that needs some attention is querying the map. At the moment it's really just focused on rendering but to properly use the maps in a game we'll need provide the ability to query the layers, tiles and properties of the map within code.

**Comment by pancisin** [comment]
Hi, is it possible to focus more on implemeting object layers ? I need it for my project. It seems to be complicated to parse it myself using monogame.extended pipeline.
Thank you.

**Comment by cupstudio** [comment]
I've looked at Object layers recently and will take a stab at it in the next week or two.  If Dylan can expound a little more on where he is with them then it would help to pick it up if he doesn't have time.

A couple of quick things I noticed off the bat:

* It appears most of the ints in TmxObject need to be changed to floats and read accordingly.
* The XML for TMX doesn't look like it creates an actual object layer, but rather an "objectgroup" (and there can be multiple).  `TiledMapReader.ReadLayer` logic would need to be updated (among other things)

**Comment by craftworkgames** [comment]
Yes, I'm currently busy with #20 so I haven't done any work on the Tiled stuff lately.

@cupstudio if you and @pancisin want to work on this together I'll poke my head in every so often and contribute to the discussion. It would be nice to get Object layers. The Tiled feature is probably the most popular of the whole library so far.

**Comment by LithiumToast** [comment]
> There seems to be an issue with gaps between tiles "tearing", it could be a bug in MonoGame?

This could probably be a floating point arithmetic problem.

**Comment by craftworkgames** [comment]
@LithiumToast we've already fixed that. It was a combination of a couple of issues.

**Comment by craftworkgames** [comment]
I'm going to close this issue because we've had a Tiled map feature for a while now. Some of the bullet points are not done but I'd rather raise new issues for those as they are requested.

**Comment by ashes999** [comment]
Is there any documentation on this? I'm looking for a simple example of how to load an existing map (with tilesets) and render it (using one `SpriteBatch` per layer, as you mentioned in the comments above).

**Comment by craftworkgames** [comment]
Our [demos](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Demo.Features/Demos/TiledMapsDemo.cs) are the best place to start
