### ISSUE TITLE
Allow drawing Tiled Maps with your own SpriteBatch

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#111]
It would be nice to make some improvements to the TiledMap renderer to allow maps to be drawn using your own `SpriteBatch` as an alternative to having one created by the layer.

@cra0zy submitted [a PR](https://github.com/craftworkgames/MonoGame.Extended/pull/110) about this recently but there's still more work to do.

> @craftworkgames What's the purpose of these changes? Can you provide an example usage?
> @cra0zy Drawing using my own camera system.
> @craftworkgames What I'm trying to understand is what the goal is? Do you want to be able to use your own SpriteBatch instead of having the layer create one for you?
> @cra0zy Yes, plus I don't want to use MG Extended camera system, it would suck for what I'm doing.

There's a few ways we could do this, maybe some `TiledMap.Draw` overloads that take a `SpriteBatch`? Maybe as `SpriteBatch` extension methods?  We should think about how it should work with the `visibleRectangle` because the camera will no longer be in play.

**Comment by cupstudio** [comment]
I can take a look at this since I was working on this method before.  What branch do I PR to?  I know we don't want to keep using master (which I heartily agree with).

Some of the options as I see it:

*  "Small Feature Branch"
*  Milestone / Release Branch
* Add TiledMaps branch

**Comment by cupstudio** [comment]
Looking for feedback on this... something smells wrong to me, but maybe this isn't as abnormal as I'm thinking.

````c#
        public void Draw(SpriteBatch spriteBatch, RectangleF visibleRectangle)
        {
            _customSpriteBatch = spriteBatch;
            Draw(visibleRectangle, true);
        }

        public override void Draw(RectangleF visibleRectangle, bool useCustomSpriteBatch = false)
        {
            SpriteBatch spriteBatch = _customSpriteBatch;
            if (!useCustomSpriteBatch)
            {
                spriteBatch = _spriteBatch;
                spriteBatch.Begin(blendState: BlendState.AlphaBlend, samplerState: SamplerState.PointClamp);
            }

            var renderOrderFunction = GetRenderOrderFunction();
            var tileLocationFunction = GetTileLocationFunction();
            var firstCol = (int)Math.Floor(visibleRectangle.Left / _map.TileWidth);
            var firstRow = (int)Math.Floor(visibleRectangle.Top / _map.TileHeight);

            // +3 to cover any gaps
            var columns = Math.Min(_map.Width, (int)visibleRectangle.Width / _map.TileWidth) + 3;
            var rows = Math.Min(_map.Height, (int)visibleRectangle.Height / _map.TileHeight) + 3;

            //_spriteBatch.Begin(blendState: BlendState.AlphaBlend, samplerState: SamplerState.PointClamp);

            foreach (var tile in renderOrderFunction(firstCol, firstRow, firstCol + columns, firstRow + rows))
            {
                var region = tile != null ? _map.GetTileRegion(tile.Id) : null;

                if (region != null)
                {
                    var point = tileLocationFunction(tile);
                    var destinationRectangle = new Rectangle(point.X, point.Y, region.Width, region.Height);
                    spriteBatch.Draw(region, destinationRectangle, Color.White);
                }
            }

            if (!useCustomSpriteBatch)
            {
                spriteBatch.End();
            }
        }
````

Also, I don't really like using bools that much in methods, so we could make a special enum or something for custom vs private spriteBatches if that makes sense.

**Comment by cupstudio** [comment]
Also, I don't really like using bools that much in methods, so we could make a special enum or something for custom vs private spriteBatches if that makes sense.

**Comment by LithiumToast** [comment]
Why not use add this code to the SpriteBatch extensions?

**Comment by craftworkgames** [comment]
I raised a new issue #120 that covers this one. I also started working on it in the [`tiled-maps`](https://github.com/craftworkgames/MonoGame.Extended/tree/tiled-maps) branch when I was in there fixing a different bug.

Sorry @cupstudio I didn't realize you'd already started. You're welcome to join me in the branch. Have a read of #120 and take a look at what I've done so far.

**Comment by craftworkgames** [comment]
Completed in #131
