### ISSUE TITLE
Object Pooling

### ISSUE THREAD

**Issue by LithiumToast** [craftworkgames/MonoGame.Extended#117]
I'm going to need object pooling for collisions at some point: objects will have the ability to be added/removed from collision world at any time for any reason. I think Entity Component System #100 and Particles #19 would also benefit from object pooling.

I propose using a [`Stack<T>`](https://msdn.microsoft.com/en-us/library/3278tedw(v=vs.110).aspx) as the internal data structure for the object pool. [`Push`](https://msdn.microsoft.com/en-us/library/6335ax0f(v=vs.110).aspx) and [`Pop`](https://msdn.microsoft.com/en-us/library/9say334k(v=vs.110).aspx) are both `O(1)` time complexity when the number of items in the stack is less than the internal size of the array.

There is also a [`ConcurrentStack<T>`](https://msdn.microsoft.com/en-us/library/dd267331(v=vs.110).aspx) available in the [.NET library on NuGet for concurrent collections](https://www.nuget.org/packages/System.Collections.Concurrent/) which I think would be a good replacement for `Stack<T>` for a concurrent object pool. Though I think a non-concurrent object pool will still be useful for certain scenarios. 

Perhaps an `IObjectPool` interface would be beneficial to allow choosing between a `ObjectPool<T>` and `ConcurrentObjectPool<T>`.

**Comment by craftworkgames** [comment]
Yes, I agree object pooling would be useful for a few things in the library. Maybe in a `Collections` namespace?

**Comment by LithiumToast** [comment]
@craftworkgames I think that's a good idea to have a `Collections` namespace. There are other data structures such as trees (quadtree, octrees) that I will eventually get added to MG.Ex that are candidates to reside in the `Collections` namespace.

**Comment by LithiumToast** [comment]
[Here is a good article](http://gameprogrammingpatterns.com/object-pool.html) about object pooling directly from the book [Game Programming Patterns](http://gameprogrammingpatterns.com).

**Comment by craftworkgames** [comment]
That's a really good article. It makes me think we need a couple of different types of pools (or a configurable one) that:
 - prevents a new object from being added if it's full
 - replaces the oldest object in the pool (or cycles through a stack)
 - replaces an object that matches a user specified criteria.

Also, since we are in a managed memory world we should consider this:

> Object pools are less common in systems that support garbage collection because the memory manager will usually deal with fragmentation for you. But pools are still useful there to avoid the cost of allocation and deallocation, especially on mobile devices with slower CPUs and simpler garbage collectors.

**Comment by LithiumToast** [comment]
> Also, since we are in a managed memory world we should consider this:

In C# we can also use take advantage of the garbage collector and the disposable pattern to return an object back to the pool instead of being garbage collected.

**Comment by LithiumToast** [comment]
The following is quoted from [Writing Faster Managed Code: Know What Things Cost](https://msdn.microsoft.com/en-us/library/ms973852.aspx)

> Note the garbage collector spends no time mourning dead objects. If an object is dead, GC doesn't see it, doesn't walk it, doesn't give it a nanosecond's thought. GC is concerned only with the welfare of the living.
(Exception: finalizable dead objects are a special case. GC tracks those, and specially promotes dead finalizable objects to the next generation pending finalization. This is expensive, and in the worst case can transitively promote large dead object graphs. Therefore, don't make objects finalizable unless strictly necessary; and if you must, consider using the Dispose Pattern, calling GC.SuppressFinalizer when possible.) Unless required by your Finalize method, don't hold references from your finalizable object to other objects.

Here is a snippet I wrote for `ObjectPool<T>` which demonstrates this:
(Note that T must inherit `IPoolable` in this demonstration)

```
        private void DestroyObject(T item)
        {
            if (!item.IsDisposed)
            {
                item.Dispose();
                ObjectsDestroyedCount++;
            }

            // Tell the garbage collector to NOT call the finalizer on the object when it becomes "dead"
            GC.SuppressFinalize(item);
        }

        private void ReturnObject(T item, bool reRegisterForFinalization)
        {
            if (reRegisterForFinalization)
            {
                ObjectsRevivedCount++;
                GC.ReRegisterForFinalize(@object);
            }

            // Reset the state of the object
            _objectResetMethod(item);

            _pooledObjects.Push(objectT);
            ObjectsReturnedCount++;
        }
```

**Comment by craftworkgames** [comment]
You might want to also look at the [Mercury Particle Engine](https://github.com/Matthew-Davey/mercury-particle-engine/blob/develop/Mercury.ParticleEngine.Core/ParticleBuffer.cs). It appears to be well optimized.

Just be careful using unmanaged code if you can help it. We need MonoGame.Extended to work on many platforms and I really don't want to be the one unpicking code that doesn't work on Android or iOS.

**Comment by LithiumToast** [comment]
@craftworkgames Well, we can't even enable the "use unsafe code" in portable class libraries so we can't do any unmanaged stuff really.

**Comment by LithiumToast** [comment]
well, I needed this; #142

Still needs work for configurability; ability to change behaviour of asking for an object and it doesn't exist.

**Comment by LithiumToast** [comment]
see #146 and #147

**Comment by LithiumToast** [comment]
To use a pooled object:
1. Request a free pooled object; Pool.Create(). This calls IPoolable.Initialize(delegate), passing the internal Pool.Return method to IPoolable through the delegate.
2. Release it; IPoolable.Return. It's up the IPoolable to call the return delegate, if available. It should return false if the delegate has already been used.

```
        private class TestPoolable : IPoolable
        {
            private ReturnToPoolDelegate _returnFunction;
...
            void IPoolable.Initialize(ReturnToPoolDelegate returnFunction)
            {
                _returnFunction = returnFunction;
            }

            public bool Return()
            {
                if (_returnFunction == null)
                {
                    return false;
                }
                _returnFunction.Invoke(this);
                _returnFunction = null;
                return true;
            }
...
        }
```

If all the objects in the pool are in use, there is an option to kill an existing pooled object by passing `killIfEmpty = true` for `Pool.Create`. This killing operation unfortunately does not have `O(1)`, but `O(n)` time complexity. Requesting an available pooled object _when the pool is not empty_ has `O(1)` time complexity. Returning a pooled object has `O(1)` time complexity.

**Comment by LithiumToast** [comment]
@craftworkgames We can close this if you want.

**Comment by craftworkgames** [comment]
@LithiumToast What you've written  here is effectively documentation. Please copy it to a page on [the wiki](https://github.com/craftworkgames/MonoGame.Extended/wiki). Then close the issue.

Ideally, I'd like to get into a habit of creating a page on the wiki for all new features if we can. Motivation to write documentation is not always high, but getting into a habit of writing *something* is better than nothing at all.

**Comment by craftworkgames** [comment]
> Well, we can't even enable the "use unsafe code" in portable class libraries so we can't do any unmanaged stuff really.

Btw.. we ended up using unsafe code in the particle system after all. So thanks for the work you did on it.

**Comment by LithiumToast** [comment]
@craftworkgames OK, I'll add some Xml documentation and write a wiki entry.

The unsafe code is only available for PCL because we are no longer targeting Silverlight, which is fine.

**Comment by LithiumToast** [comment]
@craftworkgames I added XML documentation to the code. I think writing the documentation once and having it available directly through VisualStudio is easier to maintain and manage than creating a wiki. Perhaps upon every release of MonoGame.Extended we could compile to the XML documentation and post it to the wiki instead?

**Comment by craftworkgames** [comment]
> I added XML documentation to the code; I think writing the documentation once and having it available directly through Visual Studio is easier to maintain and manage than creating a wiki.

XML documentation and wiki documentation serve a different purpose. Both are good in their own way.  

- XML comments are good for documenting the API.
- The wiki is good for giving a higher level overview of how things work.

> Perhaps upon every release of MonoGame.Extended we could compile to the XML documentation and post it to the wiki instead?

It's a good idea to generate API documentation and put it online somewhere. I'm not sure if the wiki is the right place, but it could be. I raised an issue about this a while ago #108 

For the moment I've copy and pasted your comment into the wiki so we can close this issue. If we leave it here it will get lost, if it's on the wiki we can improve it over time. I'd rather having *something* on the wiki, even it's it's just a rough draft.
