### ISSUE TITLE
WidthInPixels returning wrong width

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#118]
The property `WidthInPixels` of `TiledMap` is returning the wrong width. If the map have 10 tiles (32x32 each), the width is supposed to be 320px, right? But the return is 310px (the supposed width - 1 * tiles). Maybe [this](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Maps/Tiled/TiledMap.cs#L68) commentary is not being applied?

**Comment by craftworkgames** [comment]
I actually fixed this up last night in the `tiled-maps` branch. This code got missed when we fixed an old issue a while back.
