### ISSUE TITLE
The great `Draw` method overhaul

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#120]
So it turns out we actually have a **lot** of different `Draw` methods in MonoGame.Extended. Most of them are `SpriteBatch` extensions but there's a few (at the bottom) that are inconsistent.

This list is written from the point of view of what it looks like when you're *calling* the method. In other words, the sprite batch extensions are prefixed with `spriteBatch` and the others are called directly on the class.

I've also removed the parameter types, but left the parameter names. There's enough information here to get an idea of what the signature looks like.

### Sprites

    spriteBatch.Draw(sprite);
	spriteBatch.Draw(spriteSheetAnimator);

The `Sprite` and `SpriteSheetAnimator` also have a reversed extension method to make it look like you can all `Draw` directly on the class. I added this recently as an experiment. Not sure if it's worth it.

    sprite.Draw(spriteBatch);
    spriteSheetAnimator.Draw(spriteBatch);

### Texture Regions

	spriteBatch.Draw(textureRegion, position, color);
	spriteBatch.Draw(textureRegion, destinationRectangle, color);

### Bitmap Fonts

    spriteBatch.DrawString(bitmapFont, text, position, color);
    spriteBatch.DrawString(bitmapFont, text, position, color, wrapWidth);

### Shapes

    spriteBatch.DrawPolygon(position, polygon, color, thickness);
    spriteBatch.DrawPolygon(offset, points, color, thickness);
    spriteBatch.FillRectangle(rectangle, color);
    spriteBatch.FillRectangle(location, size, color);
    spriteBatch.FillRectangle(x, y, width, height, color);
    spriteBatch.DrawRectangle(rectangle, color, thickness);
    spriteBatch.DrawRectangle(location, size, color, thickness);
    spriteBatch.DrawLine(x1, y1, x2, y2, color, thickness);
    spriteBatch.DrawLine(point1, point2, color, thickness);
    spriteBatch.DrawLine(point, length, angle, color, thickness);
    spriteBatch.DrawPoint(x, y, color, size);
    spriteBatch.DrawPoint(position, color, size);
    spriteBatch.DrawCircle(circle, sides, color, thickness);
    spriteBatch.DrawCircle(center, radius, sides, color, thickness);
    spriteBatch.DrawCircle(x, y, radius, sides, color, thickness);

#### currently
	tiledMap.Draw(camera);
	tiledMap.Draw(camera, useMapBackgroundColor);	

	tiledTileLayer.Draw(visibleRectangle);
	tiledImageLayer.Draw(visibleRectangle);
	
#### `tiled-maps` branch (work in progress)
	tiledMap.Draw(spriteBatch, camera);
	tiledMap.Draw(spriteBatch, camera, useMapBackgroundColor);

### Scene Graphs (work in progress)

	sceneGraph.Draw(spriteBatch);

### GUI system (work in progress)

	guiManager.Draw(gameTime);
	
	guiTextureRegionDrawable.Draw(spriteBatch, rectangle);
	guiTextDrawable.Draw(spriteBatch, rectangle);
	guiLayoutDrawable.Draw(spriteBatch, rectangle);
	guiPatchDrawable.Draw(spriteBatch, rectangle);

## What should we do about this situation?

My general opinion is that the `SpriteBatch` extensions are quite nice and work well for Sprites, TextureRegions, BitmapFonts and Shapes. It seems natural to be able to do this:

    spriteBatch.Begin();
    spriteBatch.Draw(sprite);
    spriteBatch.DrawString(bitmapFont, "Hello World", Vector2.Zero, Color.White);
    spriteBatch.End();

However, extension methods can't be implemented via an interface. This means if you've got a collection of **different** *drawable* objects and you wanted to draw them all together you **couldn't** do something like this:
    
    foreach(ISpriteBatchDrawable drawable in _drawables)
        drawable.Draw(spriteBatch);

This may not actually be a **real problem** though, because it's kinda rare that you'd  be putting different types of drawables into the same collection. More often than not, the `Draw` methods have different signatures and can't all share the same interface anyway. You can of course still do this:

    foreach(Sprite sprite in _sprites)
        spriteBatch.Draw(sprite);

So anyway, the question is, should we put some effort into making these draw methods more consistent throughout the framework?
 - should we **always** have a `SpriteBatch` extension method?
 - are there cases when this wouldn't work?
 - does it make sense to also have a `Draw` method directly on the class in addition to the extension?
 - are there any missing? (I think the answer is yes)
 - any other thoughts?

**Comment by LithiumToast** [comment]
> However, extension methods can't be implemented via an interface. This means if you've got a collection of different drawable objects and you wanted to draw them all together you couldn't do something like this:

If we had a `ISpriteBatchDrawable` couldn't we also create a `SpriteBatch` extension that takes a `ISpriteBatchDrawable` as it's parameter? Something like this? Hopefully it get's inlined by JIT compiler.
```
public static void Draw(this SpriteBatch spriteBatch, ISpriteBatchDrawable spriteBatchDrawable)
{
    spriteBatchDrawable.Draw(spriteBatch);
}
```

> should we always have a SpriteBatch extension method?

Would be ideal but looks like their might be some corner cases.

> does it make sense to also have a Draw method directly on the class in addition to the extension?

It's probably OK. I don't think people should be forced to use an extension method to draw their stuff. Though it's probably easier for people to understand and read code, especially people who are new, to have and use `SpriteBatch` extensions.

**Comment by craftworkgames** [comment]
> If we had a ISpriteBatchDrawable couldn't we also create a SpriteBatch extension that takes a ISpriteBatchDrawable as it's parameter?

Good idea. Of course, this means the `Draw` implementation moves to inside the class itself in most cases. This is probably okay. 

I think a very specific `ISpriteBatchDrawable` interface makes sense. It's a common enough requirement to have a `Draw` method that takes a `SpriteBatch` as a parameter. Once you start working without sprite batches (in 3D) things get a little hairy. MG.Ex isn't currently dealing in 3D stuff though.

I'll got through all the cases later an consider what this means in terms of implementation.

> it's probably easier for people to understand and read code, especially people who are new, to have and use SpriteBatch extensions.

Interestingly we already had [a user get confused](https://github.com/craftworkgames/MonoGame.Extended/issues/101) about the `SpriteBatch` extensions. That's why I implemented the reversed draw methods on Sprites.

**Comment by LithiumToast** [comment]
> Interestingly we already had a user get confused about the SpriteBatch extensions. That's why I implemented the reversed draw methods on Sprites.
e
I see, well I guess it's best to use it one way in the library for consistency and let people choose which way they prefer in their code.
