### ISSUE TITLE
[Documentation] Create a CONTRIBUTING.md guide

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#121]
The MonoGame has recently been working on a [CONTRIBUTING.md](https://github.com/mono/MonoGame/pull/4500) guide that looks quite nice. [Tom said](https://github.com/mono/MonoGame/pull/4500#issuecomment-180458263) we are welcome to create a similar guide for MonoGame.Extended so I'm just raising this issue so we don't forget.

**Comment by lozzajp** [comment]
I am currently making a draft copy of this, literally copied the MG one and suiting it to our needs. Assume that is ok with what you have said.

**Comment by lozzajp** [comment]
@craftworkgames Do you think it would be ok to generate a similar coding style guide too?

https://github.com/MonoGame/MonoGame/blob/develop/CODESTYLE.md

**Comment by lozzajp** [comment]
@craftworkgames List of queries so far

* Do we want a [coding style guide](https://github.com/MonoGame/MonoGame/blob/develop/CODESTYLE.md)?
* Should we remove the decompiling section from the MG contributing.md? (It seems heavily directed towards people decompiling XNA which is beyond this as an extension project) - Or at least just tone it down.
* License section needs a good review

**Comment by craftworkgames** [comment]
@lozzajp I just had a quick read through the contributing guide. 

It's pretty good the way it is. It's probably best to leave the decompiling section in just to show that we support the MonoGame way of doing things. It's probably not relevant to Extended very often, but I don't think it hurts anything to have it.

> Is the MIT link correct?

Yep. MonoGame.Extended is MIT licensed just like MonoGame. We do this on purpose to keep things simple and flexible.

The third party section is still relevant, although, in a slightly different way. When we use 3rd party code  we always seek permission from the original author to include it.

> Do we want that header section?

No need for the header section in MonoGame.Extended. We haven't got a header in any files currently and I don't seen any good reason to start doing that right now.

**Comment by craftworkgames** [comment]
> Do we want a coding style guide?

The coding style guide is a bit of different beast. 

We do have a coding style, but it's quite different to the MonoGame one.

As a general rule, we follow the default [Resharper settings](https://www.jetbrains.com/resharper/features/code_formatting.html) in most cases which also happen to be pretty close to the [Microsoft conventions](https://msdn.microsoft.com/en-us/library/ms229002.aspx).

I'm in two minds about having a code style guide. On one hand it'd be nice to make it clear what we like, but on the other hand, I don't want to spell out a code style unless it's *exactly* what we want. Having a style guide that says one thing and code that says another is hypocritical.

Just to be clear, there's quite a few things about the MonoGame code style that doesn't fit our style. I'd want to clear those up before we include a guide.

**Comment by lozzajp** [comment]
I have removed the one line referencing coding style.

Removed the header part of the license section, added that we seek permission from the library authors.

Should be pretty good now but still consider it a draft, shall I make a PR to track and edit it easier?

**Comment by lozzajp** [comment]
I mentioned in gitter, forgot to track here another query:

Monogame has this line in it's Contribution file:

"After you submit a PR the MonoGame build server will build your changes and verify all tests pass. Project maintainers and contributors will review your changes and provide constructive feedback to improve your submission."

Just noticed you do indeed check a build on team city, so shall I add that line back in related to Extended?

**Comment by craftworkgames** [comment]
> Just noticed you do indeed check a build on team city, so shall I add that line back in related to Extended?

Yes, we do indeed have our [own build server](http://build.craftworkgames.com/). It's *not* the same one used by the MonoGame team but it does work the same way.

Please add that line back.

**Comment by lozzajp** [comment]
Ok done, if you are happy with it at the moment I think I will fork fresh and add the file again (so it's history doesn't go back to the original MG file) and do a PR.

**Comment by lozzajp** [comment]
@craftworkgames Sorry I kept confusing things with PRs, You have a branch called `contributing-md` that I tihnk I created somehow? Anyway it seems way out of sync of `develop` from a previous fork I had.

I now have a fresh fork in my repos with a branch called `contributing-md` which is identical to your main `develop` branch but `+ CONTRIBUTING.md` on it.

Do you want to delete your `contributing-md` branch and I will do a PR from my `contributing-md` to your `develop`?

**Comment by craftworkgames** [comment]
> Do you want to delete your contributing-md branch and I will do a PR from my contributing-md to your develop?

Okay. I deleted the `contributing-md` branch. Awaiting your PR.

**Comment by lozzajp** [comment]
[PR 319](https://github.com/craftworkgames/MonoGame.Extended/pull/319)

**Comment by craftworkgames** [comment]
I read somewhere that if you include words like "fixes #319" in your commit message, github will automatically close and reference the PR on the issue.

**Comment by lozzajp** [comment]
Ahh was wondering how that was done, should have known to at least reference it by hash sign. But in this case it would be "fixes #121"? (319 is the PR). Or you can say in the issue that it "fixes" the PR #number?

**Comment by craftworkgames** [comment]
Yeah you're right, I think it'd be #121 in this case.
