### ISSUE TITLE
Tiled doesn't work when the tileset image is the wrong dimensions

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#122]
I will try to explain the bug the max I can. I am using this tileset:

![Tileset](http://i.imgur.com/I34opCt.png)

In Tiled, I fill the ground with the second tile, like this:

![Ground](http://i.imgur.com/OnZVmQf.png)

So, I fill the bellow the ground with the fifth tile of the second row:

![Ground 2](http://i.imgur.com/3JGoBxu.png)

Seems fine, but when I test in the game, this is what happens:

![Ground in-game](http://i.imgur.com/gNCV2XG.png)

If I use the sixth tile from the second row ([this one](http://i.imgur.com/zyavzxG.png)), this is what happens:

![Ground in-game 2](http://i.imgur.com/2p2E0fD.png)

The tiles are chosen wrong. If I choise, 7, the 6 is drawn.

**Comment by craftworkgames** [comment]
Are you using Layers?

What version on MonoGame.Extended are you using? There's been a lot of bug fixes in the code recently. 

Have a try with the code in the [`tiled-maps`](https://github.com/craftworkgames/MonoGame.Extended/tree/tiled-maps) branch.

**Comment by rafaelalmeidatk** [comment]
Builded the code in the `tiled-maps` branch but the error still occurs. The layers:

![Layers](http://i.imgur.com/P7xV9IM.png)

The error occurs in any layers.

@off: Before using the updated branch, I coded the map draw like this:

    _tiledMap.Draw(spriteBatch, camera);
    spriteBatch.Begin(transformMatrix: camera.GetViewMatrix());
    [... draw stuff]

New I need do this;

    spriteBatch.Begin(transformMatrix: camera.GetViewMatrix());
     _tiledMap.Draw(spriteBatch, camera);
    [... draw stuff]

Is this correct?

**Comment by craftworkgames** [comment]
> Is this correct?

It's correct enough for the moment. I'm still working on it. There's a discussion about the `Draw` methods in #120.

> the error still occurs.

In that case I'm not sure what the problem might be. If you can provide a copy of a TMX file and tileset that reproduces the issue I'll take a look at it later. 

Alternately, you can have a go a debugging the issue yourself. You've already got the `tiled-maps` branch so you're halfway there. If you do manage to fix it just submit a PR back into that branch.

**Comment by rafaelalmeidatk** [comment]
The .tmx file: http://pastebin.com/0RQBUJ0G
tile.png: http://i.imgur.com/ZBsV5M5.png
The hills.png you already have.

I will try fix later, if I find something interesting I notify you (or just submit a PR).

**Comment by rafaelalmeidatk** [comment]
Wow, what a stupid problem xD
The tileset file is not multiple of 32 (the tile size), I will do a PR on my mind to fix it and no happens again, haha. Thanks for the support.

**Comment by craftworkgames** [comment]
Awesome. So what's the fix?

**Comment by rafaelalmeidatk** [comment]
If the tile size is 32x32 your tileset file need have a grid of 32x32, my image had a broken grid:

![screenshot_7](https://cloud.githubusercontent.com/assets/11896398/12939801/b1e23020-cfaa-11e5-9422-98aef6e6f90e.png)

I just cut it and everything worked.

**Comment by craftworkgames** [comment]
Yep fair enough. But I think MonoGame.Extended should probably handle this situation differently. The way I see it we've got 3 options:
 - throw an exception at the Pipeline to prevent this content from ever being processed.
 - throw an exception at `Content.Load`
 - load the content anyway and handle rendering the tiles properly (the same way the map editor does it)

In the first 2 cases I think the error message should be clear about what the problem is so that the user can figure out what to do next.

**Comment by rafaelalmeidatk** [comment]
I like the first or second approach, if something is wrong it can't go ahead. In the future it can raise a bigger problem. I will do the second approach and submit the PR.

**Comment by craftworkgames** [comment]
Turns out this issue runs a little deeper than we thought. The tileset image can be larger than an exact multiple of the tilesize in some cases. I assume it's because of spacing and margin's but for now I'm just going to reopen this issue and have a think about it.

**Comment by rafaelalmeidatk** [comment]
I removed my code in #126. You are correct, the approach is incorrect and I was unable to run the TiledMaps Demo.
