### ISSUE TITLE
Add an implementation of PrimitiveBatch

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#130]
There's a few different versions of `PrimitiveBatch` floating around for drawing basic shapes.

 - There's a good one in the [Farseer Physics Debug Renderer](http://farseerphysics.codeplex.com/SourceControl/latest#DebugViews/DebugView MonoGame/PrimitiveBatch.cs)
 - There's an [Xbox Live Code Sample](http://xbox.create.msdn.com/en-US/education/catalog/sample/primitives)
 - There's also one in [this MonoGame samples repo](https://github.com/CartBlanche/MonoGame-Samples/blob/master/Primitives/PrimitiveBatch.cs)

We've already got basic shapes drawing using SpriteBatch extensions implemented as part of #31 but I think it would be nice to also have this. It's likely to be better performance when drawing lots of shapes.

MonoGame has also had [an issue](https://github.com/mono/MonoGame/issues/871#issuecomment-188656650) raised about this before.

**Comment by LithiumToast** [comment]
I think it would be a good idea for `PrimitiveBatch` not to have the code for drawing shapes like I did with my implementation. There is already the `Shapes` namespace where the `PolygonF` could be used as input to the `PrimitiveBatch`. I guess the only thing missing is that each `IShapeF` needs someway to convert to a `PolygonF` so the `IShapeF` can be drawn with the `PrimitiveBatch`.

**Comment by craftworkgames** [comment]
Yeah, that's not a bad idea. I guess it would work just like `SpriteBatch` extensions but they would be extension methods on the `PrimitiveBatch` instead.

I think it makes sense to add a `ToPolygonF` method to the `IShapeF` interface since every shape can be converted to a polygon. However, I think it's an implementation detail that the `PrimitiveBatch` calls this method internally. It may not do that for some shapes like rectangles perhaps.

I think both approaches above have merits, but the `DrawCircle` approach has another benefit that you could create some overloads so that you don't have to create a `CircleF` first.

For example:

    myPrimitiveBatch.DrawCircle(radius, position, color);

We probably also want a way to draw filled shapes. Something like `DrawFilledCircle` perhaps.

**Comment by craftworkgames** [comment]
Oh I just had another thought based on what you said before.

It seems the `PrimitiveBatch` is not really about drawing shapes. It's about drawing anything and it could also be used as an alternative way to draw Sprites. The benefit would be that it's actually drawing them in 3D space and could provide some interesting ways to rotate and skew them in the third dimension. Kinda like how the [cards rotate in Hearthstone](https://www.youtube.com/watch?v=9HI3xE4xjuM)

**Comment by LithiumToast** [comment]
I think having a vanilla `PrimitiveBatch` which is extended via extension classes is best. People can add there own extension methods for their specific uses in their games.

We might as well implement the `PrimitiveBatch` for 3D and create an extension for sprites and other 2D things to use it directly. I think this would make the most sense as handling game drawing code between a `SpriteBatch` and `PrimitiveBatch` might get confusing. If you will, the "one batch to rule them all".

**Comment by craftworkgames** [comment]
> handling game drawing code between a SpriteBatch and PrimitiveBatch might get confusing. If you will, the "one batch to rule them all".

The way I see it they have a choice. They can continue to use `SpriteBatch` as they have always done or they can use the new `PrimitiveBatch` as an alternative.

**Comment by LithiumToast** [comment]
I think that's a good idea. It would probably be cool if the `PrimitiveBatch` could be configured to add and hold a buffer of different type of vertex data. I'm sure not all games will want use the same type of vertex data. The "texture, color, position" might be a common type of vertex data, but I don't think we should force people to hold on to a buffer of that type and never use it.

**Comment by LithiumToast** [comment]
Oh, I just remembered about boxing struct values via interfaces... We should not have the `PrimitiveBatch`  accept an `IShapeF` as parameter for drawing unless we use a generic parameter.
Something like this
```
void DrawShape<TShape>(TShape shape) where TShape : IShapeF
```

Same thing applies to extensions

**Comment by LithiumToast** [comment]
Scratch the buffer of different types of vertex data. I'm thinking of having each instance of `PrimitiveBatch` specify the type of vertex data it will use. Something like

```
class PrimitiveBatch<TVertexType> where TVertexType : struct, IVertexType
```
Then we could create our own `SpriteBatch` implementation would be a wrapper for a `PrimitiveBatch<VertexPositionColorTexture>`. For collision detection debug drawing I don't really care about having textures so I would probably use `PrimitiveBatch<VertexPositionColor>` or create a `IVertexType` named `VertexPositionColorNormal` just for using `PrimitiveBatch<VertexPositionColorNormal>.

For `PrimitiveBatch` we obviously want `Begin` and `End` methods, but for drawing I'm thinking of not having a `AddVertex` method but instead a `Draw` method which takes in the `PrimitiveType` and array of `TVertexType` vertices.

**Comment by LithiumToast** [comment]
Just to be consistent with `SpriteBatch` we should implement different "sorting techniques" like what is available with `[SpriteSortMode](https://msdn.microsoft.com/en-ca/library/microsoft.xna.framework.graphics.spritesortmode.aspx)`.

`Deferred`: Each `Draw` call adds a render operation to a list. When `End` is called the list is iterated and for each item in said list, the `GraphicsDevice.DrawPrimitives` is invoked. After the iteration, the list is cleared.
`Immediate`: Each `Draw` call directly invokes `GraphicsDevice.DrawPrimitives`.

Now 'Texture' sorting would be specific to vertex data... I'm not sure how to approach this exactly but perhaps we need some way hold some "tag" data with each `Draw` call which could be sorted by. This tag data could be for textures, z-order (important for alpha blending), or anything really.

**Comment by LithiumToast** [comment]
Real Time Collisions, the book I'm using for the collision detection feature, wrote about how to do this type of sorting for z-order, texture and other stuff [here](http://realtimecollisiondetection.net/blog/?p=86). His proposal was to mark each type of draw call with one or more bit values. This value of bits becomes the sorting key for deferred rendering.

**Comment by craftworkgames** [comment]
All good ideas. I'm interested to see what you come up with.

**Comment by LithiumToast** [comment]
I got permission from Cygon to base our `PrimitiveBatch` off of his `PrimitiveBatch` from the [Nuclex Framework](https://nuclexframework.codeplex.com). Will work on that no later than this weekend.

**Comment by craftworkgames** [comment]
Awesome. How did he contact you? Can you post it or link to it here?

**Comment by LithiumToast** [comment]
@craftworkgames https://twitter.com/lustranks/status/705198402858921984

**Comment by LithiumToast** [comment]
@craftworkgames [pdf email transcript](https://github.com/craftworkgames/MonoGame.Extended/files/157479/Re.Can.I.develop.some.open.source.code.based.on.N.-.Lucas.Girouard-Stranks.pdf)

**Comment by InfiniteProductions** [comment]
Don't know if anyone would be interested in this [Primitive2D](https://sourceforge.net/projects/primitives2d/) for XNA I found a while ago, it includes basic shapes too.

**Comment by craftworkgames** [comment]
@InfiniteProductions The Primitives2D code is already in the `develop` branch as SpriteBatch extension methods in the `Shapes` namespace. It works pretty well, but the PrimitiveBatch should have some significant advantages.

**Comment by LithiumToast** [comment]
I'm filling the code for this in at #152

**Comment by LithiumToast** [comment]
@craftworkgames this can be closed
