### ISSUE TITLE
Dealing with the chaos

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#138]
Okay, so here's the thing. There's a lot of open issues and I'm having trouble figuring out what we should include in the next release.

Usually I would sit down and try to figure this stuff out myself, but I gotta be honest, the plan is unclear right now. So I've decided to try something different this time. I've raised this issue to get community feedback about how we should proceed.

This is going to be be a living document. I'll update it as we figure stuff out. Right now it's just a dump of all of the open issues so we can see them organized in one place. Some of these things are already being worked on. Others have been laying dormant for quite a while. We need to figure out which ones are the most important.

 - **Goal number one is to make games.** (the big features)
 - **Goal number two is to improve the user experience** (documentation, installers, release cycle, project templates, bug fixes, API improvements)

Both of these goals are important but we need to take a balanced approach to make sure we are always working towards both of them.

*If an issue isn't working towards one of the goals, it probably doesn't belong here.*

### Policy
 - Release early, release often

### Project and Deployment
 - VSIX Project Templates

### Documentation
 - Create a CONTRIBUTING.md guide
 - Generate API documentation
 - Let's Improve the github Wiki

### Big Features
 - Scene graphs
 - GUI system
 - Particle system
 - Transition animations using a fluent syntax
 - Spriter 2D skeletal animations
 - Spine 2D skeletal animations
 - New potentiel feature: grid library
 - Add an implementation of PrimitiveBatch
 - [Tiled] Work on Object Layers
 - Entity Component System
 - SVG importer and drawer? 
 - 2D lighting with shadowing effects
 - Simple collision detection 
 - Support for the Overlap2D level editor 
 - Support for WinForms and WPF embedding
 - tIDE map editor support
 - Tiled map editor support
 

### Other Enhancements
 - The great `Draw` method overhaul 
 - Object Pooling
 - Camera center
 - Camera2D limiting rectangle
 - Sprite atlas Content Importer

### Bugs
 - [Tiled] Rendering large maps uses a lot of memory
 - Tiled doesn't work when the tileset image is the wrong dimensions 
 - SpriteSheetAnimator is a shared content object
 - Tiled Map support for "Collection of Images"

**Comment by LithiumToast** [comment]
Just FYI, object pooling is a must for collision proxy and entities.

**Comment by craftworkgames** [comment]
@LithiumToast Yes I agree completely. I'm very happy with the work you've been doing. I think we are doing the right thing getting the upgrade to 3.5 ready. I realize collision detection is a big job but it's nice we are also getting `PrimitiveBatch` and object pooling out of it.

So I was thinking about goal number one last night - Making Games.

It seems silly to constantly work on a game development library without making games with it. So I think we absolutely need to make games. 

Some of you are already making games. This is fantastic. Btw, if you are working on a game with MG.Ex let me know. I'd like to have a page that features games made with the library.

For me, making games is more about creating demos for MG.Ex. That said, there's obviously a few problems making games:

 1. It's time consuming, (how are we going to have time to make games and work on the library at the same time)
 2. We'll need art assets.
 3. We probably won't be able to agree on which type of game to make.

To deal with these problems I've come up with the following ideas.

## Make Small Games

We probably won't be able to make big games. Let's focus on making small games, game demos and such. I think adding more game like demos to the library is an achievable goal. When I made the space game demo I discovered a handful of features missing from the library, and that's the point. Even though the demo isn't really a finished game yet, it's still serving a purpose.

One way to make small games is to treat them like a game jam. I'd like to start throwing together a game demo every couple of weeks as part of a game jam. Giving yourself 48 hours to make a game is a great way to try something new, experiment with an idea or just take a break from doing other things. If we get a game demo for the library out the other end, bonus!

## Use Free Art

Good art assets are hard to come by at the best of times. However, there are a number of really great free assets around. [Kenney](http://kenney.nl/assets), [GameArt2D](http://www.gameart2d.com/freebies.html), [GameDevMarket](https://www.gamedevmarket.net/category/2d/?order_by=price-low-high&genre=). 

Rather than trying to make games and find art it's easier to find art and make games. Adding the constraint that you have to use a particular art asset is a good way to keep the scope of the game down making it more likely you'll finish something. It may not be the game you always wanted to make, but at least it'll look good.
 
## Make All The Games

I don't expect everyone to agree on what type of games to make. At best I'd be happy if more than one person collaborated on a game. More than likely most people will want to make a different game, that's actually okay. I'd rather have a handful of different game demos even if they aren't finished. Remember the purpose of having game demos is to find ways to improve the library in real world scenarios as well as show how the library works.

**Comment by InfiniteProductions** [comment]
@craftworkgames: there is also the nice [openGameArt](http://opengameart.org) which offer tile sets (especially the cute one used in [xnaressources tilemap tutorial4](http://www.xnaresources.com/default.asp?page=Tutorial:TileEngineSeries:4)

I can't be more agree regarding making game for your library, but you have to consider doing this way provide a great/bigger help on how to improve your library too. 
First, because engine makers don't really care on how people use their work and what issue they have to deal with (easy example: Unity), second, people makes engines, get bored, give up (Engine Nine, Ploobs, SunBurn, and many others).
Using your own library/engine is a much more living/dynamic approach which is also more rewarding, as for example you can figure out yourself what is lacking, how to make it better and find issues.

To conclude: I think making very basic/simple games would be enough, at least at the beginning, as the most time consuming task is game design itself (make levels, campaign(s), stuff to keep players motivated), whereas the core development takes quite a fixed amount of time.

**Comment by Gixen** [comment]
If you dont mind a user of your tools to chip in...

Since im using MG.E in a game of mine any kind of documentation would be nice. Another tip is maybe  explain the use or intent of the feature like what was done in the blog like [this](http://dylanwilson.net/implementing-a-2d-camera-in-monogame) or [this](http://dylanwilson.net/sprites-and-spritebatch-extensions-in-monogame-extended), not just "We have a spritesheet animation feature." as a bullet point and then nothing more. That kind of documentation would be a huge move towards goal two in my opinion. Lot's of things can be forgiven if the ux is good enough =)

**Comment by craftworkgames** [comment]
> That kind of documentation would be a huge move towards goal two in my opinion.

@Gixen I completely agree. Documentation is important. It's just not easy. I'm trying to make an effort to improve the documentation but I've only got a limited amount of time to sink into the project each week. That's why I'm asking for help.

What I am going to try an do is create one or two pages on the wiki each week from here on out. Hopefully this will start building up some more knowledge about the library and motivate others to contribute to the documentation also.

> I can't be more agree regarding making game for your library, but you have to consider doing this way provide a great/bigger help on how to improve your library too. 

@InfiniteProductions Yep. That's exactly the point. For me, the only reason to make games is to improve the library.

**Comment by InfiniteProductions** [comment]
Some idea for making game "frameworks" (kind of what MS does with both platformer starker kit and card game kit):

card game (mostly solitaire)
match3
dash & time management
(the three style above are very common on suppliers like Big Fish Games)
eventually: Hidden Object Game
board game
platform game (screen based, horizontal and/or vertical scrolling)
shoot'em up (again: horizontal or vertical, or top down)
top-down map based game (RPG, turn per turn strategy)
racing game (top view)
isometric view game (RPG/adventure or board like Hero Quest or Space Crusade from Gremlins, or harder: oldies from 8-bits era: Alien 8, Hydrofool, Crafton & Xunk, MGT, Batman, Head Over Hell...)

And, maybe the most important thing: game UI example (main menu, settings, career/campaign main map = to choose level from)

+ a high-level code for managing levels/campaign and players (stats/achievements), load/save settings.

Obviously such frameworks would serve more as examples as they would be far not enough specific to get efficient, especially on all devices, but it would be also a nice start for people who have more idea than programming skills, and if game are open-source, others could come and improve the code, add better content, etc

**Comment by craftworkgames** [comment]
@InfiniteProductions That's a fantastic idea.

Let's call them *starter kits* so we don't get confused with using the word framework. 

It's interesting that you mention card games on the top of the list. I've been messing around with [Kenney's Boardgame Art Pack](http://kenney.nl/assets/boardgame-pack) lately with the idea of making a card game as one of the demos.

I think turning it into a starter kit is a much better idea. We could ship Visual Studio templates #106 perhaps and of course we'll make them open source on github.

> And, maybe the most important thing: game UI example

Yes, I agree. I've been discussing this with @LithiumToast  lately and we came to the conclusion that a GUI system #20 is the next most important feature of MG.Ex. I started working on one a few weeks ago but had to get some other things organized first. I'll be getting back into it this week.

**Comment by InfiniteProductions** [comment]
Starter kit is good, as for card games, there is at least two components:
- data structure (card values, names, order relationship, deck, hand, as defined in the great [Game::Cards](https://metacpan.org/pod/Games::Cards) Perl module)
- visual: either 2D rectangles or 3D for easy rotation and resizing (for playing animation: dealing, shuffling, etc like in many solitaire games), with very special care to keep things work on all platforms (so probably shaders may not be very welcome here)

I forgot a type of game: long distance record (see for example on agame.com): it just needs scrolling (vertical or horizontal or both), bonus (mostly fuel, repair & money or anything which have the same purpose), missions and achievements management.

I have also started my own game GUI toolkit, there will be a great choice :D.

**Comment by craftworkgames** [comment]
> I have also started my own game GUI toolkit, there will be a great choice :D.

Looking forward to seeing it.
