### ISSUE TITLE
Input listeners for event driven input

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#14]
The standard way to receive input using MonoGame / XNA is polling the state of the input devices during each `Update`. This works well in some situations, depending on what type of game you're making, but other times it's nice to be able to listen for input *events* instead.

LibGDX has a good set of [input listeners](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/InputListener.html) that can be used as a reference.

@ClassicThunder has also done some [good work in this area](https://github.com/ClassicThunder/MonoGame-EventDriven-Input)

**Comment by ClassicThunder** [comment]
@craftworkgames Hmm thats an interesting implementation. I've simply exposed the events and let the user subscribe to them. The LibGDX one seems to depend on there being a scene hierarchy though I like the idea of subscribing a class who's methods you override. Seems much cleaner than having multiple input instances or unsubscribing/resubscribing events. 

Also I intent to add touch events using an API similar to Apple's. For the first iteration it will be just the touches, I'll add tap detection later.

- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesMoved:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesEnded:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesCancelled:(NSSet *)touches withEvent:(UIEvent *)event;

**Comment by craftworkgames** [comment]
Yeah, I quite like a lot of the things they have done with LibGDX. Obviously not everything translates well into C# but subscribing to a class has some advantages over event subscription. 

We could probably work around MonoGame's TextInput if it's buggy, although, we should at least report the bug if it's not already.

I'm not familiar with Apples touch library but the code you posted looks reasonable.

I guess the first step is to come up with a high level API design that's consistent across different types of input.

**Comment by ClassicThunder** [comment]
I've added very basic touch events to [my input library](https://github.com/ClassicThunder/MonoGame-EventDriven-Input) Interesting changes [here](https://github.com/ClassicThunder/MonoGame-EventDriven-Input/commit/e33abf82c7d8d61c12cbbd7f4d8d9daa8cc5a24d). Worked on my Mac, iPhone 5s, and Windows 10 pc so I'm fairly content with the testing. 

I think its at a good spot for a version 1 release. Nice things like being able to subscribe classes (like LibGDX) are lacking but all the core functionality is there. Let me know what you think and I'll work on forking the project in.

**Comment by craftworkgames** [comment]
Looks good as a first version.

If you could put the code in a folder / namespace, something like MonoGame.Extended.InputEvents or something that'll be a good place to start.

I have some idea's of my own that I'd like to incorporate but I think the easiest way is to start with what you've done and keep iterating on it.

**Comment by ClassicThunder** [comment]
Just as an update I should have a pull request ready by the end of the week with the input library added in.

**Comment by craftworkgames** [comment]
> Just as an update I should have a pull request ready by the end of the week with the input library added in.

Awesome, looking forward to it. I've been working on getting the 0.2 release ready. I'll be sure to include this in it.

**Comment by craftworkgames** [comment]
Hey @ClassicThunder How are you going with this?

**Comment by ClassicThunder** [comment]
Hey sorry for the delay, had some issues with the nuget packages and during my triple checking I found a bug that needed fixing. 

Modified the sandbox to use new code. Let me know if there is anything that needs to be changed/cleaned up/

**Comment by craftworkgames** [comment]
Thanks @ClassicThunder. Everything looks good so far. If you don't mind I'm going to refactor some of the API to be more consistent with the rest of the library plus sprinkle in a few ideas of my own.

Great work.

**Comment by craftworkgames** [comment]
As you probably noticed, I made quite a few changes to the input listeners before the 0.2 release. Here's a summary of what I did and my thoughts behind the changes:

 - **Flattened the folder structure** to keep it consistent with the rest of the project, and to be honest I was having trouble finding my way around.
 - **Merged the Shared abstract and MonoGame classes** because it doesn't really make sense for MonoGame.Extended to be structured this way. 
 - **Renamed some of the classes** because the project is already about MonoGame, so prefixing the classes with MonoGame seems redundant. I'm using a naming convention to keep the classes grouped together as an alternative to folders.
 - **Deleted the README** because it became out of date quickly. I think it's great that you documented the usage and I plan to write a blog post about every feature of MonoGame.Extended, so I'll get back to this one soon.
 - **Refactored the InputManager** to make it more flexible. I wanted to make sure that the decision to poll each input device is in the hands of the user, rather than having all of them hard coded in one place.
 - **Changed the access modifiers** on some things to public. The idea is to make it easier to extend the library and implement your own derived classes.
 - **Renamed variables and properties** to make the code more self documenting. I believe that the code itself should be the best documentation, but not the only documentation.
 - **Refactored the MouseListener** quite a bit to reduce the amount of repetition and make the class easier to understand.
 - **Used a kind of observer pattern** in the InputManager and added Settings classes for the listeners. This is a kind of experimental API, I'm not sure if it will stay, but I figured its worth a shot to see how it goes.
 - **Lots of code clean-up** spent towards the end. I went over each class one at a time, several times to make everything consistent.
 - **Added Drag events** to the mouse listener and fixed some bugs. 
 - **The click events now fire on mouse up** rather than mouse down, more consistent with how WinForms events work.
 - **Removed the division by 120** for the scroll wheel value to make it more consistent with WinForms MouseWheel events.
 -  **More code clean-up** getting ready for the 0.2 release.

I really appreciate the work you put into it @ClassicThunder. I wouldn't have thought of all of the features without you. I know it will make a great addition to the library.

Thanks.

**Comment by ClassicThunder** [comment]
Hmm I'll have to look over the changes a bit more, there never was an onclick event so not sure how you changed it to mouse up.

**Comment by craftworkgames** [comment]
> there never was an onClick event so not sure how you changed it to mouse up.

Right, there never was an OnClick event. In the PR you had these in the `Input` class

        public abstract event EventHandler<MouseEventArgs> MouseDoubleClick;+
        public abstract event EventHandler<MouseEventArgs> MouseDown;
        public abstract event EventHandler<MouseEventArgs> MouseUp;

And these in the `MonoGameMouseEvents` class

        internal event EventHandler<MouseEventArgs> ButtonReleased;
        internal event EventHandler<MouseEventArgs> ButtonPressed;
        internal event EventHandler<MouseEventArgs> ButtonDoubleClicked;

After the refactor I ended up with these in the `MouseListener` cass

        public event EventHandler<MouseEventArgs> MouseDown;
        public event EventHandler<MouseEventArgs> MouseUp;
        public event EventHandler<MouseEventArgs> MouseClicked;
        public event EventHandler<MouseEventArgs> MouseDoubleClicked;
        public event EventHandler<MouseEventArgs> MouseDragged;

What I changed was `ButtonReleased` to `MouseUp` and `ButtonPressed` to `MouseDown` respectively. Then I added click and drag events.

> The click events now fire on mouse up rather than mouse down, more consistent with how WinForms events work.

Putting naming conventions aside, I think there's a real bug in your original code. It presented itself when I implemented the drag event. If we take a look at your code from the PR.

        private void OnButtonReleased(object sender, MonoGameMouseEventArgs args)
        {
            if (ButtonReleased != null) 
            {
                ButtonReleased(sender, args);
            }
        }

        private void OnButtonPressed(object sender, MonoGameMouseEventArgs args)
        {
            // If this click is within the right time and position of the last click, 
            // raise a double-click event as well.           
            if (ButtonDoubleClicked != null &&
                _lastClick.Button == args.Button &&
                (args.Time - _lastClick.Time).TotalMilliseconds < _doubleClickMaxTimeDelta &&
                DistanceBetween(args.Current, _lastClick.Current) < _doubleClickMaxMovementDelta)
            {
                ButtonDoubleClicked(sender, args);
                //args.Time = new TimeSpan(0);
            }
            else if (ButtonPressed != null) 
            {
                ButtonPressed(sender, args);
            }

            _lastClick = args;
        } 

The problem is that *clicks* don't happen when the button is *pressed* they actually occur when the button is *released*. Without this, there's no way of knowing if the user has dragged the mouse. Imagine you clicked your mouse, then dragged it. The resulting actions would be pressed -> released (no movement) followed by pressed => moved => released.

> The original library was meant to mimic the windows message queue and a lot of the things you changes were to maintain that. For example the separation of shared and monogame along with the lack of drag and click events. 

Fair enough, I guess the goals of our projects are a bit different. 

> Original goal being the below is used on windows while the conversion from polling to events is a drop in replacement for non windows projects.

What do you mean by non-windows projects? What kind of project would you drop it into?

**Comment by ClassicThunder** [comment]
```
private void OnButtonPressed(object sender, MonoGameMouseEventArgs args)
    {
        // If this click is within the right time and position of the last click, 
        // raise a double-click event as well.           
        if (ButtonDoubleClicked != null &&
            _lastClick.Button == args.Button &&
            (args.Time - _lastClick.Time).TotalMilliseconds < _doubleClickMaxTimeDelta &&
            DistanceBetween(args.Current, _lastClick.Current) < _doubleClickMaxMovementDelta)
        {
            ButtonDoubleClicked(sender, args);
            //args.Time = new TimeSpan(0);
        }
        else if (ButtonPressed != null) 
        {
            ButtonPressed(sender, args);
        }

        _lastClick = args;
    } 
```

That code is checking to see if two subsequent clicks are close enough together to qualify for the double click event. Using the WMQ it goes as below assuming the 2nd double click event is within the specified time and range. My point is this concepts of clicks is something you added in and didn't exist before.

down even
up event
double click event
up event

> What do you mean by non-windows projects? What kind of project would you drop it into?

IMO on windows nothing beats directly hooking into the windows messaging queue directly. Personally I use it and what was added to MGE is the fallback for when the WMQ is not available. Point being the changes make sense if you disregard WMQ compatibility and consistency.

**Comment by craftworkgames** [comment]
> Using the WMQ it goes as below assuming the 2nd double click event is within the specified time and range. 

This looks like what you are referring to?
https://msdn.microsoft.com/en-us/library/aa931259.aspx

> My point is this concepts of clicks is something you added in and didn't exist before.

Yes, I added a `Click` event but I didn't invent the concept of *clicks*. The goal for me was to mimic the behavior of the events in the WinForms or WPF frameworks.

> That code is checking to see if two subsequent clicks are close enough together to qualify for the double click event.

Maybe the behavior of the WMQ is different to WinForms, but to me, your code for the `ButtonDoubleClicked` event seems to have a bug. 

I just wrote a little WinForms application to prove it.

            MouseDown += (sender, args) => Trace.WriteLine(DateTime.Now + ":MouseDown");
            MouseUp += (sender, args) => Trace.WriteLine(DateTime.Now + ":MouseUp");
            Click += (sender, args) => Trace.WriteLine(DateTime.Now + ":Click");
            DoubleClick += (sender, args) => Trace.WriteLine(DateTime.Now + ":DoubleClick");

When the mouse button is *pressed* then *released* a few seconds later, the `Click` and `MouseUp` events fire together.

    26/08/2015 11:55:19:MouseDown
    26/08/2015 11:55:22:Click
    26/08/2015 11:55:22:MouseUp

Similarly, when the mouse is *clicked* then *clicked* again, but this time with a delay between *pressed* and *released* of the second click the `DoubleClick` and `MouseUp` events get fired together.

    26/08/2015 11:59:24 AM:MouseDown
    26/08/2015 11:59:24 AM:Click
    26/08/2015 11:59:24 AM:MouseUp
    26/08/2015 11:59:24 AM:MouseDown
    26/08/2015 11:59:26 AM:DoubleClick
    26/08/2015 11:59:26 AM:MouseUp

This proves that the `ButtonDoubleClicked` should be called from `OnButtonReleased` not `OnButtonPressed`.

> WMQ compatibility and consistency (which probably makes sense considering monogame's focus on mobile).

I can't see any compelling reason why MonoGame.Extended needs to have WMQ compatibility. My vision is that these input events will eventually be used for creating GUI's for games.

**Comment by ClassicThunder** [comment]
> This proves that the ButtonDoubleClicked should be called from OnButtonReleased not OnButtonPressed.

Sorry for the delay but this is the only thing I strongly disagree with. Please try double clicking an icon on your desktop. When does the double click register. Also pleas double clicking some text in this editor. When does the selection mode change?

**Comment by craftworkgames** [comment]
> lease try double clicking an icon on your desktop. When does the double click register?
> Also pleas double clicking some text in this editor. When does the selection mode change?

Good point. That's certainly registering double click on mouse down in those cases.

> Double click should be on the second mouse down to maintain consistency with literally everything.

It's not literally everything. I've already shown the behavior of WinForms is not consistent. There's also [this question](http://stackoverflow.com/questions/14731304/why-doesnt-doubleclick-event-fire-after-mousedown-event-on-same-element-fires) from VB.NET and [this page](http://www.quirksmode.org/dom/events/click.html) from JavaScript. The primary justification seems to be handling drag events.

However, I will concede that I may have jumped to the wrong conclusion to quickly. There's also [this page](https://msdn.microsoft.com/en-us/library/windows/desktop/gg153548(v=vs.85).aspx) that confirms that double click should indeed happen on mouse down. 

And now that I think about it, we will want the behavior to be consistent with double tap on touch screens. I've raised a bug #42 to get this sorted out.
