### ISSUE TITLE
Sprite animation using sprite sheets

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#15]
We've all seen 2D animation using the [frames of a sprite sheet](https://github.com/libgdx/libgdx/wiki/2D-Animation). 

This is reasonably easy to implement but we want to design a clean and consistent API that works well with other types of animation (e.g. skeletal and transitions). Also, be careful not to leak the animation code into the base `Sprite` classes.

**Comment by cra0zy** [comment]
I'll be adding an Update method to Sprite class for setting animation speed and current frame.

**Comment by craftworkgames** [comment]
Hey @cra0zy 

Thanks for taking on this job. I've been thinking about it for a while but haven't started anything.

> I'll be adding an Update method to Sprite class for setting animation speed and current frame.

Please don't modify the `Sprite` class. I know it sounds silly, but I'd really rather keep the Sprite class as simple as possible and use it as a building block for other functionality. There's 2 ways to achieve this:

### Option 1: Create a derived class called `AnimatedSprite`

Doing it this way would allow you to add an `Update` method to the `AnimatedSprite` class and keep the animation code isolated from the `Sprite` class. Separation of concerns.

### Option 2: Create a `SpriteAnimator` class

An alternative approach is to create an animator class that takes a `Sprite` and a `TextureAtlas` in it's constructor as an animation target. This is similar to [how LibGDX does it](https://github.com/libgdx/libgdx/wiki/2D-Animation).

The advantage of this approach is that we could create different types of animators and isolate the code in a MonoGame.Extended.Animations namespace.

My current preference is option 2. Let's discuss.
