### ISSUE TITLE
[SceneGraph] Scene graph click events

### ISSUE THREAD

**Issue by rcurtis** [craftworkgames/MonoGame.Extended#151]
I'd like to be able to attach listeners to objects in the scene graph and get events on when touch/click events happen over them.  I made a branch of my own to demonstrate.  I don't think this code reflects anything that should be accepted into the code base, but it should demonstrate what I'm seeking to be able to do: https://github.com/rcurtis/MonoGame.Extended/commit/1dfa9a1d1f078d5074ec56aaee23e4cb874f30fa

If this functionality already exists and I've missed it, i apologize.

Thanks,
Robert

**Comment by craftworkgames** [comment]
Hi @rcurtis 

It's an interesting idea. I believe [LibGDX](https://github.com/libgdx/libgdx/wiki/Scene2d) does something like this with their scene 2d library.

It seems a little odd to me to couple the input system with the scene graph system directly. I mean, it's easy enough to achieve the same thing in several other ways. It's certainly open for discussion though.

The scene graph code is still pretty new and I'm sure there's plenty of room for improvement. This could be one of them.

**Comment by rcurtis** [comment]
@craftworkgames 

I agree with not coupling the input to the scene graph by necessity.  But providing the option to let the graph handle click/touch propagation would allow for pretty complex interactions while providing only basic tools.

Like I said in my original post, I'm not sure the best way to implement this, but I think its a worth while feature.

-Robert

**Comment by craftworkgames** [comment]
Looks like we're going to revisit the scene graph feature shortly #305
