### ISSUE TITLE
Proposal: add "bleeding" viewport adapter

### ISSUE THREAD

**Issue by emkrcko** [craftworkgames/MonoGame.Extended#159]
I have implemented what I call a bleeding viewport adapter which is a variation of BoxingViewportAdapter with added benefit of better scaling (well, a bit nicer) to different resolutions. 

The idea behind this viewport adapter is to define "bleed" areas (horizontal and vertical) which could be safely cut off if needed.
For example, you define your world to be 1348x900 pixels and create all graphics for that resolution, but you define a "bleed" of 148x140 (so that's 74px from left and right, and 70px from top and bottom edges) which creates a "safe area" where you put all important, interactive stuff. Outside of the safe area you add content which is not important for gameplay.

These example values (1348x900 world, with 148x140 bleed) allow you to have game which scales at least to 3:2, 16:10, 16:9, 4:3 and 5:3 resolutions without letterboxing (and that's most of mobile/tablet devices out there).

The point of opening this issue is that I think this might be useful to others so maybe it could be added to MonoGame.Extended?

In essence, this behavior could be added to BoxingViewportAdapter since setting bleed to 0 makes it behave exactly the same as BoxingViewportAdapter.

Here's the code:

```cs
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace MonoGame.Extended.ViewportAdapters {

    public class BleedingViewportAdapter : ScalingViewportAdapter {

        public int HorizontalBleed { get; private set; }
        public int VerticalBleed { get; private set; }

        public BleedingViewportAdapter(GraphicsDevice graphicsDevice, int virtualWidth, int virtualHeight, int horizontalBleed, int verticalBleed)
            : base(graphicsDevice, virtualWidth, virtualHeight) {
            HorizontalBleed = horizontalBleed;
            VerticalBleed = verticalBleed;
        }

        public BleedingViewportAdapter(GraphicsDevice graphicsDevice, int virtualWidth, int virtualHeight)
            : this(graphicsDevice, virtualWidth, virtualHeight, 0, 0) {
        }

        public override void OnClientSizeChanged() {

            var viewport = GraphicsDevice.Viewport;

            var worldScaleX = (float)viewport.Width / VirtualWidth;
            var worldScaleY = (float)viewport.Height / VirtualHeight;

            var safeScaleX = (float)viewport.Width / (VirtualWidth - HorizontalBleed);
            var safeScaleY = (float)viewport.Height / (VirtualHeight - VerticalBleed);

            float worldScale = MathHelper.Max(worldScaleX, worldScaleY);
            float safeScale = MathHelper.Min(safeScaleX, safeScaleY);
            float scale = MathHelper.Min(worldScale, safeScale);

            var width = (int)(scale * VirtualWidth);
            var height = (int)(scale * VirtualHeight);
            var x = (viewport.Width / 2) - (width / 2);
            var y = (viewport.Height / 2) - (height / 2);

            GraphicsDevice.Viewport = new Viewport(x, y, width, height);
        }

        public override Point PointToScreen(int x, int y) {
            var viewport = GraphicsDevice.Viewport;
            return base.PointToScreen(x - viewport.X, y - viewport.Y);
        }
    }
}
```

**Comment by craftworkgames** [comment]
Yeah cool.

> In essence, this behavior could be added to BoxingViewportAdapter since setting bleed to 0 makes it behave exactly the same as BoxingViewportAdapter.

So do you think it would be better to add this to the existing `BoxingViewportAdapter` or have a separate `BleedingViewportAdapter`?

**Comment by raleksandar** [comment]
I think it might be better to add it to the existing `BoxingViewportAdapter` since it is just a variation of default behavior of `BoxingViewportAdapter` but I'm not sure.

I could make a PR adding this to the `BoxingViewportAdapter` if you'd like?

**Comment by craftworkgames** [comment]
That would be good. Thanks.
