### ISSUE TITLE
Drawing Tiled Maps does not treat background colors as transparent

### ISSUE THREAD

**Issue by Darthfett** [craftworkgames/MonoGame.Extended#161]
In my tiled map, I have some tiles defined where part of the tile has a white background (not transparent).  In Tiled Map Editor, this appears as transparent, but when I call TiledMap.Draw, these tiles draw with the white background:

http://imgur.com/dqpVPhJ

**Comment by craftworkgames** [comment]
This is not currently supported. The workaround would be to change the white pixels to transparent pixels using `.png` format for the texture. I'll make this issue a bug and we'll consider it for a future release.
