### ISSUE TITLE
Spriter 2D skeletal animations

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#17]
[Spriter](http://www.brashmonkey.com/) is another 2D skeletal animation tool (see #16). I don't think there's official support for MonoGame. A quick google revealed [this](http://brashmonkey.com/forum/index.php?/topic/3057-monogame-implementation/)

Ideally it would be good if the animation API is shared between Spriter and Spine where it makes sense. Although, I suspect most people will be using one or the other. I own both these tools so I can do some testing.

**Comment by aienabled** [comment]
It seems there is now an official support for it. Link from the main site leads to this repository https://github.com/loodakrawa/SpriterDotNet Looks like a decent implementation.

**Comment by craftworkgames** [comment]
That's awesome.

**Comment by craftworkgames** [comment]
No interest in this feature.
