### ISSUE TITLE
Mouse listener still active when window is Inactive

### ISSUE THREAD

**Issue by Scellow** [craftworkgames/MonoGame.Extended#171]
The Mouse listeners is still listening for inputs even if the window is not active (background, minimized)

I believe it's an issue since we can't disable it without removing them

OS tested:

Windows 10 x64

``` csharp
namespace TheRoguer.Client.Legacy
{
    public class PlayerController : InputListenerManager
    {
        private KeyboardListener m_keyboardListener;
        private MouseListener m_mouseListener; 

        public PlayerController(Realm realm) : base()
        {
            m_mouseListener = AddListener(new MouseListenerSettings());
            m_keyboardListener = AddListener(new KeyboardListenerSettings());

            m_mouseListener.MouseClicked += On_MouseClicked;
            m_keyboardListener.KeyPressed += On_KeyPressed;
        }

        private void On_KeyPressed(object sender, KeyboardEventArgs e)
        {
            Console.WriteLine(e.Key);
        }

        private void On_MouseClicked(object sender, MouseEventArgs e)
        {
            Console.WriteLine(e.Button);
        }
    }

}
```

Proposition:

I can check myself the state of the window and decide to handle the inputs or no, but it would be nice if we could add that option in the InputListenerSetting

**Comment by Scellow** [comment]
My bad, it only affect the mouse listener!

One more thing, while window is active, if i press elsewhere the cursor comes back in the edge of that window

**Comment by craftworkgames** [comment]
Yeah, good catch. Do you know how to detect the state of the window? Could you post the code.

**Comment by ExCellRaD** [comment]
You can check if the game is active 
`if(Game.IsActive`
and if the cursorposition is within window bounds 
`&& GraphicsDevice.Viewport.Bounds.Contains(Mouse.GetState().Position))`

**Comment by Aurioch** [comment]
Well, I have tried to address the issue.

The thing is... it is sort of an intended behavior, as the `Update` method is being called from the game even when it doesn't have focus, so it's the user's (that is, programmer) job to handle it (such as `if (Game.IsActive) _mouseListener.Update(gameTime)`). Unless we make it more complicated by passing `Game` as a parameter, there's no way to make the listener pause itself... and frankly, I don't think we should do it.

However, there is a small workaround: if you create and register `InputListenerComponent` and attach listeners to it, it will automatically pause all attached listeners when the game loses focus.

Other option would be exposing 2 methods like `PauseListener` and `ResumeListener` in order for them to be attached to `Game.Activated` and `Game.Deactivated` events, but the onus will be again be on user to do it.

**Comment by craftworkgames** [comment]
The solution we have is good enough for now.
