### ISSUE TITLE
Pipeline DLL don't working

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#172]
My friend wasn't able to build our game simply by downloading from the repo, so I sent the entire project via a .zip file to him, but he still is having troubles. I checked somethings on his PC and figured that the MG Extended custom pipeline wasn't working, on the files I have this at the Importer and Processor Settings:

> [missing] TiledMapImporter
> [missing] TiledMapProcessor
> [missing] BitmapFontImporter
> [missing] BitmapFontProcessor

I have no ideia of what is going on, the same project works fine on my machine. I tried to create a project from the scratch and load a TiledMap, it worked. The problem is with the game project, so, here is it: https://www.dropbox.com/s/cn7bpfnjokjr9rt/Super%20Pete%20The%20Pirate.rar

I tried to update the Nuget Packages and reset it on the Content References, but nothing changed.

**Comment by LithiumToast** [comment]
Works fine? What's the exception he is getting?

**Comment by rafaelalmeidatk** [comment]
> C:/Users/[...]/Desktop/Super Pete The Pirate/Super Pete The Pirate/Content/maps/map1.tmx : error : Failed to create importer 'TiledMapImporter'

> C:/Users/Gabriel/Desktop/Super Pete The Pirate/Super Pete The Pirate/Content/fonts/Alagard.fnt : error : Failed to create importer 'BitmapFontImporter'

These he receives at build time.

**Comment by craftworkgames** [comment]
What version on MonoGame does he have installed?

MonoGame.Extended <= 0.4 must use MonoGame 3.4
MonoGame.Extended >= 0.5 must use MonoGame 3.5

This includes the version of the Content Pipeline installed on the machine.

**Comment by rafaelalmeidatk** [comment]
MonoGame 3.5 and MG.Extended 0.5, the Pipeline is the last too.

**Comment by craftworkgames** [comment]
Yeah, that is very weird. I don't fully understand the problem but I think I've found a solution.

If you uninstall and re-install MonoGame.Extended it seems to solve it. Run the following commands from the NuGet Package Manager Console.

    Uninstall-Package MonoGame.Extended
    Install-Package MonoGame.Extended

Let me know how it goes.

**Comment by rafaelalmeidatk** [comment]
Haha, it worked. Thanks Dylan :D
Is there some explanation?

**Comment by craftworkgames** [comment]
The other thing that seems to work is deleting the `packages` folder.

> Is there some explanation?

I've been trying to figure out exactly what's going on here but there's no obvious explanation that I can see. It feels like something to do with the way NuGet behaves. For some reason it's getting confused about what packages are already installed or something.

I've run into similar issues with NuGet before in non-game projects. So I don't think it's got anything to do with MonoGame or MonoGame.Extended at all.

There's a small chance it really is a bug in MonoGame.Extended but without a better explanation I'm gonna close the issue. If it comes up again, we'll open a new one.

**Comment by craftworkgames** [comment]
Awesome looking game btw. I'm pretty sure I've seen it around twitter a few times. Good luck with it guys. 

Once it gets closer to completion I'd be more than happy to help promote it as a "made with MonoGame.Extended" game.

**Comment by craftworkgames** [comment]
If you draw the HUD in a separate sprite batch you can prevent it from being affected by the camera.

            spriteBatch.End();

            spriteBatch.Begin(samplerState: SamplerState.PointClamp);
            // Draw the Hud
            _gameHud.Draw(spriteBatch);
            spriteBatch.End();

**Comment by rafaelalmeidatk** [comment]
> I've run into similar issues with NuGet before in non-game projects. So I don't think it's got anything to do with MonoGame or MonoGame.Extended at all.
I agree, this issue is not related exclusively with MonoGame.

>Awesome looking game btw. I'm pretty sure I've seen it around twitter a few times. Good luck with it guys.
Thanks! Yes, we are trying to spread our team on Twitter, we stoped the development of the game for some time but we are working on it again.

>If you draw the HUD in a separate sprite batch you can prevent it from being affected by the camera.
Thanks, I tested the HUD on a small map, so I didn't noticed the mistake, haha :P
