### ISSUE TITLE
Changing Resolution at Runtime

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#173]
IllustriousEpoch reported an issue on [the forums](http://community.monogame.net/t/runtime-resolution-changing/) about the ability to change the resolution at run-time; or more importantly, the fact that the viewport adapters don't handle it automatically.

>  I have the initial width and height set to 1280x720, and then I hit a button that changes it to 1600x900.

    graphics.PreferredBackBufferWidth = 1600;
    graphics.PreferredBackBufferHeight = 900;
    graphics.ApplyChanges();

> The actual rendered image stays the same fidelity and size, and position, the window simply expands outward and draws black anywhere outside the original 1280x720 area. Again, input is scaled correctly for the mouse and things.

**Comment by bsimser** [comment]
Based on a comment by IllustriousEpoch on April 25th is this really a bug? He discovered that he was setting a RenderTarget2D at LoadContent time and never updated it when he switched resolutions. Once he did it worked. Not sure this is a bug or not?

**Comment by craftworkgames** [comment]
Good point.
