### ISSUE TITLE
Suggestion: Interval<T>

### ISSUE THREAD

**Issue by guFalcon** [craftworkgames/MonoGame.Extended#174]
Hi, I'm [Psilo](http://community.monogame.net/users/throbax/activity) the developer of [Throbax TD](http://community.monogame.net/t/throbax-td-windows/6617) and I'd like to share some code with you.

# Introduction
We basically are [three guys](http://www.unterrainer.info/Home#/about) developing a game (which is already on steam early-access by the way) and during the last few years I generated quite a lot of code. A few weeks ago I saw the MonoGame.Extended project and I want to contribute. Our game-engine is quite extensive so we'll do this step-by-step starting with the smaller, more refined parts of it.

The idea is to discuss every feature/extension/structure here so that we get a feeling if you people even want it in your library or if I have to modify it and to which extent.
If I should propose to add things already present in the library, then I'm terribly sorry. I don't want to be rude, I just don't have the time to get perfectly accustomed with MonoGame.Extended right now. That will change over time, promised.
So bring on the good ideas / critique / votes or help.

# `Interval<T>`
When programming a game or, frankly speaking, when programming anything, you will be confronted with intervals.
I remember reaching the point, where I began thinking about a separate class, when I was working on the particle engine. I had about 30 values to track per particle (velocity, starting position, rotation, acceleration...) and each one of them had an upper- and lower boundary. As I'm not paid per line of code, I searched for a way to somehow reduce the length and improve the readability of it (int minNumberOfParticles, maxNumberOfParticles; float minRotation, maxRotation...).
The Interval class is a handy way to produce shorter and more readable code while introducing a new level of consistency and, as I will explain right now, accuracy as well.
 
## Accuracy
We don't always take care about it, but intervals don't only have upper- and lower bounds. They also have the property to include or exclude both bounds as well.
And when we have to take care about that, we almost certainly treat it differently each time.
 
Think about it. What do you mean by: "Pick a number between 0 and 100!".
It could be one of the following:
```
[0,100] …0, 1, 2, 3,…, 98, 99, 100
]0,100] …    1, 2, 3,…, 98, 99, 100
[0,100[  …0, 1, 2, 3,…, 98, 99
]0,100[  …    1, 2, 3,…, 98, 99
```

Most of the time we mean to include both boundaries, but we should be able to override that behavior.
 
## The requirements
So we want a generic class that you may instantiate using
	Only an upper and lower bound (you would use that constructor most of the time) and it would default the treatment of the boundaries as inclusive.
	A full constructor, specifying the treatment of the boundaries as well
 
It should have convenience-methods:
	IsInBetween, that takes a value and tells us if this given value lies within the interval
	An overload of this method, specifying the treatment of the boundaries as well, overriding the given treatment, but only for this single call.
	We would want it to adjust the values in a way, that the interval doesn't become irregular
Consider you built one:
`Interval<int> i = new Interval(3, 8);`
And now we set the lower bound to 9. That may actually happen during the lifetime of such an object and it may happen the other way round as well. Our object should, without having any other useful information, do the most sensitive thing there is to do and automatically set the upper bound to 9 as well.
 
When we think about the functionality, we should restrict the generic type-usage of this class to the interface IComparable, which allows us to do all the proper comparisons.
 
## The class/struct
After writing it I saw that I used it almost everywhere and since I was programming a game at the moment, the effort for the garbage collector was some concern. So I found that I could change it from a class to a struct (= no garbage collector overhead), without any side effects.
It doesn't change the way you use it at all.
 
## The consequences
After using it for a while now I found that the usage of this class helps making my code a lot leaner.
For example it reduced the LOC of my Particle class almost to half and it reduced the number of overloads for a few different classes as well .
Think about a randomizer-class, that gives you a random number between two given values (which I was very lucky to have when trying to change my code to support several multiplayer modes... Deterministic Lockstep is the keyword... But that is another story waiting to be told).

**Comment by ExCellRaD** [comment]
I was already working on similar stuff for the tweening animations. Currently there is a class `Range<T>` with two properties: `T Min` and `T Max`, then there is an `Interpolator<T>` class that is able to Add, substract, multiply and interpolate values of type T. The reason why these are there is for a truly generic implementation of the animations.
> Think about a randomizer-class, that gives you a random number between two given values

That would currently come down to:
`T random = Interpolator<T>.Interpolate(T min, T max, FastRand.NextSingle());`
which could be a in a method as:
`T random = Range<T>.GetRandomValue();`

About the types, currently most common value types are supported such as Vectors, Color, float, double with the option to add more using the `InterpolatorStore`.

**Comment by guFalcon** [comment]
Well. It's a small enough class to display it here. Maybe that helps you triggering some ideas or something. Your approach seems more complete and tidier.

```csharp
public struct Interval<T> where T : IComparable<T>
	{
		private T maximalValue;
		private T minimalValue;
		private bool isMinValueExclusive;
		private bool isMaxValueExclusive;

		/// <summary>
		///     Initializes a new instance of the <see cref="Interval&lt;T&gt;" /> structure.
		/// </summary>
		/// <param name="min">The minimal value.</param>
		/// <param name="max">The maximal value.</param>
		/// <param name="isMinValueExclusive">
		///     if set to <c>true</c> the lower bound is exclusive, otherwise its inclusive.
		/// </param>
		/// <param name="isMaxValueExclusive">
		///     if set to <c>true</c> the upper bound is exclusive, otherwise its inclusive.
		/// </param>
		/// <exception cref="ArgumentException">Min has to be smaller than or equal to max.
</exception>
		public Interval(T min, T max, bool isMinValueExclusive, bool isMaxValueExclusive)
		{
			this.isMinValueExclusive = isMinValueExclusive;
			this.isMaxValueExclusive = isMaxValueExclusive;
			// min > max OR max < min
			if (min.CompareTo(max) > 0 || max.CompareTo(min) < 0)
			{
				throw new ArgumentException("Min has to be smaller than or equal to max.");
			}
			minimalValue = min;
			maximalValue = max;
		}

		/// <summary>
		///     Initializes a new instance of the <see cref="Interval&lt;T&gt;" /> structure.
		///     The default way this structure treats the bounds is set to inclusive.
		/// </summary>
		/// <param name="min">The minimal value.</param>
		/// <param name="max">The maximal value.</param>
		/// <exception cref="ArgumentException">Min has to be smaller than or equal to max.</exception>
		public Interval(T min, T max)
		{
			isMinValueExclusive = false;
			isMaxValueExclusive = false;
			// min > max OR max < min
			if (min.CompareTo(max) > 0 || max.CompareTo(min) < 0)
			{
				throw new ArgumentException("Min has to be smaller than or equal to max.");
			}
			minimalValue = min;
			maximalValue = max;
		}

		/// <summary>
		///     Gets or sets the minimal value. Adjusts the max-value as well if it
		///     should currently be smaller than the given value.
		/// </summary>
		/// <value>The minimal value.</value>
		public T Min
		{
			get { return minimalValue; }
			set
			{
				if (value.CompareTo(maximalValue) > 0)
				{
					maximalValue = value;
				}
				minimalValue = value;
			}
		}

		/// <summary>
		///     Gets or sets the maximal value. Adjusts the min-value as well if it
		///     should currently be greater than the given value.
		/// </summary>
		/// <value>The maximal value.</value>
		public T Max
		{
			get { return maximalValue; }
			set
			{
				if (value.CompareTo(minimalValue) < 0)
				{
					minimalValue = value;
				}
				maximalValue = value;
			}
		}

		/// <summary>
		///     Gets or sets a value indicating whether the min value is inclusive
		///     (within the interval) or not.
		/// </summary>
		/// <value>
		///     if set to <c>true</c> the lower bound is exclusive, otherwise its inclusive.
		/// </value>
		public bool IsMinValueExclusive
		{
			get { return isMinValueExclusive; }
			set { isMinValueExclusive = value; }
		}

		/// <summary>
		///     Gets or sets a value indicating whether the max value is inclusive
		///     (within the interval) or not.
		/// </summary>
		/// <value>
		///     if set to <c>true</c> the upper bound is exclusive, otherwise its inclusive.
		/// </value>
		public bool IsMaxValueExclusive
		{
			get { return isMaxValueExclusive; }
			set { isMaxValueExclusive = value; }
		}

		/// <summary>
		///     Determines whether a specified value is in between the intervals
		///     boundaries.
		/// </summary>
		/// <param name="value">The value.</param>
		/// <returns>
		///     <c>true</c> if the given value is in between the specified value; otherwise,
		///     <c>false</c>.
		/// </returns>
		public bool IsInBetween(T value)
		{
			return IsInBetween(value, isMinValueExclusive, isMaxValueExclusive);
		}

		/// <summary>
		///     Determines whether a specified value is in between the intervals
		///     boundaries.
		/// </summary>
		/// <param name="value">The value.</param>
		/// <param name="minValueExclusive">
		///     if set to <c>true</c> treats the lower boundary as exclusive.
		/// </param>
		/// <param name="maxValueExclusive">
		///     if set to <c>true</c> treats the upper boundary as exclusive.
		/// </param>
		/// <returns>
		///     <c>true</c> if the given value is in between the specified value; otherwise,
		///     <c>false</c>.
		/// </returns>
		public bool IsInBetween(T value, bool minValueExclusive, bool maxValueExclusive)
		{
			bool isGreaterThanMin;
			bool isSmallerThanMax;
			if (minValueExclusive)
			{
				isGreaterThanMin = value.CompareTo(Min) > 0;
			}
			else
			{
				isGreaterThanMin = value.CompareTo(Min) >= 0;
			}

			if (!isGreaterThanMin)
			{
				return false;
			}

			if (maxValueExclusive)
			{
				isSmallerThanMax = value.CompareTo(Max) < 0;
			}
			else
			{
				isSmallerThanMax = value.CompareTo(Max) <= 0;
			}
			return isSmallerThanMax;
		}
```

**Comment by craftworkgames** [comment]
Yep. I like the concept but I'd say `Range` is a better name for it.

Also, I think having different *modes* for inclusive or exclusive values complicates things too much. It would be better in my opinion to just have a well defined behavior.

In other words, it's much easier to just say that the numbers are always inclusive. That way there's only one thing you need to know.

[0,100] …0, 1, 2, 3,…, 98, 99, 100

**Comment by guFalcon** [comment]
**OMG!**

"RANGE"

**OMFG!!!!**

I would never have thought of that. Thank you so much *dancing*

As for the boundaries... For INT that's right. No problem there. If you have the first value you DON'T want to have in the check, then you just subtract one from it.
But for a float range you'd have to subtract float.MinValue and that's what I wanted to circumvent with the overloads.
Just to inform; I perfectly agree with you on all points.

**Comment by craftworkgames** [comment]
> But for a float range you'd have to subtract float.MinValue and that's what I wanted to circumvent with the overloads.

I think you mean [`float.Epsilon`](https://msdn.microsoft.com/en-us/library/system.single.epsilon(v=vs.110).aspx) but I see your point.

**Comment by ExCellRaD** [comment]
Should I add a separate pull request for what I already have on this struct? I currently have it in the Easing folder, but I can see it being in the core too. What do you suggest?

**Comment by guFalcon** [comment]
Yup :)
But it's alright with me if we take that out. Happens hardly ever.

Proposed place for the Range-Struct within MG.Extended?
I would add it tonight and raise a PR...

**Comment by craftworkgames** [comment]
> Should I add a separate pull request for what I already have on this struct?

I've been finding large PR's like the tweening stuff really difficult to deal with. So maybe breaking it up and smaller PR's like this would be a good way to go.

**Comment by guFalcon** [comment]
You already have a Range in MG.Extended?

**Comment by craftworkgames** [comment]
> You already have a Range in MG.Extended?

Sort of. We have [two](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Particles/RangeF.cs) in the `Particles` namespace but they are not generic like your implementation. 

> Proposed place for the Range-Struct within MG.Extended?

I think the place for it should be the root namespace `MonoGame.Extended`.

**Comment by ExCellRaD** [comment]
> You already have a Range in MG.Extended?

I'll add what I already have, you can take a look and add what you think is missing.

**Comment by guFalcon** [comment]
Nice. Will have a look at in in the evening/night.

**Comment by guFalcon** [comment]
Nice implementation of range<T> by ExCellRad.
Closing this issue since his implementation is way better than mine.
