### ISSUE TITLE
Suggestion: Timer

### ISSUE THREAD

**Issue by guFalcon** [craftworkgames/MonoGame.Extended#175]
Hi, I'm [Psilo](http://community.monogame.net/users/throbax/activity) the developer of [Throbax TD](http://community.monogame.net/t/throbax-td-windows/6617) and I'd like to share some code with you.
# Introduction

We basically are [three guys](http://www.unterrainer.info/Home#/about) developing a game (which is already on steam early-access by the way) and during the last few years I generated quite a lot of code. A few weeks ago I saw the MonoGame.Extended project and I want to contribute. Our game-engine is quite extensive so we'll do this step-by-step starting with the smaller, more refined parts of it.

The idea is to discuss every feature/extension/structure here so that we get a feeling if you people even want it in your library or if I have to modify it and to which extent.
If I should propose to add things already present in the library, then I'm terribly sorry. I don't want to be rude, I just don't have the time to get perfectly accustomed with MonoGame.Extended right now. That will change over time, promised.
So bring on the good ideas / critique / votes or help.
# Timer

When programming a game you'll depend on timers heavily. Whether you have a damage effect, that needs to be calculated every x seconds, or a visual special effect to be controlled, you'll steer all that by adding time to variable and checking it against a limit.
Like with every work that gets repetitive, you'll get sloppy and you'll make mistakes.
And it's precisely for this reason that I wrote this class.
## Description

It should have a constructor where you would have to declare the timeout in milliseconds you want to measure.
Then you would have to update it every game-cycle, giving it the current gameTime object. Its update method will do the appropriate math with the appropriate values hidden in the gameTime object and return true, if the timeout has been reached.
It has some convenience-properties, which you may use to determine the percentage of time passed, to determine the time that is still left, or to reset or change the interval itself.
You may use a defaulted field in the update method, if you wish to add the excess time, that was not used after "triggering" the timer, to the next run of the timer (in case you have some sort of a cyclic timer because otherwise you would just "lose" this excess time).

A timer exposes several events like 'Fire' and 'Fired' which are triggered the moment it fires and afterwards and 'Updating' and 'Updated' which are triggered on update, regardless if the timer fires or not.
## Examples

Here are some examples of its usage:

This one declares a timer using the builder-pattern and sets it active.
`SpecialAbilityTimerSpawner = Timer.Builder(0f).isActive(true);`

This one is declaring two timers and connects them so that, when the first one fires, the second one gets started and the first one is set to in-active. Normally single timers are connected to themselves.

``` csharp
AbilityTimerPodRacer = Timer.Builder(0f).isActive(false).Fired(EnablingAbilityPodRacer);
AbilityDurationPodRacer = Timer.Builder(0f).isActive(false).Fired(DisablingAbilityPodRacer);
AbilityTimerPodRacer.Connect(AbilityDurationPodRacer);
```

And, a bit more complicated, this one is used for our spider. It waits until the first timer (AbilityTimerSpider) fires, then its starting to fade-out until the FadeOutTimer fires, then it stays invulnerable until the DurationSpider timer fires. That one starts to fade-in the spider again until the FadeIn timer fires. They all, of course, are connected.

``` csharp
AbilityTimerSpider = Timer.Builder(0f).isActive(false).Fired(StartFadingOutSpider);
AbilityFadeOutSpider =
        Timer.Builder(0f)
                .isActive(false)
                .Fired(StartInvulnerabilitySpider)
                .Updating(UpdatingAbilityFadeOutSpider);
AbilityDurationSpider = Timer.Builder(0f).isActive(false).Fired(StartFadingInSpider);
AbilityFadeInSpider =
        Timer.Builder(0f)
                .isActive(false)
                .Fired(EndAbilitySpider)
                .Updating(UpdatingAbilityFadeInSpider);
AbilityTimerSpider.Connect(AbilityFadeOutSpider).Connect(AbilityDurationSpider)._
     Connect(AbilityFadeInSpider);
```

You may not only subscribe to the Fired-event, but you may ask the timer on update if it just fired, like that:

``` csharp
if (SpecialAbilityTimerSpawner.Update(gameTime))
{
        // special activity is ready to start...                        
        MonsterTypes monsterType =
            MonsterMachine.GetMonsterTypeFromDescriptor(monsterToSpawnDescriptor);
        if (monsterType != MonsterTypes.NONE)
        {…}
}             
```

**Comment by craftworkgames** [comment]
Cool idea. We've already got [some timers](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended/Timers) so we'd have to think about how it all fits together but I can see how these would be useful in a real game.

**Comment by guFalcon** [comment]
I'll leave the issue open for a few days longer so everyone can have a look and 'vote'.
After that we should reach a decision about if we add it / leave it / rewrite it and close the issue.

**Comment by bsimser** [comment]
A couple of things (and I need to look at the current timers as there are already a couple that might do what you need, specifically countdown).

I think having a Func<T> or something that you can fire when a timer hits would be nice but I don't agree with doing what you're proposing:

```
if (SpecialAbilityTimerSpawner.Update(gameTime))
{
  // do something
}
```

Update(gameTime) is a void function in the framework and always has been. There's nothing for it to return and should continue to behave like this for anything (like a GameComponent). It simply runs all the updates for your game.

I think it would be better if you just checked properties or methods on each timer inside your update:

```
void Update(GameTime gameTime)
{
  if(SpecialAbilityTimerSpawner.IsActive()) 
  {
    // do something
    // do something else like
    SpecialAbilityTimerSpawner.Reset(gameTime);
  }
}
```

Better yet like I said, have an Action or Func or something fire when the timer fires so now you're just calling something like:

```
void Update(GameTime gameTime)
{
  SpecialAbilityTimerSpawner.Update(gameTime);
}
```

and inside that Func do your updates, call reset, chain to other timers, etc.

Also if you have timers depending on other timers, you probably want some kind of wrapper object to handle it all. Probably we could have a TimerComponent (derived from GameComponent) as it already has an Update and included in the main loop. So something like:

```
var timerComponent = new TimerComponent();
timerComponent.AddTimer(new CountdownTimer(1000, CountdownTimerFired));
Game.Components.Add(timerComponent);
```

Then you don't have to keep remembering to call/update your timers in your main game loop.

As suggested check out those new timers in the system as they might do what you need (or with some modifications like exposing Fire/Fired/Update/Updating events (much like handling events with the keyboard or mouse).

**Comment by craftworkgames** [comment]
We'll open this again if interest arises.
