### ISSUE TITLE
Suggestion: Utils

### ISSUE THREAD

**Issue by guFalcon** [craftworkgames/MonoGame.Extended#176]
Hi, I'm [Psilo](http://community.monogame.net/users/throbax/activity) the developer of [Throbax TD](http://community.monogame.net/t/throbax-td-windows/6617) and I'd like to share some code with you.
# Introduction

We basically are [three guys](http://www.unterrainer.info/Home#/about) developing a game (which is already on steam early-access by the way) and during the last few years I generated quite a lot of code. A few weeks ago I saw the MonoGame.Extended project and I want to contribute. Our game-engine is quite extensive so we'll do this step-by-step starting with the smaller, more refined parts of it.

The idea is to discuss every feature/extension/structure here so that we get a feeling if you people even want it in your library or if I have to modify it and to which extent.
If I should propose to add things already present in the library, then I'm terribly sorry. I don't want to be rude, I just don't have the time to get perfectly accustomed with MonoGame.Extended right now. That will change over time, promised.
So bring on the good ideas / critique / votes or help.
# Utils in General...

Like promised, here is the first description of some of our code.
It’s about the last few files in the utility-project, namely the Utils-partial classes.
I tried to write a short description about all of them.
Maybe there are some methods you think are helpful in general.
I would refactor them and document them nicely, then move them to your library, if you'd like...
## Utils

Most of those are well documented.
`InitGraphicsMode()` is the one I use to set the displaymode in our game. It's pretty complicated and has a rudimentarily tested linux-switch. Works on windows though.
## Utils.Collision

That one may be interesting. It contains some collision-sweep tests for several geometric primitives like the 
`SphereSphereSweep()` or `SpherePlaneSweep()` or `AxisAlignedBoundingBoxSweep()`.
It has `IntersectPixels()` which I use for high-precision pixel-to-pixel collision tests (after I did a cheap sweep-test of course), polygon tests and a method that encloses a rotated rectangle in an axis-aligned bounding-rectangle.
## Utils.Conversion

Contains all possible conversions like BandwidthToString (3333 -> 3.33MBit/sec) and vice versa, character-key conversions I don't use any longer, volume to db from the times of XACT-files, ConvertCsvToString and vice versa which I rely heavily upon in my translator (my localizations are in a single, optional many, UTF-8 csv-files).
Level-Screen-Tile coordinate conversions.
## Utils.Extensions

While trying to avoid them at work, I rely on extension methods heavily when I develop games. It just happened that way.
This class contains tons of them. Most prominent:
`Clamp()` for all number-types.
Read/Writer methods for non-primitive types from BinaryReader and to BinaryWriter which I use in my high-performance networking code.
The `EqualsZero()` (`GreaterZero`, `EEquals` and so on) methods are there to compensate the float-accuracy when comparing such values. They all employ an epsilon-value to the comparison. (float-values are hard to compare and may vary sometimes even if calculated the same way due to rounding-differences in mid calculation)
`Raise<T>()` is one I got praise for from excellent programmers. This extension method seems like nothing but in fact does the necessary null-check before invoking an event-handler and, as a bonus because of the way an extension method is interpreted, does that on a copy of the eventhandler-list. So it's automatically thread-safe. I don't invoke my events without it.
-> Seems to be pretty obsolete now in C# 6.0 (`event?.Invoke()` does exactly the same).
`IsInvocationList` checks if a handler is registered on an event and Remove… removes it.
The rest are the typical conversion-methods like `Rectangle` to `Rect` (own rectangle with rotation), Vector2 to Point, Vector2 to Vector3 and vice versa, and so on…
## Utils.Draw

Contains Bresenham calculations for a line and circle (returning List<Point>). Can be used to calculate Boundary brushes or to get the list of tiles covered by the range-circle of a tower (in tiles, not to draw a circle).
The rest is obsolete 2D drawing code I don't use any longer (fortunately).
## Utils.File

These methods are for in-game loading of audio- and image-files. It first tries to load .xnb files and, if not found in various directories, it looks for the image-file itself (.png or similar). Used in the cutscene-editor that works with non-xnb files (so that I don't have to change the paths in the XML file once the cutscene is through the pipeline and in the game.
## Utils.Fonts

The main method here is `WrapAndCutToFit()` which could use a major overhaul.
I use it to wrap text in game and then cut the number of lines for it to fit into a pre-defined viewport using a pre-defined font.
The methods `IndexOfNextCharAfterWhitespace()` and `IndexOfLastCharBeforeWhitespace()` are used to calculate the new caret-position in the text-input-boxes when pressing CTRL and ARROW-L/R the same time (jump word).
The rest are helper-methods like removing whitespace, etc…

**Comment by ExCellRaD** [comment]
I would also like to add Utils.Angle which would help with angle conversion (between radians, degrees, revolutions and even gradians). 
It implements methods of constraining the values to 0 and 2*pi or to -pi and +pi.
It also implements methods of getting the angle of a vector or getting a vector from and angle.

A very good implementation of this is visible at [Xenko engine](https://github.com/SiliconStudio/xenko/blob/master/sources/common/core/SiliconStudio.Core.Mathematics/Angle.cs)

**Comment by guFalcon** [comment]
Wow. That example is insane. And well written as well.
I never needed anything from toRadian() and toDegree().

**Comment by ExCellRaD** [comment]
Personally I only use radians, but it does seem like a neat little feature to add to a framework like this. Once it would be implemented, developers can use whatever unit they want for every function that needs an angle value.

**Comment by Jjagg** [comment]
About the angle conversion, MathHelper in MonoGame has a [ToDegrees](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/MathHelper.cs#L273) and [ToRadians](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/MathHelper.cs#L288) function that do this conversion (without normalization).

**Comment by ExCellRaD** [comment]
> About the angle conversion, MathHelper in MonoGame has a ToDegrees and ToRadians function that do this conversion (without normalization).

We allready added the `Angle` struct to the develop branch, it's nice to have the little extra functionality it gives.

**Comment by craftworkgames** [comment]
We'll open this again if interest arises.
