### ISSUE TITLE
Suggestion: CollisionGrid (like in QuadTree, but only a Grid)

### ISSUE THREAD

**Issue by guFalcon** [craftworkgames/MonoGame.Extended#177]
Hi, I'm [Psilo](http://community.monogame.net/users/throbax/activity) the developer of [Throbax TD](http://community.monogame.net/t/throbax-td-windows/6617) and I'd like to share some code with you.

# Introduction
We basically are [three guys](http://www.unterrainer.info/Home#/about) developing a game (which is already on steam early-access by the way) and during the last few years I generated quite a lot of code. A few weeks ago I saw the MonoGame.Extended project and I want to contribute. Our game-engine is quite extensive so we'll do this step-by-step starting with the smaller, more refined parts of it.

The idea is to discuss every feature/extension/structure here so that we get a feeling if you people even want it in your library or if I have to modify it and to which extent.
If I should propose to add things already present in the library, then I'm terribly sorry. I don't want to be rude, I just don't have the time to get perfectly accustomed with MonoGame.Extended right now. That will change over time, promised.
So bring on the good ideas / critique / votes or help.

# CollisionGrid
I already put this one on GitHub - [here](https://github.com/UnterrainerInformatik/collisiongrid).

The description is there and the code is already pretty much cleaned and refactored.

Tell me if you'd like to see it in MonoGame.Extended (and how to rename it since MonoGame.Extended already has a CollisionGrid).

**Comment by guFalcon** [comment]
@LithiumToast After looking at your board-posts I realized that you are currently working on a huge collision-library. Really looking forward to it. Especially the QuadTree implementation.

This grid is a QuadTree-replacement with a fixed grid. So no dynamically re-allocating new buckets.
I think it has a pretty good explanation in the readme.md file on the github-page.
(there is a CollisionGrid in MG.Ext already so one of them probably is incorrectly named; don't know which one though ;) Thought about both classes and I think they are both correctly named)

I think that would be a nice addition to your library, if you don't actually already have that in there.
There should be a performance-benefit compared to a QuadTree so I would use the CollisionGrid for all small, fixed size, targets are evenly distributed - environments.

**Comment by craftworkgames** [comment]
> there is a CollisionGrid in MG.Ext already

Speaking of which, I'm really not happy with the existing `CollisionGrid`. I'd like to remove it completely even before we've got a better replacement but I have a feeling a few people are using it. One thing we could do is remove it from the core library and just keep the code around for anyone that still needs it.

**Comment by guFalcon** [comment]
I just had a quick look but it seems like the CollisionGrid in MG.Ext is about something completely different.
But maybe I'm wrong.

**Comment by LithiumToast** [comment]
@guFalcon So I toke a look at your code here.

What is going on here is called [Spatial Partitioning](https://en.wikipedia.org/wiki/Space_partitioning) with using a "Uniform Grid". Here's screenshots the first two pages page on spatial partitioning and uniform grids from the book, [Real-Time Collision Detection](http://www.amazon.com/Real-Time-Collision-Detection-Interactive-Technology/dp/1558607323/ref=sr_1_1?ie=UTF8&qid=1462388698&sr=8-1&keywords=real+time+collision)

<img width="608" alt="screen shot 2016-05-04 at 12 03 21 pm" src="https://cloud.githubusercontent.com/assets/519592/15025927/8d3c5484-11f0-11e6-8a6b-6277ffddd82d.png">
<img width="608" alt="screen shot 2016-05-04 at 12 12 10 pm" src="https://cloud.githubusercontent.com/assets/519592/15026104/9ba839d8-11f1-11e6-869e-401f2e8ea64c.png">

So, uniform grids is just one of the algorithms available to choose from for the "broad phase" algorithm of the collection detection. The code you posted looks nice; I'll probably use it as a base when I get to writing the collision detection pull request.

**Comment by guFalcon** [comment]
Nice.
Thanks for the info.
I hope I made it clear in my readme.md that this is only the most basic method of spacial partitioning. Maybe I'll refactor that sometime. Maybe I'll start with the name *ggg*

Take what you want from the code. If you'd like me to change something just tell me.
Thx

**Comment by guFalcon** [comment]
@LithiumToast You know where it is if you should need it, so I close this issue.
