### ISSUE TITLE
Suggestion: LockFreeQueue

### ISSUE THREAD

**Issue by guFalcon** [craftworkgames/MonoGame.Extended#178]
Hi, I'm [Psilo](http://community.monogame.net/users/throbax/activity) the developer of [Throbax TD](http://community.monogame.net/t/throbax-td-windows/6617) and I'd like to share some code with you.

# Introduction
We basically are [three guys](http://www.unterrainer.info/Home#/about) developing a game (which is already on steam early-access by the way) and during the last few years I generated quite a lot of code. A few weeks ago I saw the MonoGame.Extended project and I want to contribute. Our game-engine is quite extensive so we'll do this step-by-step starting with the smaller, more refined parts of it.

The idea is to discuss every feature/extension/structure here so that we get a feeling if you people even want it in your library or if I have to modify it and to which extent.
If I should propose to add things already present in the library, then I'm terribly sorry. I don't want to be rude, I just don't have the time to get perfectly accustomed with MonoGame.Extended right now. That will change over time, promised.
So bring on the good ideas / critique / votes or help.

# LockFreeQueue
Well, this is somewhat named incorrectly since it, of course, has a lock, but it uses the .NET Interlocked Library to be as fast as it gets.
I use this one all over my game for multi-threaded consumer-producer setups.

[LockFreeQueue](https://github.com/UnterrainerInformatik/lockfreequeue)

**Comment by LithiumToast** [comment]
@guFalcon Microsoft already has an implementation of a [concurrent queue](https://msdn.microsoft.com/en-us/library/dd267265). Why re-invent the wheel here?

**Comment by craftworkgames** [comment]
Obviously the first thing to do here would be to compare the pros and cons of this `LockFreeQueue` with the built in .NET `ConcurrentQueue`.

If there's a clear benefit it might be worth including. Although, a performance benefit alone probably isn't enough. In my experience I've rarely used queues and when I have needed them performance isn't a concern. 

@guFalcon Why did you need this in your own game engine?

**Comment by guFalcon** [comment]
Whoa!
Sorry about that class.
I already had a summary on that one in the documentation so I just copied it when Dylan asked me for examples and now that I opened a few posts here I copied that bit again.

This class is very old.
I wrote that back in about 2010 when .NET 4.0 wasn't very widespread and therefore the concurrent queue wasn't out there for us. Although it's very fast I really don't believe for a second that it would be faster than MSs version :D...

... some time passes...

...Just looked it up.
On the other hand, the MS version looks like a locked standard-queue. There really COULD be a huge performance impact. Looks like I'm up for some testing tonight :)

@craftworkgames I use it in my ThreadPool, obviously (which is just as old as this beauty here), and basically everywhere I need a concurrent data-structure like message-queues in the Steam.net adapter, sprite-lists in-game so that I can freely add and remove sprites from those lists even from within their own update-call (which runs multi-threaded using tasks.parallel), in my LockFreePool implementation (object pooling), in my EditableList (a list where you just add and remove items concurrently but nothing really happens until you call Consolidate(); So you can decide the exact moment all of those changes apply), and in my in-game achievement-queue (every object may trigger an achievement in the update-call - again concurrently).

So I use it quite a lot. But that doesn't mean one would 'need' it.

I'm conducting tests and let you know the results.
IMHO, if the tests don't show that there's a HUGE benefit, I don't think you will need this.

### Mechanics of Throbax TD in Detail:
Standard XNA constructor-, loadContent-, Initialize- (and unloadContent-) behavior.

Update-loop:
```
// Here I prepare all of the renderTargets since my main-game loop is multi-threaded.
SingleThreadUpdatePass(gameTime);

Parallel.ForEach(Sprites, parallelOptions, item => item.Update(gameTime));
Parallel.ForEach(Flocks, parallelOptions, item => item.Update(gameTime));
Parallel.ForEach(LightningBolts, parallelOptions, item => item.Update(gameTime));
Parallel.ForEach(ParticleSystems, parallelOptions, item => item.Update(gameTime));
Parallel.ForEach(FlashEmitters, parallelOptions, item => item.Update(gameTime));

foreach (Sprite sprite in Sprites)
{
	sprite.AfterUpdateSingleThreadUpdatePass(gameTime);
}

foreach (IUpdatableVolatileSpriteList updatableVolatileSpriteList 
    in UpdatableVolatileSpriteLists)
{
	updatableVolatileSpriteList.Update(gameTime);
}
```

**Comment by guFalcon** [comment]
OK. Conducted some tests. Almost identical performance.
Like I expected the MS version is even slightly faster.
So it's a good implementation of the queue and not just a locking-wrapper.

I will remove my queue from my game then.
Thanks a lot for the pointers.
cu,
Psilo
