### ISSUE TITLE
Suggestion: SplitStopWatch

### ISSUE THREAD

**Issue by guFalcon** [craftworkgames/MonoGame.Extended#179]
Hi, I'm [Psilo](http://community.monogame.net/users/throbax/activity) the developer of [Throbax TD](http://community.monogame.net/t/throbax-td-windows/6617) and I'd like to share some code with you.
# Introduction

We basically are [three guys](http://www.unterrainer.info/Home#/about) developing a game (which is already on steam early-access by the way) and during the last few years I generated quite a lot of code. A few weeks ago I saw the MonoGame.Extended project and I want to contribute. Our game-engine is quite extensive so we'll do this step-by-step starting with the smaller, more refined parts of it.

The idea is to discuss every feature/extension/structure here so that we get a feeling if you people even want it in your library or if I have to modify it and to which extent.
If I should propose to add things already present in the library, then I'm terribly sorry. I don't want to be rude, I just don't have the time to get perfectly accustomed with MonoGame.Extended right now. That will change over time, promised.
So bring on the good ideas / critique / votes or help.
# SplitStopWatch

This class implements a stopWatch and is available on GitHub [here](https://github.com/UnterrainerInformatik/splitstopwatch).

Additionally to the normal stopWatch-functionality it may be used to debug out split-times as well. It measures the split-times and keeps track of the overall times in a variable.
Don't be afraid to stop the watch. Stopping doesn't mean you loose any value whatsoever. Think of it as a real-life stopWatch where you may press the start-button at any time after previously pressing the stop-button.

This class provides useful overloads that allow writing to a stream in a way that your measurement doesn't get compromised (the stopWatch is paused while writing to the stream). You may initialize it with a stream so that you can use all the overloads that take a string-argument or Console.Out is used as a default.
All the write-operations are performed as a printLine-call, so you don't need to close your assigned text with a newline-character.

It has a property 'isActive' that defaults to true. When this is set to false all calls to this class are aborted within a single if-statement in the called method. This is a convenience function so that you may leave your logging-code in the production code.
## Example

``` csharp
SplitStopWatch ssw = new SplitStopWatch();
ssw.start("started.");
  Thread.sleep(10);
ssw.split("split.");
  Thread.sleep(10);
ssw.stop("stopped.");
```

**Comment by LithiumToast** [comment]
@guFalcon I think this defeats the purpose of `GameTime`? I can only see `StopWatch` being useful for things which need strict timing but not are part of the game loop. For what purpose do you use this for in a game?

**Comment by craftworkgames** [comment]
We have a few [timers](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended/Timers) already. This could be an additional one. 

I'm with @LithiumToast on this. Could you provide some details on what you used it for @guFalcon?

**Comment by guFalcon** [comment]
Oh. Sorry.
We use this class for debugging only. That's why you can switch it on and off conveniently.

It's not built to become any part of the update-loop actually; just debugging by attaching different writers; nice output; nice API; small footprint.

**Comment by craftworkgames** [comment]
We'll open this again if interest arises.
