### ISSUE TITLE
Transition animations using a fluent syntax

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#18]
A while ago I worked on a project that had a fluent syntax for short animations in code. They are not as powerful as Spine #16 or Spriter #17 but they are very handy for creating quick animations and effects.

They syntax looked something like this:

    var transitionParameters = new TransitionParameters(1.0f, EasingFunctions.CubicEaseInOut);
    Animations
        .CreateSequence(playButton)
        .MoveTo(new Vector2(50, 50), transitionParameters)
        .MoveTo(new Vector2(700, 400), transitionParameters)
        .MoveTo(new Vector2(700, 230), transitionParameters)
        .MoveTo(new Vector2(400, 250), transitionParameters)
        .Delay(1.0f)
        .RotateTo(0, transitionParameters)
        .Delay(1.0f)
        .RotateTo(MathHelper.TwoPi, transitionParameters)
        .FadeOut(transitionParameters)
        .FadeIn(transitionParameters)
        .Play();

Of course, it doesn't have to work exactly the same way. Hopefully this will be a good starting point though. It might be useful to consider adding Timelines so that animations like this can be created in parallel.

**Comment by ClassicThunder** [comment]
I ran across this a while back and it is under the MIT license: [Glide by jacobalbano](https://bitbucket.org/jacobalbano/glide/src/4f1648dcf2cb428ebdd0bef1a43b08e37bc3ee6d?at=default)

**Comment by craftworkgames** [comment]
I ran across a couple more related libraries for reference.

[XnaTweener](https://xnatweener.codeplex.com/)
[GoKit](https://github.com/prime31/GoKit/wiki/1.-GoKit-Code-Basics)
