### ISSUE TITLE
Suggestion: ThreadPool

### ISSUE THREAD

**Issue by guFalcon** [craftworkgames/MonoGame.Extended#180]
Hi, I'm [Psilo](http://community.monogame.net/users/throbax/activity) the developer of [Throbax TD](http://community.monogame.net/t/throbax-td-windows/6617) and I'd like to share some code with you.
# Introduction

We basically are [three guys](http://www.unterrainer.info/Home#/about) developing a game (which is already on steam early-access by the way) and during the last few years I generated quite a lot of code. A few weeks ago I saw the MonoGame.Extended project and I want to contribute. Our game-engine is quite extensive so we'll do this step-by-step starting with the smaller, more refined parts of it.

The idea is to discuss every feature/extension/structure here so that we get a feeling if you people even want it in your library or if I have to modify it and to which extent.
If I should propose to add things already present in the library, then I'm terribly sorry. I don't want to be rude, I just don't have the time to get perfectly accustomed with MonoGame.Extended right now. That will change over time, promised.
So bring on the good ideas / critique / votes or help.
# ThreadPool

Also available on GitHub [here](https://github.com/UnterrainerInformatik/threadpool).

This class implements a thread-pool.
It buffers all the work items, which regrettably have to be classes, and reuses them. It only cleans them up at shutdown.

The reason we wrote this although there is the Parallels library is because unlike with that library you can enqueue different workers in a single thread-pool. It takes every function that is wrapped as a workload regardless of how many parameters or return-values it has. You can mix them all together and start the pool.

You may wait for the whole pool to finis (join) or on every single work-item.
## Example

``` csharp
threadPool = new ThreadPool(Environment.ProcessorCount, "testWorker");
List<IWorkItemState<bool>> wirs = new List<IWorkItemState<bool>>();

for (int i = 0; i < 50; i++)
{
    IWorkItemState<bool> wir = threadPool.EnqueueWorkItem(new Func<bool, bool>(Not), true);
    wirs.Add(wir);
}
threadPool.WaitForEveryWorkerIdle();
threadPool.ShutDown();
```

You may as well pause and resume whenever you please.

``` csharp
threadPool = new ThreadPool(Environment.ProcessorCount, "testWorker");
List<IWorkItemState> wirs = new List<IWorkItemState>();

for (int i = 0; i < 10; i++)
{
    if (i == 5)
    {
        threadPool.Sleep();
        Thread.Sleep(2000);
    }
    IWorkItemState wir = threadPool.EnqueueWorkItem(WriteToConsole, "test " + (i + 1));
    wirs.Add(wir);
}
threadPool.Wakeup();
foreach (IWorkItemState workItemState in wirs)
{
    workItemState.Result();
    workItemState.Dispose();
}

threadPool.ShutDown();
```

Take a look at the included unit-tests for further guidance.

**Comment by LithiumToast** [comment]
@guFalcon The design choice of multi-threading whole games will most likely take off in the next year or two. This is because multi-threaded rendering is possible with next generation graphics API like [Metal](https://developer.apple.com/metal/), [DirectX 12](http://www.geforce.com/hardware/technology/dx12), or [Vulkan](https://www.khronos.org/vulkan/). 

Having a thread pool and worker items could be one way to have the game function all the way. This type of design will have to be re-visted when the new MonoGame API that will sit on top of next generation graphics API is finished.

**Comment by craftworkgames** [comment]
> The design choice of multi-threading whole games will most likely take off in the next year or two.

I think it will be popular among a select group of game developers but I doubt everyone will care. A lot of indie game dev's won't need heavily optimized multi-threaded games any more than they need them now.

That said, if we are going to start adding threading features to the library I agree we should consider how this will work with next gen graphics API's. If and when MonoGame moves that way, we should move with it.

**Comment by guFalcon** [comment]
Totally agree with that.

This started way before the tasks.parallel library was out there to make the update-loop parallel for multi-core computers. So its performance is actually pretty impressive; very close to a tasks.parallel loop actually. But in-game we now use the tasks.parallel library as well.

Now we only use it to do different things, like loading game-assets or preparing data-structures in a single separated worker-thread.

```
Start pool, throw things in. If the player starts the level then wait for pool to become idle again and start the level.
```

I'm pretty sure one could do that with a simple worker-thread as well.

You could use the idea of having a simplified background-loader (thread) but I think that's all you can get out of that bit.

**Comment by craftworkgames** [comment]
We'll open this again if interest arises.
