### ISSUE TITLE
Should we support GameComponents?

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#184]
In the past I've been reluctant to support [`GameComponent`'s](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.gamecomponent.aspx) in MonoGame.Extended because some people [don't like them](http://gamedev.stackexchange.com/questions/4899/in-xna-should-i-use-the-built-in-game-component-classes) for [various reasons](http://blog.nuclex-games.com/2010/08/to-gamecomponent-or-not-to-gamecomponent/).

At the very least they are a *design smell* because they take a `Game` in the constructor. This makes them difficult to unit test and tightly coupled to the rest of your game.

That said, it might be time to consider supporting them. After all, we are a MonoGame extension and they do make some things easier.

For example, I've been experimenting with an Animations component and this is how it would be initialized.

    Components.Add(new AnimationComponent(this));

After that, you could start animating things using a fluent API for example:

    _sprite.Move(new Vector2(100, 0), duration: 1.0f);

And that's all you would have to do because the `Update` method gets called automatically. 

While this works, and we could use it for other components like particles, or a GUI system there are some other design smells in this particular implementation.

For example, the animations component registers itself as a component with the games `Services` collection and as a static singleton on the FluentAnimations class.

            game.Services.AddService(typeof (IAnimationService), this);
            FluentAnimations.AnimationService = this;

This is pretty stinky stuff when it comes to writing unit tests. Usually I'd be totally against it but I thought I'd raise it for discussion first.

Should we support `GameComponents`?
Should we register game services?
Should they be optional?  In other words, we have them but people can choose not to use them by manually calling `Update` etc.

**Comment by LithiumToast** [comment]
Take a look at the code for [GameComponent](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/GameComponent.cs). The `Game` property could be removed and it would still function.

**Comment by ExCellRaD** [comment]
> The Game property could be removed and it would still function.

Yeah, passing null works just the same as passing a game object. It's probably something monogame kept to stay compatible with XNA.

**Comment by craftworkgames** [comment]
Yeah, we could remove the dependency on `Game` for our components at least by doing what [Cygon did](http://blog.nuclex-games.com/2010/08/to-gamecomponent-or-not-to-gamecomponent/).

Although, in my experiment I'm actually using `game.Services.AddService` so there might still be a reason to keep it.

Doe that mean you two are in favor of supporting game components in the library?

**Comment by RUSshy** [comment]
Reason i choose monogame over unity is because i can make the game as a like, not having to follow entity component system or other thing

The best would be to be optional

**Comment by LithiumToast** [comment]
> Does that mean you two are in favor of supporting game components in the library?

@craftworkgames Yes.

> The best would be to be optional

@RUSshy Yeah totally. Game components can be used two ways. One way is to add a game component instance to the `Components` collection instance. Something like

```
var myGameComponent = new MyGameComponentThingThatDoesSomethingCool();
...
myGame.Components.Add(myGameComponent);
```

Another way is to just update it explicitly in the update loop.
```
var myGameComponent = new MyGameComponentThingThatDoesSomethingCool();
...
void Update(GameTime gameTime)
{
    myGameComponent.Update(gameTime);
}
```

@RUSshy Would the second way to work for you if the component was already built and you just wanted to use it?

**Comment by RUSshy** [comment]
@LithiumToast  The second way is perfect :p

**Comment by LithiumToast** [comment]
@RUSshy Cool. Just a warning though, using game components in that way will make the properties `Enabled`, `Visible`, `UpdateOrder`, `DrawOrder` not do anything. You could re-use these properties if you wanted though by writing a little more code, something like

```
var myGameComponent = new MyGameComponentThingThatDoesSomethingCool();
...
void Update(GameTime gameTime)
{
    if (myGameComponent.Enabled)
    {
        myGameComponent.Update(gameTime);
    }
}
```

The `UpdateOrder` and `DrawOrder` though would be useless unless you did something fancy though since the order is explicit by the code, like

```
var myFirstGameComponent = new MyGameComponentThingThatDoesSomethingCool();
var mySecondGameComponent = new MyGameComponentThingThatDoesSomethingAwesome();
...
void Update(GameTime gameTime)
{
    if (myFirstGameComponent.Enabled)
    {
        myFirstGameComponent.Update(gameTime);
    }

    if (mySecondGameComponent.Enabled)
    {
        mySecondComponent.Update(gameTime);
    }
}
```

**Comment by craftworkgames** [comment]
Okay cool. It looks like we are getting some clear criteria:
- We will support game components.
- They will be optional.
- If possible, we'll avoid the need to inject a `Game` instance into the constructor.

> Cool. Just a warning though, using game components in that way will make the properties Enabled, Visible, UpdateOrder, DrawOrder not do anything.

Thinking about this, I wonder if there's a pattern we could come up with that separates the *service*** from it's *game component* counterpart.

The best I could come up with was something like this:

    public class GameComponent<T> : GameComponent
        where T : IUpdate
    {
        public GameComponent(T service, Game game) 
            : base(game)
        {
            Service = service;
        }

        public T Service { get; }

        public override void Update(GameTime gameTime)
        {
            base.Update(gameTime);
            Service.Update(gameTime);
        }
    }

It kinda works, but it doesn't really feel right.

The other obvious way would be to wrap every method and property. This sounds like a lot of work for very little benefit. 

I think our best option is to implement every service** as a game component and let people use it how they like. This makes it optional in a sense, but it's not explicit in the design and could shy some people away.

** I'm not sure if "service" is the right word. They could also be called a system, manager, etc.


The other thing we need to think about is what will become a game component in the library. Looking over what we have already some candidates include:

 - ParticlesComponent
 - AnimationComponent (or separate ones for tweening, sprite sheets, skeletal)
 - InputListenerComponent (or separate ones for mouse, keyboard, gamepad, touch, etc).
 - FramesPerSecondComponent
 - CollisionComponent (and or PhysicsComponent in the future)

Introducing these will be breaking changes to the API, but at least we'll have some consistency and a clear pattern to follow.

**Comment by LithiumToast** [comment]
@craftworkgames How about introducing an `IGameService` and then have the generic `GameComponent<TGameService> : IGameService`? `IGameService` would inherit `IUpdateable` and so forth.

**Comment by craftworkgames** [comment]
@LithiumToast I'm not sure what you mean? How would that help?

**Comment by LithiumToast** [comment]
@craftworkgames Uh, I mean't like `GameComponent` could be a wrapper for a "service" where the service itself is updatable or drawable or anything really, just like you mentioned in the comment above. If we introduce a `IGameService`, then we can be sure there is some common properties or methods for all services, if we need it at all. Might be best just leave the constraint for the wrapper to a `object`. Either way, I was thinking of casting the wrapped object instance to `IUpdate` and `IDraw` so it can be updated and drawn if it implements those interfaces.

**Comment by craftworkgames** [comment]
We'll definitely be doing this as part of #198
