### ISSUE TITLE
Add more `DrawString` overloads for `BitmapFont`

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#188]
There's a whole bunch of [extra `DrawString` overloads we could implement](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.spritebatch.drawstring.aspx) for `BitmapFont`'s. In particular, we don't currently have a way to [set the `layerDepth` at all](http://community.monogame.net/t/using-layerdepth-with-drawstring-and-bitmapfont/7583).

**Comment by craftworkgames** [comment]
I added layer depth when merging #182 but the other overloads a more complicated.

**Comment by bsimser** [comment]
I wonder if this should be like the Draw extensions for the other classes modeled on the DrawString methods, each one just collapsing down to a single method. I took a look at what's there now but it's just the two methods (with one internal called by the public one). Maybe just do a rewrite of this file to structure it like the DrawString methods, using the one method that exists as the one that the others call?

**Comment by bsimser** [comment]
If you want you can assign this to me. Just working on it now.

Adding in support for StringBuilder text so you can do this:

`_stringBuilderText = new StringBuilder();`
`_stringBuilderText.AppendLine("Lorem Ipsum comes from sections 1.10.32 and 1.10.33");`
`_stringBuilderText.AppendLine("of \"de Finibus Bonorum et Malorum\" (The Extremes");`
`_stringBuilderText.AppendLine("of Good and Evil) by Cicero, written in 45 BC. This");`
`_stringBuilderText.AppendLine("book is a treatise on the theory of ethics, very");`
`_stringBuilderText.AppendLine("popular during the Renaissance. The first line of");`
`_stringBuilderText.AppendLine("Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes");`
`_stringBuilderText.AppendLine("from a line in section 1.10.32.");`
`_stringBuilderPosition = new Vector2(50, 60);`

And this:

`_spriteBatch.DrawString(_bitmapFont, _stringBuilderText, _stringBuilderPosition, Color.AliceBlue);`

To get this:

![image](https://cloud.githubusercontent.com/assets/301535/18252980/a7cac596-734e-11e6-8da4-8cac5764457d.png)

**Comment by bsimser** [comment]
Not sure how useful this will but here it is with rotation support (rotating each character, not the entire text). 

![image](https://cloud.githubusercontent.com/assets/301535/18254980/21f114b2-7361-11e6-985a-bd22e7c8b910.png)

**Comment by bsimser** [comment]
Got all the options in now so DrawString supports scaling, rotation, layers, SpriteEffects, etc.

![image](https://cloud.githubusercontent.com/assets/301535/18256232/b609480a-736f-11e6-9786-e51199131258.png)

**Comment by bsimser** [comment]
This is now in PR #253. Let me know if you see any problems (I updated the demo project as well and included some keyboard handling to showcase the features).

**Comment by craftworkgames** [comment]
Awesome work @bsimser. I'll merge this later today.

The rotation stuff is a little odd, but I understand why. I guess we'd need to move the point of origin to rotate the whole sentence. Tbh, I'm not even sure how rotation works with SpriteFonts but it would be nice to get them consistent.

**Comment by bsimser** [comment]
Yeah it's strange but works. If you change the origin to a vector in the middle of the font it'll just rotate the letters around the center (rather than 0, 0). Problem is I didn't go the extra mile to adjust the origin based on the size of the bitmap font. We probably would need an Origin property on the BitmapFont class or some way to get the max size of a single character to determine it.

**Comment by craftworkgames** [comment]
Wait.. wouldn't you want the origin to be the middle of the sentence that you're rendering?

For example, if I rendered "Hello World" and rotated it I'd expect something like this (with the red dot as the point of origin for every letter):

![image](https://cloud.githubusercontent.com/assets/3201643/18262818/61f5a05e-7448-11e6-945c-302a8dc3ec85.png)

So to do rotation like that you'd have to measure the bounding rectangle of the whole text first, then set the origin when rendering each character.

**Comment by bsimser** [comment]
I think you want both ;) so yeah, individual letters (for say doing an animation on a sign at a carnival) and the whole word. Version 2.

**Comment by craftworkgames** [comment]
There's still overloads we could add, but let's either raise new issues as they come up rather than keeping these old issues open.
