### ISSUE TITLE
Have IBoundingVolume interface for Bounding Frustum/Box/Sphere etc?

### ISSUE THREAD

**Issue by UncleThomy** [craftworkgames/MonoGame.Extended#195]
Hi guys,

I was wondering if we could just go ahead and implement an interface for the Bounding Frustum/Box/Sphere class, which would dictate stuff like Intersect(), Contain(), etc

I don't see any downside and on the upside we can just cast all of these for generic comparisons like
((IBoundingVolume) myBoundingVolume).Contains(myVector3);
or (myBoundingVolume as IBoundingVolume) for that matter

What do you think?

**Comment by craftworkgames** [comment]
> Bounding Frustum/Box/Sphere class

I'm not sure what you mean. None of these are types in MonoGame.Extended. We can't have them implement our interfaces because MonoGame doesn't reference MonoGame.Extended (nor should it).

**Comment by LithiumToast** [comment]
@UncleThomy You will get something along the lines of what you requested when I get to collision detection.

**Comment by UncleThomy** [comment]
how in the world did i end up on Monogame extended? Sorry about that.
