### ISSUE TITLE
Bring over the Mercury Particle Engine Tests

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#197]
It just occurred to me that we merged the Mercury Particle Engine into our library and forgot to bring over [the unit tests](https://github.com/Matthew-Davey/mercury-particle-engine/tree/develop/Mercury.ParticleEngine.Core.Tests)

I don't see any reason not to do this and it will add more value to our unit test coverage for little effort.

**Comment by ExCellRaD** [comment]
I can probably do that tomorrow if you want.

**Comment by craftworkgames** [comment]
Yes. Thank you.

**Comment by ExCellRaD** [comment]
`HslColor` and `LineSegment` use commas in their `ToString()` methods, is it ok to change these to spaces? Commas can have some number format issues in certain languages.

**Comment by craftworkgames** [comment]
Yeah that's a good idea.

My thinking would be to take a look at the [ToString methods](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Vector2.cs#L876) in MonoGame and see if we can use a similar format. Taking a quick look, it appears to be pretty consistent. 

    {X:123.45 Y:678.90}
    {R:255 G:255 B:255 A:255}

The only other thing I would say is that HSL [appears to be typically represented as degrees and percents](https://en.wikipedia.org/wiki/HSL_and_HSV), so let's keep those symbols. Something like:

    {H:1.0° S:100.0 L:100.0}

I'm guessing we've probably missed a number of other ToString methods in the library, but maybe that's a topic for another time.

**Comment by ExCellRaD** [comment]
> `{H:1.0° S:100.0 L:100.0}`

Would you rather have %-symbols for the S and L values? When using invariant culture, the % symbol is formatted like this: `n %` (with a space in between).

That would result in something like
`{H:1.0° S:100.0 % L:100.0 %}`

It is possible to remove that space with a custom `NumberFormat` though, but I don't know if that is a good idea?

**Comment by craftworkgames** [comment]
> Would you rather have %-symbols for the S and L values?

I wouldn't bother.
