### ISSUE TITLE
A Roadmap in the README

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#198]
Tonight I created a draft of a roadmap of features I'd like to see in the library before we reach the v1.0 milestone. The goal is to have a broad range of features that are found in most game frameworks without going too deep.

I'd like to avoid having every possible feature on the roadmap. Let's limit it to a set of features that make up v1.0 and things we've already implemented. Everything else stays as a feature request until we've reached the v1.0 milestone.

I broke the list up into categories to ensure we've got some coverage in each area. I've also intentionally left some features out to reduce the scope (e.g. Skeletal animation using Spine). That doesn't mean we *can't* have them, it just means they are not required for the milestone.

The roadmap is dual purpose. Obviously publishing it in the main README will help people understand what's in the library. It's also intended to help people figure out what to work on next. However, I realize that some people will still want to work on other things and that's okay too.

Stuff in **bold** we've already got. Stuff in *italics* we're already working on. No doubt there's still outstanding bugs in some features.

## Animations
 - _Tweening_
 - **Sprite Sheets**
 - Game Component

## Content
 - **Texture Atlases**
 - **Bitmap Fonts**
 - **Tiled Maps**

## Collision Detection
 - **Bounding Shapes**
 - **Intersection and overlap testing**

## Input Management
 - **Event based input (input listeners)**
 - Gesture detection (taps, panning, flinging and pinch zooming)
 - Button Mapping (W=Up, A=Left, Space=Jump, etc)

## Graphics and Scenes
 - **Sprites**
 - **Scene Graphs**
 - **Camera**
 - **Simple shape rendering**
 - Screen Management 

## GUI System
 - _Controls_
	 - _Label_
	 - _Button (Text or Image)_
	 - _Toggle Button (Checkbox)_
	 - Progress Bar
	 - Text Box
	 - Image
	 - Slider
 - Layout
	 - Canvas
	 - Stack Panel
	 - Wrap Panel
	 - Dock Panel
	 - Grid
 - Dialog
 - Window
 - _Skinning_
 - _Events_
 - Drag and Drop

## Particle System
 - **Emitters**
 - **Modifiers (age, drag, gravity, rotation, velocity, vortex)**
 - **Profiles (box, circle, line, point, ring, spray)**
 - **Sprite Batch Renderer**
 - Game Component

## Sound and Music
 - ?

## Math and Utilities
 - **Timers**
 - **Virtual Screens (viewport adapters)**
 - **Bounding Shapes**
 - **Collections**
 - **FPS Counter**
 - **Random Numbers**

## Platforms
 - **Windows**
 - **Linux**
 - **Mac**
 - Android
 - iOS

**Comment by Jjagg** [comment]
What do you mean with the Platforms section? That MG.E is not tested or missing features (e.g. touch) for Android and iOS? In theory everything should work, right?

**Comment by craftworkgames** [comment]
Yes that's right. Everything should work but we haven't officially tested mobile platforms yet.
