### ISSUE TITLE
Build with it or build on top of it?

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#208]
I have been using MG.Extended for a while, and it helped me alot then. I want to contribute more but I don't know which way the project is going. Until now, I use some classes of the library to make small things, but what about when it comes to scenes and bigger things? When creating scenes and more "connected systems", a good time will be spent setting everything up and running successfull. To avoid that, we can create a template just like MG does (this already [was suggested](https://github.com/craftworkgames/MonoGame.Extended/issues/106)). But the point is, we go this way, or continue creating separated classes to implement on the games? Or maybe both?

If we choose to create a template, some things that could be already done:
- The NuGet packages and Content.mgcb with the DLLs
- Some viewport adapter working
- A scene that displays a map (maybe with Tiled) and the camera
- Maybe a sprite base class to animate sprites?
- Mouse and keyboard manager classes (already configurated within the game loop)
- The same to the FPS display

I believe this is the most basic a game can have, and the most annoying (or maybe hard?) things a beginner faces when start development with MonoGame.

**Comment by craftworkgames** [comment]
In general I think this is a great idea as long as people aren't forced to do things a particular way (within reason).

I think we'd probably end up with a few different templates. Initially I'd create a very basic hello world template with a viewport adapter and the MonoGame.Extended logo spinning in the middle.

But it also makes sense to have a handful of "starter kit" style templates that setup things like Tiled and other more complete demos to provide a head start when creating different types of games.

I've had something like this on my to-do list for a while but I haven't had a chance to get around to it. Would you like to have a stab at getting something going?

**Comment by rafaelalmeidatk** [comment]
Yes, I agree with you. I will begin with the scene management. Do I call it "SceneManager" or "ScreenManager"?

I made a starter kit to use on an event (sorry, the code is messy) and it has the screen management, you can see it [here](https://github.com/rafaelalmeidatk/MG-Platformer-SK/blob/master/MG%20Platformer%20SK/MG%20Platformer%20SK/Managers/SceneManager.cs). You already saw this code before and said that singletons maybe isn't the way to go. Now I agree too, but I made it singleton to get the instance anywhere I wan't, IDK how to do it without a singleton. Maybe a static variable on the Game1.cs?
