### ISSUE TITLE
Scene graphs

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#21]
For completeness I'm going to add [scene graphs](http://stackoverflow.com/questions/5319282/game-engines-what-are-scene-graphs) to the list. 

> They are useful for representing translations, rotations and scales (along with other affine transformations) of objects relative to each other.

I'm not convinced they are a top priority, as we may get similar functionality out of the Spine #16 or Spriter #17 enhancements but they are a nice to have.

**Comment by LithiumToast** [comment]
This would be nice for having game objects "inherit" affine transformations (translation a.k.a. position, rotation, scale, shear, reflections) from other game objects. For example having the camera follow a player or specific game object around.

**Comment by craftworkgames** [comment]
I've been working on the GUI system #20 lately and I can say that having decent scene graph functionality would really help. As I usually do when I'm working on a big feature like this; I like to do plenty of research by reading about how similar systems work in other libraries. 

The LibGDX [scene2d.ui](https://github.com/libgdx/libgdx/wiki/Scene2d.ui) is probably the best example of this:

> [scene2d](https://github.com/libgdx/libgdx/wiki/Scene2d) is libgdx's 2D scene graph. At its core, it provides basic 2D scene graph functionality: actors, groups, drawing, events, and actions. This is a lot of utility that applications can leverage, but it is reasonably low level. For games this is fine because most actors are application specific. For building UIs, the scene2d.ui package provides common UI widgets and other classes built on top of scene2d.

So yeah, I'm thinking we probably need something like this sooner rather than later. It could make a good foundation for building other functionality like the GUI system.

**Comment by rafaelalmeidatk** [comment]
I have done a simple screen base and transition between they to my game, maybe this can be used as base? Every screen have their `LoadContent`, `UnloadContent`, `Update` and `Draw`. However, there need to have a SceneManager to handle the transitions, what make me think that the Template you talked about is the way to go for the Extended library.

**Comment by craftworkgames** [comment]
@rafaelalmeidatk Do you mean something like [this](https://github.com/craftworkgames/MonoGame.Extended/tree/gui-system/Source/MonoGame.Extended/Screens)?

I've created [`gui-system`](https://github.com/craftworkgames/MonoGame.Extended/tree/gui-system) and [`scene-graph`](https://github.com/craftworkgames/MonoGame.Extended/tree/scene-graph) branches to work on these features. To be honest, there's not much done yet. I'm still working through the design and I've been pretty busy with other things lately.

If you want to take a look at what I've done you're more than welcome to help. At this stage though, I think discussing the design is probably the most important bit.

**Comment by rafaelalmeidatk** [comment]
Yeah, exactly like that. Well, it's the first time I contribute to a repo, I don't know what to do xD

**Comment by craftworkgames** [comment]
> Well, it's the first time I contribute to a repo, I don't know what to do xD

Github is promoting [this awesome tutorial](https://guides.github.com/activities/hello-world/) at the moment they like to call *Hello World*. I went through it the other day, it's pretty helpful to get started.

**Comment by rafaelalmeidatk** [comment]
So, how do you plan to it be used? Mine `ScreenManager` is a singleton class (to prevend have more than one screen at the same time) and in the `Game1.cs` I place the `ScreenManager` methods to handle everything, like `ScreenManager.LoadContent()`, `ScreenManager.Update()`, etc.

**Comment by craftworkgames** [comment]
> So, how do you plan to it be used?

A this stage I'm still figuring that out. I'm doing lots of research into how other game frameworks do similar things. [LibGDX scene2d and scene2d.ui](https://github.com/libgdx/libgdx/wiki/Scene2d.ui) is a pretty good example.

> Mine ScreenManager is a singleton class

I'm not a fan of singleton classes. They are difficult to test and are often considered a bit of a code smell. In most cases, it's kind of obvious that you wouldn't create more than one `SceneManager` anyway. Besides, people will often find a clever ways to use multiple `ScreenManger`'s so I don't see any benefit to restricting it.

Do you have the code for yours available somewhere? I'm happy to take a look at it and see if there's any idea's I've missed if you like.

**Comment by craftworkgames** [comment]
I made a car with the new scene graph feature :smile: 

![car-scene-graph-demo](https://cloud.githubusercontent.com/assets/3201643/12865050/056d1cca-cced-11e5-81bf-a1fd4a4c0b43.gif)

**Comment by rafaelalmeidatk** [comment]
@craftworkgames Sure, check [here](https://github.com/rafaelalmeidatk/Super-Pete-The-Pirate/blob/master/Peter%20The%20Cat/Managers/SceneManager.cs) the code. What you said makes sense, restrict it is bad. I have the feeling that I'm at the wrong issue discussion, this one is only to the graphs or the entire system?

**Comment by craftworkgames** [comment]
>  I have the feeling that I'm at the wrong issue discussion, this one is only to the graphs or the entire system?

I can understand your confusion. There's a few different related discussions going on.

This one is specifically about the "scene graphs" feature. There's also one about the "GUI system" #20 (hopefully that's what you mean by *entire system*?)
They are related because I'm going to use the scene graph feature to build the GUI system. I need to finish scene graphs before I can finish GUI.
