### ISSUE TITLE
ViewportAdapter: Virtual dimensions are integers and not floats

### ISSUE THREAD

**Issue by kevhiggins** [craftworkgames/MonoGame.Extended#210]
I'm currently integrating Farseer into one of my projects, and wanted to let the Camera2D class handle the scaling between Farseer world coordinates to screen coordinates.

Below is how I'm configuring the virtual dimensions of the world using the screen dimensions divided by the pixels per meter I have defined. Unfortunately, doing it like this ends up rounding the world dimensions significantly, and scaling incorrectly.

`var viewportAdapter = new BoxingViewportAdapter(Window, GraphicsDevice, 1280 / PIXELS_PER_METER, 704 / PIXELS_PER_METER);`

I've tested replacing the virtualWidth and virtualHeight for the ViewportAdapter classes with float, and that fixed the issue I was experiencing.

Is there already a better way to handle this that I'm not seeing?

Here is the branch containing my changes for reference:
https://github.com/kevhiggins/MonoGame.Extended/commits/virtual-viewport-to-float

**Comment by craftworkgames** [comment]
> I'm currently integrating Farseer into one of my projects, and wanted to let the Camera2D class handle the scaling between Farseer world coordinates to screen coordinates.

Could you explain this a little more? What exactly are you doing on the Farseer side of things?

**Comment by kevhiggins** [comment]
Sure thing.

The Farseer world is created, and all body position and dimensions are scaled using the PIXELS_PER_METER constant via the ConvertUnits class.
```
ConvertUnits.SetDisplayUnitToSimUnitRatio(PIXELS_PER_METER);
ConvertUnits.ToSimUnits(VALUE);
```
While running the update method, the simulation units are used exclusively for updating positions, and object dimensions.

Finally, when it's time to draw the physics world, rather than scale everything back up temporarily, I thought it would be easier to use the MonoGame.Extended camera, and the spriteBatch.Begin() transformMatrix parameter.
```
var viewMatrix = camera.GetViewMatrix(Vector2.Zero);
spriteBatch.Begin(transformMatrix:viewMatrix);
spriteBatch.Draw(sprite);
spriteBatch.End();
```

The problem I am seeing with the ViewportAdapter having integer as its type instead of float, can be seen in the example below.

```
var float PIXELS_PER_METER = 204;
var windowWidth = 1280;
var windowHeight = 704;
graphics.PreferredBackBufferWidth = windowWidth ; 
graphics.PreferredBackBufferHeight = windowHeight ;

var virtualWidth = windowWidth / PIXELS_PER_METER;
var virtualHeight = windowHeight  / PIXELS_PER_METER;

var viewportAdapter = new BoxingViewportAdapter(Window, GraphicsDevice, (int)virtualWidth, (int)virtualHeight);

// After converting to int, if we scale back up to pixels, the virtual window no longer maps to the game window
// viewportAdapter.VirtualWidth * PIXELS_PER_METER = 1224 != 1280
// viewportAdapter.VirtualHeight * PIXELS_PER_METER == 612 != 704
```

**Comment by craftworkgames** [comment]
Hmm.. I see the dilemma but I don't think changing the `VirtualWidth` and `VirtualHeight` properties to `float`'s on the viewport adapter is really the right solution here. 

Outside your particular implementation there's really no reason for them to be floats and it should be easy enough for you to simply store the float versions yourself.

You could simply store them in member variables somewhere and use those instead.

    _virtualWidth = windowWidth / PIXELS_PER_METER;
    _virtualHeight = windowHeight  / PIXELS_PER_METER;

    _virtualWidth * PIXELS_PER_METER;
    _virtualHeight * PIXELS_PER_METER;

Sorry mate. I know this change is a tiny one and I really did want to find a reason to accept it but I just can't see how it makes sense outside this scenario.

**Comment by kevhiggins** [comment]
No problem. Thanks for taking a look at it. I definitely don't want to add stuff just because it works in my case, so if I can think of a more compelling use case someday, I'll maybe try again.
