### ISSUE TITLE
TiledLayer draws only as high as it is wide

### ISSUE THREAD

**Issue by geselle-jan** [craftworkgames/MonoGame.Extended#211]
When I use `MonoGame.Extended.Maps.Tiled.Draw(this SpriteBatch spriteBatch, TiledLayer layer, Camera2D camera);` with a map that is higher that it is wide, it draws the layer from top to bottom only as far as the maps width, after that I get only transparency.
When I increase the maps width in tiled I can confirm that the height of the part of the map that gets drawn is directly correlated to the width. As soon as the map gets wider than high, the problem disappears.

**Comment by geselle-jan** [comment]
I just found the issue:

In `TiledTileLayer.cs` in Line 72 there was:

`_renderTarget = new RenderTarget2D(_renderTargetSpriteBatch.GraphicsDevice, _map.WidthInPixels, _map.WidthInPixels);`

But it should be:

`_renderTarget = new RenderTarget2D(_renderTargetSpriteBatch.GraphicsDevice, _map.WidthInPixels, _map.HeightInPixels);`

**Comment by craftworkgames** [comment]
Thanks for the contribution :)
