### ISSUE TITLE
[Shapes] Wrong Rectangle Intersection

### ISSUE THREAD

**Issue by Spessi** [craftworkgames/MonoGame.Extended#213]
Hi, I think there's a bug in the Intersects method for RectangleF.

Example code:

``` c#
RectangleF rect1 = new RectangleF(0, 0, 32, 32);
RectangleF rect2 = new RectangleF(32, 32, 32, 32);
bool res = rect1.Intersects(rect2);
```

'res' will be true, although they're not intersecting (just 'touching').

**Comment by craftworkgames** [comment]
It appears you're right.

We really should have unit tests around these types of things. For example:

        [Test]
        public void RectangleF_Intersects_Test()
        {
            var rect1 = new RectangleF(0, 0, 32, 32);
            var rect2 = new RectangleF(32, 32, 32, 32);

            Assert.IsTrue(rect1.Intersects(rect2));
        }

        [Test]
        public void Rectangle_Intersects_Test()
        {
            var rect1 = new Rectangle(0, 0, 32, 32);
            var rect2 = new Rectangle(32, 32, 32, 32);

            Assert.IsFalse(rect1.Intersects(rect2));
        }

It's quite clear from these 2 tests that something is wrong here. They should have the same behavior.

Are you interested in writing some more unit tests like this and submitting a PR?  The goal would be to make `RectangleF` behave like `Rectangle` where it makes sense.

**Comment by lozzajp** [comment]
@craftworkgames did you fix this 7 days ago?

**Comment by craftworkgames** [comment]
> did you fix this 7 days ago?

When the issue was raised I quickly wrote a unit test to confirm that it was indeed a bug. Rather than throwing that unit test away, I fixed the issue and checked it in.

> Are you interested in writing some more unit tests like this and submitting a PR? The goal would be to make RectangleF behave like Rectangle where it makes sense.

The reason I left this issue open is because I think there's more work to be done. We need to write some more tests to confirm that things work the way we expect.

The tests are pretty simple. Just confirm that the methods on `RectangleF` behave the same way they do on MonoGame's `Rectangle` class where appropriate.

**Comment by lozzajp** [comment]
I made a start on some tests, basically mimicing MonoGames Rectangle tests but adding some variation to test for float amounts.

I have them on a local branch, I don't quite know the process from there. Is it basically publish branch, make PR, you accept/merge?

**Comment by craftworkgames** [comment]
> Is it basically publish branch, make PR, you accept/merge?

Yep. Pretty much.

If you've got the changes in your own fork on github just [submit a PR](https://help.github.com/articles/using-pull-requests/). There's plenty of tutorials around.

For small changes I'm happy to have them submitted directly into the `develop` branch.

Thanks.

**Comment by lozzajp** [comment]
I was getting a 403 error trying to publish (I am thinking no write access to your repo?) so will probably fork it and make a PR, either way will try when I am on later.

**Comment by craftworkgames** [comment]
> so will probably fork it and make a PR

Forking the repo is the right way to do it.

**Comment by craftworkgames** [comment]
Looks like this was fixed already.
