### ISSUE TITLE
Pathfinding Library

### ISSUE THREAD

**Issue by killerrin** [craftworkgames/MonoGame.Extended#215]
I'm currently working on building out a generalized Pathfinding Library for MGE, so I figured I would get this opened up for discussion on various types of pathfinding and to allow us a centralized location to discuss how we should go about designing the API and implementing it 

**Features**
- I am currently looking to have the library support both A\* and Dijkstra methods of pathfinding with a focus on 2D Pathfinding.
- The initial version will only support square grids and we can add additional layouts from there.

**Comment by killerrin** [comment]
So I currently have a working prototype for the Pathfinding Library over here https://github.com/killerrin/Monogame-Pathfinding.

Right now I currently have A* working along with a basic renderer to show the paths for testing. Once I get it to a good state I'll submit a pull request to formally merge it into MGE

**Comment by killerrin** [comment]
Since Pathfinding tends to take a long time with larger grids, how would everybody feel if I tried to make the Pathfinding portion async?

Alternatively, I could just leave it as a synchronous library and if someone needed it to run async, they could do a Task.Run

**Comment by craftworkgames** [comment]
Looks pretty good so far. I don't have time right now to do a proper code review but at first glance I think it's on the right track.

Btw.. as a general rule you wouldn't commit the `packages` folder to source control.

**Comment by killerrin** [comment]
Seriously? *doh* I've been doing Git wrong this entire time

**Comment by craftworkgames** [comment]
> Seriously? doh I've been doing Git wrong this entire time.

Yep. Take a look at the [.gitignore file](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/.gitignore#L137) from this repo. That's just using the standard Visual Studio git ignore template provided by github.

**Comment by killerrin** [comment]
Alright, so I decided that on the Async front, it is better to keep it as a Synchronous API that way if someone wanted to do it async they could by writing a wrapper. To help with that I've made sure to make it so that things which are most likely to be shared or modified across threads are locked, should someone go that route.

I have also abstracted the API a bit more to more easily allow parts to be swapped out in addition to making it easier to debug visually through the usage of a new PathfindingResult class that contains the main items which were generated in the pathfinding (Path, Open/Closed lists)

Lastly, now that I have A* up and running, I'm currently working on adding in a couple other pathfinding methods using the RedBlobGames writeups http://www.redblobgames.com/pathfinding/a-star/introduction.html

**Comment by craftworkgames** [comment]
> it is better to keep it as a Synchronous API that way if someone wanted to do it async they could by writing a wrapper. 

I think that's the right choice for now. At some point we might want to add `Async` versions of some of the methods but when we do that we'd still keep the synchronous methods as well.

> To help with that I've made sure to make it so that things which are most likely to be shared or modified across threads are locked

Writing thread safe code can be difficult to get right and if you're forcing locks inside methods it could hurt performance and make it difficult for people to optimize. Personally I'd probably leave that out until we know for certain we are going to need it. In my experience it's better to let the user be in control of how to make their own code thread safe.

**Comment by killerrin** [comment]
Well, at the moment the Lock is only within GridNode under the properties for MovementCost and Navigatable. The idea being that since each FindPath call has all of the variables local-scoped to the method in question, it would be easy to multi-thread a bunch of paths should someone want to. 

The problem is though that the only thing that would be required to be shared across all of those instances is the PathfindingGrid. Now the Grid itself is fine since you can't modify anything on the grid, the problem is that the Nodes that make up the grid have methods that can be modified (Movement Cost, Navigable) to allow someone to theoretically mess with the grid mid-game (a tree falls over and now this path is blocked) without needing to recreate the grid from scratch and manually set all of the values again. So my idea was that I lock those two properties.

---

So I have a couple different ways I could do this segment. What do you think of them?

1. I take out the Locks on GridNode and have the version in the library only be the synchronous version. If someone wants to they can implement IGridNode and IPathfindingGrid themselves and pass their version of the grid into the PathfindingEngine
2: I duplicate GridNode and have one version with locks and the other without. I would then try to find a way to template the Grid (needs some reorganization since I instantiate the Nodes within the Grids constructor) or make a new one which uses the new node

**Comment by craftworkgames** [comment]
> What do you think of them?

Either way would work. I'm glad you're thinking about this stuff and putting things behind interfaces so they can be customized. It's probably easiest to implement the non-locking versions first and think about the locking versions once we get around to doing the `Async` stuff. That way everything is consistent and we are only doing what we need when we need it.

**Comment by killerrin** [comment]
Thanks, this is honestly the first time I have attempted using interfaces to this extent. I'm usually on the side of Abstract Classes. Glad to see that you approve so far.

---

So I decided to go with the second method I renamed the current GridNode which uses locks to ThreadSafeGridNode and then made a duplicate version which doesn't.

Then to make both versions compatible with the PathfindingGrid I decided to create an IGridNodeFactory interface that defines a CreateNode(position) method which gets passed into the PathfindingGrid's constructor. The idea being that instead of forcing someone to create different grids for each node type, they simply pass in a factory which creates the nodes for the PathfindingGrid to use when its instantiating the grid

**Comment by charles-esterbrook** [comment]
If it's really just one method, you can pass a Func<> or a delegate. I don't use classic factories in C# since it has those features.

**Comment by killerrin** [comment]
True, I could go that route and it would fill the same purpose; but at the same time I would argue that having a parameter of Func<NodePosition, IGridNode> would be a less readable solution than a single parameter of IGridNodeFactory.

Not to mention that by abstracting it out to an interface it becomes object oriented which fits well within the general coding style of C#.

**Comment by LithiumToast** [comment]
@killerrin Delegates (Func<T>, Action<T>, etc) are objects too.

**Comment by killerrin** [comment]
Alright, so progress update. While the current version does work, I have begun to refactor the code in an attempt to support standard graphs. I'm going to try and do this while keeping an implementation chain so that we wouldn't need to write a different version of the pathfinding algorithm for each type of graph.

**Comment by craftworkgames** [comment]
Cool. Good to know.

**Comment by craftworkgames** [comment]
This issue is old and seems to be dead. If path-finding is important it'll come back up again.
