### ISSUE TITLE
Can't build sandbox project on Linux

### ISSUE THREAD

**Issue by WardBenjamin** [craftworkgames/MonoGame.Extended#22]
I expected some fiddling with the dependencies and such, but I also ran into an interesting issue with the MonoGame Content Builder and the Sandbox csproj. Since you don't install the Pipeline the same way on Windows as you do on Linux, you cannot rely on importing the `.targets` file, and then cannot build content the cool new way with just the content project, and instead have to do it manually. Any ideas? Does this effect us at all or should I open up an issue on Monogame's issue list?

**Comment by WardBenjamin** [comment]
I found a way to fix this (it's not MonoGame's fault, they don't have a proper installer in release yet.

Could we talk about a blog post about this? I am going to write something up, and (1) I don't currently have a blog released to talk about it in, and (2) your blog gets a lot of traffic interested in MonoGame.

**Comment by craftworkgames** [comment]
@WardBenjamin Sure. If you write something up I'll put a guest post on my blog. I use [MarkdownPad](http://markdownpad.com/) to write the posts so if you want to do the same it'll make it easier for me to format it before posting. 

Working on MonoGame.Extended seems to be exposing a few bugs and shortcomings with MonoGame. I think it's our responsibility to report these back to the MonoGame team and if possible produce simple reproductions. The main problem for me is that I don't have a machine that can run the original XNA to test how it is supposed to work.

> your blog gets a lot of traffic interested in MonoGame.

I wouldn't say my blog gets a *lot* of traffic at this stage. I've only had the blog up for about a month, but the traffic it does get seems to be mostly MonoGame users (makes sense). Every blog post goes a little way to increasing that traffic and the visibility of MonoGame.Extended which is great.

**Comment by WardBenjamin** [comment]
@craftworkgames I wrote something up earlier today that I can send to you when I next get access to my laptop. Unfortunately, I don't have access to a windows machine that I can install MarkdownPad on, though I'll definitely do what I can with tools available for Linux that I have.

I do have a machine that can run XNA at home, I believe. I'll check it out when this vacation is over.

**Comment by WardBenjamin** [comment]
So.... I don't have an email for you so here's the post!

Unfortunately Github is going to render links/etc and you won't be able to see the raw text, so you'll have to do that manually again :/

**Comment by WardBenjamin** [comment]
Monogame's cross-platform development capabilities are no longer as lacking as they used be, but they still have some odd issues every once and a while. In particular, when working on Linux distros such as Ubuntu, you will find that MonoGame lacks an installer, though they offer compiled binaries and a working version of the Pipeline tool. While this works fine, you can sometimes get some peculiar errors when working with MonoGame, specifically that it is missing the .targets file used to build the MGCB file included in your project, if you have one. 

To fix this, you can drop a copy of this file (located [here](https://github.com/mono/MonoGame/blob/1756c713b4aede3db5568f69012daf68be2d8c6a/MonoGame.Framework.Content.Pipeline/MonoGame.Content.Builder.targets)) into the folder that XBuild (Mono's equivalent to MSBuild) uses to hold these target files. Here's a copy of the rules used to find such files:

MSBuild extensions are usually installed in $(MSBuildExtensionsPath), which XBuild resolves to $prefix/lib/mono/xbuild . When used in Import, like: `<Import Project="$(MSBuildExtensionsPath)\TestTargets.targets"/>`, xbuild tries various values for the msbuild property $(MSBuildExtensionsPath), in order:

    1. Paths specified in the environment variable $MSBuildExtensionsPath.
    2. /Library/Frameworks/Mono.framework/External/xbuild on Mac OSX.
    3. $XDG_CONFIG_HOME/xbuild/tasks (or Environment.SpecialFolder.ApplicationData)
    4. $prefix/lib/mono/xbuild (default location)

I found mine in the third option, `$XDG_CONFIG_HOME/xbuild/tasks` (note that you may have to create the tasks subfolder). To locate your `XDG_CONFIG_HOME`, just paste: `printenv | grep XDG_CONFIG_HOME` into a bash shell. Then, drop the MonoGame.Content.Builder.targets file from earlier into your `$(MSBuildExtensionsPath)\MonoGame\v3.0\` folder, creating the subfolders if they do not exist. I found my MSBuildExtensionsPath at `/home/user/.config/xbuild/`, though yours may differ.

Happy coding!
Benjamin Ward

**Comment by craftworkgames** [comment]
@WardBenjamin Thanks. 

This is fine. I can actually edit the post and see the raw Markdown anyway.

Do you have a title for the post? 
Would you like me to link to your twitter account or anything?

I'll see if I can find time to post it on the blog tonight.

**Comment by craftworkgames** [comment]
@WardBenjamin I'm ready to post it on the blog as soon as I have a post title.

**Comment by WardBenjamin** [comment]
I didn't really this think about a title..... How about "Automatic content building on Linux"?

If you would like, I'm @TheProgramm3r on Twitter and @WardBenjamin here.

**Comment by WardBenjamin** [comment]
@craftworkgames huh, looking at the titles on your blog, maybe "MonoGame" should be added to the title.... You can decide where I guess. There's a few places that it could go.

**Comment by craftworkgames** [comment]
@WardBenjamin It's up. Let me know if there's any issues.

http://dylanwilson.net/automatic-content-building-on-linux-with-monogame

**Comment by craftworkgames** [comment]
> looking at the titles on your blog, maybe "MonoGame" should be added to the title

I do this so that it makes it easier to find in Google. At least, that's the theory. Not sure how well it working in practice.

**Comment by WardBenjamin** [comment]
Looks good, and thanks for posting this for me!

I'm going to head over to the MonoGame page and figure out where they are on the Linux installer so that I can yell at them about including the `.targets` file if they have not. I have a feeling that once the installer works, quite a few issues will be fixed.
