### ISSUE TITLE
Rendering single layers with the new TiledMap-Renderer

### ISSUE THREAD

**Issue by McSora** [craftworkgames/MonoGame.Extended#229]
Hello everyone,
I'm posting this issue now, so we dont forget to support all the previous features of Map-Rendering after implementing the new renderer.

So the new TiledMap-Renderer is here and is now ready to render a whole map at once.
What's missing is the rendering of single layers.

I am currently using this method with the old map-renderer for rendering my entities within my map.
It's the easiest way to render the map with entities without having to render all the single tiles and look if the tile should now be in front or behind the player,npc,cat,dog,... (it still has its problematic cases though...).

So, there are bottom TileLayers and there are top TileLayers.
You could imagine it rendering like this:

```
maprenderer.RenderBottomLayers();
entityrenderer.Render();
maprenderer.RenderTopLayers();
```

(in this scenario the maprenderer would wrap the tiledMap and/or the spritebatch to call the Draw() methods like:
...
`spriteBatch.Draw(tiledTileLayer, ...); //using the old spritebatch extension methods.`
...)

I believe it would best to implement a possibility to render single layers like we could before, for the new renderer is not able to do so yet, because it is building the list of rendered triangles of all layers at once :)

**Comment by craftworkgames** [comment]
This issue seems to have a lot of cross over with #230. Unless I missed something, it might be better close this issue?

**Comment by McSora** [comment]
I guess so, yeah ;)
I seperated the two issues in the first place because i saw them as two different ways to render
but as the discussion in #230 evolved, it became more the issue for "implement more rendering-methods" :D

**Comment by craftworkgames** [comment]
Yeah fair enough.
