### ISSUE TITLE
ShapeBatch: Fill & Stroke

### ISSUE THREAD

**Issue by LithiumToast** [craftworkgames/MonoGame.Extended#232]
It's pretty common for drawing libraries to support drawing shapes using two modes: stroke and fill.
Fill is for setting the color inside the object. Stroke is for setting the color of the poly-line around the object.

The `ShapeBatch` currently only supports a simple stroke with a line width of 1 pixel. This is due to how OpenGL / DirectX treat the graphic primitive `PrimitiveType.LineList`. To get strokes with a width of greater than 1 pixel triangles will have to be used as the graphic primitive. See https://roundline.codeplex.com

**Comment by craftworkgames** [comment]
Yeah, we could do this but I'm not sure there's going to much demand for such a feature.
