### ISSUE TITLE
[Tiled] Make Objectgroups in tiles accessible

### ISSUE THREAD

**Issue by TheUltimateHose** [craftworkgames/MonoGame.Extended#236]
Looking through the source code, i found that object groups (those in map -> tileset -> tile -> Objectgroup) are deserialized, but ignored when writing the tile data. Because of that, I'm not sure if something like that is already being worked on. The main reason why I would love to see this implemented is because collision data is stored in those object groups (I'm not sure if there even is something which can be saved there) and having access to that collision data would allow the implementation of a much more accurate creation of collision grids for the collision world, as the current implementation (as far as I know/saw) simply looks whether a tile exists in the grid or not.

**Comment by craftworkgames** [comment]
> Looking through the source code, i found that object groups (those in map -> tileset -> tile -> Objectgroup) are deserialized, but ignored when writing the tile data. 

Are you talking about Object Layers? Here's some code I wrote the other day that uses a rectangle in an object layer to represent the player spawn point.

            _tiledMap = Content.Load<TiledMap>("level-1");

            var entitiesLayer = _tiledMap.GetObjectGroup("entities");
            var spawn = entitiesLayer.Objects.FirstOrDefault(i => i.Name == "Player Spawn");

            if (spawn != null)
                _entityFactory.CreatePlayer(new Vector2(spawn.X, spawn.Y));

> collision grids for the collision world, as the current implementation (as far as I know/saw) simply looks whether a tile exists in the grid or not.

Yeah, collision grids as they currently stand are not real great. There's working being done to greatly improve the collision story. Hopefully the first cut of that will be PR'd shortly.

**Comment by TheUltimateHose** [comment]
> Are you talking about Object Layers?

No. I'm talking about a feature in Tiled that can be found under `View` -> `Tile Collision Editor` and lets you define objects which are then "associated" with that tile. Those are saved inside the tileset as seen here:
![tile_data](https://cloud.githubusercontent.com/assets/10011726/17892346/1eb97908-6941-11e6-8db7-8efd23bd6f77.png)

>  i found that object groups [...] are deserialized

as seen in [TmxTile.cs](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline/Tiled/TmxTile.cs#L32)

> but ignored when writing the tile data

as seen in [TiledMapWriter.cs](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs#L49), where the Properties are written, but not those objectgroups.

**Comment by TheUltimateHose** [comment]
whoops, I thought that would close the tab...

**Comment by craftworkgames** [comment]
>  I'm talking about a feature in Tiled that can be found under View -> Tile Collision Editor and lets you define objects which are then "associated" with that tile.

Ah I see. Well that makes a lot more sense now.

I've got a long list of things to do before I'll have time to get to this. Are you interested in implementing the feature and submitting a PR?

**Comment by TheUltimateHose** [comment]
Sure, although I'm quite busy too (school just started again) I'll try to get this done as good as possible.

**Comment by TheUltimateHose** [comment]
Turns out I had more time today than I expected, so I actually did it; see [This pull request](https://github.com/craftworkgames/MonoGame.Extended/pull/246).

However, I didn't come around to testing it, but it should work.
