### ISSUE TITLE
Monogame versions outdated

### ISSUE THREAD

**Issue by WardBenjamin** [craftworkgames/MonoGame.Extended#25]
When working on my Linux system, I had some very odd issues with missing SDL system libraries at runtime, while my other Monogame projects work fine. Hunting through the dependencies, this is because we are compiling against MonoGame v3.1.2.0 rather than the latest,  v3.4.0.459. Why is this? Is the PCL outdated?

Update: Looking at Nuget, I see that this is the case. Damn, that's an issue. Linux has quite a few issues that have been fixed in the more recent versions.

**Comment by WardBenjamin** [comment]
@craftworkgames Pinging you before I close this so that you see it.

**Comment by craftworkgames** [comment]
So this is only an issue on Linux then? Contact the maintainer of the NuGet package and ask what the deal is. Maybe you can rebuild it yourself.

**Comment by WardBenjamin** [comment]
This is technically an issue for all platforms, since you are restricted to using MonoGame v3.1 instead of v3.4. I'll definitely ask the MonoGame team about this

**Comment by WardBenjamin** [comment]
Welp... this is an issue. I haven't completely verified this yet, but I'm going to try and use Piranha to build a PCL for Monogame 3.4. Hopefully we can update all of the dependencies then.

**Comment by craftworkgames** [comment]
> Keep in mind that we will probably have to update the PCL every time that Monogame releases a new version.

Maybe we can automate the process on the build system. That could be a really good thing anyway. I've thought about doing this for other libraries, like a Farseer Physics PCL.

**Comment by WardBenjamin** [comment]
> Maybe we can automate the process on the build system.

That's definitely possible.

Anyway, right now I'm trying to get Piranha to work on my system (Ubuntu 14.04) and it hasn't been playing nice with Mono so far. Having an odd issue with `[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Directory '/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks' not found.` I haven't been able to find why it's searching for this directory in the first place.... If you want to play with it as well, I pushed a clone of MonoGame v3.4 with the necessary Piranha stuff to https://github.com/WardBenjamin/MonoGame/tree/PCL_v3.4. The command you need to run can be found here: https://github.com/WardBenjamin/MonoGame/blob/PCL_v3.4/ThirdParty/Piranha/GenerateMonoGamePCL.cmd. Don't forget to generate and build the WindowsGL version of MonoGame beforehand.

**Comment by craftworkgames** [comment]
> If you want to play with it as well, I pushed a clone of MonoGame v3.4 with the necessary Piranha stuff

I'm at work (my day job) at the moment so I can't really help. Sorry. Also, I don't have any Linux distros installed.

I know @DDReaper had a lot to do with building the MonoGame PCL. Maybe he can shed some light on it.

 The way I understand it, the PCL is an just an empty shell to provide the interfaces to the real DLL that gets used. This is called the "bait and switch" method. I don't really understand why the version would have anything to do with it since the MonoGame interface shouldn't be changing.

**Comment by WardBenjamin** [comment]
I don't know why it would, but if I can get this PCL to compile I'm going to find out; I wouldn't be surprised if that was the issue. I know the interface changed a little bit.... there's 2 major versions between the PCL currently and the up-to-date Monogame package.

**Comment by craftworkgames** [comment]
> I know the interface changed a little bit

I'd be very surprised if the interface changed in any code that we are actually using.

This whole thing kinda reminds me of [this issue](https://github.com/craftworkgames/FarseerPhysics.Portable/issues/4) which, unfortunately, we didn't actually get to the bottom of.

**Comment by WardBenjamin** [comment]
As per https://github.com/mono/MonoGame/issues/4056, I have found a way to compile MonoGame v3.4 as a PCL, using Piranha. Now, the dependencies can be updated to the latest version, and this does in fact fix my odd dependency issue.

**Comment by craftworkgames** [comment]
> I'll do this and add it as part of my PR for my Sprite code.

If it's not too much trouble can you keep the PR's separate?  If it is a hassle, don't worry about it.

I asked on https://github.com/mono/MonoGame/issues/3944 if there has been any progress on the PCL build automation. If they haven't already done it, maybe we can help get it into the next release of MonoGame.

**Comment by WardBenjamin** [comment]
Yeah I can keep the PR's separate. I'll go make one specifically for the PCL stuff now.

**Comment by WardBenjamin** [comment]
Whoo it works! Closing as per https://github.com/craftworkgames/MonoGame.Extended/pull/26

**Comment by ClassicThunder** [comment]
Out of curiosity what about using the new shared projects feature in VS 2013 and Xmarian? 

The idea is the code reuse is based upon the source code, a shared project references no external libraries or frameworks of its own but uses the leverages the ones in the project it is linked to. This way we are using whatever version of MonoGame the developer is using.

Also theoretically this would make the MonoGame.Extended work with both XNA and FNA.
