### ISSUE TITLE
Dialog window in Gui

### ISSUE THREAD

**Issue by Aurioch** [craftworkgames/MonoGame.Extended#255]
So, in rewriting one of my projects, I have come to the point where I kinda sorta need a dialog window in gui for level editor, so I though I'd write one myself for `Monogame.Extended`.

My idea was to write `GuiDialog` to be similar in functionality to `GuiComponent`, so that it can be created and called whenever without having to search for `GuiComponent` in the list of game's components. Also, I think `GuiDialog` should capture all the input events so that it doesn't "bleed through" to the rest of GUI or the game itself.

While I can hack out something (and have done for one game), I'm not confident that I'll be able to write it properly so that it fits with the rest of the framework.

**Comment by craftworkgames** [comment]
> so that it can be created and called whenever without having to search for GuiComponent in the list of game's components.

How do you think the API will work?  Can you post a snippet of code showing what it might look like when you create a dialog? Don't worry about getting it perfect, it's just for discussion purposes.

> While I can hack out something (and have done for one game), I'm not confident that I'll be able to write it properly so that it fits with the rest of the framework.

Sometimes it's easier to hack something up first so that we have something concrete to talk about. Even if it doesn't fit into the framework it'll be a good starting point.

**Comment by craftworkgames** [comment]
Hey, we got permission from Cygon to use his GUI code.

https://twitter.com/Cygon4/status/774661576913629185

> @craftworkgames Yes, I don't mind. In fact it's nice if it lives on somehow :)

Also, linking this to #20

**Comment by Aurioch** [comment]
Nice! I'm already close to adapting it; there are few classes I need to adapt, then test out some changes (especially the ones involving `System.IO` and `System.Reflection` namespaces), then write a demo sample.

**Comment by craftworkgames** [comment]
Hey

I just thought I'd let you know I found 2 other XNA / MonoGame GUI systems somewhat randomly today that I've never seen before. I wasn't actually looking around for GUI systems but saw a post about them on the [MonoGame Indie Devs](https://www.facebook.com/groups/MonoGameIndieDevs/) facebook page. 

[NeoForce](https://github.com/NeoforceControls/Neoforce-Mono) and [MonoForce](https://github.com/Cyral/MonoForce/tree/master/Source). MonoForce is supposed to be an improved version of NeoForce so in many senses they are the same library.

I don't know how you're going with Nuclex but I dunno, these might help in some way.
