### ISSUE TITLE
TiledMap.Draw seems to be broken with animated tiles

### ISSUE THREAD

**Issue by bsimser** [craftworkgames/MonoGame.Extended#256]
Working off the develop branch I think I found a bug. I tried loading up the demo app with some other test maps. One map has some animated tiles in it (untitled.tmx in the TiledMap demo). I'm also using a BoxingViewAdapter but it seems to do this on all adapters.

If I try drawing it with the extension method, it looks whacko

```
_map.Draw(_camera.GetViewMatrix());
```

I get this:

![image](https://cloud.githubusercontent.com/assets/301535/18334220/0ec90b1e-7533-11e6-99aa-022fd356abc1.png)

If I draw the same map using the layer method:

```
spriteBatch.Begin(transformMatrix: _camera.GetViewMatrix());
foreach(var layer in _map.Layers)
{
  layer.Draw(spriteBatch, null, null, gameTime);
}
spriteBatch.End();
```

I get this:

![image](https://cloud.githubusercontent.com/assets/301535/18334257/5d1f6222-7533-11e6-8098-e80db14dd1c7.png)

With animated tiles.

So tried another map (with no animated tiles) (leve03.tmx) and it renders fine both ways.

Am I losing my mind?

I can put together a new sample if nobody else is seeing this and try to reproduce it.

**Comment by LithiumToast** [comment]
It's probably just a bug with the new Tiled renderer.

**Comment by bsimser** [comment]
Thanks @LithiumToast. Is this a component you're working on or something that's just lingering (animated tile support) that maybe I should look at? (I don't need animated tile support, just stumbled over it in my test code).

**Comment by LithiumToast** [comment]
Well, see #221 and #223.

**Comment by bsimser** [comment]
Cool. I knew about 221 but didn't read 223. Finally did. Great work you guys, waiting for that to hit develop. I'm closing this if there needs to be one to address animated tiles it should be started with a proper test case and more info than what's here. Thanks
