### ISSUE TITLE
Gui Editor

### ISSUE THREAD

**Issue by pmyn** [craftworkgames/MonoGame.Extended#259]
Hello, 
MonoGame.Extended is a really great lib !!!
I want ask about Demo.Gui.
You use custom converters for read GUI content from title-screen.gui
Did You use some available editor or own custom one ?

Really thanks :+1:

**Comment by OptimusPi** [comment]
Feel free to join a conversation over at https://gitter.im/craftworkgames/MonoGame.Extended :) 

I am new around here so I don't know the answer for you. Best of luck!
