### ISSUE TITLE
[Framework] At some point we'll probably move to .NET Standard

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#262]
MonoGame.Extended works really well as a portable class library (PCL) but things are changing. At some point in the future we'll need to consider changing to the new .NET Standard.

https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

> .NET Standard will replace Portable Class Libraries (PCLs) as the tooling story for building multi-platform .NET libraries.

This could be a great thing, but it's probably too early to make the adoption.

I'm just raising this issue primarily so we don't forget about it but if anyone is interested in investigating further, it would be interesting to know if we could get the library to compile and run against .NET Standard on all of our supported platforms.

**Comment by bsimser** [comment]
.NET Standard (and support for Core) should maybe be a 2.0 version? Separate project/thread/fork/whatever. I only say this because a) It's unclear with MonoGame when they're going to support Core and how long they'll maintain two major versions b) while .NET core is at v1 it's still so young and changing every week. .NET Standard is even newer and still evolving. I think to make it easier to manage the library as a whole there probably should be a .NET Core and .NET Framework version but that's just my opinion. At the very least we can start by running the [API Port](https://github.com/Microsoft/dotnet-apiport) command line tool to check the compatibility of the library.

**Comment by craftworkgames** [comment]
I've used .NET Core at work and I think it's probably the right choice, at some point, in the future to replace PCL's.

Practically speaking though, I have no idea if it would work with MonoGame or not. I suspect not.

I raised this issue in case someone wants to investigate it further.

**Comment by craftworkgames** [comment]
This isn't gonna happen anytime soon. As far as I can tell we'd need MonoGame to support .NET standard and that's unlikely.

We'll reopen this issue if new information comes to light.

**Comment by exts** [comment]
@craftworkgames any plans on reopening this issue? Now that [monogame works](https://github.com/cra0zy/MonoGame) under .net core 2, would love to use this w/ my .netcore 2.0 project.

```
warning NU1701: Package 'MonoGame.Extended 1.0.617' was restored using '.NETFramework,Version=v4.6.1' ins
tead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
```

The warning I get currently.

**Comment by craftworkgames** [comment]
Yep, let's reopen the issue. I'm not sure if I'll get time to look at this myself but I'll keep it in mind.

**Comment by craftworkgames** [comment]
I'm looking into this as of today.

**Comment by Trapov** [comment]
@craftworkgames any news yet?

**Comment by craftworkgames** [comment]
Yes, absolutely.

I've already done this on the `2.0` branch and I'll be merging it back into `develop` soon.

**Comment by Trapov** [comment]
@craftworkgames i've looked into your changes, you're referencing the PCL version (_Monogame.Framework.Portable_) instead of the .net standard version (_MonoGame.Framework.DesktopGL.Core_), which, of course, is a bit different, since it targets specific platform.

What i'm trying to say is that the current package of Monogame.Extended wont work for .net standard/core solutions as far as i concerned.

- https://github.com/MonoGame/MonoGame/issues/5339#issuecomment-342686703 - about (_MonoGame.Framework.DesktopGL.Core_)
- https://github.com/MonoGame/MonoGame/issues/5724#issuecomment-311313438 - about (_Monogame.Framework.Portable_)

**Comment by Trapov** [comment]
![image](https://user-images.githubusercontent.com/13402883/40465664-6101b81a-5f3b-11e8-91ad-82a889e4ed21.png)

vs


![image](https://user-images.githubusercontent.com/13402883/40465672-6d1fd5fa-5f3b-11e8-804f-9de81ff3a135.png)

**Comment by craftworkgames** [comment]
> What i'm trying to say is that the current package of Monogame.Extended wont work for .net standard/core solutions as far as i concerned.

What makes you say that?  Have you tested it yourself? 

If something doesn't work then of course we need to fix it but my initial tests (by building some demos) indicate that it will work just fine referencing the PCL. 

Firstly, I know it's not ideal to be getting that warning but technically speaking there shouldn't be anything in the PCL that prevents it from working. Bait-and-switch PCL's are just empty stubs that get replaced by the real DLL at compile time.

Secondly, keep in mind that this is very much a work in progress. I've done my best to get something working fairly quickly. There's plenty of room for improvement. I talked to @SimonDarksideJ about this the other day and he said that nobody has tried to build a .NET Standard version of the old MonoGame PCL. So as far as I'm aware, we're stuck with this approach for now.

That said, if you think there's a better approach, I'm all for it. Referencing the PCL feels a little hacky and certainly wasn't how I wanted to do it in the first place. Maybe, if there's only going to be 2 x NuGet packages for MonoGame, we can take the same approach with Extended?

**Comment by Trapov** [comment]
@craftworkgames oh, hm, it seems to be working with it. The other day it wasn't building & complaining about namspaces, guess was something wrong with my tooling. 

> Maybe, if there's only going to be 2 x NuGet packages for MonoGame, we can take the same approach with Extended?

I think in the 3.8 version monogame is going to push DX and GL packages, need to submit an issue and ask, i guess.

Anyway thank you for the response! :smiley:

**Comment by craftworkgames** [comment]
> any updates yet?

There's still some unresolved problems around the order that you need to build the projects. I've fixed this in the cake script though so if you just run the `build.ps1` file it should do the right thing.

> Also what's up with the Monogame.Extended.Entities package?

Yep, so the Entities package has had a complete re-write from the ground up. There were lots of problems with the old one and fixing it wasn't really feasible. The new one is mostly stable as far as I'm aware, although there's probably a little work left to do on it.

> does it include the features that are available in the current API?

In terms of what you can do with the new API I think it's all covered although the approach is a bit different. A lot of inspiration was borrowed from [artemis-odb](https://github.com/junkdog/artemis-odb) among others. When I merged it back into `develop` I did write up some [docs](http://docs.monogameextended.net/Features/Entities/).

> oh i see they are in the develop branch already, was lookin' at the 2.0 branch.

Ah yeah, that's a good point. I'll go clean up some of these old branches now.
