### ISSUE TITLE
[Tiled] Clean up the Tiled API to remove any inconsistencies

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#267]
The Tiled API has evolved over time and has become a little clunky in some places. 

For example, we have a few different ways of exposing list properties:

```
    public IReadOnlyList<TiledTileset> Tilesets => _tilesets;
    public IReadOnlyList<TiledObjectGroup> ObjectGroups => _objectGroups;
    public IReadOnlyList<TiledLayer> Layers => _layers;
    public IEnumerable<TiledImageLayer> ImageLayers => _layers.OfType<TiledImageLayer>();
    public IEnumerable<TiledTileLayer> TileLayers => _layers.OfType<TiledTileLayer>();
```

My preference is to make them all use `IReadOnlyList` becase it provides the best of both worlds. Indexed protected collections.

It's also bothered me for a while that `ObjectGroups` are separated from layers. In the editor they are just another type of layer.

There's also some general code cleanup to do.

**Comment by musbah** [comment]
The tilesets tiles contain `ObjectGroups` as well though, so you can't really say that they're only used in the ObjectLayer, unless you think of tilesets as containing a layer.

**Comment by craftworkgames** [comment]
> The tileset tiles contain ObjectGroups as well though, so you can't really say that they're only used in the ObjectLayer, unless you think of tilesets as containing a layer which I'm not sure is the case.

Yeah, maybe so. I guess it just bothers me that it's inconsistent with the Tiled Editor.

**Comment by musbah** [comment]
I actually just looked at tiled, and it seems that every tileset tile contains it's own ObjectLayer, so I think your idea might work.

**Comment by craftworkgames** [comment]
> it seems that every tileset tile contains it's own ObjectLayer

Where is that in the editor? I can't seem to find it.

**Comment by musbah** [comment]
You press on view, then on Tile Collision Editor, and then press on a tile in the tileset. Shows you the object layer in the properties, you can name it and what not. Then you can add objects to the layer using the tools.

**Comment by OptimusPi** [comment]
Wanted to write a quick reminder before I forget; "TiledTileSet" should be renamed to "TiledTileset" to match other usages of the word "Tileset" as one. Thanks!

**Comment by musbah** [comment]
I was looking through some code today, and looking at [TiledObject.cs
](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Maps/Tiled/TiledObject.cs) I noticed that there was no point in adding X and Y. I kind of find it hard to explain so I'm just going to show snippets.

The below is pretty much what we have right now(I removed what wasn't necessary for the example to make it easier to understand):

        public TiledObject(TiledObjectType objectType, int id, int? gid, float x, float y, float width, float height)
        {
            X = x;
            Y = y;
        }

        public float X { get; }
        public float Y { get; }
        public Vector2 Position => new Vector2(X, Y);

I was wondering if it wouldn't be better to just change that into something like:

		public TiledObject(TiledObjectType objectType, int id, int? gid, float x, float y, float width, float height)
        {
			Position = new Vector2(x,y);
        }

        public Vector2 Position { get; private set; }

or maybe having `X` and `Y `without `Position`, the way it is now just seems redundant.

**Comment by craftworkgames** [comment]
Yeah, it seems reasonable. I mean it's not really hurting anything to have X and Y available either so I'm not really bothered either way.

**Comment by bsimser** [comment]
The thing about having a Vector2 is you can do operations against it which I find is more useful. If you really want an X/Y property then just have a getter that returns that portion of the Vector2 but otherwise it seems redundant.

**Comment by craftworkgames** [comment]
Yeah, fair enough. 

@musbah Are you going to do a PR with some changes?

**Comment by musbah** [comment]
@craftworkgames I'll do a PR in a bit, just need to test it out first and see if X and Y are used anywhere and change them.

**Comment by OptimusPi** [comment]
Did we catch all of the "TileSet" -vs- "Tileset" inconsistencies? I got latest before doing my PR and noticed at least one instance. "Tileset" is preferred... Thanks!

**Comment by musbah** [comment]
@OptimusPi I don't believe we did, one obvious thing is the file names. We should probably change `TiledTileSet.cs` and `TiledTileSetTile.cs` and `TiledTileSetTileFrame.cs`.

**Comment by craftworkgames** [comment]
> other than the actual filenames it seems like all of them were caught.

Great news. I think technically it's not the filenames themselves, but the way they are referenced in the project file. So I think it'll mean editing the csproj file to fix that.

**Comment by HyperionMT** [comment]
@craftworkgames and @musbah I'm working on closing out #125 but in order to render the objects correctly I need to know the layer depth.  My plan is to make TiledObjectGroup derive from TiledLayer and include them in TiledMap.Layers.  I'll leave the TiledTilesetTile.ObjectGroups alone as it makes sense to keep them there.  Since the two of you were discussing this earlier in the issue (and it wasn't clear if you guys ever came to an agreement) I wanted to ask if you guys had any objections.

**Comment by craftworkgames** [comment]
> My plan is to make TiledObjectGroup derive from TiledLayer and include them in TiledMap.Layers.

Sounds good to me. It seems more consistent with the way the editor works this way.

**Comment by craftworkgames** [comment]
I did a big clean up the other night. There's always more to do but I don't see any need to keep this issue open.
