### ISSUE TITLE
[Tiled] Split the Tiled renderer out of the map code

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#268]
So a while back when we did some work on #230 it was a little unclear how we should handle rendering the Tiled maps to allow end users to configure and customize rendering for different situations.

Then recently I was reading about [Retained Mode](https://msdn.microsoft.com/en-us/library/windows/desktop/ff684178%28v=vs.85%29.aspx) rendering and I realized that there's many benefits to splitting the _model_ from the _rendering_. I think that's what we should do for the Tiled renderer (and perhaps other parts of the framework).

This would allow the responsibility of rendering the map be separated from the map data. The beauty of this approach is that different types of renderers could be implemented independently of a `TiledMap` allowing for different renderers to be optimized for different situations.

**Comment by HyperionMT** [comment]
Is anybody currently working on this?  If not I'd like to take a shot.

What I'd like to do is create a FullMapRenderer with the existing code and create an IMapRenderer interface future renderers can implement.  I think IMapRenderer would look something like:

```
IMapRenderer
    void SwapMap(TiledMap newMap);

    [Obsolete]
    void Draw(Camera2D camera);
    void Draw(Matrix viewMatrix);
```


I think once that's done we might be able to extract an interface on the Tiled objects which the renderers can reference so they can support any future map formats as well.  Any comments/suggestions?

**Comment by craftworkgames** [comment]
> Is anybody currently working on this? If not I'd like to take a shot.

Nobody is currently working on it.

You've been doing some great work already, so yeah, you're welcome to take this on.

To be honest, I'm not sure what the intention of `SwapMap` would be, but I'll leave it in your capable hands and see what you come up with.

Thanks.

**Comment by HyperionMT** [comment]
I was thinking for projects with multiple maps (levels) you wouldn't want to create a new renderer just to display the next level, instead you would swap out the current map with a new one.

**Comment by craftworkgames** [comment]
Yeah, that makes sense.

It would be nice to update the demo to swap between each of the different maps that way.

**Comment by craftworkgames** [comment]
Completed in #292
