### ISSUE TITLE
Platform-based build configurations

### ISSUE THREAD

**Issue by WardBenjamin** [craftworkgames/MonoGame.Extended#27]
Hey Dylan,

In some of my projects, I have created different build configurations for each platform. This means that multiple versions of MonoGame.Framework are referenced via Nuget, and only the platform-specific one that is required by the build configuration is actually used.

Would you be interested in this for the sandbox project? It's not too much work for me, and it would save me hacking together a new csproj file and editing references every time I pull.

**Comment by craftworkgames** [comment]
I think it's a very good thing to have everything work out of the box for everyone. I don't want you to be hacking together csproj files and editing references all the time. That sux.

On the other hand, I'm not entirely convinced that having multiple people working in the sandbox project is going to scale very well. At this stage I'm not sure how to solve that problem. We definitely need a way to make changes to the library and test them in some sort of "game" like project. Maybe that's a sandbox, maybe it isn't.

> I have created different build configurations for each platform.

Do you have a repo I can look at to understand how this works? It sounds good on paper but I'm not sure what to expect from the PR.

If it makes the project better and won't break anything, by all means.

I'm

**Comment by WardBenjamin** [comment]
I don't have a repo that you can look at, since the project isn't open-source, but I can paste some info in here. Here's what the references inside of `foobar.csproj` might look like:

    <ItemGroup>
      <Reference Include="System" />
      <Reference Include="System.Data" />
      <Reference Include="System.Data.DataSetExtensions" />
      <Reference Include="System.Xml" />
      <Reference Include="System.Core" />
      <Reference Include="Tao.Sdl" Condition="'$(Configuration)'=='LinuxDebug' Or '$(Configuration)'=='LinuxRelease'">
        <HintPath>..\packages\MonoGame.Framework.Linux.3.4.0.459\lib\net40\Tao.Sdl.dll</HintPath>
      </Reference>
      <Reference Include="MonoGame.Framework" Condition="'$(Configuration)'=='WinDebug' Or '$(Configuration)'=='WinRelease'">
        <HintPath>..\packages\MonoGame.Framework.WindowsGL.3.4.0.459\lib\net40\MonoGame.Framework.dll</HintPath>
      </Reference>
      <Reference Include="MonoGame.Framework" Condition="'$(Configuration)'=='LinuxDebug' Or '$(Configuration)'=='LinuxRelease'">
        <HintPath>..\packages\MonoGame.Framework.Linux.3.4.0.459\lib\net40\MonoGame.Framework.dll</HintPath>
      </Reference>
      <Reference Include="OpenTK, Version=1.1.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4" Condition="'$(Configuration)'=='WinDebug' Or '$(Configuration)'=='WinRelease'">
        <HintPath>..\packages\MonoGame.Framework.WindowsGL.3.4.0.459\lib\net40\OpenTK.dll</HintPath>
      </Reference>
      <Reference Include="OpenTK, Version=1.1.0.0, Culture=neutral,  PublicKeyToken=bad199fe84eb3df4" Condition="'$(Configuration)'=='LinuxDebug' Or '$(Configuration)'=='LinuxRelease'">
        <HintPath>..\packages\MonoGame.Framework.Linux.3.4.0.459\lib\net40\OpenTK.dll</HintPath>
      </Reference>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\packages\Newtonsoft.Json.7.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
      </Reference>
    </ItemGroup>

Then, the file `foobar.sln` would contain the following: (where 0F2707D7-703B-4876-AA0B-144FED64CA83 is the project GUID, and there are copies of the project-specific config for each project)

	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		LinuxDebug|Any CPU = LinuxDebug|Any CPU
		LinuxDebug|Mixed Platforms = LinuxDebug|Mixed Platforms
		LinuxDebug|x86 = LinuxDebug|x86
		LinuxRelease|Any CPU = LinuxRelease|Any CPU
		LinuxRelease|Mixed Platforms = LinuxRelease|Mixed Platforms
		LinuxRelease|x86 = LinuxRelease|x86
		WinDebug|Any CPU = WinDebug|Any CPU
		WinDebug|Mixed Platforms = WinDebug|Mixed Platforms
		WinDebug|x86 = WinDebug|x86
		WinRelease|Any CPU = WinRelease|Any CPU
		WinRelease|Mixed Platforms = WinRelease|Mixed Platforms
		WinRelease|x86 = WinRelease|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxDebug|Any CPU.ActiveCfg = LinuxDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxDebug|Mixed Platforms.ActiveCfg = LinuxDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxDebug|Mixed Platforms.Build.0 = LinuxDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxDebug|x86.ActiveCfg = LinuxDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxDebug|x86.Build.0 = LinuxDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxRelease|Any CPU.ActiveCfg = LinuxRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxRelease|Mixed Platforms.ActiveCfg = LinuxRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxRelease|Mixed Platforms.Build.0 = LinuxRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxRelease|x86.ActiveCfg = LinuxRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.LinuxRelease|x86.Build.0 = LinuxRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinDebug|Any CPU.ActiveCfg = WinDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinDebug|Mixed Platforms.ActiveCfg = WinDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinDebug|Mixed Platforms.Build.0 = WinDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinDebug|x86.ActiveCfg = WinDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinDebug|x86.Build.0 = WinDebug|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinRelease|Any CPU.ActiveCfg = WinRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinRelease|Mixed Platforms.ActiveCfg = WinRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinRelease|Mixed Platforms.Build.0 = WinRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinRelease|x86.ActiveCfg = WinRelease|x86
		{0F2707D7-703B-4876-AA0B-144FED64CA83}.WinRelease|x86.Build.0 = WinRelease|x86
	EndGlobalSection

**Comment by WardBenjamin** [comment]
Finally, each project needs to have a normal packages.config file, such as this one:

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="MonoGame.Framework.Linux" version="3.4.0.459" targetFramework="net45" />
      <package id="MonoGame.Framework.WindowsGL" version="3.4.0.459" targetFramework="net45" />
      <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net45" />
    </packages>

**Comment by craftworkgames** [comment]
Oh understand it now, we do something similar at work. So by manually editing the project file you can conditionally change the project references based on the solution platform.

This sounds pretty reasonable, we just need to document it somewhere. Perhaps a README in the project since it requires manually editing the project files to maintain.

The only change I would make is to make use of the `$(Platform)` [macro](https://msdn.microsoft.com/en-us/library/c02as0cs.aspx) so instead of creating multiple configurations you end up with something like this:

$(Configuration) = Debug or Release
$(Platform) = Windows or Linux

Then the project changes become:

	<Reference Include="MonoGame.Framework" Condition="'$(Platform)'=='Windows'>
		<HintPath>..\packages\MonoGame.Framework.WindowsGL.3.4.0.459\lib\net40\MonoGame.Framework.dll</HintPath>
	</Reference>
	<Reference Include="MonoGame.Framework" Condition="'$(Platform)'=='Linux'>
		<HintPath>..\packages\MonoGame.Framework.Linux.3.4.0.459\lib\net40\MonoGame.Framework.dll</HintPath>
	</Reference>

Doing it this way has the advantage that you only ever have 2 configurations (Debug and Release) and many platforms (Windows, Linux, etc).

Note: At this point we don't need AnyCPU, Mixed Platforms or x86. They can be deleted.

At least that's how it [works in Visual Studio](https://msdn.microsoft.com/en-us/library/ms165408.aspx). Hopefully it makes sense in a Linux environment too.

**Comment by WardBenjamin** [comment]
Huh, I never thought to do it like that. The way that I suggested was mostly autogenerated by VS originally, and it worked so I never thought to change it.

> This sounds pretty reasonable, we just need to document it somewhere. Perhaps a README in the project since it requires manually editing the project files to maintain.

Yeah I can do this once I actually get things to run on my end. There's no more issues with MonoGame itself, but the content stuff never actually seems to build, even with the properties properly set on the mgcb file. I've opened up an issue on mono/MonoGame, but I have a feeling it won't be resolved until after I have access to my normal Windows dev PC.

**Comment by craftworkgames** [comment]
Great. Thanks for all your help so far. It's nice having a Linux guy on the team.

>I've opened up an issue on mono/MonoGame, but I have a feeling it won't be resolved until after I have access to my normal Windows dev PC.

Yeah, it sux that they are lagging behind on Linux. Hopefully the issues will only be temporary though.

**Comment by WardBenjamin** [comment]
Yeah I agree. One of the MonoGame guys said they would take a look after one of his PR's was merged (something to do with the installer). That probably means it'll take a while.

**Comment by craftworkgames** [comment]
> I've opened up an issue on mono/MonoGame

Should probably get into the habit of linking to the issue for future reference.

**Comment by WardBenjamin** [comment]
Yeah, not a bad idea. Here's a link: https://github.com/mono/MonoGame/issues/4059

**Comment by WardBenjamin** [comment]
Whoops :P

**Comment by craftworkgames** [comment]
> @WardBenjaminWardBenjamin closed this a minute ago
@WardBenjaminWardBenjamin reopened this a minute ago
Whoops :P

Lol. It happens.

**Comment by WardBenjamin** [comment]
Well.... so here's the deal. I can build everything that doesn't require the Monogame custom build .targets file from MonoDevelop (the C# editor I use on Linux), however I cannot build content, with one caveat: if I use xbuild on the solution from the command line it builds fine. It seems that MonoDevelop does not support custom .targets files... I may have to amend that blog post I wrote.

**Comment by WardBenjamin** [comment]
I'm also having some issues with the .targets file in the first place... it refuses to be used to build the .mgcb file, while the MGCB tool works correctly.

**Comment by craftworkgames** [comment]
> the MGCB tool works correctly.

At least you have a workaround for the time being.

**Comment by WardBenjamin** [comment]
So... I'm alive again. I have access to my Win8.1 box so I can try to get this sorted. If you are manually adding dependencies, it seems to work as-is with the configuration stuff that I've written, however the issue with the .targets file is still... an issue. Hopefully we can get a workaround somewhere inside of the MonoGame plugin at least.

**Comment by WardBenjamin** [comment]
Welp. Seems like we won't be able to add custom platforms. The only supported ones are x86, x64, ARM, AnyCPU, and Mixed Platforms. I can still do the configurations like I illustrated before... what's your opinion on what I should do?

**Comment by craftworkgames** [comment]
No problem. Thanks for investigating it. Just do them however you think it works best.

**Comment by WardBenjamin** [comment]
By the way, this will eventually be obsolete since MonoGame is moving towards a unified DesktopGL platform rather than WindowsGL, Mac, and Linux. This (I believe) will be a part of MonoGame 3.5.

**Comment by craftworkgames** [comment]
>  this will eventually be obsolete since MonoGame is moving towards a unified DesktopGL platform rather than WindowsGL, Mac, and Linux. This (I believe) will be a part of MonoGame 3.5.

That's exciting.

I'm going to close this issue. If we come up with a different way to have a sandbox project on multiple platforms open a new issue.
