### ISSUE TITLE
BoxingViewPort doesn't work on Mac.

### ISSUE THREAD

**Issue by Cryru** [craftworkgames/MonoGame.Extended#273]
Instead of black bars the image is just stretched to fill the whole window.

**Comment by bsimser** [comment]
Do you have some code and more information on this? I don't see issue on my Mac.

**Comment by Cryru** [comment]
On Windows: http://i.imgur.com/DLERrQa.png
On Mac: http://i.imgur.com/O1aF0n4.png

This is the exact same code which is:

`graphics.PreferredBackBufferWidth = 960;`
`graphics.PreferredBackBufferHeight = 540;`
`graphics.ApplyChanges();`
`ScreenAdapter = new BoxingViewportAdapter(game.Window, game.GraphicsDevice, 400, 400);`

Maybe I'm doing something wrong here.

**Comment by craftworkgames** [comment]
This sounds familiar.

There was a bug in MonoGame a while back that caused a similar issue with the `BoxingViewportAdapter` if you where using MonoGame DX as opposed to GL. 

So more than likely, it's got something to do with the version of MonoGame you're referencing on the Mac. 

@Cryru What version of MonoGame are you referencing?
@bsimser What version of MonoGame are you referencing?

As a general rule, MonoGame.Extended doesn't actually do any platform specific code. All of that responsibility is delegated to MonoGame.

I believe this is the related MonoGame issue https://github.com/MonoGame/MonoGame/issues/4018

**Comment by Cryru** [comment]
On PC I am using 3.5 and a GL project, on Mac whatever version the latest xamarin addin is.

**Comment by craftworkgames** [comment]
Probably best to raise this with the MonoGame team.
