### ISSUE TITLE
Should we support FNA?

### ISSUE THREAD

**Issue by ClassicThunder** [craftworkgames/MonoGame.Extended#28]
Since both MonoGame and [FNA](http://fna-xna.github.io/) strive to be accurate to the original XNA API any code written for one should work for all of them. I don't know how much work it would be but I think it would greatly expand out potential user base. 

Related to [Splitting the project into different DLLs and NuGet packages](https://github.com/craftworkgames/MonoGame.Extended/issues/10) as it would add more work there.

**Comment by craftworkgames** [comment]
>  I think it would greatly expand out potential user base.

Any idea what the size of the user base is? Based on the stars on github it looks to be about 10% of MonoGame's.

To be honest, I don't think it would be a *lot* of work. But I do question if it's the right time to do it. MonoGame.Extended is only about 2 months old and is far from a mature project. Adding any extra overhead to the development cycle now could slow us down for not much gain.

That said, if you're really keen, give it a go and report back with what you find out.

Btw, are you using FNA in your own projects?

**Comment by ClassicThunder** [comment]
> Any idea what the size of the user base is?

Honestly not sure, the game list released using it is pretty impressive though. Terraria and Rouge Legacy being 2 of the big ones.  

> Adding any extra overhead to the development cycle now could slow us down for not much gain.

Keeping shared project up to date with all of the files in the project should be the extent of the maintenance. I'll experiment more over the weekend but I was able to get my input library to run against both XNA and FNA by simply loading up the templates and adding the project. 

> Btw, are you using FNA in your own projects?

I've used FNA much more than MonoGame actually. In particular I've found the input and window management much more consistent. I think this is a result of FNA being based on SDL, a widely used library who's purpose is to provide consistent and cross platform low level behavior. As a result the fundamentals have been 

BTW are we using Protobuild to generate the Nugets? Looking into its capability having it generate a shared project looks like it might be trivial, I'll bring it up on their github and see what they think.

**Comment by craftworkgames** [comment]
I've only had a very brief look into Shared Projects myself but if I'm understanding correctly it could work something like this:

Shared Project - contains ALL of the code.
MonoGame.Extended - contains very little, but references the SP.
FNA.Extended - contains very little, but references the SP.

When the projects are compiled you would end up with 2 output assemblies, one compiled for MonoGame and one compiled for FNA but both containing exactly the same code.

Does that sound correct to you? (Please correct me if I'm wrong).

> the game list released using it is pretty impressive though. Terraria and Rouge Legacy being 2 of the big ones.

Looks to me like most of the games released using FNA are ported by one guy, Ethan Lee. It really is a very [impressive list](http://www.flibitijibibo.com/index.php?page=Portfolio/Ports) and it would appear that FNA is very stable, even if it's not used by many people.

It also looks like it started life as a fork of MonoGame anyway, but a lot of work has been put into it to make it much more stable on desktop OS's. Support for mobile devices has been dropped.

> BTW are we using Protobuild to generate the Nugets?

MonoGame.Extended doesn't use Protobuild. It's just *one* portable class library (PCL) project that can be referenced from many platforms. This is by far the easiest option and I don't want to use Protobuild until there's a really good reason to do so.

Of course, if there really is a good reason to use Protobuild or whatever I'm open to the idea. I just don't want to be spending my nights maintaining lots of crap. My time is already pretty limited.

**Comment by ClassicThunder** [comment]
> Does that sound correct to you? (Please correct me if I'm wrong).

Sounds correct. Basically the shared project contains the code while the MonoGame.Extended and FNA.Extended projects define the references for generating the nugets. 

> MonoGame.Extended doesn't use Protobuild.

Okay then ignore that bit. Protobuild is the only method I know of for generating dealing with cross platform mono projects so I just assume MonoGame.Extended was using it.

**Comment by craftworkgames** [comment]
I installed Visual Studio 2015 today and took a closer look at how Shared Projects work. They certainly do make code sharing between projects a lot easier.

> Protobuild is the only method I know of for generating dealing with cross platform mono projects

MonoGame.Extended is not exactly cross platform per se, it leverages the cross-platformness of MonoGame. Thanks to the work done by @DDReaper and the MonoGame PCL.

Anyway, it sounds like we have a way to support FNA. Although, I had trouble compiling FNA myself. They don't seem to have a NuGet package either.

**Comment by ClassicThunder** [comment]
Yeah getting it up and running is not as simple as with MonoGame. What OS are you trying to get it running on?

**Comment by craftworkgames** [comment]
Windows 10. Although, it shouldn't be any different to Windows 8.

The issue was getting the dependencies sorted. Tbh, I didn't put in much effort.
