### ISSUE TITLE
Threaded content managers and paletted textures

### ISSUE THREAD

**Issue by JustinHughart** [craftworkgames/MonoGame.Extended#282]
![palettes](https://cloud.githubusercontent.com/assets/5400346/19778456/740fdf58-9c42-11e6-9875-0d63051f1f8e.png)

So for my game, I have a threaded content manager and support for textures with palettes (without shaders), and I'm willing to sit down and clean up the code and submit it to Monogame.Extended. So with that said, is anyone interested in this, and what kind of coding guidelines must I follow if the people want it?

**Comment by craftworkgames** [comment]
It sounds interesting, although, I don't think you've provided enough info to be able to tell if these features are a good candidate for the library. What do they do and why would I need them to make a game?

As for the coding guidelines, just try to keep your code consistent with other code in the library and follow [C# Naming Guidelines](https://msdn.microsoft.com/en-us/library/ms229002(v=vs.110).aspx) as much as possible.

Oh and I really appreciate having some way to test PR's. Either updated demos or unit tests depending on the changes. Small changes are okay if I can clearly see what the code is doing during a code review.

**Comment by JustinHughart** [comment]
Well first off I should say my game is a multiplayer RPG, so it has certain needs. Needs include loading assets on the fly and, due to the nature of RPGs, have recolored enemies, as well as custom clothing colors. One way to go about the recolor thing would be shaders, but I chose to use the option to forego shaders altogether and create them as textures. So I'll go over features of those systems in a bit of detail. Also I'm not 100% sure this are the best way of handling this.

For threaded content managers, it acts like a ContentManager. You request a texture, and it'll check a cache to see if it has already been loaded. It adds it to a queue of things to load if it isn't already in the queue, and returns null. If the load task isn't running, it'll make it run as well. My entities are expected to not draw themselves until their textures are loaded, so when it goes to draw, it'll run LoadContent() again, eventually receiving the texture requested. I feel like there's a decent amount of game types, especially RPGs, that could benefit from this, which is why I offer.

For the paletted textures, it takes two things iirc, a graphicsdevice and a content manager. You ask for a texture, and you give it a texturepath and a palette. Like the threaded content manager, it has a cache of these things that operates the same way. When creating a texture, it extracts the base texture's color data and iterates over it, replacing each pixel with a new color from the palette. It then uses that new color data to make a new texture, and handles unloading them as needed. Unfortunately this process is currently on the CPU, and thus is slow, especially with large textures and palettes. For a game like mine, it's not bad though. In my personal implementation, this process is threaded as well, as to not hang the game when it loads a new enemy type like a random boss intrustion, or a player joining your game with a different outfit than you.

I guess I'd need to look over how Monogame.Extended is coded to find that out, but am I correct in assuming you'll work with me to help keep my code quality high if you accept it?

By PRs, do you mean pull requests? I can make a demo without a problem, but I've actually never made a unit test before so I wouldn't know the first thing about that honestly... Either way, if you accept it, I'm willing to work with you on it.

**Comment by craftworkgames** [comment]
I don't think the paletted textures fit into MonoGame.Extended.

The threaded content manager is an interesting idea but I'm not entirely certain how it fits into the library at this stage. I'd be happy to revisit this issue at some point in the future but for now I'm going to close this issue.

**Comment by JustinHughart** [comment]
Well, gotta do what you gotta do to keep your library focused, but I will say that at least in the circle I visit, people get annoyed about having to physically duplicate textures and save them as individual files. Dealing with setting up a system for palettes, either through a shader or through what I described is also not very easy for a beginning user, to the point of being considered eldritch magic, although they may want that functionality. I offered it since it's a feature that could make a pixel art dev's life easier.

As for the threaded content manager, I don't know why they're not already threaded. In how games are today, the need for that sort of thing is increasingly.... increasing. Although I definitely understand, even with the palette thing, that you have to build a focus, so perhaps this is a bad time for both. At the very least, those two features, even back before monogame was a thing, were something I wish I had, as well as was very common in my circle. Not that it's the entire world, but at some point, I implore you to reconsider. Thank you for at least entertaining the idea for now!

**Comment by craftworkgames** [comment]
They do sound like good ideas. I just don't think it's the right time to include them in the library.

My main issue is that we've already got a lot going on in the `develop` branch at the moment. 

However, thinking about it a little more, maybe this is a good candidate for features that are split away from the core library (i.e. #275 ). That way, we could have the features but version them separately from everything else.

If you're interested, maybe you'd like to create a fork and figure out how this might work?

**Comment by JustinHughart** [comment]
I understand that now's not exactly a good time. It's not a super great time for me either, as I have a month until finals at uni and I'm way behind due to severe illness. But I did want to give back to to the community, especially after BMFont was so helpful! 

As for core and split, my opinion on this is as follows. Threaded content managers should definitely be a core feature. Almost every game could make use of it. It allows for loading screens that are animated, seamless background loading of assets without freezing the game, etc. I can't think of anything that would be more "core" in this library. For paletted textures, I agree with splitting that off into a branch aimed specifically at pixel art, but I'm not sure what other features we could have. You can't really have a separate package for a single thing, right? So I'd recommend holding off on that until we can figure out some other more pixel-oriented things to fill the package with.

Also, I'm not going to lie, I'm not too sure what you want me to accomplish with a fork of it. I've been making games since I was 12 (although I haven't been to confident to release one yet), but that's all I've ever done. I'm not super duper familiar with git. I understand what forking will do, but I'm not sure about this nuget and packaging thing and all that. I really am clueless about working together with other devs, but I'm willing to put in the time to learn it if you'll have me!

**Comment by OptimusPi** [comment]
Justin, join the gitter chat sometime! I made a successful contribution to this project. Even though it was my first ever GitHub pull request, it was easy in the end! 

First you fork into your own branch, and clone that to your visual studio. Next you make your changes and  make sure to write a description of what you did and why. Polish it nicely.

Then, create a pull request (which is saying, merge my code into the "real" code/develop branch)

If it's not "good enough" to be accepted, there will be a discussion through GitHub comments on how to make it better. Easy peasy! Include screenshots if appropriate.

**Comment by JustinHughart** [comment]
Right, I understand that, but he's talking a bit above that I believe. Not to sound ungrateful or anything, I really do appreciate any help, but I'm not sure what exactly I should be trying to accomplish by that fork, how nuget applies to this, and how he wants me to experiment with using a new package in nuget... That much makes me lost! Also, gitter chat? I saw that somewhere in one of the issues but I lost the link and then I couldn't find it looking for it and it was a nightmare so I gave up, haha. Thanks to that, I found the link though, thank you!

**Comment by craftworkgames** [comment]
>  Not to sound ungrateful or anything, I really do appreciate any help, but I'm not sure what exactly I should be trying to accomplish by that fork, how nuget applies to this, and how he wants me to experiment with using a new package in nuget... That much makes me lost!

Yeah, sorry. This is not easy stuff.

> Also, gitter chat? 

Gitter is our [real time chat room](https://gitter.im/craftworkgames/MonoGame.Extended). If you want to contribute, it's a great place to start.
