### ISSUE TITLE
[Tiled] Maps with many tiles render incorrectly

### ISSUE THREAD

**Issue by HyperionMT** [craftworkgames/MonoGame.Extended#284]
I was playing around with a few of the demos today (from the develop branch) and noticed that if I used "untitled.tmx" with the TiledMaps demo it would only display a strip of tiles towards the top of the map even though the entire map should have shown the grass tile.  Another interesting thing to note is that these tiles only came from the "Grass" layer and neither of the other two layers were displayed.

For reference here is what the map looks like in the Tiled editor:
![tilededitor](https://cloud.githubusercontent.com/assets/23129284/19829768/5c723a04-9db8-11e6-8fbf-765c0d589023.png)

And here it is at runtime:
![runtime](https://cloud.githubusercontent.com/assets/23129284/19829782/a68b0e5e-9db8-11e6-87f6-02c94fa9cc8a.png)
Note that the tiles stop rendering part way through the last row.  The coordinates of the first invisible tile are (384, 32) which is tile number 15,884 rendered RightDown (not including any other layers).

I then erased all the grass tiles outside of the "main" map area but left the map size 500x500 and ran the demo again:
![runtimeedited](https://cloud.githubusercontent.com/assets/23129284/19829797/d69a08c0-9db8-11e6-92ec-0d291408ba7d.png)

As you can see it rendered correctly this time so it seems to be tied to the number of non-blank tiles and not the size of the map itself.  Please let me know if any other information would be helpful.

**Comment by musbah** [comment]
The interesting thing is that your runtime actually renders something while mine doesn't. I just tested it out and it doesn't render any part of the map at all by default. I'm going to look at the tiled map code a bit closer and see if I can find the root of the problem.

**Comment by HyperionMT** [comment]
Not sure why you didn't see any of the map drawn, did you notice the coords in my 2nd screenshot?  By default the demo places you in the center of the map which has nothing drawn, I had to hold the up arrow until I saw tiles draw around Y=100.

I was actually just looking at the same piece of code after doing some additional testing and I think I know what's going on.  I started over with a new map with only 1 layer to take that complexity out.  I was able to get a 128x128 1-layer map (all tiles non-blank) to draw flawlessly, more than that and I started seeing problems.  I noticed while debugging that the vertex buffer size was 65536 which I've seen referenced as the maximum size for DrawIndexedPrimitives.  Admittedly those references were for XNA but I'm guessing MG has a similar limit.

If this is indeed what the issue is I think the fix would be to break up the vertex buffer into chunks of 65536 and call DrawIndexedPrimitives multiple times.

**Comment by musbah** [comment]
I did go to the positions, nothing was drawn, it was weird...

Anyway, you can always test the platformer and what not, to make sure it still works. Also you can run the unit tests using NUnit (they're in MonoGame.Extended.Tests).

If you don't find any problems you might as well create a pull request, I can help you test it when you do to see if it works on my end.

**Comment by HyperionMT** [comment]
Thanks @musbah, all the unit tests pass but there don't appear to be any for Tiled maps.  I also ran the Platformer demo and all the maps in the TiledMap demo and everything looks good.  I created PR #285 with the fix if you want to give it a shot.

**Comment by craftworkgames** [comment]
I'm completely happy with the way you've handled this guys. 

The discussion here is great. It gives me the info I need to see what the PR is all about and I'm pleased that you've spent the time to test the changes against existing demos and unit tests 😄 

I've nothing more to say other than thank you.
