### ISSUE TITLE
[Tiled] Isometric map rendering is incorrect in certain situations

### ISSUE THREAD

**Issue by HyperionMT** [craftworkgames/MonoGame.Extended#295]
I believe this broke during the conversion from SpriteBatch rendering to DrawIndexedPrimitives.  Basically the problem is that by grouping tile draws by tileset, when there are multiple tilesets on the same layer, we mess up the z-order of individual tiles such that they don't always overlap properly.  I believe this would happen in any draw order but the screenshot below is from TiledMaps.Demo level05.tmx which is isometric with left-up draw order.

![isometricproblem](https://cloud.githubusercontent.com/assets/23129284/20043274/3e1867b2-a458-11e6-9148-54b8eabf77a7.png)

Tileset 1 (TS1) - 1 Tile - Stone
Tileset 2 (TS2) - 1 Tile - Dirt
Tileset 3 (TS3) - 1 Tile - Grass

If rendering was working properly all columns above would look the same but with different textures on each level.

**Comment by craftworkgames** [comment]
For reference, here's how it looks in the Tiled map editor.

![image](https://cloud.githubusercontent.com/assets/3201643/20055544/5a57c1c2-a52d-11e6-911e-cecb275b7394.png)

**Comment by HyperionMT** [comment]
Yea, I'm pretty sure Tiled is drawing it wrong too.  Even if what Tiled is displaying is correct we've still got a bug.  Whoever picks this up should do some research and possibly reach out to the Tiled folks to confirm the behavior before starting work.

**Comment by craftworkgames** [comment]
> Yea, I'm pretty sure Tiled is drawing it wrong too. 

Really? That could get quite confusing. How exactly did you create the map if it wasn't rendering correctly in the editor?

**Comment by HyperionMT** [comment]
You can still place tiles they just don't overlap correctly and you end up with your screenshot. If you take a look at the draw order on that map you'll see its left to right bottom to top so there's no way the bottom row of tiles should draw above the next. 

Another reason I think it's broken is because if you change to each of the other render orders nothing happens. It seems to me like it's always using right to left top to bottom.

**Comment by LithiumToast** [comment]
Looks like render order in Tiled is [only supported with orthogonal maps.](http://discourse.mapeditor.org/t/what-is-the-render-order-option-doing/110)

The problem with this map is the multiple tilesets. Having multiple tilesets forces the renderer to switch textures at runtime. Each texture switch forces the renderer to use separate draw calls for rendering. The renderer tries to minimize texture switching since texture switching has performance penalties. This is done by grouping all the tiles for each tileset together for each layer. This can be seen in the following screenshot.

<img width="468" alt="screen shot 2016-12-29 at 12 47 24 pm" src="https://cloud.githubusercontent.com/assets/519592/21554514/fe7fde3c-cdc4-11e6-97c1-396c801074e4.png">

The grass, dirt and stone tiles are grouped and rendered together in one draw call for each. The stone tiles are drawn first, then the dirt tiles, and finally the grass tiles. Using the painter's algorithm, you can see that the groups visually stack on top of each other.

The solution here is to use one single texture for all the tiles. This solution is on the developer.

**Comment by LithiumToast** [comment]
Here's a screenshot of the rendered map after combining all the tilesets into one larger tileset.

RightDown:
<img width="510" alt="screen shot 2016-12-29 at 2 19 20 pm" src="https://cloud.githubusercontent.com/assets/519592/21555981/d8d07b12-cdd1-11e6-857f-ba09e887091a.png">

RightUp:
<img width="505" alt="screen shot 2016-12-29 at 2 05 33 pm" src="https://cloud.githubusercontent.com/assets/519592/21555803/51c84c18-cdd0-11e6-95de-e9913d1e33a0.png">

LeftDown:
<img width="510" alt="screen shot 2016-12-29 at 2 20 43 pm" src="https://cloud.githubusercontent.com/assets/519592/21556004/0ddc7a4a-cdd2-11e6-920d-1458bcff8d59.png">

LeftUp:
<img width="508" alt="screen shot 2016-12-29 at 2 21 49 pm" src="https://cloud.githubusercontent.com/assets/519592/21556016/30d629a6-cdd2-11e6-8ae7-560164613be2.png">

**Comment by HyperionMT** [comment]
I agree with your explanation as to why this is happening but I disagree with the solution.  What you propose is more of a workaround to a bug in MGE (ignoring the way I expect the tiles to show, we still aren't drawing them in the same way as Tiled does so I consider that a bug).  A solution wouldn't require a developer to avoid functionality.  A user shouldn't have to modify their tilesets which work fine in Tiled just because we're forcing them into an optimization they may not need/care about.  I think a better solution would be to add a MapRendererConfig.OptimizeTilesetDrawOrder property that would enable/disable this optimization so the user can decide what they want.

That being said I have no need of this functionality, it was just something I noticed when testing my own changes.  If we want the official answer to be "combine your tilesets" then that's fine.

**Comment by LithiumToast** [comment]
@HyperionMT Well, the alternative solution is not a good one. It will kill the performance and thus the frames per second just by switching textures (which implies many draw calls also contributing to the performance killer). We are talking about a separate draw call every time a different tileset is used in the render order of tiles. Worse case scenario is that every tile is a separate tileset and no two same tiles are placed next to each other in render order causing every drawn tile to be a separate draw call. Further more, each draw call needs a vertex buffer and index buffer. It does not make sense to create a vertex and index buffer for just one tile. Some graphic drivers even have a limit on how vertex buffer objects and index buffer objects can be created regardless of their size.

For example, in this test map (doesn't matter what render order), 15 draw calls would be needed to draw these 18 tiles in the alternative solution. That is obviously not going to scale well with large maps in the worse case scenarios.

**Comment by HyperionMT** [comment]
@LithiumToast, I understand where you're coming from, obviously its not something you'd want to disable by default.  All I'm saying is that we shouldn't make decisions for our users since we can't predict the scenarios they might be used in.  If it makes sense for them to disable it, lets let them disable it.  I'm open to other solutions as well, that was just an example of what we could do.

Anyway, like I said I don't care all that much if this gets fixed so I'll leave it up to @craftworkgames to decide if this issue should be closed or left open for someone to eventually fix.

**Comment by LithiumToast** [comment]
@HyperionMT Well the best solution is to use the content pipeline to merge tilesets automatically into one large texture atlas tileset. The developer is then free to use as many tilesets as he or she wishes and the best performance possible is still maintained with the Tiled map renderer. Just to be clear here, I changed the render code in my develop branch to allow for drawing individual layers. Devil's in the details, but it is possible for each _tile layer_ to use a different texture without degrading performance horribly. This means a solution that uses the content pipeline to merge tiles from multiple tilesets into one larger tileset only has to consider tiles used for that _tile layer_.

**Comment by craftworkgames** [comment]
> The solution here is to use one single texture for all the tiles. This solution is on the developer, not us.

I actually agree with @LithiumToast on this one. We shouldn't be complicating the code in the library to cater for something that has an easy workaround.

> All I'm saying is that we shouldn't make decisions for our users since we can't predict the scenarios they might be used in. If it makes sense for them to disable it, lets let them disable it. I'm open to other solutions as well, that was just an example of what we could do.

As far as I'm concerned this is an edge case. Trying to support multiple tilesets across multiple layers is quite a difficult thing to do and I haven't yet heard a compelling reason to do so. Let's spend our time and energy elsewhere. That said, if there *is* actually a good real world scenario to do it, I'm curious to know what it is.

> Well the best solution is to use the content pipeline to merge tilesets automatically into one large texture atlas tileset. The developer is then free to use as many tilesets as he or she wishes and the best performance possible is still maintained with the Tiled map renderer.

Yes, this certainly seems like a better solution. If there's a demand for it, I'd rather implement this over a more complicated renderer.

When it comes to these kinds of problems there's two ways to solve them. The first is with code (as programmers, we tend to lean this way). The second is *documentation*; not quite as glamorous, but sometimes it's the right solution.

At the end of the day, the end goal is to make games. If the solution is to pack all the tiles into a single texture, so be it.

> Anyway, like I said I don't care all that much if this gets fixed so I'll leave it up to @craftworkgames to decide if this issue should be closed or left open for someone to eventually fix.

I'll close this issue. If a more compelling reason comes along, we'll revisit it then.
