### ISSUE TITLE
[Installment] NuGet Package seems not to work?

### ISSUE THREAD

**Issue by edenprojectde** [craftworkgames/MonoGame.Extended#303]
I installed the NuGet for MonoGame.Extended and added a reference to the Pipeline DLL in the mgcb file;
All i'm getting is this:
http://prnt.sc/d6jly1

My Project is in a shared environment
http://prntscr.com/d6jm3q

I use it with the Latest Monogame, Xamarin, VS Version 2k15 update 2

**Comment by craftworkgames** [comment]
Screenshot seems to be removed. Probably best to just paste them directly into GitHub.

Can you provide some more details please.

**Comment by edenprojectde** [comment]
In short .. Visual Studio says there is already a link to the Content.mgcb and that 
"Importer 'BitmapFontImporter' had unexpected failure!"
![screenshot_19](https://cloud.githubusercontent.com/assets/6115966/20242920/62fe97f8-a940-11e6-98a5-8beabaabbe7d.png)

**Comment by edenprojectde** [comment]
I dont know what can really help to provide you with information about this if i could i would send it to you but i dont really see where to begin :')

**Comment by edenprojectde** [comment]
I could uninstall the Nuget Package and let my Solution Build without errors; I also have referenced the Pipeline DLL in the Content.mgcb
It is as soon as i add the Pipeline DLL that it wont work anymore when i try to build it.

**Comment by edenprojectde** [comment]
[fonts.zip](https://github.com/craftworkgames/MonoGame.Extended/files/587540/fonts.zip)

**Comment by edenprojectde** [comment]
I see my missdoings now .. i didnt see we need to export the font as an XML..

**Comment by craftworkgames** [comment]
Awesome. I'm glad you got it sorted.

The official NuGet package is quite old now. You might be interested in [installing the pre-release package](https://github.com/craftworkgames/MonoGame.Extended/wiki/How-to-use-the-pre-release-NuGet-packages).

Also, if you're having trouble building content, sometimes it's worth trying to build it using the Content Pipeline tool directly. It usually provides more info.

![image](https://cloud.githubusercontent.com/assets/3201643/20243013/bf0a7a44-a990-11e6-891d-cfd2b50f8f2e.png)

**Comment by edenprojectde** [comment]
The Content Pipeline doesnt show any context(i mean literally since 3.5 of mono the log is empty) when i build it so i cant really see whats going on :')
Otherwise i would love to use it like its meant to be.
