### ISSUE TITLE
[BitmapFont] MeasureString produces the wrong height

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#309]
I noticed today while working on GUI stuff that the `MeasureString` method of `BitmapFont` class is not working as I expected.

![image](https://cloud.githubusercontent.com/assets/3201643/20419504/b0140d5a-ada2-11e6-96ea-0e871c880d38.png)

I'll probably fix this tonight, but I wanted to raise the issue first.

I'm pretty sure this worked in the past. We should probably have better regression tests for this kind of thing. I'll write a unit test tonight.

It would also be interesting to think about having some kind of screenshot tests for graphics code.

**Comment by lozzajp** [comment]
Was this from where I added multi line height measuring?

If you use your same scenario but write a second line, does the height then work as expected? (It might be a bug with just the first line).

**Comment by craftworkgames** [comment]
I've been looking into this a little more. The issue runs a bit deeper than I first thought.

![image](https://cloud.githubusercontent.com/assets/3201643/20596743/a46de4ba-b28b-11e6-81c6-c484e6359944.png)

As you can see in the above screenshot strings with newline characters (`\r\n`) are pretty close.

Wrapped text on the other hand is completely wrong. 

Also, a little more subtly I think it feels wrong to be measuring the height using the "line height" rather than the "character height". For example, I think the green box is a more appropriate measurement of the text vs the red box we are currently doing.

![image](https://cloud.githubusercontent.com/assets/3201643/20596865/4fb89982-b28c-11e6-927d-d1e651e64cd3.png)

This change is a little more complicated, because it's going to break existing behavior and throw word wrapping out of wack. I've been trying to create a demo that covers the different scenarios.

**Comment by lozzajp** [comment]
I assume it is [here](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/BitmapFonts/BitmapFont.cs#L75) where we measure `BitmapFontRegion.Height` instead of the currently largest character in the string.

I am not sure how word wrapping is happening there, you mean there are no `\r\n` characters?

**Comment by craftworkgames** [comment]
The problem is that we're using different code to measure the string vs rendering it. I've started refactoring it to resolve this problem but it's going to take a bit more work to do it properly.

As I said, we need good tests. As it stands, the current demo only tests about half the code.

Oh yeah, and while I think of it, it would be nice to know how our `MeasureString` method compares to the [`SpriteFont.MeasureString`](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.spritefont.measurestring.aspx) method.

**Comment by lozzajp** [comment]
I couldn't figure out writing a test without making a game run etc. 😕

**Comment by craftworkgames** [comment]
> I couldn't figure out writing a test without making a game run etc. 

Having *any* kind of test is better than nothing, even if it's just a red box drawn around the string like I've done in these screenshots.

Unit tests have the advantage that they run all the time on the build server to make sure we haven't broken something that worked previously. This is particularly useful for these kinds of "invisible" things like `MeasureString`.

Unfortunately, trying to retrofit unit tests into code that's already written is often harder than writing the test at the time the code was originally authored. In this case, also because there's a whole bunch of different scenarios to think about.

The next step is to clearly define what we expect:
 - when rendering a single word
 - when rendering a sentence
 - when rendering a word wrapped sentence
 - when rendering a sentence with new line characters
 - when rendering a rotated string
 - when rendering a scaled string
 - did I miss some?

Each of these should become a unit test of `MeasureString`.
