### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#32]
The icon on the [NuGet package](https://www.nuget.org/packages/MonoGame.Extended/) is currently the boring default.

This is a call out to get some logo designs for the project. The [MonoGame logo](https://github.com/Mono-Game/MonoGame.Logo) might be a good starting point. Although, we should ask permission first before using their logo in ours.

Alternately, we could create something unique and interesting. Ideas are welcome.

**Comment by ClassicThunder** [comment]
Here's my very amateur attempt ![MGE](http://i.imgur.com/ayaKsZI.png)

**Comment by craftworkgames** [comment]
@ClassicThunder I like the idea, but it will need to fit neatly into a square. Great first draft though.

**Comment by craftworkgames** [comment]
I came up with something. It's intended to look a little like the MonoGame logo for familiarity but different enough that's it's obviously a different project.

![image](https://cloud.githubusercontent.com/assets/3201643/9427873/19fa11ce-49d6-11e5-8379-5708ca38aedf.png)

@tomspilman are you okay with this? I don't want to step on any toes here. If you'd rather the logo look completely different I'm okay with that too.

**Comment by craftworkgames** [comment]
And the NuGet version.

![image](https://cloud.githubusercontent.com/assets/3201643/9427914/47df8284-49d8-11e5-8601-d33941ff578b.png)

**Comment by tomspilman** [comment]
Sure that is fine with me

@KonajuGames ???

**Comment by KonajuGames** [comment]
That is fine with me as well.

**Comment by craftworkgames** [comment]
Thanks. I'll be publishing the 0.2 release with the new logo shortly :smile:
