### ISSUE TITLE
[Tiled] OutOfMemoryException when loading tileset

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#320]
I'm using the newest build just to use the particle manager, but the tiled renderer is throwing an exception that I can't figure out how to solve. I receive the exception on the constructor of `TiledTileset` (notice the `_regions` count):

![image](https://cloud.githubusercontent.com/assets/11896398/20862729/10a157c4-b99a-11e6-9515-3c60258e94da.png)

That's the .tmx file: https://github.com/rafaelalmeidatk/Winter-Defense/blob/master/Winter%20Defense/Content/maps/map1.tmx
And the tileset: https://github.com/rafaelalmeidatk/Winter-Defense/blob/master/Winter%20Defense/Content/imgs/tilesets/Tileset.png

Any ideas to solve it?

EDIT: for some reason the `TileHeight` is set to 0.

**Comment by rafaelalmeidatk** [comment]
I rebuilt the project again and I made the map from scratch. Now everything works fine, sorry for the issue xD

**Comment by craftworkgames** [comment]
> for some reason the TileHeight is set to 0.

That's super weird. My guess is that the Pipeline didn't process the map properly. Perhaps there was a version mismatch or something?

In any case, I don't think we can guard against something like that.

Well, actually, now that I think about it, maybe we could write the version number into the XNB file and check it on load (if that is indeed the cause of the issue). Might be a good idea anyway.

Thanks for raising it and letting us know you got it working.

**Comment by rafaelalmeidatk** [comment]
> Perhaps there was a version mismatch or something?

It was exactly that, the pipeline version was older than the main dll.

**Comment by craftworkgames** [comment]
> It was exactly that, the pipeline version was older than the main dll.

Good to know. Obviously we can't "fix" that but we can make it more obvious that it's a problem.
