### ISSUE TITLE
[TextureAtlas] Null reference exception when importing a texture atlas

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#321]
*Originally posted [on the community forums](http://community.monogame.net/t/something-wrong-with-mgcb-pipeline-tool-and-monogame-extend/8496)*

I downloaded and installed MGCB 3.5.1.1679 tool and Monogame.Extend

But When I import atlas json file, I have following error.

    C:/Users/liul/Documents/Visual Studio 2015/Projects/Game1/Game1/Content/Culling.json
    C:/Users/liul/Documents/Visual Studio 2015/Projects/Game1/Game1/Content/Culling.json : error : Object reference not set to an instance of an object.
    C:/Users/liul/Documents/Visual Studio 2015/Projects/Game1/Game1/Content/Culling.png

Already have it referenced in pipeline tool.

**Comment by craftworkgames** [comment]
Could you post the contents of one of the JSON files please.

Also, try naming your texture with a different name to the atlas. For example, use Culling.png and Culling-atlas.json.

Unfortunately, an "Object reference not set to an instance of an object." error doesn't really tell us much. Once we figure out the issue we should probably implement some better error handing so the message is clearer.

**Comment by chanliu1983** [comment]
{
"imagePath": "texture.png",
"SubTexture": [{
"frameHeight": 128,
"y": 1,
"frameX": -30,
"width": 60,
"frameY": -14,
"height": 114,
"name": "tree1",
"frameWidth": 128,
"x": 1
}],
"name": "NewProject"
}

Now I simplify it
Only two files.
texture.png which is the texture fine.
texture.json content as above, it shall be the atlas.

Thanks a lot.
Lei

**Comment by craftworkgames** [comment]
Where did you get this JSON from?

The problem appears to be that the JSON file is in the wrong format. You need to use the generic JSON exporter in [TexturePacker](https://www.codeandweb.com/texturepacker)

**Comment by chanliu1983** [comment]
@craftworkgames Oh Thanks, I use dragonBone, it can export animation and Texture Atlas, so only this TexturePacker is supported?

**Comment by craftworkgames** [comment]
Correct.

We don't currently have support for Dragon Bones. We have talked about it in the past but there hasn't been enough interest.

Of course, this is an open source project so if someone wants to implement support that'd be cool.
