### ISSUE TITLE
How can I use MonoGame.Extended with Windows 10?

### ISSUE THREAD

**Issue by Fox9MonoGame** [craftworkgames/MonoGame.Extended#323]
I want to use MonoGame.Extended in a MonoGame Windows 10 Universal project. What is the easiest way to do that?
I have installed the MonoGame.Extended template and it works. But it was not possible to run your template on my Windows Phone device, because I couldn't choose my device in Visual Studio.
Is it not possible to use the template with a Windows Phone device?

**Comment by craftworkgames** [comment]
> I have installed the MonoGame.Extended template and it works.

What template are you talking about?  If you're talking about [this one](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/ProjectTemplates) I think you might be confused about it's purpose. That template is only used for creating demos.

To use MonoGame.Extended in you're own project you simply reference it like any other library (either as a [NuGet package](https://github.com/craftworkgames/MonoGame.Extended/wiki/How-to-use-the-pre-release-NuGet-packages) or by [referencing the source project or dll directly](https://github.com/craftworkgames/MonoGame.Extended/wiki/Building-MonoGame.Extended-from-source).

I don't know of a reason why it wouldn't work on a Windows Phone device. Although, I don't actually own a Windows Phone so I haven't tested it myself.

I presume you can [find a tutorial](http://stackoverflow.com/questions/36670542/how-to-setup-project-for-monogame-windows-8-1) on how to setup a Windows Phone project with MonoGame on the internet somewhere.

After that, just reference the MonoGame.Extended DLL as described above. It should work.
