### ISSUE TITLE
[Tiled] Broken visible layers in tilemap renderering

### ISSUE THREAD

**Issue by Taikatou** [craftworkgames/MonoGame.Extended#325]
TileMapLayer visible property is not utilised.

I have updated FullMapRenderer.BuildRenderDetails() to accommodate this.

`else if (objectLayer != null && objectLayer.IsVisible)
{
    //add to renderering
}`

I am happy to make this fix if this is the correct way to fix this problem. :D

**Comment by craftworkgames** [comment]
@LithiumToast said he was going to do some work on the Tiled renderer today. It should be easy enough to incorporate this change then.

**Comment by LithiumToast** [comment]
@Taikatou The renderer does not draw objects, but it's easy enough just to check if tile or image layers are not visible and just don't render anything if so.

Here's a snippet of the new code.
```
public void DrawLayer(TiledLayer layer, float depth = 0.0f)
        {
            if (!layer.IsVisible)
                return;
```

**Comment by LithiumToast** [comment]
@craftworkgames This can be closed.
