### ISSUE TITLE
[Particles] msvcrt.dll and windows UWP

### ISSUE THREAD

**Issue by Taikatou** [craftworkgames/MonoGame.Extended#327]
Been trying to publish my app to Windows Store. However, I cannot get past certification process.

This is the error  

`API memcpy in msvcrt.dll is not supported for this application type. MonoGame.Extended.dll calls this API.`

I removed the reference to no avail however I discovered this DLL is also imported in `ParticleBuffer.cs`
`[DllImport("msvcrt.dll" ...`

Should we remove this because it isn't the most portable solution?

**Comment by LithiumToast** [comment]
P/Invokes should not exist in PCLs. It should be removed.

**Comment by craftworkgames** [comment]
The particle code was ported from the [Mercury Particle Engine](https://github.com/Matthew-Davey/mercury-particle-engine).

Any `DllImport`'s left over is purely an accident and should be removed.

**Comment by Taikatou** [comment]
@craftworkgames Will love to. :)

**Comment by craftworkgames** [comment]
Great 👍

**Comment by LithiumToast** [comment]
@Taikatou Where are you at with this?

**Comment by craftworkgames** [comment]
I removed the code that was referencing the `DllImport` and as far as I can tell nothing is broken.
