### ISSUE TITLE
[Particles] Particle System is not data driven

### ISSUE THREAD

**Issue by jeffgamedev** [craftworkgames/MonoGame.Extended#333]
The particle system as exhibited in the demo is great for creating dynamic graphics quickly, but in it's current state, all particle effects are hard coded. It would be nice to have an editor that the user can preview and generate JSON to load in the game later, instead of having to change C# code every time you want to tweak a particle.

libGDX has such a particle editor: https://github.com/libgdx/libgdx/wiki/2D-Particle-Editor

**Comment by craftworkgames** [comment]
I plan to work in this after I've finished (nothing is ever finished ;) ) the GUI system.

I was thinking, maybe we can create a particle editor with the new GUI system perhaps.

**Comment by jeffol** [comment]
Sounds like a good plan! The particle editor can be a simple project:
I'd guess the major features would be:

- Adjust / change particle settings

Adjust particle settings

**Comment by jeffgamedev** [comment]
Particle System has been data driven for a while, and external editor is pending release.
