### ISSUE TITLE
[ECS] Another reference for ECS

### ISSUE THREAD

**Issue by KinoshitaShimizu** [craftworkgames/MonoGame.Extended#341]
Time ago I also implemented one, though it had a very different behavior, still I'll submit the code if it can help for reference.

There are many things that could be implemented nowadays, but my viewpoint is quite far from this, and I'd like to be able to understand so I can try to contribute to Monogame.Extended project.

```
#if EDITOR
extern alias Xna;
using ContentSerializer = Xna::Microsoft.Xna.Framework.Content.ContentSerializerAttribute;
using ContentSerializerIgnore = Xna::Microsoft.Xna.Framework.Content.ContentSerializerIgnoreAttribute;
#else
using Microsoft.Xna.Framework.Content;
#endif

using Microsoft.Xna.Framework;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;
using MonoGame.Extended;
using MonoGame.Extended.Entities.Components;
using MonoGame.Extended.Entities;

namespace Eien.Engine.Architecture
{
    public class GameObject : IGameComponent, ICloneable
    {
        [ContentSerializerIgnore]
        [XmlIgnore]
        public bool IsInitialized = false; //Aids the Initialize() function

        //RUNTIME Status bool to know if it has been properly linked
        [ContentSerializerIgnore]
        [XmlIgnore]
        public bool IsLinked = false; //This means, does it have a reference to where it is currently? Game, Parent, and in this case World and Map

        //EDITOR data
        [ContentSerializer]
        [XmlAttribute]
        public string Name { get; set; } = ""; //Used to identify the object itself, might use a GUID instead

        /*Runtime linking properties*/
        [ContentSerializerIgnore]
        [XmlIgnore]
        public TileGame Game;
        [ContentSerializerIgnore]
        [XmlIgnore]
        public World World;
        [ContentSerializerIgnore]
        [XmlIgnore]
        public TileMap Map;
        [ContentSerializerIgnore]
        [XmlIgnore]
        public GameObject Parent;

        /*Common properties*/
        [ContentSerializer]
        [XmlAttribute]
        public bool IsActive { get; set; } = false; //if it's not active, then it and his childrens will not receive Draw() and Update()


        /*Extended properties*/
        [ContentSerializer]
        [XmlElement]
        public List<GameObject> AttachedObjects { get; set; } = new List<GameObject>(); //we can add collision boxes and suchs here   

        public void DoLink(TileGame game, World world, TileMap map, GameObject parent = null)
        {
            Game = game;
            World = world;
            Map = map;
            Parent = parent;
            IsLinked = true;

            foreach (var attachedObject in AttachedObjects)
                attachedObject.DoLink(this);

            if (!IsInitialized)
                Initialize(); //we initialize it afterwards
        }

        public void DoLink(GameObject fullyLinkedParent)
        {
            DoLink(fullyLinkedParent.Game, fullyLinkedParent.World, fullyLinkedParent.Map, fullyLinkedParent);
        }

        public virtual void Update(GameTime gameTime)
        {
#if DEBUG
            if (!IsLinked)
            {
                System.Console.WriteLine(String.Format("{0}:1 -> WARNING: A class was attempted to use without being properly linked.", this.GetType()));
                return; //We can't do a thing if this is not linked... or rather, too dangerous
            }
#endif
            if (IsActive)
            {
                //if requires resource allocation
                var yieldable = this as IYieldable;
                if (yieldable != null && yieldable.HasAllocatedResources)
                {
                    yieldable.AllocateResources(); //let's allocate resources
                }

                //let's try to invoke all attached objects events
                foreach (var attachedObject in AttachedObjects)
                {
                    if (!attachedObject.IsLinked) //if not linked, let's link it
                        attachedObject.DoLink(this);

                    attachedObject.Update(gameTime);
                }
            }
        }

        public virtual void Draw(GameTime gameTime)
        {
#if DEBUG
            if (!IsLinked)
            {
                System.Console.WriteLine(String.Format("{0}:2 -> WARNING: A class has been used without being properly linked.", this.GetType()));
                return; //We can't do a thing if this is not linked... or rather, too dangerous
            }
#endif

            if (IsActive)
            {
                //if requires resource allocation
                var yieldable = this as IYieldable;
                if (yieldable != null && !yieldable.HasAllocatedResources)
                    yieldable.AllocateResources(); //let's allocate resources

                //let's try to invoke all attached objects events
                foreach (var attachedObject in AttachedObjects)
                {
                    //Maybe object added on last update?
                    if (!attachedObject.IsLinked) //if not linked, let's link it
                        attachedObject.DoLink(this);

                    if (attachedObject.IsLinked)
                        attachedObject.Draw(gameTime);
                }
            }
        }

        public override string ToString()
        {
            if (Name.Length != 0)
                return Name + " [[" + base.GetType().Name + "]]";
            else
                return base.GetType().Name;//base.ToString();
        }

        //It makes it exit it's own parent
        public void Detach()
        {
            if (Parent != null)
                if (Parent.AttachedObjects.Contains(this))
                    Parent.AttachedObjects.Remove(this);
            Parent = null;
            IsLinked = false;
        }

        public object Clone()
        {
            //Reflection clone of all public properties
            var cloned = (GameObject)Activator.CreateInstance(this.GetType());
            var propInfo = this.GetType().GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
            foreach (var item in propInfo)
                if (item.CanWrite)
                {
                    //If it's a GameObject, we can just clone that
                    if (typeof(GameObject).IsAssignableFrom(item.GetValue(this).GetType()))
                        cloned.GetType().GetProperty(item.Name).SetValue(cloned, ((GameObject)item.GetValue(this)).Clone());
                    //If it's a list of ICloneables, we can clone that too
                    else if (item.GetValue(this).GetType().GetInterfaces().Any(t => t.IsGenericType
                        && t.GetGenericTypeDefinition() == typeof(IList<>)) && item.GetValue(this).GetType().GetGenericArguments().Length > 0 && item.GetValue(this).GetType().GetGenericArguments()[0].GetInterfaces().Any(t => t == typeof(ICloneable)))
                    {
                        var sourceList = (IEnumerable<ICloneable>)item.GetValue(this);
                        var clonedList = (IList)Activator.CreateInstance(item.GetValue(this).GetType());
                        foreach (var go in sourceList)
                            clonedList.Add((ICloneable)go.Clone());
                        cloned.GetType().GetProperty(item.Name).SetValue(cloned, clonedList);
                    }
                    //If it's a non-cloneable, then we set the value
                    else
                        cloned.GetType().GetProperty(item.Name).SetValue(cloned, item.GetValue(this));
                }
            return cloned; //return cloned
        }

        public virtual void Initialize()
        {
            IsInitialized = true;
        }
    }
}
```

This class was built to be able to directly serialize and deserialize (thus, there is the issue with every item being a bit too unique), and so, the parents link with their children on runtime. Only the main tree had to be linked manually through code, and the rest links through the tree automatically.

So, the list is exposed. I think this is the first thing my viewpoint doesn't fit, but I guess I can do so. Recently had been adjusting it to fit the way Monogame.Extended works like, but doesn't fit, so I'd rather toss it than keep a parallel class to Entity.

There also was the IYieldable class which basically defines whether if it has to allocate resources or not, so they are not allocated on load, but on the runtime instead, useful for loading screens (gathering all IYieldable in a list which have HasAllocatedResources = false, and then running through them AllocateResources()).

There are many other things that could be fun to try implementing (although I believe are in progress) in the Monogame.Extended ECS, but I have no idea if could exceed if I adjusted it. In my case, originally there were 2 types (Container and children, originally named GameObject and Attachable).

I'd like to adjust my paradigm to yours, because I don't think I should go and wrapping all of your classes to use them. If I can, I'll just use yours instead, but if I can't, I guess I'll have to go and wrap.

**Comment by LithiumToast** [comment]
How do you use `GameObject` in your game? Do you derive `Player`, `NPC`, etc from `GameObject` for example?

**Comment by LithiumToast** [comment]
Also, I think `Microsoft.Xna.Framework.IGameComponent` is not really suitable for objects with lots of instances like game objects / entities. See http://gamedev.stackexchange.com/questions/9204/what-are-the-cons-of-using-drawablegamecomponent-for-every-instance-of-a-game-ob
It's more suitable for manager or system objects which there are only a couple instances. Examples of where `IGameComponent` is suitable would be like for a UI manager, particles manager, collision manager etc. In this case, an ECS manager would be a `IGameComponent` and own instances of `GameObject`/`Entity`.

**Comment by KinoshitaShimizu** [comment]
@LithiumToast Yes. World, Map, Player, Character, etc, are derived from it.

I didn't intend originally to implement "Microsoft.Xna.Framework.IGameComponent" at all, was playing around with it a while ago since read the name somewhere. Didn't find any use to it either. I apologize for my laziness and not rolling back.

Also tried implementing IDrawable and IUpdateable, but they add events that I don't find use for.

Had been thinking in also detecting wether if it implemented IGameComponent interface instead of enforcing it on it.

There were also functions like Detach, and so, but it seemed too alike to the current ECS so I gave up on it, and instead, I am looking forward to using the ECS of Monogame.Extended, and that I can avoid wrapping an Entity.

**Comment by KinoshitaShimizu** [comment]
@craftworkgames Well, my standpoint is the following, Entity hides the "Components" list, and sets functions to make use of it, like AttachComponent and DetachComponent, while the GameObject (whose code I just posted) does not. Instead, it checks wether if the children are linked or not for using them, if they are linked all good to go, if not, then it might have been added suddenly and can't be used like that.

However, I have access to the AttachedObjects List, and I can perform queries on it if I had the need (using Linq) or different operations. Furthermore, adding an object is just "adding it" instead of calling a function to add it.

**Comment by LithiumToast** [comment]
> World, Map, Player, Character, etc, are derived from it.

This can be problematic. See the [decoupling pattern Component](http://gameprogrammingpatterns.com/component.html) for why and good segue into what entity components are good for.

**Comment by KinoshitaShimizu** [comment]
@LithiumToast  Hmm, I think I understand now what you mean (not clearly enough, but I'll keep reading on this and thinking until I grasp the proper idea), I indeed had to do some weird stuff on my code sometimes, so this time I began looking on a better solution for ECS, but I found the implementation in Monogame.Extended quite interesting. Thank you very much for your time on replying me about this.

After reading that, indeed I understand a lot of what you mean, and many things make sense. Simpler objects which doesn't necessary involve drawing or updating for every instance of them, but acting as helpers (components) of one which can handle all what really needs, reduced and cleaner call stack, many benefits indeed.


I still wonder about the "private" components list, but I think if I really need it exposed, I'll override it to expose it... but it's "private"... Could you please explain me why this? I apologize if I am being persistent in something maybe obvious.

**Comment by LithiumToast** [comment]
@KinoshitaShimizu If you want to know more about ECS, you can also read the [`Data Locality optimization pattern`](http://gameprogrammingpatterns.com/data-locality.html) which talks about Entity Component System at the end near the paragraph "How are game entities defined?".

**Comment by KinoshitaShimizu** [comment]
@LithiumToast Wow... read it whole. It's one of the most interesting things I've read... and now I understand Java's terrible performance. It is indeed interesting, thank you very much for linking to it.

Hmm, I definitely understand a lot of things now, it doesn't seem that the current ECS implements much of it, but it might be alright like that (?). However, I understand now reasons to hide the Components list, and the issue with excessive polymorphism. Given any of the locality methods, none can be "naturally" used if it's a "List". I wonder if it's possible to make a struct GameList<T,N> (where T is the struct and N the array size, while holding an List<> in case of limit exceeded, but that'd be a bit much), but I'll leave that for myself I think.

Quite fascinating indeed it is, but there is something that should be improved on current ECS? (aside from implementing all versions, just kidding)

**Comment by LithiumToast** [comment]
>is [there] something that should be improved on current ECS?

Yes. In my opinion there are couple things that could make it better. One thing is I would like to experiment with components being structs for making use data locality when processing active components. But this is probably going to have to wait for C# 7 language features such as reference returns. Code would look something like this:

```
public ref TComponent GetComponent<TComponent>() where TComponent : IEntityComponent, struct
{
     ... // get the index, i, somehow
     return ref components[i]; // return the storage location, not the value
}
```

In the mean time entity components are probably going to remain being objects for flexibility. However, using a data structure (such as a pool) to achieve O(1) add and remove operations of entities and entities components would make things better if lots of entities and/or components are removed constantly.

**Comment by KinoshitaShimizu** [comment]
@LithiumToast I see. Certainly C# 7 brings some interesting new features. I guess as for now I'll leave the ECS be as it is. I might try making one that does use a pool later on, but as for now I'll just check around the code. Thank you very much for explaining all this.

**Comment by LithiumToast** [comment]
@KinoshitaShimizu We changed the ECS code to use [Artemis](https://thelinuxlich.github.io/artemis_CSharp/) as a base. You can check it out in action by looking at the `StarWarrior` game demo in the demos source code.

As far as being cache friendly, it is a lost cause for use with C#. See https://github.com/thelinuxlich/artemis_CSharp/issues/68 The only thing that would change with C#7 would to force all components to be structs instead of classes and use `ref` return feature to attach / get a component. While possible, it is more complex on the programmer. Performance testing would need to be done to justify the change.
