### ISSUE TITLE
NuGet package does not contain MonoGame.Extended.Screens namspace

### ISSUE THREAD

**Issue by italodirenzo93** [craftworkgames/MonoGame.Extended#342]
The latest NuGet package does not contain this code.

**Comment by craftworkgames** [comment]
When you say latest, what version are you talking about?

Have you seen the [pre-release NuGet feed](https://github.com/craftworkgames/MonoGame.Extended/wiki/How-to-use-the-pre-release-NuGet-packages)?

**Comment by craftworkgames** [comment]
Resolved in the 0.6.377 release. Although, we're probably going to move Screens into the Gui package.
