### ISSUE TITLE
Content Manager Issue for tiled maps

### ISSUE THREAD

**Issue by JLHunter** [craftworkgames/MonoGame.Extended#348]
I tried with a few versions, but I cannot get the Tiled maps to work properly. It seems that the project goes from all-inclusive, to separate NuGet packages. From TiledMapRenderer to FullMapRenderer... It's all very confusing. All with no up to date documentation? If it is, it's hard to tell which is new or old.

- The official version does not contain Tiled or Graphics so you cannot use tiled maps.
- The latest development build does not reference the importer properly. Says [missing] [null].
- Older development versions, like 6.271-beta, do not contain the second content pipeline DLL in the tiled package folder that is required. But it references the importer correctly. Just does not work.

Is this an issue, or user error? If user error, can I have some support on how to render a map? No documentation I can find on google, youtube, or through the limited tutorials here seem to work.

**Comment by LithiumToast** [comment]
"Official" version is out of date, latest code is on `develop` branch or pre-release on NuGet packages.
It's true the lastest develop has some problems with Tiled. #349 solves these problems.

**Comment by craftworkgames** [comment]
It's true. Things have been a bit chaotic for a while. 

Particularly with the Tiled renderer, we've been trying to figure out a decent way to do things that solves a bunch of problems with the older renderer and yet flexible enough to cater for most situations. I'm sure you can appreciate that it's impossible to please everyone, but there's a bunch of people working hard making it the best it can be.

Keeping documentation up-to-date is difficult while things are changing so rapidly. The demo's are the best source of truth at the moment. We try to keep those up-to-date as much as possible. 

There's still a few more things to do but I think we're getting closer to stability. Doing a new official version is definitely overdue. I've been thinking about doing a release a lot lately. I've got a rough idea what it's going to look like, but there's still some details to flesh out.

I really appreciate that you've raised this issue. It helps to clear up what still needs to be done. You might also find it helpful to join our [gitter chat](https://gitter.im/craftworkgames/MonoGame.Extended)

**Comment by JLHunter** [comment]
Thanks for the fast replies. A stable release, even if it doesn't have all the bells and whistles, would be nice. At least basic functionality to start off with.

I'll be awaiting such a time. This is a nice product :) 👍
