### ISSUE TITLE
Unable to build certain content

### ISSUE THREAD

**Issue by Gixen** [craftworkgames/MonoGame.Extended#354]
There could be a possible problem when building content using the nuget content pipeline,
I had trouble building json-files related to texturepacker and TexturePackerJsonImporter. I keep getting a System.IO.FileNotFound exception.
However, building the content pipeline from source and then referencing that dll through the pipelinetool, building the same json works without any problems.

**Comment by craftworkgames** [comment]
I'm not entirely certain what the problem is here.

I think we've already fixed it in 0.6.377
