### ISSUE TITLE
[NuGet] Content Pipeline DLL's need to live in the same folder together

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#355]
A few people have been [reporting issues](http://community.monogame.net/t/missing-importer-and-processor/8901/3) since the 0.6 release of the NuGet packages.

To my surprise after looking into the issue I discovered that the NuGet packages don't work as intended with the Content Pipeline.

The default behavior of NuGet packages when you install them is to put things in versioned folders matching the package name. 

![image](https://cloud.githubusercontent.com/assets/3201643/24099664/4866850a-0dbc-11e7-8b24-fb7cfc65f162.png)

But if you reference the Content Pipeline DLL's from these folders directly the Content Pipeline shows errors or in same cases crashes.

![image](https://cloud.githubusercontent.com/assets/3201643/24099772/bff1f938-0dbc-11e7-9608-37b112523f4e.png)

It turns out that for everything to work correctly *all* of the relevant DLL's need to be in the same folder when they're referenced from the `Content.mgcb` file.

To workaround the issue I had to copy the Content Pipeline DLL's and all of their dependencies (including Newtonsof.Json) into the same folder then update the references. Everything worked as expected after this.

![image](https://cloud.githubusercontent.com/assets/3201643/24099825/03f16b14-0dbd-11e7-94ee-04a7372d9c3b.png)

So.. now I'm looking for ideas on how we can solve it? 

 - Maybe we distribute all of the Content Pipleine DLLs in one NuGet package?
 - Or perhaps we run some sort of script when the NuGet packages are installed?
 - Or we could simply ship one Content Pipeline DLL like we did previously?

I'd really like to get this solved soon as it's effectively making the NuGet packages useless.

**Comment by jeffol** [comment]
I'm not currently experiencing any issues building content with the Content Manager and separated DLLs.

![refs](https://cloud.githubusercontent.com/assets/3392831/24116724/a612bd00-0d75-11e7-958c-64433dd92038.png)
![ss3](https://cloud.githubusercontent.com/assets/3392831/24116729/ae45c5b2-0d75-11e7-9aac-c601adad8893.png)
![ss4](https://cloud.githubusercontent.com/assets/3392831/24116734/b26bb8a4-0d75-11e7-8ad5-80390d6c8fe4.png)

**Comment by jeffol** [comment]
It should be noted that when I press "OK" on the DLL reference editor that the Content Pipeline application does crash. This is odd because I didn't have any issues setting it up when the launched Nuget package was first launched. But, regardless of the reference editor crashing, my content is building properly with the DLLs being separated.

**Comment by githubfito** [comment]
i had that issue. When I joined the libraries the problem was solved:

/reference:..\MonoGame.Extended.Content.Pipeline.dll
/reference:..\MonoGame.Extended.Content.Pipeline.Tiled.dll
/reference:..\MonoGame.Extended.dll
/reference:..\MonoGame.Extended.Graphics.dll
/reference:..\MonoGame.Extended.Tiled.dll
/reference:..\Newtonsoft.Json.dll

with MonoGame.Extended.0.6.359 and MonoGame.Framework.DesktopGL.3.6.0.1625

**Comment by LithiumToast** [comment]
Looks like the references for the content pipeline projects are messed up.

See [`MonoGame.Extended.Content.Pipeline.Graphics.csproj`](https://github.com/LithiumToast/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline.Graphics/MonoGame.Extended.Content.Pipeline.Graphics.csproj), [`MonoGame.Extended.Content.Pipeline.csproj`](https://github.com/LithiumToast/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj), and [`MonoGame.Extended.Content.Pipeline.Tiled.csproj`](https://github.com/LithiumToast/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline.Tiled/MonoGame.Extended.Content.Pipeline.Tiled.csproj)

**Comment by craftworkgames** [comment]
> They should all reference MonoGame libraries in the installed location on the machine which is C:\Program Files (x86)\MonoGame\v3.0\ on Windows.

Why's that?  Is it because it'll be the same version used by the Content Pipeline?  

Technically it should work either way, but technically if you're using the NuGet packages the Content Pipeline tool should also be a NuGet package.

> Also Newtonsoft.Json.dll would be a required reference for the content pipeline, so that should be added as a reference to anyones .mgcb.

That makes sense. I wonder why it was never an issue in the past? It seems that if the DLL just happens to be in the right place at the right time it'll work.

Having to manually add references to the Content Pipeline is pretty painful and it relies on documentation. We kinda got away with that when it was only one DLL you had to reference but it's a bit more complicated now there's many.

Ideally, I'd like to simplify the whole process. Either by automating it with a script or making it super simple by only having one Content Pipeline DLL to worry about. I know it's not *technically correct* to just have one DLL but to be honest I don't really see any real downsides.

**Comment by jeffgamedev** [comment]
> by only having one Content Pipeline DLL to worry about. I know it's not technically correct to just have one DLL but to be honest I don't really see any real downsides.

I think this makes the most sense. Technically, one could have a MGE project that never uses the Content Pipeline builder. Maybe the Content Pipeline DLL should be it's own package? 😆

**Comment by LithiumToast** [comment]
Well as long as the content pipeline remains decoupled from the runtime having one library for the content pipeline would work. That code is not shipped with the game itself under normal circumstances anyways.

**Comment by craftworkgames** [comment]
> Maybe the Content Pipeline DLL should be it's own package?

Yeah, I was thinking about that too. The only problem I can see is that it's on the user to make sure they keep the versions in sync. Although, that problem already exists so we wouldn't be making it any worse.

At the moment all of our packages are deployed at the same time with the same version. It's the simplest way to make sure they are compatible with each other. Although, it's possible that in the future we might want to version them separately. In any case, I don't think we should worry about that until it's a problem.

> Well as long as the content pipeline remains decoupled from the runtime having one library for the content pipeline would work. That code is not shipped with the game itself under normal circumstances anyways.

Agreed.

**Comment by craftworkgames** [comment]
So it sounds like we're getting closer to a solution then?

We'll roll all of the content pipeline code back into a single project and deploy it as a single NuGet package?  

There's a couple of other ways we could do it but I think that's the simplest and easiest to understand.

**Comment by LithiumToast** [comment]
As for `Newtonsoft.Json.dll`, it looks like it can find it if the project references a library that knows it's location via transitivity?

**Comment by craftworkgames** [comment]
> As for Newtonsoft.Json.dll, it looks like it can find it if the project references a library that knows it's location via transitivity?

I think we should just include it in the NuGet package so that it's in the same folder as everything else.

I'm happy to try get this solved tonight unless someone else is keen to give it a go?  All PR's are automatically built into NuGet packages on the build server so it's easy enough to test.

**Comment by craftworkgames** [comment]
Okay. I think I've got it all sorted aside from updating the wiki page.

Can I get you guys to test the pre-release NuGet packages to make sure it all works and the instructions make sense?

If we're all good I'll push them to nuget.org tomorrow.

**Comment by jeffgamedev** [comment]
I just updated my project to the latest pre-release package. Everything worked just fine, no crashes or odd behavior, built with the new pipeline package. 👍
