### ISSUE TITLE
[Tiled] Basic map with alpha issues

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#358]
I created a very simple map just to draw it on the screen, but the tiles that have transparency aren't drawn correctly:
![image](https://cloud.githubusercontent.com/assets/11896398/24325577/4b6cfe0c-117a-11e7-82ae-20b83d250717.png)

On Tiled:
![image](https://cloud.githubusercontent.com/assets/11896398/24325581/55d31480-117a-11e7-8ce3-e223a883b13d.png)

The code I've used is pretty simple, did I miss something?
```using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using MonoGame.Extended.Graphics;
using MonoGame.Extended.Tiled;
 
namespace MapTest
{
    public class Game1 : Game
    {
        GraphicsDeviceManager graphics;
        SpriteBatch spriteBatch;
 
        private TiledMap _map;
        private TiledMapRenderer _mapRenderer;
 
        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
        }
       
        protected override void Initialize()
        {
            base.Initialize();
 
            _mapRenderer = new TiledMapRenderer(GraphicsDevice);
        }
 
        protected override void LoadContent()
        {
            spriteBatch = new SpriteBatch(GraphicsDevice);
            _map = Content.Load<TiledMap>("map");
        }
       
        protected override void UnloadContent()
        {
            _map.Dispose();
        }
 
        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();
 
            _mapRenderer.Update(_map, gameTime);
 
            base.Update(gameTime);
        }
       
        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);
 
            _mapRenderer.Draw(_map);
 
            base.Draw(gameTime);
        }
    }
}
```

Download the `.tmx` file along with the tileset:
https://ufile.io/55da9 (I can't attach it here, idk why but it says "We don’t support that file type." even if the file is a .zip).

**Comment by craftworkgames** [comment]
I threw this map into the Tiled demo and it works fine.

Try adding these lines to your `Draw` method.

            GraphicsDevice.BlendState = BlendState.AlphaBlend;
            GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
            GraphicsDevice.RasterizerState = RasterizerState.CullNone;

@LithiumToast I'm wondering if we should make this the default behavior of the `TiledMapRenderer`?  It already takes the `GraphicsDevice` in it's constructor.

**Comment by rafaelalmeidatk** [comment]
This code solved the issue, thanks!
