### ISSUE TITLE
Document how to build a MonoGame PCL

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#36]
Currently MonoGame.Extended depends on a custom build of the MonoGame PCL found in the [Dependencies folder](https://github.com/craftworkgames/MonoGame.Extended/tree/master/Dependencies). This seems to work pretty well and allows us to keep up to date without depending on the NuGet package, which unfortunately is a few versions behind.

@WardBenjamin You implemented this in #25 and #26. It occurred to me today that if / when we need to do this again, I have no idea how to do it. Could I ask you to write up a guide on how to do this? Bullet points and links are fine.

On a related topic, I've considered setting up an automated process for things like this. I think there'd be some value in providing unofficial release builds of various different libraries (MonoGame, Farseer, etc) for people that don't want to get their hands dirty compiling the source code.

Thanks

**Comment by WardBenjamin** [comment]
I can definitely do this. Where do you want it after I write it? It's a fairly simple process, and only requires a few steps, so I can list them here (at least until we have a better place). 

Steps to generate a MonoGame PCL:
 - Clone the desired MonoGame version
 - Run protobuild and generate the Windows versions of MonoGame
 - Build MonoGame WindowsGL
 - Run the Windows or Bash script in Third Party/Piranha

I will make a repository with the Piranha components that are necessary sometime today, I can't do it at the moment since I have to head out, but it'll get done.

**Comment by craftworkgames** [comment]
> Where do you want it after I write it?

Maybe in a README.md with [the DLL in the Dependencies folder](https://github.com/craftworkgames/MonoGame.Extended/tree/master/Dependencies) perhaps. I tend to put documentation as close to the place people will be when they need it.

Please include links to whatever tools and repos are required.

> I can't do it at the moment since I have to head out, but it'll get done.

There's no rush. I'd just like to have it there for future reference.

**Comment by WardBenjamin** [comment]
You can remove the "Help Wanted" tag for this by the way. I've been fairly busy but I'll get around to it.

**Comment by craftworkgames** [comment]
> You can remove the "Help Wanted" tag for this by the way.

Done.

**Comment by WardBenjamin** [comment]
Don't worry, I'm still doing this. School starting has made me busy but I'm starting to come up with a little bit of time again.

**Comment by craftworkgames** [comment]
No worries. Thanks for letting me know. It's always hard to know when people abandon open source projects. Great to know you're still with us :smile:

**Comment by WardBenjamin** [comment]
@craftworkgames I finally got Monogame to move on a bit with this! Reference: https://github.com/mono/MonoGame/issues/4689
