### ISSUE TITLE
[Tiled] Bug loading TMX with multiple tile sets

### ISSUE THREAD

**Issue by brogine** [craftworkgames/MonoGame.Extended#361]
Hello. I'm having a problem when building some tmx with the pipeline tool.
I have a map with multiple tileset files. 

If i use tiles from the first tileset, building process works great. The problem appers when i use some tiles from the second one.
If my guesses are right, TiledMapProcessor (line 245) is not taking in account "firstgid" attribute of tileset.

```
<tileset firstgid="1" source="Tileset 1.tsx"/>
<tileset firstgid="1025" source="Tileset 2.tsx"/>
```

![sin titulo](https://cloud.githubusercontent.com/assets/4042589/24444751/e6f7d34a-143d-11e7-9eb8-c1e28619bab1.png)
[Maps.zip](https://github.com/craftworkgames/MonoGame.Extended/files/878263/Maps.zip)

Thank you!

**Comment by craftworkgames** [comment]
Thanks for reporting this and providing some test data to reproduce it :)

**Comment by LithiumToast** [comment]
Hi @brogine,
I'm responsible for the code that caused this bug. Unfortunately I'm a little busy this time of year. If you or someone else doesn't find the fix, I'll get to it in the near future.

**Comment by brogine** [comment]
Hello guys. Thank you for your quick response and attention. 
I've just made a test out of my changes and its passing, at least for the case i was having here.

I hope to solve this bug with such a simple solution.

**Comment by craftworkgames** [comment]
> I hope to solve this bug with such a simple solution.

Great. What is the simple solution?

**Comment by brogine** [comment]
It is in the pull request i created a few minutea ago

**Comment by craftworkgames** [comment]
Unfortunately, PR #362 didn't fix this issue.

I've added a [new map](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Demo.TiledMaps/Content/level08.tmx) to the Tiled demo that reproduces the issue (but it's not included in the Content.mgcb file right now).

Let's have another go at it.

**Comment by LithiumToast** [comment]
Debugging this. It appears importing `.tsx` tileset files is not properly handled. I fixed the problem, however the demo map `level08.tmx` is using staggered isometric representation which is not supported.

@craftworkgames You added that map yes? Can you change it to use the supported isometric representation?

**Comment by craftworkgames** [comment]
> You added that map yes? Can you change it to use the supported isometric representation?

My bad. I actually forgot we didn't support staggered isometric yet. Fortunately the change was simple and I think the map looks better that way anyway.
