### ISSUE TITLE
Hi.

### ISSUE THREAD

**Issue by githubfito** [craftworkgames/MonoGame.Extended#366]
hi. is working creategrid to import a tiled layer with solid background?

"public static CreateGrid(CollisionWorld world, TiledTileLayer tileLayer)"

thanks.

**Comment by craftworkgames** [comment]
No, not currently.

The collision system is being rewritten slowly but it might be some time before we have a working collision package.

**Comment by githubfito** [comment]
thanks to you and colaborators for this awesome help
