### ISSUE TITLE
Questions about devloping without the pipline

### ISSUE THREAD

**Issue by d0narnbl1tz** [craftworkgames/MonoGame.Extended#375]
Hey,
its an impressive extension to monogame, but i ask me a few Questions:
i want to avoid the pipline complete..
or at least as much as i can, because of making all my stuff easier to replace or moddable.
i also use rider as ide and not visual studio.
so now i have text implemented via various BMFont code samples.

But ist there any good way by using extended?
especially something that does not depend on using prerendered bitmaps?
And is there maybe an way of loading tile maps without the pipline when using extended.tiles?
or do i need to write my own workaround?

Or what would also a suitable idea, is there an solution that uses the pipline but only for converting the files on runtime? that would be an awesome solution, using the normal code but having just a bunch of files in the filesystem^^
or maybe there is a kind of wrapper that "casts" files from filesystem to an suitable input for all stuff that is depending on the pipline

Thank you for the time answering these few Questions in advance.

Greetings
Daniel

And last and least, sry for the shitty english and the workarounds xD

**Comment by craftworkgames** [comment]
Can I ask, why are you trying to avoid using the Pipeline completely?

Honestly, I do understand the desire to avoid using the Pipeline. We've had a few requests along this line of thinking before and it's certainly something we've considered supporting *but* right now it's not top priority.

It's certainly possible that we'll support it in the future *but* there's a bunch of reasons (both technical and non-technical) that make it difficult to support both ways of doing things and I'm yet to hear a good reason to not use the Pipeline other than "i don't wanna".

On the other hand there are [good reasons](http://www.infinitespace-studios.co.uk/general/monogame-content-pipeline-why/) why you should use the Pipeline and it would be a shame to disadvantage those that want to use it.

> Or what would also a suitable idea, is there an solution that uses the pipline but only for converting the files on runtime? that would be an awesome solution, using the normal code but having just a bunch of files in the filesystem^^

This is actually a pretty cool idea. I'll have a think about this for a future feature of Extended.

**Comment by d0narnbl1tz** [comment]
Yeah you can ;)
Its not just i don´t wanna, i used it a few times before, but i want this time a simple moddable game, where everybody can simply change an texture on the fly.
Adding scripts(as long as i achieve some days in future a kind of script support) as plugins with their own assets via a simple folder is also in my mind.
And last, thinking about using zlib(or an other compression lib) to compress my content on my own with support to load uncompressed too, alongside with an delta patch algorithm for the compressed content, so i could achieve decrased patch size.

What i also miss is the ability to encrypt my content with the pipline tool.(yeah i wrote in the first part of my text moddable, but some stuff should not be moddable sometimes)

>>Or what would also a suitable idea, is there an solution that uses the pipline but only for converting the >>files on runtime? that would be an awesome solution, using the normal code but having just a bunch of >>files in the filesystem^^
>
>This is actually a pretty cool idea. I'll have a think about this for a future feature of Extended.

👍
