### ISSUE TITLE
[Particles] Triggered/drawn at LayerDepth

### ISSUE THREAD

**Issue by toddgibson** [craftworkgames/MonoGame.Extended#381]
I think it would be wonderful to have an overload method to Trigger that allows for specifying layer depth for drawing...

public void Trigger(Vector2 position, float layerDepth);

I have need of this in my current project. I may make an attempt to implement it, but I've not delved into the guts of your wonderful project thus far. :)

**Comment by craftworkgames** [comment]
This seems like a good idea. I haven't looked into what's involved but I assume it would be relatively straightforward.

I've got quite a lot on my plate at the moment but perhaps someone else what's to submit a PR?

**Comment by toddgibson** [comment]
I actually got this implemented and working last night, it was pretty easily accomplished.  I'll submit a PR for it tonight.
