### ISSUE TITLE
Camera2D bounding frustum returns a half-pixel offset

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#39]
Currently the `Camera2D.GetBoundingFrustum` method returns a half pixel offset value.

This was implemented intentionally as follows, but it seems a little odd to me. 

        private Matrix GetProjectionMatrix(Matrix viewMatrix)
        {
            // Note: This projection matrix is the same one used inside of the MonoGame SpriteBatch by default.
            var projection = Matrix.CreateOrthographicOffCenter(0, _viewportAdapter.VirtualWidth, _viewportAdapter.VirtualHeight, 0, -1, 0);

            // Half pixel offset.
            // TODO: Check to see if we really should be applying a half pixel offset here?
            projection.M41 += -0.5f * projection.M11;
            projection.M42 += -0.5f * projection.M22;

            Matrix.Multiply(ref viewMatrix, ref projection, out projection);

            return projection;
        }

There are also some unit tests setup that confirm the outputs are indeed off by half a pixel:

        [Test]
        public void Camera2D_GetBoundingFrustum_Test()
        {
            var graphicsDevice = TestHelper.CreateGraphicsDevice();
            var camera = new Camera2D(graphicsDevice);
            var boundingFrustum = camera.GetBoundingFrustum();
            var corners = boundingFrustum.GetCorners();

            const float delta = 0.01f;
            TestHelper.AreEqual(new Vector3(0.5f, 0.5f, 1), corners[0], delta);
            TestHelper.AreEqual(new Vector3(800.5f, 0.5f, 1), corners[1], delta);
            TestHelper.AreEqual(new Vector3(800.5f, 480.5f, 1), corners[2], delta);
            TestHelper.AreEqual(new Vector3(0.5f, 480.5f, 1), corners[3], delta);
            TestHelper.AreEqual(new Vector3(0.5f, 0.5f, 0), corners[4], delta);
            TestHelper.AreEqual(new Vector3(800.5f, 0.5f, 0), corners[5], delta);
            TestHelper.AreEqual(new Vector3(800.5f, 480.5f, 0), corners[6], delta);
            TestHelper.AreEqual(new Vector3(0.5f, 480.5f, 0), corners[7], delta);
        }

And this:

        [Test]
        public void Camera2D_ContainsVector2_Test()
        {
            var graphicsDevice = TestHelper.CreateGraphicsDevice();
            var camera = new Camera2D(graphicsDevice);
            
            // the edge cases fall on the half pixel boundary
            Assert.AreEqual(ContainmentType.Disjoint, camera.Contains(new Vector2(0.45f, 0.45f)));
            Assert.AreEqual(ContainmentType.Contains, camera.Contains(new Vector2(800.45f, 480.45f)));
            Assert.AreEqual(ContainmentType.Contains, camera.Contains(new Vector2(0.55f, 0.55f)));
            Assert.AreEqual(ContainmentType.Disjoint, camera.Contains(new Vector2(800.55f, 480.55f)));
        }

Indeed, this was intentional, but I question if it's the right thing to do.

We should check the behavior of other frameworks like LibGDX and consider if this should be changed for the 0.3 release.

**Comment by craftworkgames** [comment]
I fixed this and now the following unit test passes:

        [Test]
        public void Camera2D_GetBoundingFrustum_Test()
        {
            var graphicsDevice = TestHelper.CreateGraphicsDevice();
            var camera = new Camera2D(graphicsDevice);
            var boundingFrustum = camera.GetBoundingFrustum();
            var corners = boundingFrustum.GetCorners();

            const float delta = 0.01f;
            TestHelper.AreEqual(new Vector3(0,   0,   1), corners[0], delta);
            TestHelper.AreEqual(new Vector3(800, 0,   1), corners[1], delta);
            TestHelper.AreEqual(new Vector3(800, 480, 1), corners[2], delta);
            TestHelper.AreEqual(new Vector3(0,   480, 1), corners[3], delta);
            TestHelper.AreEqual(new Vector3(0,   0,   0), corners[4], delta);
            TestHelper.AreEqual(new Vector3(800, 0,   0), corners[5], delta);
            TestHelper.AreEqual(new Vector3(800, 480, 0), corners[6], delta);
            TestHelper.AreEqual(new Vector3(0,   480, 0), corners[7], delta);
        }

I believe this makes sense. A the viewing rectangle of a new camera will be the same rectangle as the viewport without any scaling or other transforms.

**Comment by KonajuGames** [comment]
I believe it was DirectX9 (which XNA was originally based on) required a
half-pixel offset to get pixel-perfect rendering in orthographic mode.
DirectX10 and later removed this half-pixel offset.​

**Comment by craftworkgames** [comment]
@KonajuGames Right, but shouldn't MonoGame be abstracting this concept away regardless? Since MonoGame.Extended sits on top of MonoGame I figured any offsetting would already be accounted for in the layers underneath.

In any case I think it makes more sense without the half pixel offset. Hopefully it works on all platforms that way. I'd love to setup some screenshot tests to confirm this.
