### ISSUE TITLE
[NuclexGui] Change colour of GuiControlLabel

### ISSUE THREAD

**Issue by Nosrick** [craftworkgames/MonoGame.Extended#402]
Pretty much as the title suggests, it'd be nice to be able to change the colour of the labels. If it's possible, I'm not sure how to do it.

**Comment by jonmseaman** [comment]
@Nosrick I was thinking about implementing this, as I could use the functionality as well. 
Would it suffice to be able to specify a frame/style with the label control? You would then just have to edit the skin file to set up some new styles to be used, and possibly some new fonts if you wanted to use a different font.

I could also set up a color property possibly... I'll think about it some more.

**Comment by jonmseaman** [comment]
@Nosrick The pull request shown above should solve your issue if you are still interested. You can have labels with different styles, which allows for different colors to be used on different labels.
