### ISSUE TITLE
RectangleF wrong assignment

### ISSUE THREAD

**Issue by christopher-fabian** [craftworkgames/MonoGame.Extended#406]
Hey,

I've found a bug in RectangleF.
In CreateForm() line 167 - 170:
result.X = minimum.Y;
result.Y = minimum.Y;
result.Width = maximum.X - maximum.X;
result.Height = maximum.Y - minimum.Y;

It should be:
result.X = minimum.X;
 result.Y = minimum.Y;
result.Width = maximum.X - minimum.X;
result.Height = maximum.Y - minimum.Y;

**Comment by craftworkgames** [comment]
I guess not many people use this method.

I'll fix it now. Thanks mate.
