### ISSUE TITLE
Question regarding "Experimental"

### ISSUE THREAD

**Issue by joakimskoog** [craftworkgames/MonoGame.Extended#411]
Hi,

I'm just wondering about the "experimental" tag that is used on `MonoGame.Extended.Collisions` and `MonoGame.Extended.Entities (experimental)`. Will we see lots of breaking changes or maybe even obsoletion? Is it safer to roll my own solutions for these until they are more stable?

**Comment by craftworkgames** [comment]
The Collisions package is highly likely to be replaced entirely at some point.

Entities is a little more stable.
