### ISSUE TITLE
new TiledMapRenderer -> System.TypeInitializationException

### ISSUE THREAD

**Issue by feydk** [craftworkgames/MonoGame.Extended#412]
Using version 0.6.568.0

The following code

`TiledMapRenderer mapRenderer = new TiledMapRenderer(GraphicsDevice);`

yields this result:

**An unhandled exception of type 'System.TypeInitializationException' occurred in MonoGame.Extended.Graphics.dll**

**Additional information: The type initializer for 'MonoGame.Extended.Graphics.Effects.EffectResource' threw an exception.**

That's the full exception. Not much to go by.
Same result regardless if I put that code in Initialize() or LoadContent().

All dll's have the same version number. Installed from NuGet in VS.

**Comment by LithiumToast** [comment]
Could post the entire stack trace?

**Comment by wipe2238** [comment]
Same setup as author:
   w MonoGame.Extended.Graphics.Effects.EffectResource.get_DefaultEffect()
   w MonoGame.Extended.Graphics.Effects.DefaultEffect..ctor(GraphicsDevice graphicsDevice)
   w MonoGame.Extended.Graphics.TiledMapRenderer..ctor(GraphicsDevice graphicsDevice)
   w MyDll.Game.Initialize()
   w Microsoft.Xna.Framework.Game.DoInitialize()
   w Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   w Microsoft.Xna.Framework.Game.Run()

**Comment by craftworkgames** [comment]
Looks like issue #351 which has already been fixed but not released.

You could try using the [pre-release packages](http://craftworkgames.github.io/MonoGame.Extended/NuGet-Pre-Release/).
