### ISSUE TITLE
[Entities] Entity.Get<T> for unattached component

### ISSUE THREAD

**Issue by cheprogrammer** [craftworkgames/MonoGame.Extended#413]
Hello!

For right now, attempting to get an unattached component for entity throws an exception.
In my project I'm working on enhanced rendering system, which supports different rendering components with hierarchical scene tree.

For now, I'm using following extensions:

```
public static class EntityExtension
 {

        private static readonly Logger Log = LogManager.GetCurrentClassLogger();

        /// <summary>
        /// Gets the entity component or null (if component doesn't exist)
        /// </summary>
        /// <typeparam name="T">Type of component</typeparam>
        /// <param name="source">Source entity</param>
        /// <returns>Component of type T or null</returns>
        public static T TryGet<T>(this Entity source) where T : EntityComponent
        {
            Log.Trace($"Attempting to get a component '{typeof(T).Name}'");

            T result;
            try
            {
                result = source.Get<T>();
            }
            catch (Exception)
            {
                result = null;
                Log.Trace($"Attempt to get a component '{typeof(T).Name}' failed");
            }

            return result;
        }
}
```

In case of unattached component the exception processing time is nearly:
00:00:00.013 - 00:00:00.016, which impacts performance a lot.

Maybe, it is more suitable to return null on attempting to get unattached component?

Best regards,
Denis

**Comment by LithiumToast** [comment]
What type of exception does it throw for you? 

If I understand correctly, 
[https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Entities/EntityManager.cs#L334](this line could be changed) to use `as` for casting.

**Comment by craftworkgames** [comment]
It seems pretty sensible to me to return null instead of throwing an exception in this case.

**Comment by cheprogrammer** [comment]
Hi @LithiumToast , here it is:

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=MonoGame.Extended.Entities
  StackTrace:
       at MonoGame.Extended.Entities.EntityManager.GetComponent(Entity entity, EntityComponentType componentType)
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by LithiumToast** [comment]
So `components` is null on that line. Are you doing some sort of multithreading? Is it possible that components have not been registered yet?

**Comment by cheprogrammer** [comment]
My case is nor usual, so, please, correct me, if I'm doing something wrong:

During the Update I'm creating entity and attaching my own Transform component and Rendering Component.
I have two systems - one system interested in Transform (on Update layer), and another interested in Rendering component (on Draw layer), but OnEntityAdded invokes firstly for Rendering, than for Transform - so, that ruins the execution logic. 

That happens because in list of processing systems Rendering systems takes the first place and I can't do anything to change the order of systems.
