### ISSUE TITLE
Drawing TiledMapTileObject

### ISSUE THREAD

**Issue by maaex** [craftworkgames/MonoGame.Extended#415]
Hi!

We're making a game using MonoGame.Extended and Tiled. We use Tiled object layers to place game objects that are parsed in various ways depending on their types. Some of these objects are of the type TiledMapTileObject, and some of them we would like to draw to the screen (using a spritebatch for the most control).

Currently there is no good way to get the tile texture (or even which tileset it belongs to) from the TiledMapTileObject, all you can get is a TileSetTile object or a local tileset identifier.

Looking at the [constructor](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Tiled/TiledMapTileObject.cs) for TiledMapTileObject it is actually reading these values but not saving them. I suggest adding the tileset and/or global identifier as properties to the TiledMapTileObject. That way the texture and texture region could be extracted from the tileset.

**Comment by craftworkgames** [comment]
I haven't looked at this closely but on the surface it seems like a reasonable suggestion. Would you like to make the required changes and submit a PR?

**Comment by maaex** [comment]
Done!
