### ISSUE TITLE
[GuiButton] Button does not respect stretching

### ISSUE THREAD

**Issue by aravol** [craftworkgames/MonoGame.Extended#419]
Despite `Stretch` causing my curtain `GuiLabel` ("Press any button to continue") to occupy the entire screen, the following does not seem to be as true of a `GuiButton`. The following is the offending code

    GuiSystem = new GuiSystem(
        new WindowViewportAdapter(game.Window, game.GraphicsDevice),
        new GuiSpriteBatchRenderer(game.GraphicsDevice, () => Matrix.Identity))
    {
        Screen = new GuiScreen(skin)
    };

    var quitButton = new GuiButton()
    {
        Text= "Quit",
        HorizontalAlignment = HorizontalAlignment.Stretch,
        VerticalAlignment = VerticalAlignment.Stretch
    };
    quitButton.Clicked += (sender, args) => game.Exit();
    GuiSystem.Screen.Controls.Add(quitButton);

**Comment by craftworkgames** [comment]
Hey @aravol 

The GUI system is still in a "work in progress" state, although, I don't think anyone is actively working on it at the moment.

If you're interested, you're welcome to try and fix some of these issues yourself? 

I'd like to get back to it at some point, but it's not currently on my radar. Thanks for reporting the issue anyway.

**Comment by wutipong** [comment]
@aravol  not really sure if it helps (haven't tried yet), but you might want to wrap it with some container like uniform grid for example. 

last time i tried it occupied the whole screen (even if I don't want it to).
