### ISSUE TITLE
MouseListener double click events should fire on mouse down rather than mouse up

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#42]
It seems there's some contention #14 about the correct behavior of double click events in the mouse listener.

The argument is about when the events should fire. In WinForms the double click event fires *immediately* before the mouse up event as can be seen when holding down the mouse button for a couple of seconds before the double click registers.

    26/08/2015 11:59:24 AM:MouseDown
    26/08/2015 11:59:24 AM:Click
    26/08/2015 11:59:24 AM:MouseUp
    26/08/2015 11:59:24 AM:MouseDown
    26/08/2015 11:59:26 AM:DoubleClick
    26/08/2015 11:59:26 AM:MouseUp

This behavior also seems to be consistent in [VB.NET](http://stackoverflow.com/questions/14731304/why-doesnt-doubleclick-event-fire-after-mousedown-event-on-same-element-fires) and [JavaScript](http://www.quirksmode.org/dom/events/click.html).

However, as it's [documented here](https://msdn.microsoft.com/en-us/library/windows/desktop/gg153548(v=vs.85).aspx) and can be observed when double clicking an icon on your desktop, or double clicking to select some text in a text editor the event registers on mouse down (not mouse up).

> In effect, the second WM_LBUTTONDOWN message that would normally be generated becomes a WM_LBUTTONDBLCLK message.

Taking into account the double tap behavior on touch screens, I think the MouseListener should be changed to respond to the double click on mouse down. 

We'll have to reconsider what this means for drag and drop events. If they can't be implemented correctly the MouseListener they may need to be removed and reconsidered for a GUI library later.

**Comment by cra0zy** [comment]
On Linux double click event occurs on MouseUp

**Comment by craftworkgames** [comment]
> On Linux double click event occurs on MouseUp

Interesting. I haven't had a chance to take another look at this bug yet. What do you think we should do?

**Comment by cra0zy** [comment]
Maybe implement 2 double click events? one that occurs on mouse up and the other on mouse down

**Comment by craftworkgames** [comment]
Interesting thought. Kinda like how WPF has a [[`PreviewMouseDoubleClick`](https://msdn.microsoft.com/en-us/library/system.windows.controls.control.previewmousedoubleclick(v=vs.110).aspx) event perhaps.

Tbh, I'm not sure it really matters that much. I think I'd rather just pick one way and go with it.

**Comment by craftworkgames** [comment]
Fixed.

**Comment by WardBenjamin** [comment]
Whoo! I think this is the last part of version 0.3!
