### ISSUE TITLE
I think people could benefit from logging capabilities being included.

### ISSUE THREAD

**Issue by Icecream-Burglar** [craftworkgames/MonoGame.Extended#420]
I've just published a logging library I think people could benefit from. Perhaps especially in the game-development field where logging is somewhat important.
It shouldn't be too difficult to integrate into Monogame.Extended if anybody is interested.

Let me know what you think: https://github.com/Icecream-Burglar/WaterLogged

**Comment by craftworkgames** [comment]
There are already plenty of good logging libraries. Personally I use [Serilog](https://serilog.net/).

It seems to me that logging libraries work best as a standalone dependency.

In what way do you think it would be beneficial to integrate something like this into MonoGame.Extended?

**Comment by Icecream-Burglar** [comment]
I was just thinking a unified logging implementation would allow people to write extensions and things for one interface that could directly log strongly typed objects relevant to game development. But the drawback would be forcing a specific logging library on everybody.

**Comment by aravol** [comment]
I could see at least a couple prebaked GameComponents keeping an eye on performance and executing some logging actions, but even those would could be implemented such that they hook into whatever logging you choose via events

**Comment by Icecream-Burglar** [comment]
There's still a required interface then to mediate between the game and the chosen library.
As per the title of this issue "I think people could benefit from logging capabilities being included", "Logging capabilities" doesn't necessarily mean a full-blown library. In the actual body of the issue, I was merely volunteering to do it in the event somebody decided it was necessary to cake-in an entire library.

**Comment by craftworkgames** [comment]
We may reconsider this at some point but right now I think it's a distraction.
