### ISSUE TITLE
[GuiButton] buttons with complex button content

### ISSUE THREAD

**Issue by wutipong** [craftworkgames/MonoGame.Extended#423]
Currently, GuiButton displays a label on top of a background. In my case, I need larger buttons contains two lines of text and an image icon which is dynamically loaded at the runtime (let say, I'm implementing the load/save screen.).

I've tried adding controls into `GuiButton.Controls` member and nothing happens. It turns out that the control needs to be a subclass of `GuiLayoutControl` in order to layout the child controls under that control (otherwise the child controls are not displaying at all). Maybe ... having `Controls` member at the GuiControl class level is misleading, IMHO.

In order to implement this, I'm considering implementing a custom control, and making changes to the button by making the GuiButton holds a GuiLayoutControl inside (and add whatever controls to that control). There are quite a few drawbacks and potential problems (like ... placing buttons inside a button?). So I'm not quite sure if that'd be wise.

Not really sure which way is more preferable. So I'd like to ask what would you think about that? Maybe I can help with implementing that.

**Comment by craftworkgames** [comment]
Hey @wutipong 

Sorry for not getting back to you earlier. The truth is, the GUI system still needs quite a bit of work and nobody is currently working on it.

I've had a few ideas on what we might do in the next iteration on the GUI system but I'm not really sure of the direction it's going tbh.

Of course, if you do want to work on it, by all means go ahead.

**Comment by wutipong** [comment]
No worries :). I understand that no one is working one it at the moment. 

I've actually started working on my UI thing based on your code. If it went well, I will post some PR just in case you're interested.

**Comment by craftworkgames** [comment]
Sure thing. Either way, I'd love to see what you end up creating.
