### ISSUE TITLE
[Input] Input is repeating in KeyPress event

### ISSUE THREAD

**Issue by Piku201** [craftworkgames/MonoGame.Extended#425]
Despite being subscribed to the `KeyPress` event, it is still repeating using the `InitialDelay` and `RepeatDelay` properties. I'm pretty sure this should only apply to the `KeyTyped` event?

**Comment by craftworkgames** [comment]
That's a good question. If I remember correctly the behavior was originally based off the old school [WinForms KeyPress event](https://msdn.microsoft.com/en-us/library/system.windows.forms.control.keypress(v=vs.110).aspx) so it would be interesting to know how that behaves.

Either way, I think it would be nice to have more control over this stuff. Maybe some flags to be able to turn off repeating on the various events perhaps?

**Comment by Piku201** [comment]
Looking at the source, I may have found a way to set repeating on or off. But first I need to find out how to actually contribute anything to the code. (It's my first time using GitHub)

**Comment by craftworkgames** [comment]
There's loads of tutorials on the internet about how to use git and Github but it can be a little overwhelming at first. My first experience with git was very confusing so I'll try and give you a run down of the basics.

If you've already got a Github account, the first thing you need to do is [create your own fork of the repo](https://help.github.com/articles/fork-a-repo/). 

My advice, if you're on Windows, is to install [cmder](http://cmder.net/). It's a very nice way to interact with git on the command line.

Then you can [clone the forked repo](https://help.github.com/articles/cloning-a-repository/) to your local machine. 

    git clone https://github.com/Piku201/MonoGame.Extended.git

Once you've made some changes and are ready to push the changes back into the repo you'll need to know a [handful of other git commands](http://rogerdudler.github.io/git-guide/). Don't worry about branching and merging just yet. The only commands you really need to know to get started are these:

    git add *
    git commit -m "Commit message"
    git push

In that order..

Oh, and the other handy one is `git status` which you can run at any time to see the state of your changes. 

That's about it. Once you've got some changes in your own fork you can [make a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by Piku201** [comment]
Thanks a lot for your support!

**Comment by Piku201** [comment]
Problem should be solved then, closed.
