### ISSUE TITLE
Screen as DrawableGameComponent

### ISSUE THREAD

**Issue by felaugmar** [craftworkgames/MonoGame.Extended#429]
I noticed that [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) is a [DrawableGameComponent](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.drawablegamecomponent.aspx) and that it manages all [Screens](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/Screen.cs) just by calling the methods (Update, Draw, Initialize, LoadContent, etc.) of all them (The visibles).

What you think of making the [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) a simple class, with the [Register](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs#L40), [FindScreen](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs#L30) and maybe others methods and the [Screen](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/Screen.cs) a [DrawableGameComponent](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.drawablegamecomponent.aspx).

That way we could just Add and Remove the Screens from the [Components](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.game.components.aspx), turn them not Visible, turn them back to Visible, Enable and Disable them etc.

**Comment by stefanrbk** [comment]
> That way we could just Add and Remove the Screens from the Components, turn them not Visible, turn them back to Visible, Enable and Disable them etc.

How does your proposed method improve the implementation? [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) contains all the [Screens](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/Screen.cs) separately from the [DrawableGameComponents](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/DrawableGameComponent.cs) in [Components](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Game.cs). Doing so means we can add new functionality to the [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) system separately from MonoGame updating [Components](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Game.cs).

Also, you have the ability to use multiple [ScreenGameComponents](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs). Best thing I can think of is maybe having the map, the text boxes, etc of a RPG on separate [Screens](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/Screen.cs) in one [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs), then your inventory and its different menus on separate [Screens](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/Screen.cs) in another [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) and switch between them.

**Comment by felaugmar** [comment]
I think the way that is being done now does unnecessary things.

Because [DrawableGameComponent](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.drawablegamecomponent.aspx) already handles for you the methods (Update, Draw, Initialize, LoadContent, etc.) and in this case, they are being handled by the [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) instead .

Well, ok, [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) is a [DrawableGameComponent](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.drawablegamecomponent.aspx) and is separating the [Screens](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/Screen.cs) from the MonoGame's [Components](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Game.cs#L177), but this is really needed?

I think it's a nice design to keep all [DrawableGameComponent](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.drawablegamecomponent.aspx) in one place instead of creating your own, letting to the MonoGame the worry of calling the methods while [ScreenGameComponent](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/ScreenGameComponent.cs) only Manages which [Screens](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Screens/Screen.cs) should be ON and it's properties.

Also, nothing changes for the user, everything possible now will be keep intact.

**Comment by stefanrbk** [comment]
I am currently building a clone of Pokemon FireRed to find parts of  MonoGame.Extended that need work. The way I'm using it there is that the map, textboxes, and the onscreen menus are going to be Screens that live in one ScreenGameComponent I will override into a "MapScreenGameComponent" class. Then there will also be a ScreenGameComponent I will override into a "InventoryScreenGameComponent" class with screens for the list of items and different menus. So, in otherwords, it would function like a WinForm with popup dialog boxes.

Having all the Screens in the Components would get messy for a screen manager. For example, WinForms. The standard WinForms window has a Components list, where the parts of the window go into. Each Component itself has a list of Components, so you could have a window with a tab containing a button containing a picture. That picture is not in the main window's Components list. It is a tree. Each level goes to the next for the next step, whether that is to Update, Draw, etc. Keeping the Screens directly in the main game Components is a simple approach, but what I know is that games are rarely ever simple.

**Comment by LithiumToast** [comment]
@felaugmar `DrawableGameComponent` and `GameComponent` is one way to separate out modules of game rendering and logic. Not every game will use the `Game.Components`; some people like to call their rendering and update logic by hand in `Game.Draw()` and `Game.Update` respectively.

**Comment by felaugmar** [comment]
I see, I agree with what you said @LithiumToast, primarily on the **order**, that would be really a bad thing, you wanting to change the orders for your `Components` and the UI `Components` interfering you in that.

Some workarounds could probably work here, like defining a range for the UI `Components`, but It's not worth the work and would only increase the work for the user when using.

Well, I'll close this issue.
