### ISSUE TITLE
Can I bring my Circle over?

### ISSUE THREAD

**Issue by killerrin** [craftworkgames/MonoGame.Extended#43]
Awhile ago I wrote a Pull Request to get a circle into MonoGame, though I think general concensus is that it shouldn't be in the core library. 

That said, since it looks like we are trying to create an official Monogame Extension Library, I was wondering if this would be something we would be interested in adding to the Extended Library?

Heres the Pull Request where you can see the files
https://github.com/mono/MonoGame/pull/3419

**Comment by WardBenjamin** [comment]
Tentatively, I feel that this is some very good work and it should be included (perhaps in MonoGame.Extended.Utilities? I don't know). CC @craftworkgames

**Comment by craftworkgames** [comment]
Sorry guys, I've been extra busy today.

> I was wondering if this would be something we would be interested in adding to the Extended Library?

Yes, I think this could be a good addition to the library.

> perhaps in MonoGame.Extended.Utilities?

I'd rather use more descriptive namespaces like `MonoGame.Extended.Shapes` or `MonoGame.Extended.Geometry` perhaps.

Pretty much everything in the PR looks really good. We just need to be careful to keep the API as  consistent as possible. For example, in our Sprite class there's a method called  [`GetBoundingRectangle`](https://github.com/craftworkgames/MonoGame.Extended/blob/master/Source/MonoGame.Extended/Sprites/Sprite.cs#L60) and in the Circle class there's a method called [`ToRectangle`](https://github.com/mono/MonoGame/pull/3419/files#diff-c5dede4989ab48ad181f4a16c05f6ae7R473). It's only a subtle difference, but I'd like to try an keep things like this consistent across the API. Which do you guys prefer?

If we are going to introduce a `MonoGame.Extended.Shapes` namespace it would make sense to include other kinds of shapes. Triangle, Polygon and Line maybe. I noticed some of this has already been discussed in the [MonoGame PR discussion](https://github.com/mono/MonoGame/pull/3419#issuecomment-70435158)

Lastly, I think it's important to take a hard line on what we are including and what we are not. @KonajuGames put it nicely when he said:

> It can be a slippery slope.  Personally I think MonoGame is not a collision
detection library, and that is best handled by more dedicated libraries
such as Farseer and Bepu.  That said, Circle is a simple primitive and is
often used in larger games for 2D culling purposes.

MonoGame.Extended is not a collision detection library either. However, it *can be* the *glue* between your game and collision detection. What I mean by that is, the shape classes shouldn't contain any physics specific stuff. They should remain consistent with the [Rectangle](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Rectangle.cs) class in MonoGame. That's already the case in the PR, I just wanted to make it clear.

In the future, we might want to add support for conversion from these shapes to [Farseer Physics shapes](http://farseerphysics.codeplex.com/SourceControl/latest#SourceFiles/Collision/Shapes/PolygonShape.cs) but in that case it should live in a different namespace and most likely a different assembly (e.g. MonoGame.Extended.FarseerPhysics.dll). I did something similar on previous project and the idea was to convert our shapes (in pixels) to Farseer shapes (in world units).

LibGDX has a [similar set of shapes](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/physics/box2d/Shape.html).

There might be some cross over with #31 here too.

**Comment by craftworkgames** [comment]
@killerrin Are you going to start working on this or did you just raise it for discussion?

**Comment by killerrin** [comment]
Nope, I'm going to submit the pull request. Was off the grid the past few days

**Comment by craftworkgames** [comment]
Looks great. Thanks.
