### ISSUE TITLE
[ObjectPool] not setting Capacity as part of its constructor

### ISSUE THREAD

**Issue by RamiAhmed** [craftworkgames/MonoGame.Extended#433]
Hi!

First off; thanks for a great extension to MonoGame! It really helps speed up development.

I noticed that your ObjectPool is not settings its Capacity through its constructor. Coupled with the "ReturnNull" policy this renders the pool unusable, because it will always return null after the first element. Our workaround for now is to use "IncreaseSize" policy.

I believe the fix is extremely simple: Remember to set Capacity (property) to the capacity argument as part of the ObjectPool constructor.

**Comment by craftworkgames** [comment]
Thanks for letting us know :)
