### ISSUE TITLE
[ECS] Maximum 16 entity components are possible

### ISSUE THREAD

**Issue by fl0ttsch1** [craftworkgames/MonoGame.Extended#437]
First of all, I really like working with the Entity Component System, you did a great job there!

But it seems there is an unintentional limit for the entity component count.
Having 16 components works fine, when implementing the 17th I get:

```
System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'
in MonoGame.Extended.Entities.BitVector.set_Item(Int32 index, Boolean value) in C:\BuildAgent\work\b0358f41d1a3fba\Source\MonoGame.Extended.Entities\BitVector.cs:Line 98.
in MonoGame.Extended.Entities.EntityManager.FillComponentBits(BitVector bits, Type[] types) in C:\BuildAgent\work\b0358f41d1a3fba\Source\MonoGame.Extended.Entities\EntityManager.cs:Line 440.
in MonoGame.Extended.Entities.EntityComponentSystem.CreateSystems(List`1 systemTypeInfos, Int32 componentCount) in C:\BuildAgent\work\b0358f41d1a3fba\Source\MonoGame.Extended.Entities\EntityComponentSystem.cs:Line 207.
in MonoFight.Testing.EntityTestScreen.Initialize() in C:\projects\MonoFight\src\MonoFight\Testing\EntityTestScreen.cs:Line 35.
in MonoGame.Extended.Screens.ScreenGameComponent.Initialize() in C:\BuildAgent\work\b0358f41d1a3fba\Source\MonoGame.Extended\Screens\ScreenGameComponent.cs:Line 54.
in Microsoft.Xna.Framework.Game.InitializeExistingComponents()
in Microsoft.Xna.Framework.Game.Initialize()
in MonoFight.MonoFightGame.Initialize() in C:\projects\MonoFight\src\MonoFight\MonoFightGame.cs:Line 75.
in Microsoft.Xna.Framework.Game.DoInitialize()
in Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
in MonoFight.Program.Main() in C:\projects\MonoFight\src\MonoFight\Program.cs:Line 17.
```

Maybe the error is related to the length of the BitVector used in the ECS?

**Comment by craftworkgames** [comment]
That certainly seems unintentional.

Are you running from source?  Would you be interested in trying to fix this one?

**Comment by fl0ttsch1** [comment]
After debugging against the source, turns out everything is fine with MonoGame.Extended.Entities.

The problem occurs because I call EntityComponentSystem.Scan inside my screen's Initialize method, which is called initialized twice, as already mentioned in [issue 405](https://github.com/craftworkgames/MonoGame.Extended/issues/405).

Maybe there should be an exception thrown when EntityComponentSystem.Scan is called more than once?

**Comment by craftworkgames** [comment]
> Maybe there should be an exception thrown when EntityComponentSystem.Scan is called more than once?

Yes definitely.

Tbh, I've never really been big fan of how the whole `Scan` thing works as an API design but I haven't found the time to really put some deep thought into it.

**Comment by LithiumToast** [comment]
See http://community.monogame.net/t/entities-is-throwing-an-index-out-of-range-exception-potential-bug-resolved/9863/
