### ISSUE TITLE
Text fields

### ISSUE THREAD

**Issue by ClassicThunder** [craftworkgames/MonoGame.Extended#44]
In my opinion text fields are ubiquitous enough that is is worth bringing them in separate of the more general GUI functionality. I created text fields as part of my [GUI Framework](https://github.com/ClassicThunder/MonoGameGui) and began the process of isolating the TextField from the other systems into a separate library [here](https://github.com/ClassicThunder/MonoGame-TextField).

The library is in a bit of a disarray (it was put on hold while I finished up the input library) but I'll try and summarize where it is at.

All of the functionality in terms of selecting, rendering, copying, pasting, and manipulating the text should be complete. However, its not tied into any input system currently. They is where the MonjoGame.InputListeners comes in (and the main reason I really wanted the double click to register on the second mouse down). 

Theoretically integrating with the input system, and fleshing out the unit tests is all that is needed to finish up the library. By default it is only multi-line so adding a single line option that figures out an appropriate height is something I want to do. Also worth nothing it simply draws the text, cursor, and a background for the selected text: there is no outline, background or, border.

When do you want to have the .3 release? If its near the end of the month I could probably have the text fields ready by then.

**Comment by craftworkgames** [comment]
So if I understand correctly this is about the ability to select / edit text and being decoupling from the GUI framework?

How do you picture this working in terms of the API? In other words, what would the code look like to setup a basic "text field" in a game. How would it be different to using a "text box" from the GUI library?

> When do you want to have the .3 release? If its near the end of the month I could probably have the text fields ready by then.

I'd like to keep the releases short and regular. There's a [few things](https://github.com/craftworkgames/MonoGame.Extended/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+0.3%22) marked to go in the next release. I'm not sure how long they'll take or if they'll all make it in. I'd rather have regular high quality releases rather than trying to pack lots of half finished stuff into every release.

If this doesn't make it into the 0.3 release, it should only be a few weeks until the 0.4 release anyway. Let's focus on what we want and getting the API right rather than when it will be released.

**Comment by ClassicThunder** [comment]
I image there being 2 classes. 

TextField
SingleLineTextField

TextField would take a rectangle and max character size. The text wraps at the width and creates news lines as need. Lines that extend below the specified area are clipped be default but there would be a flag to disable clipping. 

The SingleLineTextField takes in a top left point or a center left point and has a set height. This is basically a helper wrapped around the TextField restricting the height and making it easier to align with other objects.

The constructors would require an instance of the InputHandler class. You would be able to get/set the current string, set/get the selected range, get the current size, and enable/disable input. 

Other behavior I would like to add is the ability to override functions to customized how the cursor and selected text is rendered. I'll take the time to actually stub it out sometime next week but hopefully this get the point across.

**Comment by craftworkgames** [comment]
This looks like a reasonable set of requirements for some sort of TextField class.

What I still don't understand is what you mean by this:

>  is is worth bringing them in separate of the more general GUI functionality.

Currently MonoGame.Extended doesn't have any GUI functionality, so I'm still trying to get my head around what that is going to look like in terms of classes and namespaces.

For example, do you picture a bunch of classes representing *controls* in a `MonoGame.Extended.Gui` namespace much like you've done [here](https://github.com/ClassicThunder/MonoGameGui/tree/master/GuiContent/Elements). How does the TextField class fit into it? Would it live in a different namespace? What's the benefits of doing it this way?

I guess my confusion with this discussion is that we seem to be talking about the *solution* without really being clear on what the *problem* is. What problem are we trying to solve here?

**Comment by ClassicThunder** [comment]
My bad not separate as in a separate name space, but separate temporally. As in I can get it done way before I can get the basic of a gui system done, so I think its worth rolling out the text fields as soon as it is ready instead of waiting until the details of the rest of the GUI system is hashed out.

**Comment by craftworkgames** [comment]
>  I think its worth rolling out the text fields as soon as it is ready instead of waiting until the details of the rest of the GUI system is hashed out.

I'm okay with this in the short term. My concern is that if people start using it and there's lots of breaking changes to the API as we build a proper GUI system it'll be painful.

**Comment by craftworkgames** [comment]
I'm working on a gui system so I don't think we need to keep this issue around.
