### ISSUE TITLE
[ECS] Port of Java's Artemis-odb to ME

### ISSUE THREAD

**Issue by megabobik** [craftworkgames/MonoGame.Extended#442]
I think about porting Java's Artemis-ODB to ME framework. What you think about it ?

**Comment by esengine** [comment]
Although I have not used this framework, but I am willing to learn this.

**Comment by megabobik** [comment]
@esengine it is fastest ECS framework on Java and easy to work with

**Comment by esengine** [comment]
I am looking forward :+1:

**Comment by craftworkgames** [comment]
> I think about porting Java's Artemis-ODB to ME framework. What you think about it ?

It depends.

Firstly, [MonoGame.Extended.Entities](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended.Entities) is already a port of [Artemis_CSharp](https://github.com/thelinuxlich/artemis_CSharp). So my first question is what makes odb better?

Secondly, assuming odb has better performance in Java, that doesn't mean it'll have better performance in C#. There's enough differences between the languages and compilers that a straight "port" is usually not enough. The code needs to be carefully considered as it's brought across.

That said, our ECS is nowhere near perfect. In fact, there's plenty of room for improvement both in the API design and likely performance. I'm always in favor of learning from other projects. If we can use odb to make improvements then I'm all for it.

**Comment by megabobik** [comment]
MonoGame.Extended.Entities is pretty outdated. Many things present in Artemis-odb  is not avaialble(plugins, managers etc.) At first i just try to put Artemis-odb on c#'s rails, then accomodate it to c#.
