### ISSUE TITLE
Plan for ECS in 2.0?

### ISSUE THREAD

**Issue by jonmseaman** [craftworkgames/MonoGame.Extended#449]
I was thinking about some useful features for the ECS. Do you have a plan for how it is going to develop in 2.0? I was thinking that it would be nice to support inheritance for components, so I was wondering about this. I may try to implement it myself as it would be useful for me.

To add more to the inheritance for components.
I would like a SpriteComponent which inherits from TransformComponent.
The sprite component would be drawn by the SpriteSystem, but it would also have a position, hence inheriting from TransformComponent. The TransformComponent would then still be able to be accessed via a PhysicsSystem, too adjust for gravity/etc.

**Comment by craftworkgames** [comment]
I'm definitely planning on making some significant changes to the ECS in 2.0. Some of the existing classes are being refactored to be more easily used as components and systems.

Honestly, I don't think inheritance is a good idea for components. At least not the way you've described. It actually kinda defeats the purpose of using components in the first place. It's theoretically possible to have component classes inherit from a base class, and it some cases that might be useful, I think that's more the exception than the rule though. I'm not saying you shouldn't do it, but you should use inheritance sparingly.

I suggest you read up on how most [entity component systems](https://www.google.com.au/search?q=entity+component+system) work. 

It's quite common and highly desirable to have the transform component separate from the sprite component. This way you can compose entities that have a transform + sprite, just a sprite or just a transform. You'd be surprised how many things in your game won't need a sprite but will need a transform.

Here's a few references I've found to explain things pretty well:

 - http://cowboyprogramming.com/2007/01/05/evolve-your-heirachy/
 - https://www.gamedev.net/articles/programming/general-and-gameplay-programming/understanding-component-entity-systems-r3013/
 - http://gameprogrammingpatterns.com/component.html

You'll notice in all three of the above examples, even though they are quite different implementations the sprite / render component is separated from the transform / position component. None of them use inheritance. There's plenty more examples of this pattern around.

In fact, if you read the [wikipedia page on Composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) you'll notice that it looks a *lot* like an entity component system when you use composition.

**Comment by jonmseaman** [comment]
Thanks for the reference material
