### ISSUE TITLE
[Tweening] Tween animation jumping around

### ISSUE THREAD

**Issue by Sendoushi** [craftworkgames/MonoGame.Extended#450]
I'm setting a simple animation like this:

```csharp
protected void CreateTween()
{
    _sprite.CreateTweenChain(CreateTween).MoveTo(_animPos, ANIM_TIME, EasingFunctions.Linear);
}
```

The problem is that it is jumping around:
![game006](https://user-images.githubusercontent.com/3297394/34606891-ffcf4a52-f208-11e7-8c74-56da3603b957.gif)

Am I doing something wrong? Should I prepare the sprite, animation time or the new position somehow? Like rounding the numbers?

**Comment by craftworkgames** [comment]
Hmm.. not sure exactly what's going on here but I do know there's a few bugs like this in the tweening system.

I'm planning on revamping the tweening stuff in the 2.0 release (don't hold your breath though, it could take quite a while).

In the mean time, you're welcome to try and fix the issue yourself.

**Comment by Sendoushi** [comment]
That seems like an interesting project but I'm new to C# and the framework, could you point me in the right direction?

**Comment by craftworkgames** [comment]
At a guess I would say [this bit of code](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Tweening/PropertyTween.cs#L54) is probably the place to start.

protected override bool OnUpdate(float deltaTime)
        {
            if (!_initialValue.HasValue)
                _initialValue = _getValue();

            _currentMultiplier = EasingFunction(CurrentTime/Duration);

            if (CurrentTime >= Duration)
            {
                CurrentTime = Duration;
                _currentMultiplier = 1.0f;
                return true;
            }

            var difference = Subtract(TargetValue, _initialValue.Value);
            var multiply = Multiply(difference, _currentMultiplier);
            var newValue = Add(_initialValue.Value, multiply);
            _setValue(newValue);
            return false;
        }

I think what might be happening is that when the animation completes (CurrentTime >= Duration) then the `_currentMultiplier` is not actually being applied to the animation.

It appears that the `_currentMultiplier` is correctly being set to `1.0` when the animation completes but this new value is not actually being applied to anything. It might be a simple matter of calling `_setValue` (with the lines above it) inside the if statement.

**Comment by craftworkgames** [comment]
Something like this should do it.

```csharp
        protected override bool OnUpdate(float deltaTime)
        {
            if (!_initialValue.HasValue)
                _initialValue = _getValue();

            _currentMultiplier = EasingFunction(CurrentTime/Duration);

            var isComplete = CurrentTime >= Duration;

            if (isComplete)
            {
                CurrentTime = Duration;
                _currentMultiplier = 1.0f;
            }

            var difference = Subtract(TargetValue, _initialValue.Value);
            var multiply = Multiply(difference, _currentMultiplier);
            var newValue = Add(_initialValue.Value, multiply);
            _setValue(newValue);
            return isComplete;
        }
```

**Comment by Sendoushi** [comment]
On it. Just trying to set everything up on the IDE: http://prntscr.com/hwdttg

**Comment by craftworkgames** [comment]
I rewrote the tweening code from scratch for 2.0 and this issue no longer exists.
