### ISSUE TITLE
MonoGame.Extended.Tiled Tile Bleeding

### ISSUE THREAD

**Issue by Toemsel** [craftworkgames/MonoGame.Extended#452]
Depending on the View and Proj Matrix the tiles start to bleed.

This is how I calculate the view and proj matrix:

```
 //Get the "local" scale. This scalation depends on the virtual and actual resolution ratio.
    float localScaleX = ScreenWidth / VirtualWidth;
    float localScaleY = ScreenHeight / VirtualHeight;

    //Don't use float position values. Only int for exact PX coordinates on the screen.
    Vector2 position = new Vector2((int)TransformationComponent.Position.X,
        (int)TransformationComponent.Position.Y);

    //If the position changes, a matrix adjustment is required.
    ViewMatrix = Matrix.CreateTranslation(new Vector3(-position, 0.0f)) *
        Matrix.CreateTranslation(new Vector3(-Origin, 0.0f)) *
        Matrix.CreateRotationZ(TransformationComponent.Rotation) *
        Matrix.CreateScale(localScaleX * ScaleX, localScaleY * ScaleY, 1f) *
        Matrix.CreateTranslation(new Vector3(Origin, 0.0f));

    //The projectMatrix also depends on scale and resolution properties.
    ProjectionMatrix = Matrix.CreateOrthographicOffCenter(0, ScreenWidth, ScreenHeight, 0, 0, 1f);
```

Drawing is just the simple call:

`            MapRenderer.Draw(Map, CameraComponent.ViewMatrix, CameraComponent.ProjectionMatrix, ShaderComponent?.Shader ?? null, 0);`

Depending on localScaleX and Y the bleeding does occur. (Or don't) I did try to floor or round. (Without success)

**Comment by LithiumToast** [comment]
Try setting the `Graphics.SamplerState` to `SamplerState.PointClamp` before drawing.

**Comment by EnemyArea** [comment]
and a Power Of Two texture works well too

**Comment by Toemsel** [comment]
@EnemyArea Textures are already power of Two.
@LithiumToast This did the trick! Now it works.
Wouldn't it be advantageous to include this settings already into the extension? (Parameter, Property,...)
