### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by Yothri** [craftworkgames/MonoGame.Extended#455]
Hi,

I just found the sample in the documentation to create a simple animation. I am using this texture
![player_sheet](https://user-images.githubusercontent.com/5815215/34937210-4e2bfcd0-f9e4-11e7-9cd5-bb7686f24ec6.png)
This is my atlas file (normally its a .xml but GitHub doesnt allow xmls to upload)
[player_atlas.txt](https://github.com/craftworkgames/MonoGame.Extended/files/1631228/player_atlas.txt)

This is my code in LoadContent():

```
var playerTex = Content.Load<Texture2D>("gfx/player_sheet");
var playerMap = Content.Load<Dictionary<string, Rectangle>>("atlas/player_atlas");
var playerAtlas = new TextureAtlas("player_sheet", playerTex, playerMap);
var playerAnimationFactory = new SpriteSheetAnimationFactory(playerAtlas);

playerAnimationFactory.Add("walk", new SpriteSheetAnimationData(new[] { 0, 1 }, isLooping: true));
playerSprite = new AnimatedSprite(playerAnimationFactory, "walk");
``` 

And this is my code in Update():
`playerSprite.Update(gameTime.ElapsedGameTime.Seconds);`

And this is my Draw():
```
batch.Begin(transformMatrix: camera.GetViewMatrix());
batch.Draw(playerSprite);
batch.End();
```

The first frame however is drawing, but its not drawing the second at all. Didnt got it working a single time. Tried also to explicitly Play() the sprite without success.

**Comment by craftworkgames** [comment]
I think the problem is that the `gameTime.ElapsedGameTime.Seconds` property will always be zero. You'll want to use the `gameTime.ElapsedGameTime.TotalSeconds` instead.

```csharp
var deltaTime = (float) gameTime.ElapsedGameTime.TotalSeconds;
playerSprite.Update(deltaTime);
```

Alternately, there's also an `Update` method that takes a `GameTime` directly or you can use the `GetElapsedSeconds` extension method as a shortcut to the code above.
