### ISSUE TITLE
[Tiled] TiledMapProcessor had unexpected failure!

### ISSUE THREAD

**Issue by johmarjac** [craftworkgames/MonoGame.Extended#475]
Background Info: I created a tileset based on single tile images, not an already existing sheet.

StackTrace: 
```
D:/Repositories/PlatformerGame/PlatformerGame/Content/Levels/testkarte.tmx : error : Processor 'TiledMapProcessor' had unexpected failure!
1>  System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
1>     bei MonoGame.Extended.Content.Pipeline.Tiled.TiledMapLayerModelContent..ctor(String layerName, TiledMapImageContent image)
1>     bei MonoGame.Extended.Content.Pipeline.Tiled.TiledMapProcessor.<CreateTileLayerModels>d__11.MoveNext()
1>     bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
1>     bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
1>     bei MonoGame.Extended.Content.Pipeline.Tiled.TiledMapProcessor.Process(TiledMapContent map, ContentProcessorContext context)
1>     bei Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
1>     bei MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
```

**Comment by craftworkgames** [comment]
Are you talking about this feature?

![image](https://user-images.githubusercontent.com/3201643/36418619-1cad0470-167b-11e8-88fb-dbdae76b93d9.png)

If so, it's not currently supported.

Loading individual tiles like this in MonoGame has a huge performance impact. To do it properly we'd have to pack the tiles into a tileset anyway. So there's really no great benefit to supporting this feature.
Maybe one day perhaps when we have a built in texture packer.

Speaking of texture packers; there's a program called [Texture Packer](https://www.codeandweb.com/texturepacker) that might help. There's a "free" version and I'm pretty sure it supports tileset style packing that will work in Tiled.

**Comment by johmarjac** [comment]
@craftworkgames yes I was talking about that feature. But yeah it makes no sense then to implement it. I already creates the spritesheet.

Thanks anyways for clearing that up.

**Comment by twixthehero** [comment]
Came across this after I saw NPEs trying to import.

Maybe it would be a good idea to update the docs saying "Collection of images" is not supported?

**Comment by lithiumtoast** [comment]
We will consider it. The Tiled code is going to get revamped in v4. It is likely the Tiled code will no longer use the content pipeline altogether. An option is to throw a better exception message.

**Comment by pedrosifreitas** [comment]
> Are you talking about this feature?
> 
> ![image](https://user-images.githubusercontent.com/3201643/36418619-1cad0470-167b-11e8-88fb-dbdae76b93d9.png)
> 
> If so, it's not currently supported.

I'm still having this problem even though I'm not using this feature
