### ISSUE TITLE
Entity class is sealed

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#484]
I need to make changes to the `Entity` class in my library, but it is `sealed`. I understand that this class should not be inherited (like creating a Player class) as it breaks the concept of an ECS, but I need additional methods/properties on the class and I am unable to do it.

What are your thoughts on making this a change in the library?

**Comment by mstauber** [comment]
I can't say much for the ECS system as I haven't used it. Do you need to do more than what extension methods can offer on the Entity object?

If so, you can use reflection to manipulate the object however you like.

Here: https://stackoverflow.com/questions/4097682/c-sharp-use-reflection-to-get-a-private-member-variable-from-a-derived-class

**Comment by craftworkgames** [comment]
Could you provide more details on what you're trying to do?  What additional methods / properties would you like to add?

Perhaps we can help find another way to achieve the desired result or some kind of workaround.

**Comment by rafaelalmeidatk** [comment]
> Do you need to do more than what extension methods can offer on the Entity object?

Yes

> Could you provide more details on what you're trying to do? What additional methods/properties would you like to add?

Basically, I need those other components to know about the change of position of the ` TransformComponent`, so they can act on that. Specifically, I need my `ColliderComponent` to know that the entity position has been changed, so it can trigger some routines on my physics system and update some stuff so that the collision shape is in sync with the entity position.

So I would create a method on the `Entity` class that is only triggered by the `TransformComponent`, then the `Entity` can propagate this to all the components. I know this it breaks the idea of how an ECS works, but I can't this of another way of the components to know about something that changed on another component. This is pretty much what Nez does here: https://github.com/prime31/Nez/blob/master/Nez.Portable/ECS/Components/Physics/Colliders/Collider.cs#L193
But the difference is that the transform is directly in the entity class, what facilitates the problem and doesn't break so much the ECS.

**Comment by stefanrbk** [comment]
I have been studying the ECS we have as well as the concept of ECS in general. You would want to handle any change like that with an event or something similar. Your `ColliderComponent`s could subscribe to a `TransformComponent.OnChange` event and get updated that way. Otherwise a management class could be built which references the components you are wanting to update and you could trigger it for the change.

**Comment by LithiumToast** [comment]
@rafaelalmeidatk You have two options.

1. Use the [Observer pattern](http://gameprogrammingpatterns.com/observer.html). In C# this is literally events. Nothing is stopping you from doing what @stefanrbk suggested; you would be responsible for wiring up and tearing down the event handlers in your game logic.

2. Create a system that has the sole responsibility of flushing the position information from all `TransformComponent`s to `ColliderComponent`s. Note that this system should run _before_ your physics system *and* it should only register for entities that have both a `TransformComponent` and a `ColliderComponent`. 

You can get smart with 2. and make this your "broad phase" system by taking the code for `TransformComponent2D` and exposing the flags: if the world or local matrix is dirty then it needs to be removed (from old position) and added (with new position) in a broad phase data structure such as a spatial hash (what Nez uses). Then your physics system becomes the "narrow phase" system that would query the broad phase data structure for all entities in question. The runtime should be `O(n)` if implemented correctly.

**Comment by rafaelalmeidatk** [comment]
Thanks, I ended up utilizing @stefanrbk's idea:

    [EntityComponent]
    public class TransformComponent : TransformComponent2D
    {
        public delegate void OnTransformChanged(TransformChange change);
        public event OnTransformChanged OnTransformChangedHandler;

        public new Vector2 Position
        {
            get => base.Position;
            set
            {
                base.Position = value;
                OnTransformChangedHandler?.Invoke(TransformChange.Position);
            }
        }

        public new Vector2 Scale
        {
            get => base.Scale;
            set
            {
                base.Scale = value;
                OnTransformChangedHandler?.Invoke(TransformChange.Scale);
            }
        }

        public enum TransformChange
        {
            Position,
            Scale,
        }
    }

I could use 2. as you pointed out, but I would have two system looping through the objects without need, as of now the physics system already take care of this and only run the collision checks when something moves.
