### ISSUE TITLE
[ECS] Entity ID missing ?

### ISSUE THREAD

**Issue by Scellow** [craftworkgames/MonoGame.Extended#497]
Hello

Looks like the ECS is similar to Artemis, but one thing is missing, the Entity class doesn't have an id property, why is that ? How can i differentiate entities, specially for networking purposes ?

https://github.com/junkdog/artemis-odb/blob/master/artemis-core/artemis/src/main/java/com/artemis/Entity.java#L26

**Comment by LithiumToast** [comment]
You can easily use `Entity.Name` a `string` for an identifier if you so wish.

**Comment by craftworkgames** [comment]
> You can easily use Entity.Name a string for an identifier if you so wish.

This seems like a reasonable workaround for now but I don't see any harm in adding an `Id` field onto the class.
