### ISSUE TITLE
[ECS] Something about Entity.Detach<T> removes entity from all systems

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#506]
So im just trying to remove a component from my player entity, but when I do so, the player gets removed from all systems that it belongs to. There is something about when the entity gets marked with WaitingToRefreshComponents (which happens after calling Detatch) it gets contains == true in this piece of code in EntityProcessingSystem.cs.

    internal virtual void RefreshEntityComponents(Entity entity)
    {
        var contains = entity.SystemBits[Index];
        var isInterested = Aspect.Matches(entity.ComponentBits);

        if (contains)
            Remove(entity);
        else if (isInterested)
            Add(entity);
    }

The player entity is currently being handled by 3 of my systems, and then I've just attached a dummy component which isnt part of any system, and detached that one. And still my player entity gets removed from every system after that.

**Comment by LithiumToast** [comment]
From http://community.monogame.net/t/something-about-entity-detach-t-removes-entity-from-all-systems/10648

**Comment by bjornrandir** [comment]
My current workaround looks like this:

internal virtual void RefreshEntityComponents(Entity entity)
        {
            var contains = entity.SystemBits[Index];
            var isInterested = Aspect.Matches(entity.ComponentBits);

            if (contains && !isInterested)
                Remove(entity);
            else if (isInterested && !contains)
                Add(entity);

            if (contains && entity.WaitingToBeRemoved)
                Remove(entity);
        }

But I'm not good enough to determine how this solution should be better implemented, when it comes to its SystemBits and ComponentBits etc etc. Just thought I'd post my workaround if it helps identify the real issue.

**Comment by sunnysmiles17** [comment]
The systems start to process the entity again when I reattach the previously removed component. Hopefully this info helps. Sorry if this is old news to you guys.

**Comment by craftworkgames** [comment]
This is one of a bunch of bugs in the old ECS.

Rest assured, they have been (or will be) fixed in the new ECS once it's merged back into `develop`. Migrating your code over to the new ECS takes a little bit of time but it's not that difficult.

**Comment by Mason11987** [comment]
Thanks @bjornrandir.  That work around did the job for me, I was pulling my hair out trying to figure out what was happening.

**Comment by craftworkgames** [comment]
I believe this is fixed in the new ECS.
