### ISSUE TITLE
CircleF.Contains() uses incorrect formula.

### ISSUE THREAD

**Issue by dualdragoon** [craftworkgames/MonoGame.Extended#511]
The CircleF.Contains() method simply subtracts the point provided from the center of the circle and then checks that the absolute values of the resulting value's x and y are less than or equal to the radius of the circle. However this does not work for telling if something is actually within the circle. Say you have a circle centered at 16,16 with a radius of 16. If you were to check the point 0,0 which is not within the circle but still fulfills the check then you get an incorrect response. I know that using the Math.Sqrt() method isn't very efficient but using the actual distance formula would result in the correct response. Without using the distance formula the CircleF is pretty much treated as a square for the purposes of the Contains() method as it currently is.

**Comment by stefanrbk** [comment]
To cut down on the usage of square root, you could use the existing logic as a rough test (as if the point is outside the square, then it is definitely outside the contained circle), and if the point is within the square, then the precision of the distance formula could be used to determine if the point is in the circle.

**Comment by dualdragoon** [comment]
That could work. I only noticed it because I have a button class that I wrote that supports circular and elliptical buttons and the circular buttons where responding when they shouldn't be.

**Comment by stefanrbk** [comment]
I use the distance formula in my code for touchscreen joysticks and it runs pretty smooth, so calling it a few times a frame shouldn't be too bad especially if operating on float values.

**Comment by stefanrbk** [comment]
You are right. Just squaring the radius means we don't need the square root! I guess I need to brush up on my algebra! Haha

**Comment by stefanrbk** [comment]
Well, square root is needed if you care about the actual distance like in my joystick code or a collision system, but not for a quick inside/outside check

**Comment by jonmseaman** [comment]
I submitted a PR for this issue. #515
