### ISSUE TITLE
[Demos] Convert all of our old demo projects to .NET core

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#512]
I've already created a few new demos to prove the concept, but I haven't had a chance to convert all of our old demos to .NET core yet.

I was hoping to work through each demo one at a time and make some improvements to them at the same time, but it's becoming apparent that no having demos makes testing things more difficult.

For example, when somebody submits a PR I need some way to verify that it actually works to some degree. In an ideal world we'd have a full suite of unit tests but writing unit tests around MonoGame has proved difficult. Running the demos is the next best thing.

Following along with one of the existing demos is probably easy enough. Mostly you need to replace the contents of the `.csproj` files and [remove a bunch of crap](https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/).

**Comment by jonmseaman** [comment]
Sure, I can look into it tomorrow. I'll see if I can convert Demo.SpaceGame then go from there.

**Comment by jonmseaman** [comment]
#514 
I started work on converting the demos.
