### ISSUE TITLE
BoxingViewportAdapter has wrong behavior on Linux DesktopGL

### ISSUE THREAD

**Issue by Sejsel** [craftworkgames/MonoGame.Extended#519]
There are multiple issues with BoxingViewportAdapter with the following setup:
```
MonoGame 3.6.0.1625
MonoGame.Extended 1.1.0
SDL 2.0.8
Platform: DesktopGL
```

- Using Camera2D.WorldToScreen() with this adapter is not precise. Especially when the window is tall and thin or short and wide this can be off by tens of pixels. This is not an issue with ScalingViewportAdapter.

- Reset() has to be called manually after creating the camera or the viewport won't apply until the windows resized (either not documented or behavior differs from other platforms).

- The BoxingViewportAdapter stops working after not using the camera, for example after swapping to another screen and back or even to another instance of the same screen.

**Comment by craftworkgames** [comment]
I don't have a Linux machine to reproduce this issue.
You're welcome to re-open the issue if it's still a problem and you're willing to fix it.
