### ISSUE TITLE
[Tiled] You should not see a red background to this text

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#520]
I was running the demos tonight and I noticed the following.

![image](https://user-images.githubusercontent.com/3201643/42219047-e29a9562-7f0d-11e8-9474-e4275c66c588.png)

Honestly, I can't remember exactly *why* we have that text in the demo but clearly something is broken. Probably something to do with setting a transparent color.

Needs some investigation.

**Comment by stefanrbk** [comment]
That is a test for the transparent color property we are currently ignoring from what I can tell! I was going to plug a crude fix into the processors to filter out the transparent colors to see if I could get that to go away, but wanted #509 finished first 😄.

**Comment by craftworkgames** [comment]
@stefanrbk Yeah no problem mate. I just wanted to raise the issue here so we didn't forget to look into it.

I'm not entirely certain what the solution is here. It could be that we simply decide not to support this type of transparency and in that case the work would be to update the demo.

On the other hand, if it's easy to fix and / or people actually care about this functionality then yeah, let's go ahead and fix it.

**Comment by stefanrbk** [comment]
When I was working on the processors, I found a color property. I'm going to check that out as the name is pretty cryptic to me. There has to be some way to implement it somehow! 😄

**Comment by stefanrbk** [comment]
#521 Done! 😉

**Comment by stefanrbk** [comment]
@craftworkgames this can be closed now that #521 is merged... :grin:

**Comment by craftworkgames** [comment]
Ah yes, so it is :grin:
