### ISSUE TITLE
[ECS] Screens as Systems

### ISSUE THREAD

**Issue by Trapov** [craftworkgames/MonoGame.Extended#534]
It's a bit opinionated feature request, but for me the `ScreenManager` class looks like a system and the `Screen` class like a component. If i want to use those with the ECS package, ofc i can implement them as a system and components (**1**).

```csharp

class ScreenSystem : ISystem
{
    private readonly ScreenManager _screenManager;
    ...
    ...
}

class HeroScreenComponent : GameScreen
{
    ...
    ...
    ...
}

```
**(1)**

The problem with the screen components – they expose to much and don't look like components at all.

Maybe create `ScreenSystem` as an abstract class and give consumers an easy way to implement screen systems?

**Comment by captkirk88** [comment]
**Note: I do not use MonoGame Extended's ECS, I used a forked version of Artemis and have no experience with this repo's version.** Screen systems should not be a part of a ECS.  That is the problem with ECS, it tends to be misunderstood that everything needs to be in it.  You can have things separate without any issues.  You would probably have a easier time rolling your own Screen system.  I don't think MonoGame Extended is meant to be all encompassing.

**Comment by craftworkgames** [comment]
First, let me just start by saying that there's a little bit of history at play here. The short version is that the Screens code was added to the library quite a while before the ECS. As I work through the library for version 2.0 I will be reconsidering how things fit together (if it makes sense to do so).

I agree that the `ScreenManager` is somewhat like an ECS `ISystem`.

However, I don't agree that a `GameScreen` is like an ECS component. Components in an ECS are usually  lightweight data objects that hold state about entities. Components are meant to be attached to entities. Entities are typically things in your game like players, fireballs and spawn points. Screens don't really fit that analogy in my opinion.

That said, I appreciate the feedback and I'll think about this some more as we move forward.

@captkirk88 I'm curious, which version of Artemis did you fork?

**Comment by Trapov** [comment]
> Screens don't really fit that analogy in my opinion.

@craftworkgames, yeah they most certainly do not. That's why I stated that:

> The problem with the screen components – they expose too much and don't look like components at all.

I just didn't know how to combine the two together, so I placed one in the components box. Felt weird to not include them in my ECS parts, altho screens ain't lightweight they do consist somewhat of a state and not so much logic.

**Comment by captkirk88** [comment]
@craftworkgames the latest master branch that I could pull which hasn't been updated in awhile though.  So far it has worked for me though.  To be honest, everyone uses a different style of handling game objects.  In my opinion, a ECS for MonoGame Extended doesn't exactly fit.  When I see MonoGame Extended, I think it is a more higher level API for creating graphics.  A helper for things like dealing with 3D Cameras and rendering.  To make life easier.  Not to organize game assets.  Just my 2 cents.

**Comment by craftworkgames** [comment]
> the latest master branch that I could pull which hasn't been updated in awhile though. So far it has worked for me though.

Just keep in mind that we've completely rewritten the ECS in the `develop` branch to fix a bunch of issues with the old ECS (among other things). If you're using the ECS I'd recommend using the new one.

**Comment by rafaelalmeidatk** [comment]
@Trapov You are giving ECS more responsibilities than it should have. Of course, you can do it, but maybe you should reconsider. Apparently, you are thinking that the ECS is created at the begin of the game and persists between the game screens, like the title screen, the options screen, the game screen, etc. But in fact, with these listed screens in mind, the ECS should only be used on the game screen that is where it is useful because this is the screen where you have *entities*, many entities, and these entities can receive components that have systems acting on them.

The other screens aren't like that, they have windows, inputs and all these GUI stuff that IMO aren't entities, they don't need components and systems acting on them. This is my opinion, you can use ECS on any screen, yeah, but I think that you are overthinking it and is using the right tool on the wrong place.

**Comment by Trapov** [comment]
@rafaelalmeidatk, i don't really know how would you do such thing in the current ECS implementation. Have you worked with the newest package? If you have then can you give me a small example of how to do so?

**Comment by Trapov** [comment]
@craftworkgames, i suppose this isn't an issue, but rather a discussion about the design. And since there's nothing really to do — better close the issue?

**Comment by craftworkgames** [comment]
>  And since there's nothing really to do — better close the issue?

Yes, let's do that.

**Comment by captkirk88** [comment]
@craftworkgames Is v1.1.0 the latest and greatest for the MonoGame.Extended.Entities?  Either the nuget package is broken and it is not including the basic classes like World or WorldBuilder or I got the wrong version.  I figure it is probably that I have the wrong version.

**Comment by captkirk88** [comment]
No problem, adding it as a project to my solution is the route I'm going to have to go regardless.
