### ISSUE TITLE
[Tiled] Accessing Tile Properties in a Normal Tile Layer

### ISSUE THREAD

**Issue by captainkidd5** [craftworkgames/MonoGame.Extended#537]
Just curious if there's a way to access a specific tile's ID. I know for object layers I'm able to access objects using something like 
```
    TiledMapObject[] objectLayer = MyMap.GetLayer<TiledMapObjectLayer>("Objects").Objects;
    foreach (var objl in objectLayer)
    {
        string type;
        objl.Properties.TryGetValue("type", out type);

        if (type == "WoodenPost")
            // Do something etc.
    }
    
```

But if I try the same thing with just a regular tile layer: 

```
    TiledMapTile[] tileLayer = MyMap.GetLayer<TiledMapTileLayer>("background").Tiles);
    foreach(var tile in tileLayer)
    {
        if(tile.GlobalIdentifier == 148)
        {

        }
    }
```

The first line errors. Anyone have a solution to this?

**Comment by craftworkgames** [comment]
> The first line errors. Anyone have a solution to this?

Can I ask what error you're getting?

Looking at the first line I can see an extra bracket at the end of the line. Is that the problem?

**Comment by captainkidd5** [comment]
Sure I'm getting this:
`cannot implicitly convert type "Systems.Collections.ObjectModel.ReadOnlyCollection<Monogame.Extended.Tiled.TiledMapTile>" to "Monogame.extended.tiled.tiledmaptile[]" `


Interestingly enough this works

` foreach (TiledMapTile tile in myMap.GetLayer<TiledMapTileLayer>("Buildings").Tiles)
            {
                allTiles.Add(tile);`

Maybe a bit off topic, but I'm having a lot of trouble with using the Depth parameter when rendering individual tiledmap layers. It seems that the depth parameter doesn't do anything, and that draworder is determed by which layer is drawn first, regardless of the depth argument. Sprites drawn using spritebatch also disregard the layers and are always drawn on time of them, also strange. Here's my code for that:

`public override void Draw(GameTime gameTime, SpriteBatch spriteBatch, TiledMapRenderer renderer)
        {
            
           

            if (player.Health > 0)
            {
                spriteBatch.Begin(SpriteSortMode.FrontToBack, transformMatrix: cam.GetViewMatrix());
                
                

                renderer.Draw(backGround, cam.GetViewMatrix(),depth: (float).1);

                player.anim.Draw(spriteBatch, new Vector2(player.Position.X, player.Position.Y), (float).3);

                renderer.Draw(buildings, cam.GetViewMatrix(), depth: (float).2);
                renderer.Draw(midGround, cam.GetViewMatrix(), depth: (float).4);
                renderer.Draw(foreGround, cam.GetViewMatrix(), depth: (float).5);
                renderer.Draw(alwaysFront, cam.GetViewMatrix(), depth: (float).6);
`

**Comment by craftworkgames** [comment]
> Sure I'm getting this:
cannot implicitly convert type "Systems.Collections.ObjectModel.ReadOnlyCollection<Monogame.Extended.Tiled.TiledMapTile>" to "Monogame.extended.tiled.tiledmaptile[]"

Probably a bit late to answer this now but I think adding `.ToArray` would solve this one.
