### ISSUE TITLE
Demo for TiledMap is missing

### ISSUE THREAD

**Issue by mo-norant** [craftworkgames/MonoGame.Extended#539]
[This link is missing](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Demo.TiledMaps/Content/Content.mgcb)

A decent tutorial for the TiledMap is missing. I can't get it to work. Could please someone help to make an multilayered.

**Comment by stefanrbk** [comment]
> multilayered

are you referring to a map with group layers?

**Comment by craftworkgames** [comment]
There's a Tiled Maps demo here: https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Features/Demos/TiledMapsDemo.cs
