### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by killerrin** [craftworkgames/MonoGame.Extended#54]
How would we feel about adding in a Timer Class? Its something that MonoGame doesn't have, and something that every Game Dev ends up having to create in all of their projects. 

I have two timers which I would be willing to add to the project, I made it a couple months ago for a MonoGame 'Game Engine' which I used in my Capstone Project which I think could fit this bill perfectly

Timer - https://github.com/KillerrinStudios/Anarian-Game-Engine-MonoGame/blob/master/Anarian%20Game%20Engine.Shared/DataStructures/Timer.cs
Clock - https://github.com/KillerrinStudios/Anarian-Game-Engine-MonoGame/blob/master/Anarian%20Game%20Engine.Shared/DataStructures/ContinuousClock.cs

The Timers themselves are event based, so once you set them up all you have to do is call the Update on them to update the time and once the Timer hits its goal (Timer counts down to 0 and Clock reports every x seconds), it fires off the Completed Event to let you know

**Comment by craftworkgames** [comment]
I've used similar timers before in previous projects. They could be helpful.

I'd be hesitant about calling them `Timer` though. There's already `System.Timers.Timer` and `System.Threading.Timer` in the BCL. Another `Timer` class could get confusing.

As a side note: I also think there might be some bugs in the way MonoGame calculates frame times for the Update method. It's intended to run at 60 fps and always seems to return the same value, but I don't think they are accumulating the time properly. There's an [old artice](http://gafferongames.com/game-physics/fix-your-timestep/) about time-stepping that did the rounds a few years ago. Not sure how true it is though.

**Comment by killerrin** [comment]
Alright, I'll submit a pull request

**Comment by killerrin** [comment]
Alright, I'll submit a pull request
