### ISSUE TITLE
[Input] International Keyboard

### ISSUE THREAD

**Issue by gktval** [craftworkgames/MonoGame.Extended#540]
Does anyone have a solution for international keyboards. I was doing some testing before I release my game and someone had a qwertz keyboard, so they had to use alt+V to use @ instead of the normal shift+2.  I'd prefer not to use windows messages since this game in cross-platform. Any help would be appreciated. Thanks

**Comment by stefanrbk** [comment]
I did a quick Google search, and [this](https://code.msdn.microsoft.com/windowsdesktop/Changing-Keyboard-Layout-d50b27da) looks promising if anyone wants to take a look.

**Comment by gktval** [comment]
As far as I can see, that is just a code snippet. I have no idea where the InputLanguage class is. Glanced at the codeproject link, doesn't seem like it is very complete. Some of the snippets referred use user32.dll, which would strictly be for windows users.

**Comment by gktval** [comment]
I posted the same question on the MG community forum. All I can figure out is to use Game.Window.TextInput event handler, which will get me half way there. Then manually code ctrl/alt +key for all the major keyboard layouts to get the special characters like @,[],{},<>,#, etc.

**Comment by stefanrbk** [comment]
Now that I have more time to look at it, `InputLanguage` is part of `System.Windows.Forms`, so I agree we should look at doing it a different way. I was looking for a strictly .NET core approach and i'm not seeing a decent solution.  I think we should add something to the `Monogame.Extended.Input` library to determine the language of the keyboard. We could add a keycode to get the physical key location on the keyboard or a translation method to change the input around. I think this is something we need, but I'm not sure how we should do it. @craftworkgames, what are your thoughts on it?

**Comment by gktval** [comment]
I did look at the option of using Game.Windows.Textinput event. That looked at the characters being type and worked correctly for the majority of the QWERTY, QWERTZ, and AZERTY keyboards. It also worked for the special characters underneath the numerical buttons. However, it did not work with the AltGr + [key] commands. Finally, the event did not work with Android as it gave me a TypeLoadException to the TextInputArgsEvents.

**Comment by craftworkgames** [comment]
> what are your thoughts on it?

Honestly, this is not really an issue I've ever had a need for myself. If it's something you guys need I'm fine with having it in the library as long as it doesn't add too much complexity.

We certainly don't want to have a dependency on `System.Windows.Forms` if we can help it. I mean, there are ways we could do it but obviously it would only work on Windows that way so getting it to work under .NET Core is the preferred approach.

This feels like one of those problems that might have to have some platform specific wrapper code. MonoGame does this kind of thing all the time. It's a tricky problem and not something we've had to deal with in Extended yet. Testing and keeping things working on all platforms can be a huge pain.

**Comment by Apostolique** [comment]
This whole keyboard problem will be fixed in MonoGame 5.0 eventually. We don't have much info about when it will be released though.

**Comment by Ellpeck** [comment]
I think a good solution to this problem would be the ability to toggle between the current underlying input querying system, which uses the fixed (what I assume is American) keyboard layout, and a system using `Window.TextInput`. That way it would still be cross-platform compatible and it would also work automatically with different keyboard layouts if desired.

**Comment by gktval** [comment]
@Ellpeck If you read above, Windows.TextInput is not cross-platform.

**Comment by Ellpeck** [comment]
That's why I'm saying it should be optional, though. If you're building a game for an operating system that it doesn't work with, you could just not enable it. It's also not actually linked to anything that inherently isn't cross-platform, it just doesn't work on some platforms.

**Comment by craftworkgames** [comment]
Thinking about this a bit more and my feeling is that it would add quite a lot of complexity to support. 

Generally speaking, I'd prefer to keep the cross-platform specific issues in MonoGame and have Extended leverage what it can do.

So until MonoGame has better support for it, we won't be supporting it in Extended.
