### ISSUE TITLE
Upcoming major release prerelease package

### ISSUE THREAD

**Issue by gandhibobandhi** [craftworkgames/MonoGame.Extended#546]
Hi, I was trying to follow the examples in the source for a while without realising there are some major differences between the current `develop` branch and the latest nuget release for `MonoGame.Extended.Gui`. Also worth noting that `develop` is the default branch which is selected when coming to the project's github page.

As i'm starting a new project, I would rather code around a prerelease package that includes the new changes as opposed to the current version which will apparently change significantly in the next release. Would it be possible to publish the current `develop` branch as a prerelease package on nuget.org?

Thanks,
Adam

**Comment by craftworkgames** [comment]
I don't publish the pre-release packages to nuget.org but there are a few options.

1. If you can build the source code locally, you can also build the NuGet packages yourself. Just run the `build.ps1` PowerShell script and the [cake script](https://cakebuild.net/) will automatically build the packages for you. You don't even need to download cake yourself, this is built into the PowerShell script.

2. Every commit and pull request is built by our [build system](http://build.craftworkgames.com/guestLogin.html?guest=1). On here there's also [a NuGet feed](http://docs.monogameextended.net/NuGet-Pre-Release/) that you can use to access the pre-release packages

3. Of course, you can always just reference the source code directly in your project. This is useful if you want to make changes to Extended and maybe submit a PR back. 

I hope this helps.

Cheers.
