### ISSUE TITLE
An error occurred when I wanted to save the scene as json

### ISSUE THREAD

**Issue by esengine** [craftworkgames/MonoGame.Extended#549]
```C#
           var skinService = new SkinService();
            var serializer = new GuiJsonSerializer(SceneView.Instance.Content)
            {
                Converters =
                {
                    new SkinJsonConverter(SceneView.Instance.Content, skinService),
                    new ControlJsonConverter(skinService)
                },
                NullValueHandling = NullValueHandling.Ignore,
                DefaultValueHandling = DefaultValueHandling.Ignore
            };

            using (var streamWriter = new StreamWriter(saveFileDialog.FileName))
            {
                using (var writer = new JsonTextWriter(streamWriter))
                {
                    serializer.Serialize(writer, SceneView.Instance.System.ActiveScreen);
                }
            }
```

This is my serialization code, and an error occurred while executing this sentence.

```C#
serializer.Serialize(writer, SceneView.Instance.System.ActiveScreen);
```

Error message: Newtonsoft.Json.JsonWriterException:“Token PropertyName in state Property would result in an invalid JSON object. Path 'content'.”
![image](https://user-images.githubusercontent.com/18465053/45800520-b9774680-bce3-11e8-9a43-05a6e3c88e26.png)

I haven't used json serialization, I don't know why this is causing such a result, can you help me how to solve this problem?

@craftworkgames

**Comment by esengine** [comment]
![test1](https://user-images.githubusercontent.com/18465053/46208560-b45a6d00-c35d-11e8-8a8c-21f9577c4c55.gif)

I made an editor for this ui, only serialized, I don't know how to save this scene. Can you tell me what is a good way?

**Comment by craftworkgames** [comment]
> Can you tell me what is a good way?

As I mentioned above, there is no way to do this without implementing a lot of changes to the serialization code. 

If you want to do this yourself you're welcome to fork the project and have a go. The [JSON.NET documentation](https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm) is very good.

**Comment by esengine** [comment]
Ok, I think I should try to do this, hope that I can complete it successfully, maybe my code is not very standardized, I hope to be able to merge into the project. I will try my best to get the job done.

**Comment by craftworkgames** [comment]
@esengine If you manage to get this done please submit a pull request.
For now though, I'm going to close this issue (just trying to do a little clean up around here).
