### ISSUE TITLE
Adding images and logo to README

### ISSUE THREAD

**Issue by WardBenjamin** [craftworkgames/MonoGame.Extended#55]
I have found that the easiest way to serve images is by placing a copy inside of the gh-pages branch, and serving it via github pages (we can also do this with Markdown-formatted text, or HTML). I have done this on my branch, and will add a logo to the README in the master branch using this if/when my gh-pages branch is merged into the one here.

Here's a usage of this, if I'm not being too clear: http://www.jefclaes.be/2012/04/add-images-to-github-readme.html

**Comment by WardBenjamin** [comment]
I just tried to open a pull request for this purpose, but it seems that I cannot since there's no gh-pages branch already here. Could you push a copy of master to gh-pages @craftworkgames?

**Comment by craftworkgames** [comment]
> I have found that the easiest way to serve images is by placing a copy inside of the gh-pages branch, and serving it via github pages

What problem are we trying to solve here?

If it's getting the logo image in the readme I think the *easiest* solution is to just link it directly out of the master repository.

    ![example](https://raw.githubusercontent.com/craftworkgames/MonoGame.Extended/master/Logos/logo-banner-800.png)

![example](https://raw.githubusercontent.com/craftworkgames/MonoGame.Extended/master/Logos/logo-banner-800.png)

In the future I might consider making a `gh-pages` branch to host documentation or something but I'm not going to do that simply to serve a logo for the readme.

**Comment by WardBenjamin** [comment]
Fair enough, I'll change it to be so. The advantage of the gh-pages branch is that it's very easy to set up and ignore; that way the logos, docs, and other things don't need to be versioned in the regular repository along with the code, dependencies, and other things.

**Comment by craftworkgames** [comment]
> The advantage of the gh-pages branch is that it's very easy to set up and ignore

Yes it is. It's also very easy to setup and go unnoticed. I kind of like the idea that the repository makes it clear to new users that we have logos and documentation. It also makes it really simple to get started.

I'm not saying I'm completely opposed to the idea. Adding logos and other crap grows the repository size which is a bad thing. However, it's currently the logos only take up about 100KB so I can live with that.
