### ISSUE TITLE
Bitmap fonts and files have to be in the Content root directory or they will just not load

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#56]
I got an email this morning with a nice compliement from @Gixen :smile: 

> [Community | MonoGame] [PM] Awesome extensions and bugs?
> 
> to dylan 
> from Gixen
> September 17
> Hi! I just started using MonoGame.Extended and it's awesome. Well, sofar i've only used the bitmap  class but anyway. However, it seem no matter how i build it in the content pipeline, the bitmap fonts and files has to be in the content root directory or they will just not load.

> Otherwise, keep up the good work!

> To respond, visit http://community.monogame.net/t/awesome-extensions-and-bugs/6330/1 in your browser.

For some reason the link to the topic at the bottom of the email doesn't work.

> Sorry, you don't have access to that topic!

Anyway, I thought I'd raise it as a bug here for further investigation.

@Gixen Do you have any more details you'd like to add? How are you trying to setup the Content directory?

**Comment by WardBenjamin** [comment]
I have no evidence for this since I haven't looked into this in much detail, but I bet it has something to do with the fact that there are two files, and that they aren't being looked for in relation to each other, but rather just in the root directory.

**Comment by craftworkgames** [comment]
> but I bet it has something to do with the fact that there are two files, and that they aren't being looked for in relation to each other, but rather just in the root directory.

I suspect you're right but to fix it we need to reproduce it first. 

The relevant bits of code would be the [BitmapFontReader](https://github.com/craftworkgames/MonoGame.Extended/blob/master/Source/MonoGame.Extended/BitmapFonts/BitmapFontReader.cs) and the [BitmapFontProcessor](https://github.com/craftworkgames/MonoGame.Extended/blob/master/Source/MonoGame.Extended.Content.Pipeline/BitmapFonts/BitmapFontProcessor.cs).

It's currently stripping the path out of the file like this:

    var assetName = Path.GetFileNameWithoutExtension(fontPage.File);

Which would be loosing information.

We'd have to do some experiments with [BMFont](http://www.angelcode.com/products/bmfont/) to see how the paths are saved to the file when they are not directly in line with the texture.

**Comment by Gixen** [comment]
I really should check my email better, this response-chain went right into the spamfolder. =P
I just used the default directory setup, creating folders through the pipeline manager.

**Comment by craftworkgames** [comment]
> I just used the default directory setup, creating folders through the pipeline manager.

Good to know. Did you have both files in the same folder? There's 2 test cases I can think of that we should consider.

The first is when both files are in the same sub-folder:

	- Content
		- SubFolder1
			- font-file.fnt
			- font-file_0.png

And the second is when the files are in different sub-folders. I'm not sure if this is likely to actually  happen in the real world though.
			
	- Content
		- SubFolder1
			- font-file.fnt
		- SubFolder2
			- font-file_0.png

**Comment by Gixen** [comment]
Both in the same folder.

**Comment by craftworkgames** [comment]
@Gixen I think I've fixed this now. If you want to test it you can reference the development NuGet package directly from our build server:

http://build.craftworkgames.com/guestAuth/app/nuget/v1/FeedService.svc/

Or just download an development build from github.

I haven't quite finished the testing so I'll leave this issue open for now.

**Comment by Gixen** [comment]
Cool, i'll test it tomorrow after work.

**Comment by Gixen** [comment]
So, i saw there was a new build, alpha 3.44 and i tested with that build, but it still didnt work. I followed the exception and it was still looking for it in the content root. Or should i test direcly with a downloaded dev-build?

**Comment by craftworkgames** [comment]
Sorry I've been pre-occupied for a couple of days. I should have explained it a bit clearer.

You'll need to add that URL to your Packages Sources in Visual Studio options.

![image](https://cloud.githubusercontent.com/assets/3201643/10221006/b96281e8-688e-11e5-9c3f-389faf53ed52.png)

Then when you update the package you'll need to make sure you've selected the correct package source from the drop down at the top. Be sure to check the Include Pre-release box.

![image](https://cloud.githubusercontent.com/assets/3201643/10221054/269c8902-688f-11e5-833a-8c272755bd1a.png)

These screenshots are from VS2015 but hopefully they make it clear.

The latest version (as of these screenshots) is v0.4.7

Alternately, you can try downloading the [package directly](http://build.craftworkgames.com/repository/download/MonoGameExtended_CI/486:id/MonoGame.Extended.0.4.7.nupkg)

**Comment by Gixen** [comment]
Well, now i know how to add more package sources =D

**Comment by Gixen** [comment]
Made a new project with the latest stable, added bitmapfonts to a new folder, tried running it.
![testing font](http://i.imgur.com/cubLUJC.png)

**Comment by craftworkgames** [comment]
Well I don't speak German but with a little help from google translate I can see that it could not find the file.

This could be caused by a few things. 
 - Have you made sure the file actually exists at that location? 
 - Does the Pipeline tool have any errors? 
 - Have you made sure the Pipeline is referencing the correct version of the DLL in the `Content.mgcb` file? 
 - Are you putting the correct path to the file in the `Content.Load` call?  It should be something like `"Subfolder/bitfont_thickoutline"`
 - What happens if you try to load another asset from that location (e.g. a `Texture2D`)?

Take a look at the [Sandbox](https://github.com/craftworkgames/MonoGame.Extended/tree/master/Source/Sandbox) project. It's currently loading the `courier-new-32.fnt` from a folder called `Fonts`.

    _bitmapFont = Content.Load<BitmapFont>("Fonts/courier-new-32");

Cheers

**Comment by Gixen** [comment]
It's swedish ;)
Well, shit. 
I forgot to put in the correct filepath. =D

Issue solved!

**Comment by craftworkgames** [comment]
Wonderful! :smile:
