### ISSUE TITLE
Platformer demo physics PR for dynamic bodies and a question about contribution

### ISSUE THREAD

**Issue by zoeysaurusrex** [craftworkgames/MonoGame.Extended#560]
Good morning,

Allow me to say that this project is awesome! I've been using the dotnet core fork and it's working like a charm. I created a PR to handle a TODO in the World.cs of the Platformer demo to deal with dynamic body to dynamic body resolution:

https://github.com/craftworkgames/MonoGame.Extended/pull/559

Firstly, I hope I'm conforming to internal standards, but I also wanted to offer help. In my own project, I support a few additional use cases and I wanted to see if this project could use them. Some of those use cases are as follows:

- Supporting event handlers in the Body so that parent objects could choose to cancel or allow the collision (This is based on the same idea behind Unity collision triggers, aka, we wanna know it happened but not actually collide)

- Enabling a "physics material" type of construct. I'm attach these to the body so that collision resolution can take into account things like friction and bounciness.

Is any of that useful? I'm a few days out from finishing up those use cases on my own, and I'd be happy to contrib them back here.

**Comment by craftworkgames** [comment]
I think these are good ideas. We've just have to be careful, particularly with using event handlers that we don't accidentally create memory leaks. Designing a good API around this stuff can be quite a challenge.

**Comment by zoeysaurusrex** [comment]
That's a good callout. I'm sure there are also other ways to accomplish triggering collisions versus event handlers.
