### ISSUE TITLE
[Documentation] MonoGame.Extended does not reflect latest stable tag

### ISSUE THREAD

**Issue by wacharlb** [craftworkgames/MonoGame.Extended#571]
It appears that the documentation for MonoGame.Extended located at http://docs.monogameextended.net/ does not reflect any sort of stable version of MonoGame.Extended including the latest tagged version v1.1.0 in NuGet. In fact, this documentation appears to reflect the latest development commit version (unstable). However, this is difficult to verify without digging into the Git commit history since there is no version information attached to the documentation on the above URL. Moreover, the v1.1.0 stable version's documentation that can be built an run locally is minimal at best and provides a minimal guide for proper use of the library. I would respectfully suggest not to put out the documentation for prerelease software that obscurely advertises itself as being stable and/or tagged software. At the very least it should reference what version of the library is being documented for clarity.

**Comment by craftworkgames** [comment]
Hi @wacharlb 

I understand your concern and you're completely correct. The docs are not in a great state at the moment.

Unfortunately, to get all of the problems sorted there's going to need to be significant effort involved. I'm not currently in a position to dedicated any time to this problem. Like most projects of any decent size there's always lots of things we could be spending out time on. Documentation is not currently at the top of the list.

At some point I do plan to dedicate some time to solving these problems and I always appreciate any input from the community. I'd love to hear your thoughts on how we can do better in this area.

That said, this is open source. If you or someone else is willing to help then things move faster. I'd love it if we had more resources on this problem.

**Comment by AristurtleDev** [comment]
Documentation site has been updated for installation pages to indicate the current version that should be installed.
