### ISSUE TITLE
[Entities][branch:develop] Remove WorldBuilder, Publicize World instance methods

### ISSUE THREAD

**Issue by captkirk88** [craftworkgames/MonoGame.Extended#576]
WorldBuilder currently has a very limited function in the develop branch.  I think it is redundant considering World#RegisterSystem doesn't do anything particularly heavy that would require it to be restricted.  Having the ability to add systems and remove them at the programmers discretion should be considered.

Adding a way to get all components related to a entity would also be nice.  I did that in my own version but have not tested the performance implications.  It involved modifying the abstract ComponentMapper to contain a abstract Get method and adding the below method to ComponentManager
```csharp
        public IEnumerable<object> GetComponents(int entityId)
        {
            for (var componentId = 0; componentId < _componentMappers.Count; componentId++)
            {
                var mapper = _componentMappers[componentId];
                if (mapper?.Has(entityId) ?? false)
                {
                    yield return mapper.GetComponent(entityId); //GetComponent being a protected internal method in the abstract ComponentMapper class
                }
            }
        }
```
If there was a interface for Components themselves, this method could return a interface of IComponent.  But that could be considered redundant since you expect a component object regardless.

**Comment by captkirk88** [comment]
Oh and a World#Initialize method would need to be added to accommodate shifting `system.Initialize(this)` in World#RegisterSystem.

**Comment by captkirk88** [comment]
Crap I am missing some more items that would need to be addressed for that change.

In the World constructor
```csharp
            RegisterSystem(ComponentManager = new ComponentManager());
            ComponentManager.Initialize(this);
            RegisterSystem(EntityManager = new EntityManager(ComponentManager));
            EntityManager.Initialize(this);
```

**Comment by craftworkgames** [comment]
I've read through your proposed changes but you've failed to answer the most important question. 
Why? 

> WorldBuilder currently has a very limited function in the develop branch. I think it is redundant considering World#RegisterSystem doesn't do anything particularly heavy that would require it to be restricted.

The purpose of the world build is to ensure that all of the systems and created and registered *before* the world.

> Having the ability to add systems and remove them at the programmers discretion should be considered.

I think you might be underestimating how complicated this change might be. It would certainly make some of the performance optimizations more difficult and again.. why?

> Adding a way to get all components related to a entity would also be nice.

Why do you need this?

> If there was a interface for Components themselves, this method could return a interface of IComponent. 

Again, why? Having an `IComponent` interface doesn't actually make anything better. In fact, it adds a new restriction that all component must implement the interface. This is a problem if you want to use a class from a library that you didn't write as a component on your entity.

**Comment by captkirk88** [comment]
1.  The issue I have with WorldBuilder is that I need to be able to add/remove systems based on certain criteria that may happen.  A unrelated but valid example could be special circumstance systems for processing a specific set of world wide entities, like a random world event that is processed through a system.

2.  For serializing the components to a save.

3.  You got a point.  I managed to add that functionality in to mine with a extension method that doesn't remove the original design.

I'm closing this though because it was mainly a suggestion and seems like you are reserved about letting the developer manage the performance implications of more advanced/useful features.

**Comment by craftworkgames** [comment]
> seems like you are reserved about letting the developer manage the performance implications of more advanced/useful features.

Just to be clear, I'm not opposed to change. I'm just having a hard time understanding how these changes would help with anything. In fact, adding and removing systems at run-time is more likely to have a negative effect on performance because the garbage collector would kick in more often. A lot of the existing optimizations are designed to prevent exactly that from happening.

To do what you're asking I recommend using a flag inside the system to early exit if it doesn't need to do anything. This should provide the best possible performance balance between CPU cycles and memory management.

Last but not least.. the design we've used is actually based off the very fast [artemis-odb java framework](https://github.com/junkdog/artemis-odb/wiki/World). Many of the same optimizations apply to C# but I was quite careful to consider the differences between how the Java and .NET garbage collector works.

**Comment by captkirk88** [comment]
I have used artemis-odb, it is indeed the fastest ecs I have ever seen.  I have struggled to find one of similar performance in C#.  Even with artemis-odb I had to do some funky work around with the WorldBuilder, like recreating the world, including 50,000 entities, if I had to add a system.  Luckily, even that was extremely fast.

**Comment by captkirk88** [comment]
For the .Net GC, I would recommend taking full advantage of "No GC regions".  And the Large Object Heap compaction to CompactOnce.

```csharp
System.Runtime.GCSettings.LargeObjectHeapCompactionMode = 
                System.Runtime.GCLargeObjectHeapCompactionMode.CompactOnce;
```

As well as enabling SustainedLowLatency mode.
```csharp
System.Runtime.GCSettings.LatencyMode = System.Runtime.GCLatencyMode.SustainedLowLatency;
```
