### ISSUE TITLE
Entity can't be retrieved on OnEntityRemoved

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#577]
If I use this following code on an `EntityProcessingCode`:

    protected override void OnEntityRemoved(int entityId)
    {
        var entity = GetEntity(entityId);
    }

`entity` will be `null`, I don't know what it was or what component it had before being removed. I solved this problem by moving [this line](https://github.com/craftworkgames/MonoGame.Extended/blob/dbc57e0f8acd8d9635c65f11b3ce40b7603670b1/Source/MonoGame.Extended.Entities/EntityManager.cs#L109) to the top of the method. I am not sure if this is the best solution.

**Comment by craftworkgames** [comment]
>  I solved this problem by moving this line to the top of the method.

That seems like a reasonable solution to me. I can't think of any obvious reason why it would break anything. 

Do you want to submit a PR for the change?
