### ISSUE TITLE
Demo project template throwing Sdl-related error

### ISSUE THREAD

**Issue by mathshane** [craftworkgames/MonoGame.Extended#578]
Using MonoGame 3.7.1.189

Upon adding the demo project template to my Visual Studio 2017 templates, I'm getting this error when trying to first run. Note that I don't get this error when manually adding MonoGame.Extended to my project.

> Exception thrown: 'System.TypeInitializationException' in MonoGame.Framework.dll
An unhandled exception of type 'System.TypeInitializationException' occurred in MonoGame.Framework.dll
The type initializer for 'Sdl' threw an exception.

**Comment by craftworkgames** [comment]
Thanks for reporting this issue.

**Comment by lithiumtoast** [comment]
Closing as it is related to MonoGame specifically and is most likely already fixed in the upcoming 3.8 release. If you are still experiencing the problem, please let us know.
