### ISSUE TITLE
mobile(android/ios) BitmapFont error

### ISSUE THREAD

**Issue by bluesabi** [craftworkgames/MonoGame.Extended#582]
Hi
I have a question

vs2017
monogame 3.7.1
monogame.Extended install nuget

Document reporting.
Create fonts
Add to Content.mgcb
Add dll
/reference:..\..\packages\MonoGame.Extended.Content.Pipeline.1.1.0\tools\MonoGame.Extended.Content.Pipeline.dll
build

android BitmapFont test
font load ...

font = Content.Load <BitmapFont> ("font / tfont");

error
Microsoft.Xna.Framework.Content.ContentLoadException: Could not find ContentTypeReader Type. Please provide the name of the assembly that contains the assembly type in the full name: MonoGame.Extended.BitmapFonts.BitmapFontReader, MonoGame.Extended (MonoGame.Extended.BitmapFonts.BitmapFontReader, MonoGame.Extended)

The spritefont works well.

What should I do more?
Is not mobile supported?
(android / ios)

**Comment by Apostolique** [comment]
In the file where you do `font = Content.Load ("font / tfont");` have you tried also adding `using MonoGame.Extended.BitmapFonts;`?

**Comment by craftworkgames** [comment]
> Microsoft.Xna.Framework.Content.ContentLoadException: Could not find ContentTypeReader Type. Please provide the name of the assembly that contains the assembly type in the full name: MonoGame.Extended.BitmapFonts.BitmapFontReader, MonoGame.Extended (MonoGame.Extended.BitmapFonts.BitmapFontReader, MonoGame.Extended)

This error indicates that the `Content.Load<BitmapFont>` method it can't find the DLL containing the `BitmapFontReader` type.

The most likely cause is that the `MonoGame.Extended.dll` hasn't been copied to the output directory during compile for some reason. Although, I'm not sure why that would be but it might give you a hint where to start looking.

As far as I'm aware, there's no reason why the DLL wouldn't load on mobile devices but I have't tested this extensively myself.
