### ISSUE TITLE
Interfaces for a cleaner design and more flexibility

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#59]
I've been thinking about this for a while. I think it's time we talked about creating some interfaces for common methods and properties.

## Updating

The first one is to cover the reuse of an `Update` method so that many *updatables* can be added to a collection of `List<IUpdate> _updatables`. Something like this:

    public interface IUpdate
    {
         void Update(GameTime gameTime);
    }

Personally I've never been a huge fan of `GameTime`. I'd rather just pass around a `float deltaSeconds` in most cases because it makes the class reusbale outside MonoGame / XNA. Most people that using MonoGame seem to like `GameTime` so I guess I can live with that.

Unfortunately, the framework already contains an interface called [`IUpdatable`](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.iupdateable_members.aspx) that looks like this:

```
  public interface IUpdateable
  {
    bool Enabled { get; }
    int UpdateOrder { get; }
    event EventHandler<EventArgs> EnabledChanged;
    event EventHandler<EventArgs> UpdateOrderChanged;
    void Update(GameTime gameTime);
  }
```

The problem with the `IUpdatable` interface is that it has too much going on. A lot of the time when you want to implement an `Update` method you don't need or want the other crap. Particularly `UpdateOrder`. Using this interface makes it more complicated to implement the class and IMHO doesn't add a lot of value.

Of course, there's no reason why a class couldn't implement both interfaces.

## Drawing

Similarly to the updating I propose we have a simpler `IDraw` interface.

    public interface IDraw
    {
        void Draw(GameTime gameTime);
    }

This would be the sibling on the [`IDrawable`](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.idrawable_members.aspx) interface from the framework.

## Common Properties

I also think there's a few property based interfaces that are helpful.

    public interface IRotatable
    {
        float Rotation { get; set; }
    }

    public interface IMovable
    {
        Vector2 Position { get; set; }
    }

    public interface IScalable
    {
        Vector2 Scale { get; set; }
    }

    public interface ITranfromable : IMovable, IRotatable, IScalable
    {
    }

    public interface IColorable
    {
        Color Color { get; set; }
    }

The benefit of breaking these up into one interface per property is that we can write nice extension methods, for example in an Animation library you might have some extension methods like this:

    public void MoveTo(this IMovable movable,  Vector2 position);
    public void RotateTo(this IRotatable rotatable, float angle);
    public void ScaleTo(this IScalable scalable,  Vector2 scale);
    public void FadeTo(this IScalable colorable,  Color color);

Then these methods become available on any class that have the respective properties. The class can pick which of the properties it wants and leave out the others. For example, it's common to have `Position` and `Rotation` without scale or color.

## Naming conventions and clashes

I think the advantages of having interfaces like these is clear but [naming them is hard](http://martinfowler.com/bliki/TwoHardThings.html). The names I've proposed above are okay, but they could also be called `IMove`, `IRotate`, `IScale` and `IColor` or something else.

One concern is that game developers trying to use MonoGame.Extended in an existing project might end up with name clashes if they already have similar interfaces defined. Although, we may not be able to do anything about that unless we pick obscure names which I'd really rather avoid.

Thoughts?

**Comment by cupstudio** [comment]
> I'd rather just pass around a float deltaSeconds in most cases

I do the exact same thing in my framework... why should I have to recalculate and cast to a float for nearly every single object in the game?

**Comment by craftworkgames** [comment]
I've created a bunch of these interfaces discussed here.

Currently the interfaces are passing around `GameTime`'s but it still bothers me that we don't just pass around `deltaSeconds`. I was thinking as an alternative we could add an extension method to `GameTime` like this:

    public static float GetElapsedSeconds(this GameTime gameTime)
    {
        return (float) gameTime.ElapsedGameTime.TotalSeconds;
    }

And it could be used like this:

    var deltaSeconds = gameTime.GetElapsedSeconds();

What do you think?

**Comment by cupstudio** [comment]
I actually like that quite a lot - I think it's a great solution and keeps things in the MonoGame flavor (using `GameTime` in Update).

I have a followup question prompted by the `IDraw` interface.

I've been using `Draw(SpriteBatch spriteBatch)` for my drawable classes.

I remember seeing somewhere (granted, this was very early on in my MonoGame experience) that reducing the number of SpriteBatches can be very helpful for performance.  This of course depends on what you are drawing and how often the same texture would be used.  As a result, I've taken to generally passing around a single spriteBatch most of the time, and very strongly avoid doing many calculations or creating new vars in the Draw() phase as those are high priority for speed.

Do you think there is any value in this approach, or does creating multiple new batches each loop have little to no impact?

**Comment by craftworkgames** [comment]
> Do you think there is any value in this approach, or does creating multiple new batches each loop have little to no impact?

There's certainly some performance concerns having many sprite batches. Although, in my experience the worst thing you can do on a modern GPU is switch textures too often. If you look deep into the implementation (if my memory serves me) of how a `SpriteBatch` works you'll find that when it renders a sprite from a different texture, it actually stops the current batch and starts a new one internally.

> and very strongly avoid doing many calculations or creating new vars in the Draw() phase as those are high priority for speed.

A handful of calculations won't hurt. As a general rule, MonoGame is already doing a lot of calculations and creating a lot of variables during the `Draw` calls. Adding a few more isn't going to make a lot of difference.

All that said, when you're optimizing for stuff like this you've got to consider the pros and cons. Having a handful of sprite batches won't make a lot of difference. I'd say you could easily get away with a few dozen in every `Draw` call. So I wouldn't panic about "just having one".

There are of course some very good reasons to have multiple sprite batches. For one, you can render some nice effects by using layers and you can apply different transforms to each batch. For example, you might want the foreground batch to not be affected by the camera; to show a HUD or GUI over top of the game.

And the last thing to remember is *why* are you optimizing. Does your game already run nicely at 60fps? If so then, don't bother spending bucket loads of time optimizing things. It's just a waste.

**Comment by craftworkgames** [comment]
I implemented the [`GameTime` extension](https://github.com/craftworkgames/MonoGame.Extended/commit/6b42a15ab388a8e705e32513035ec8f7aeec43f6). It seems nice.

**Comment by cupstudio** [comment]
Awesome!  Thanks for taking the time to add some of that insight.  Right now I am working on updating my forms framework to fully rely on MGE for anything it can so that I can remove a lot of the duplicated functionality.  I will probably continue sharing SpriteBatches for things like buttons and other small controls.  When it comes to scrolling those controls obviously need to start a new SpriteBatch in order to use Scissor Rectangles.
