### ISSUE TITLE
Is there a Segment2 to Segment2 intersection method?

### ISSUE THREAD

**Issue by 7sharp9** [craftworkgames/MonoGame.Extended#590]
Segment2 seems to have a bounding box intersection but I can't seem to find Segment / Segment intersection.  Maybe I missed it?

**Comment by craftworkgames** [comment]
It would seem that nobody has ever implemented it.

Would you care to do it yourself and make a PR?

**Comment by craftworkgames** [comment]
> Which class would be optimal for this?

Yeah, I mean many libraries implement some sort of static helper classes for these kinds of things. After all they tend to all be pure functions (similar to a `Math` library) and they don't really belong on the "shape" classes themselves.

For example, LibGDX has a static class called [`Intersector`](https://libgdx.badlogicgames.com/ci/nightlies/docs/api/com/badlogic/gdx/math/Intersector.html) that does these kinds of things.

I'm not too concerned where the actual algorithms come from. They tend to be readily available in books and so forth. 

They main thing I'm looking for is a nice clean consistent API that fits the rest of the library. For example, we strictly are following the [C# naming guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines).

Oh and one last thing.. returning `null` from these low level math libraries can have a negative performance impact [due to boxing](http://mdfarragher.com/2017/10/30/boxing-and-unboxing-in-csharp/). 

The pattern I've seen most often is to have these methods return a `bool` to indicate an intersection has occurred and have an `out` parameter with the intersection details.

**Comment by 7sharp9** [comment]
Im consuming from F# so in this case the F# compiler converts the out's to a tuple:

```fsharp
match Intersect(box, line) with
| (true, intersectionPoint) -> //do stuff with intersection point
| false -> //do something now the intersection failed
```

**Comment by lithiumtoast** [comment]
@7sharp9 We can just adapt from ray intersection for a bounding box. It's practically identical.

```
// Segment2.cs
...
    public bool Intersects(Segment2 value, out Point2 intersectionPoint)
    {
            var minimumPoint = value.Start;
            var maximumPoint = value.End;
            var minimumDistance = float.MinValue;
            var maximumDistance = float.MaxValue;

            var direction = End - Start;
            if (!PrimitivesHelper.IntersectsSlab(Start.X, direction.X, minimumPoint.X, maximumPoint.X, ref minimumDistance, ref maximumDistance))
            {
                intersectionPoint = Point2.NaN;
                return false;
            }

            if (!PrimitivesHelper.IntersectsSlab(Start.Y, direction.Y, minimumPoint.Y, maximumPoint.Y, ref minimumDistance, ref maximumDistance))
            {
                intersectionPoint = Point2.NaN;
                return false;
            }

            if (minimumDistance <= 0)
                intersectionPoint = Start;
            else
            {
                intersectionPoint = minimumDistance * direction;
                intersectionPoint.X += Start.X;
                intersectionPoint.Y += Start.Y;
            }

            return true;
    }
```

**Comment by 7sharp9** [comment]
@lithiumtoast I was actually looking at the slab test yesterday, I saw that the rays could be created from segments like you did above.  I ended up confusing myself with how would I know if the intersection was further than the extent of the initial segment?

**Comment by lithiumtoast** [comment]
@7sharp9 `IntersectsSlab` is the same as the following snippet of code from the "orange" book of collision detection.

<img width="485" alt="screen shot 2019-02-08 at 10 55 20 pm" src="https://user-images.githubusercontent.com/519592/52517739-a7476780-2bf4-11e9-9449-d07dee504d58.png">

The last 3 lines in that for loop in the else path is the check to see it's past the slab.

**Comment by lithiumtoast** [comment]
My apologies, you asked for line-to-line.

It's page 152.

Here's the reference diagram:

<img width="455" alt="screen shot 2019-02-08 at 11 18 57 pm" src="https://user-images.githubusercontent.com/519592/52517930-f642cc00-2bf7-11e9-85e7-42a0abfb56f4.png">

The code snippet:

<img width="452" alt="screen shot 2019-02-08 at 11 23 45 pm" src="https://user-images.githubusercontent.com/519592/52517989-a1538580-2bf8-11e9-8eb6-f0cd4297ebcf.png">

<img width="500" alt="screen shot 2019-02-08 at 11 20 51 pm" src="https://user-images.githubusercontent.com/519592/52517949-3609b380-2bf8-11e9-9bc5-8e4a4a56e06c.png">

<img width="505" alt="screen shot 2019-02-08 at 11 21 16 pm" src="https://user-images.githubusercontent.com/519592/52517953-40c44880-2bf8-11e9-9873-1eb804a7c434.png">

<img width="502" alt="screen shot 2019-02-08 at 11 23 04 pm" src="https://user-images.githubusercontent.com/519592/52517974-8254f380-2bf8-11e9-9a95-c600ad58d86b.png">

**Comment by lithiumtoast** [comment]
Soooo the code would be something like this:

```
// Tell the compiler we would very much like this helper function to be inlined
[MethodImpl(MethodImplOptions.AggressiveInlining)]
float SignedTriangleArea2D(Point2 a, Point2 b, Point2 c)
{
    return (a.X - c.X) * (b.Y - c.Y) * (a.Y - c.Y) * (b.X - c.X);
}

public bool Intersects(Segment2 value, out Point2 intersectionPoint)
{
    var area1 = SignedTriangleArea2D(Start, End, value.End);
    var area2 = SignedTriangleArea2D(Start, End, value.Start);

    if (area1 == 0 || area2 == 0 || area1 * area2 >= 0) return false;

    var area3 = SignedTriangleArea2D(value.Start, value.End, Start);
    var area4 = area3 + area2 - area1;
    if (area3 * area4 >= 0) return false;
 
   var t = area3 / (area3 - area4)
   var direction = End - Start;
   intersectionPoint = Start + t * direction;
}

```

**Comment by 7sharp9** [comment]
Thanks for the info @lithiumtoast Maybe I was conflating two different algorithms.  I remember reading the slab test and it was referring to rays rather than segments, I wondered how I know my segment intersects rather than the ray.  I think it was probably AABB vs ray that I read.

**Comment by lithiumtoast** [comment]
No problem. Yeah I did the same thing at first. I updated the C# solution slightly with the floating-point check for zero with `area3` and `area4` as is recommended by the book (I did it for `area1` and `area2` but forgot for `area3` and `area4`).
