### ISSUE TITLE
Prevent pushing dynamic bodies

### ISSUE THREAD

**Issue by EnemyArea** [craftworkgames/MonoGame.Extended#591]
Hey guys,

there should be a solution to prevent pushing a dynamic body with an other dynamic body.
They should collide, but not pushable. In many games you need e.a. npcs which moving around a a town, but you must not push them or they should push you. But if you ran into one or they ran into you, the character must stop / flow around.

**Comment by craftworkgames** [comment]
I think we need a little more context here.

What are you talking about exactly?

**Comment by EnemyArea** [comment]
If you look at the platformer demo, you can push the enemies around. But why should I push my other dynamic bodies around? They should move, but don't get pushed away.

**Comment by lithiumtoast** [comment]
The collision code definitely needs to be refreshed. I think what is mentioned here is the ability to *not push* an NPC when you, the player, collide.
