### ISSUE TITLE
please add DrawElipse()

### ISSUE THREAD

**Issue by Shadowblitz16** [craftworkgames/MonoGame.Extended#603]
can you add drawElipse() to the spriteBatch?
it would be a circle but with a x and y radius
thankyou

**Comment by craftworkgames** [comment]
If you're interested in submitting a pull request for this please do so.

**Comment by craftworkgames** [comment]
This might be useful.
https://www.geeksforgeeks.org/midpoint-ellipse-drawing-algorithm/

**Comment by Shadowblitz16** [comment]
@craftworkgames how would this be converted into a drawing function?
it return void and idk how I would actually draw it if I knew the x and y radius.

**Comment by craftworkgames** [comment]
Take a look at the [existing methods](https://github.com/craftworkgames/MonoGame.Extended/blob/7c8de64caa135eaea39885a99e0e8e706a85bfad/Source/MonoGame.Extended/Math/ShapeExtensions.cs). They are implemented as `SpriteBatch` extension methods.

**Comment by jonmseaman** [comment]
Done.
https://github.com/craftworkgames/MonoGame.Extended/pull/613

**Comment by Shadowblitz16** [comment]
@craftworkgames what version is this in?
I am latest beta build release and it doesn't exist

**Comment by craftworkgames** [comment]
@Shadowblitz16 I've literally just uploaded brand new [NuGet packages for version 3.7.0 to nuget.org](https://www.nuget.org/packages?q=MonoGame.Extended) tonight.

In fact, they are so new, they might not be listed by the time you click the above link. (NuGet says it might take up to an hour).

**Comment by Shadowblitz16** [comment]
oh ok
