### ISSUE TITLE
net standard nuget packages: some fails

### ISSUE THREAD

**Issue by ferama** [craftworkgames/MonoGame.Extended#607]
Hey all, I'm experimenting with monogame and monogame.extended library.

I followed the instruction on http://www.monogameextended.net/posts/getting-started-with-monogame-extended about the net core version.

I successfully built a simple example that loads and displays a tiled map.

The problem is that the command

$ dotnet build

complains about:

Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.

and

Failed to load assembly '/Users/ferama/.nuget/packages/monogame.extended.tiled/3.6.0-beta0001/lib/netstandard2.0/MonoGame.Extended.Tiled.dll': Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  Could not load file or assembly 'MonoGame.Extended.Graphics, Version=3.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

The project then run fine anyway, but don't know if is something I should worry about.

I'm trying to build a basic stack on which develop a game and I want a robust one.

Unfortunately most of the guides that I find online about monogame and related extensions seems to have some issues on Mac and Linux (don't have a windows machine)

I'm going to try to build monogame.extended from scratch bypassing the nuget repo as soon as I have some time to look more closely at it and maybe better understand what cause the issue.

I'm new to the dotnet world so maybe I'm missing something obvious

**Comment by craftworkgames** [comment]
Hmm... that's a curious one.

The only thing I can think of based on the messages you've posted is that the referenced packages don't exactly match the right versions for some reason. For example, it seems to be looking for `MonoGame.Extended.Graphics, Version 3.6.0.0` but I would expect it to be referencing `3.6.0-beta0001`

Since everything seems to be working I wouldn't worry about it. Chances are these messages will go away when we bring it out of beta.

**Comment by ferama** [comment]
To let you know I've build MonoGame.Extended from scratch adding the source to my project and the error are gone, so it seems there is some issue with the nuget packages.

**Comment by craftworkgames** [comment]
Good to know.

Not sure what's wrong with the NuGet packages. They work for me and plenty of other people I've talked too. Of course, if we can reproduce the issue at some point I'll try to fix it.

Btw.. if you run the `build.ps1` script locally it will make NuGet packages. It'd be interesting to see if building them yourself helps or not. Either way, I'm just glad you found a way around it.

**Comment by ferama** [comment]
I built each package using $ dotnet build. I didn't use the build.ps1 script (I'm on linux and Mac machines, no Windows as I said in the first post)

**Comment by craftworkgames** [comment]
Ah, sorry. I forgot you weren't on Windows.

Of course, if you had a closer look you might have noticed there's also a `build.sh` script as well. 😉 Everything in MonoGame.Extended is intended to be cross-platform. We use the [cake build](https://cakebuild.net/) system to do the heavy lifting on the build server.

I've never personally built it on Linux or Mac but I believe it's been done before so it should work.

**Comment by ferama** [comment]
I noticed the build.sh script, I forgot to mention it, but it not worked either. Maybe this should be a new issue:

`$ bash build.sh
Downloading packages.config...
Downloading NuGet...
Feeds used:
  /Users/ferama/.nuget/packages/
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.33.0.
  GET https://api.nuget.org/v3-flatcontainer/cake/0.33.0/cake.0.33.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/cake/0.33.0/cake.0.33.0.nupkg 35ms
Installing Cake 0.33.0.
Adding package 'Cake.0.33.0' to folder '/Users/ferama/tmp/MonoGame.Extended/tools'
Added package 'Cake.0.33.0' to folder '/Users/ferama/tmp/MonoGame.Extended/tools'
The 'tool' directive is attempting to install the 'vswhere' package
without specifying a package version number.
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version
It's not recommended, but you can explicitly override this warning
by configuring the Skip Package Version Check setting to true
(i.e. command line parameter "--settings_skippackageversioncheck=true",
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
The 'tool' directive is attempting to install the 'GitVersion.CommandLine' package
without specifying a package version number.
More information on this can be found at https://cakebuild.net/docs/tutorials/pinning-cake-version
It's not recommended, but you can explicitly override this warning
by configuring the Skip Package Version Check setting to true
(i.e. command line parameter "--settings_skippackageversioncheck=true",
environment variable "CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
Error: One or more errors occurred. (VSWhere: Process returned an error (exit code 255).)
	VSWhere: Process returned an error (exit code 255).`

**Comment by craftworkgames** [comment]
> Error: One or more errors occurred. (VSWhere: Process returned an error (exit code 255).)
VSWhere: Process returned an error (exit code 255).`

Actually, that's quite interesting. It looks like we no longer depend on VSWhere at all but there are some unused lines of code left over in the cake script.

Remove the following lines from the `build.cake` file and you should be good to go.

```csharp
#tool nuget:?package=vswhere

// other lines here

var vsLatest  = VSWhereLatest();
var msBuildPath = vsLatest?.CombineWithFilePath("./MSBuild/15.0/Bin/amd64/MSBuild.exe");
```

I'm currently in the middle of some other changes but I'll push these changes to the `develop` branch soon.

**Comment by ferama** [comment]
It almost works (fails on some of the demos due to some fonts not found) but actually I feel more comfortable at the moment to embed the framework source in my project. Anyway thanks for your help.
