### ISSUE TITLE
Camera2D Zoom values are not clamped

### ISSUE THREAD

**Issue by dhasenan** [craftworkgames/MonoGame.Extended#61]
Setting Camera2D.Zoom to -1f, for instance, results in a zoom of 1 and a 180 degree rotation. This is probably not intended.

**Comment by craftworkgames** [comment]
Agreed. This isn't intended. What do you think it should do instead? Always clamp above zero + Configurable clamping values? 

I think it needs to be flexible but have sensible default values.

**Comment by dhasenan** [comment]
The minimal sensible change would be to throw an ArgumentException when setting the zoom below 0.

**Comment by craftworkgames** [comment]
Yep fair enough. That leaves the responsibility of clamping to the user. I'll just have to remember to update the sample to show how to use it.

**Comment by craftworkgames** [comment]
@dhasenan I implemented the minimum change to throw an ArgumentException then it really bothered me how much state we are asking to user to manage themselves to prevent the exception from being thrown.

What do you think about [this implementation](https://github.com/craftworkgames/MonoGame.Extended/commit/e961b58eff39400a29050e20e457abbf1966b0ab)?

I think it adds value without taking anything away.

**Comment by dhasenan** [comment]
That looks pretty awesome.

**Comment by craftworkgames** [comment]
Cool.

While I was doing it I was thinking maybe we could add some sort of bounds checking feature to keep the camera inside a specified rectangle in a similar way.
