### ISSUE TITLE
Game.CreateContent() for using with libraries that don't use the game class directly

### ISSUE THREAD

**Issue by Shadowblitz16** [craftworkgames/MonoGame.Extended#610]
can Game.CreateContent() be added as a static parameterless extension?
this would make it easier to make libraries, editors, and unit tests without having to instantiate a game object.

for example you would just do.. 
```
using Monogame.Extended.Content
using Microsoft.Xna.Framework;
public class SomeClass
{
    ContentManager Content { get; set; } = Game.CreateContent();
    public static void FunctionThatUsesContent()
    {
        //Code here
    }
}
```
I think this would just be easier to use overall and allow people more freedom to make their games other than managing objects

**Comment by craftworkgames** [comment]
It's not technically possible to create static extension methods in C# like the one you've shown.

More importantly, though, I'm struggling to understand the intent?  What would the `CreateContent` method actually do?  Is it intended to create a `new ContentManager()` each time or return the default one attached to the `Game1` class?

In either case, I'm not sure if it's the best thing to do long term. As your game grows the strategies you use to manage content will change. For example, you might want to load certain when the player moves to the next level and likewise unload old content from the previous level. Some content will stick around for the lifetime of the game, while other content will be short-lived.

That said, if we can identify common patterns I'm not opposed to having these kinds of helper methods but they need to be thought out properly in the context of making real games.

**Comment by Shadowblitz16** [comment]
It would create a new one.

I think being able to create a new content manager without having to specify parameters that are attached to a instance of a object would be very helpful.

this would allow people to decouple logic and drawing from the game class.
and creating a graphics device or a spritebatch from it would also be possible.
```
        internal static GraphicsDevice Device  { get; private set; } = Content.GetGraphicsDevice();
        internal static SpriteBatch    Sprites { get; private set; } = new SpriteBatch(Device);
```

**Comment by craftworkgames** [comment]
I see where you're coming from but hiding the coupling between the different classes doesn't really decouple them. It's just less obvious.

Also, be careful with global static state. It tends to come back and bite you later on. 

I'll certainly keep these ideas in mind as I'm making improvements to the library, but as for this specific thing I don't think it belongs in the library.
