### ISSUE TITLE
Expose layerDepth in ShapeExtensions

### ISSUE THREAD

**Issue by Ellpeck** [craftworkgames/MonoGame.Extended#623]
The `ShapeExtensions` class is quite useful, however there have been certain occasions where I would've liked to use it while also supplying a `layerDepth` for sorted rendering. 

Currently, all methods in the `ShapeExtensions` class pass a `layerDepth` of 0 to the `SpriteBatch.Draw` call. It would be nice to be able to set the layer depth yourself, possibly through an optional parameter.

**Comment by craftworkgames** [comment]
Hey mate,

This is something I've been wanting to do for ages. You've given me the motivation, so I implemented it tonight.

Let me know if you run into any problems 😄 

There's also a new shapes demo in the Features project 😄
