### ISSUE TITLE
[Shapes] FillCircle, FillEclipse, FillPolygon

### ISSUE THREAD

**Issue by Shadowblitz16** [craftworkgames/MonoGame.Extended#629]
can the following methods be implemented in spritebatch?
-FillCircle
-FillEclipse
-FillPolygon

**Comment by craftworkgames** [comment]
Yep, that's a good idea. I just haven't got around to it.

Issue #574 is also about this. It's worth having a read of that issue and taking a look at the related code.

If you're willing to have a go at implementing this yourself I'd be happy to accept a pull request. Don't worry about using the `PrimitiveBatch` stuff unless it makes things easier. I'm happy if they are just added to the existing `SpriteBatch` extensions.

Just one thing to keep in mind. If you do submit a PR please make sure you've updated the [shapes demo](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Features/Demos/ShapesDemo.cs#L36). I won't be accepting pull requests that add new features unless a demo is included.

**Comment by padesso** [comment]
Started implementing this and have most of the shapes being drawn using the PrimitiveBatch from the Velcro Physics project.  Would the preference be to have backwards compatibility with the ShapeExtensions API or replace that completely?

**Comment by craftworkgames** [comment]
> Would the preference be to have backwards compatibility with the ShapeExtensions API or replace that completely?

I'm fine with replacing it if it makes the API better. It probably make sense to make it work much the same way it already works in Velcro.

**Comment by padesso** [comment]
It's been a bit of a trade-off. We get things like filled polygons but we **seem** to lose the ability to set line thickness and need to specify projection and view matrices, which complicates usage a bit.

**Comment by craftworkgames** [comment]
> We seem to lose the ability to set line thickness and need to specify projection and view matrices

There's always going to be a few teething problems when you introduce something new. I don't think any of these things are show stoppers though, and they can be improved over time.

**Comment by padesso** [comment]
PR accepted for this.  I believe the issue can be closed.
