### ISSUE TITLE
can we get a translate, rotate and scale helpers for sprite batch?

### ISSUE THREAD

**Issue by Shadowblitz16** [craftworkgames/MonoGame.Extended#631]
can we get a the following functions for spritebatch?
- `translate(float x, float y, float z)`
- `rotate(float rx, float ry, float rz)`
- `scale(float sx, float sy, float sz)`
- `translate(Vector3 offset)`
- `rotate(Vector3 angle)`
- `scale(Vector3 scale)`

this would affect all drawn things.

**Comment by craftworkgames** [comment]
It's already pretty easy to do this kind of thing by passing a transformation matrix into the `SpriteBatch.Begin` call.

```cs
var transformMatrix =
    Matrix.CreateTranslation(100, 0, 0) *
    Matrix.CreateScale(0.8f) *
    Matrix.CreateRotationZ(MathHelper.TwoPi / 32f);

_spriteBatch.Begin(
    samplerState: SamplerState.LinearClamp, 
    blendState: BlendState.AlphaBlend, 
    transformMatrix: transformMatrix);
```

![image](https://user-images.githubusercontent.com/3201643/64425998-c35ea900-d0f0-11e9-9388-1061d42dd805.png)
