### ISSUE TITLE
useful things for both 2D and 3D games

### ISSUE THREAD

**Issue by Shadowblitz16** [craftworkgames/MonoGame.Extended#632]
I was wondering if the following shapes could be added?
-Line
-Cubiod
-Ellipsoid
-Tetrahedron
-Cone
-Cylinder

using the format (x1,y1,z1),(x2,y2,z2) and (x1,y1),(x2,y2)
and have drawing and collision functions for it like so..
```cs
void SpriteBatch.DrawShape(Shape shape, Matrix matrix)
void SpriteBatch.DrawShape(Shape shape, Vector3 offset, Vector3 scale, Vector3 rotation)
bool Shape.Intersects(Shape other, bool solid);
bool Shape.Intersects(Shape other, bool solid, out Vec3 point);
```
and texture support for shapes.
i'm not sure how binding a texture would work but preferably something simple like so..
```cs
Shape.BindTexture(Texture2D texture, int side, WrapType wrapX, WrapType wrapY)
```

example of uv mapping enums..
```cs
public enum CubeUV : int
{
  Top,
  Bottom,
  Left,
  Right,
  Front,
  Back
} 
public enum ElipseUV : int
{
  Top,
}
```

example of use would be..
```cs
MyCube.BindTexture(texture, CubeUV.Top | CubeUV.Bottom, WrapType.Clamp, WrapType.Wrap)
```
note that different UV enums would be used for different shapes
the whole point in the texture binding for shapes is that it wouldn't require software and would be easy to do with code.

anyways this would be really nice for both 2d and 3d and is a improved version of https://github.com/craftworkgames/MonoGame.Extended/issues/629

**Comment by craftworkgames** [comment]
There are literally thousands of these "nice to have" features that we could spend our time implementing.

However, I've learned from experience that it's almost always a waste of time trying to implement these things out of the context of making actual games.  If you do this you have to make assumptions and they don't really work as you expected when you're working on an actual game.

So please don't take it personally if I close these issues without much explanation. I prefer to spend my time focusing on real world issues that are actually affecting people making games.
