### ISSUE TITLE
Tiled Importer fails to read maps with multiline string properties

### ISSUE THREAD

**Issue by Ellpeck** [craftworkgames/MonoGame.Extended#635]
As outlined in the [TMX format documentation](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#property), a string property that contains multiple lines is stored inside the `property` element rather than in the `value` attribute:

> When a string property contains newlines, the current version of Tiled will write out the value as characters contained inside the property element rather than as the value attribute. It is possible that a future version of the TMX format will switch to always saving property values inside the element rather than as an attribute.

The Tiled Importer does not reflect this, causing it to throw an exception due to the `value` attribute being missing.

**Comment by craftworkgames** [comment]
Thanks for the bug report.

Would you be able to provide an example map that has the problem?

**Comment by Ellpeck** [comment]
This is an edited version of level01.tmx from the demos project, so it uses all of the asset files from there.
https://gist.github.com/Ellpeck/e00f6be27e3793ef7761d0eab9ccebff#file-level01-tmx-L86-L89
