### ISSUE TITLE
ShapeExtensions layerDepth inconsistency

### ISSUE THREAD

**Issue by feydk** [craftworkgames/MonoGame.Extended#638]
SpriteBatch.Draw use float for layerDepth, with the float being a value of 0 to 1. ShapeExtensions uses int, effectively making it very hard/impossible to achieve the same draw order if you mix SB and ShapeExtensions draw calls.

Why this inconsistency?

**Comment by craftworkgames** [comment]
Ah man, total oversight. Thanks for reporting it. It's now fixed in the `devleop` branch.

**Comment by cjhooker** [comment]
Hi! I was hoping to get the nuget with this fix included. I added the Craftwork Games Build Server NuGet Package Source to my sources per http://docs.monogameextended.net/NuGet-Pre-Release/ but it keeps asking me for credentials. Is that intentional?

**Comment by craftworkgames** [comment]
@cjhooker Looks like some things have changed in the recent Team City updates and the NuGet feed is no longer working (without authentication). I tried a few things I'm not sure what I need to do to fix it or if they even support the guest feed anymore.

In the mean time, you can easily build the NuGet packages yourself.

1. Clone the repository locally using `git` (it must be a real git repo for versioning to work properly).
2. Make sure you've got at least Visual Studio 2019 installed.
3. Run `build.ps1`

Once it completes you'll have NuGet packages in the `artifacts` folder. You can add a local folder as a NuGet feed package source.

**Comment by craftworkgames** [comment]
Actually, I think I fixed the NuGet feed now.

**Comment by cjhooker** [comment]
Yes, the NuGet feed works for me now. Thanks for the quick response!
