### ISSUE TITLE
monogameextended.net is down

### ISSUE THREAD

**Issue by ashelleyPurdue** [craftworkgames/MonoGame.Extended#640]
title

**Comment by craftworkgames** [comment]
Thanks for letting me know.

Appears to be some sort of issue with Azure. Things are not loading in the portal either. 

I'll wait and see if it blows over and if not I'll look into it further.

If it helps, looks like the http://docs.monogameextended.net/ site is still up.

**Comment by craftworkgames** [comment]
Actually, it appears to be a DNS issue. You can get to the site using this URL instead.

https://monogameextended.azurewebsites.net/

**Comment by craftworkgames** [comment]
#fixed
