### ISSUE TITLE
Entities do not appear in the Platformer

### ISSUE THREAD

**Issue by janfokke** [craftworkgames/MonoGame.Extended#643]
Cause: The animation code is broken and commented out

**Comment by lithiumtoast** [comment]
Yeah, I noticed that the platformer game is completely broken right now when manually testing.

Honestly, I'm more in favour of just using this platformer (https://github.com/SimonDarksideJ/XNAGameStudio/wiki/Platformer) and deleting this broken one. This won't happen until after v4.

**Comment by Scythen** [comment]
@lithiumtoast Looks like that platformer is broken as wel

**Comment by lithiumtoast** [comment]
It's just not adapted to MonoGame; it's an XNA 4.0 project.
