### ISSUE TITLE
How should the Camera2D.Zoom property actually work?

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#65]
Currently the `Zoom` property of the camera actually represents the scale of the scene. For example:

 - A zoom value of 0.5 appears to put the camera further away from the scene allowing more to fit into the viewport
 - A zoom value of 2.0 appears to put the camera closer to the scene allowing less to fit into the viewport.

Obviously this achieves the desired effect but it feels a little odd. It could also be thought that smaller values = closer and larger values = further away. I tried to figure out how [other game frameworks do it](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/OrthographicCamera.html#zoom) but it's surprisingly difficult to find detailed documentation on the zoom property.

If we do decide to change the way it behaves this will be a breaking change to anyone already using it. That said, if there is a compelling enough reason to change it, now is the time to do it before the library is more widely used.

**Comment by nanexcool** [comment]
I think it's fine as it is. A lens can zoom to 2X, 4X, etc... and that's what represented currently. On my Android camera it shows 1.0X, and if I zoom the number increases.

**Comment by craftworkgames** [comment]
@nanexcool Good to know. 

I had another look around and it looks like [Flixel](http://flixel.org/docs/org/flixel/FlxCamera.html#zoom) does it that way.

The [LibGDX Camera tutorial](https://github.com/libgdx/libgdx/wiki/Orthographic-camera) has the following code:

        if (Gdx.input.isKeyPressed(Input.Keys.A)) {
            cam.zoom += 0.02;
        }
        if (Gdx.input.isKeyPressed(Input.Keys.Q)) {
            cam.zoom -= 0.02;
        }

Which feels like it's the opposite way around.

I guess either way works. I think I might be a little paranoid. I'll close the issue unless anyone else has any objections.
