### ISSUE TITLE
Suggestion: Remove Size2 (and possibly Point2)

### ISSUE THREAD

**Issue by jamieyello** [craftworkgames/MonoGame.Extended#650]
Size2 (in RectangleF.Size) has consistently been converted Point2 in my library due to serving no purpose. All extensions I write are interchangeable between Point2 Size2 and Vector2.
https://github.com/jamieyello/DownUnder-UI

I would suggest getting rid of both Point2 and Size2 in favor of Vector2. I'd be able to cut my extensions by a third.

There's also the fact that being able to add and subtract points is very useful, something I had to write an extension method for Point2 in a WithOffset. (Since operator extensions are impossible)

**Comment by lithiumtoast** [comment]
Hello @jamieyello,

There already exist implicit operators for these types. Perhaps an implicit operator for `Size` would help you. As for Point2 vs Vector2 see the [previous discussion](https://github.com/craftworkgames/MonoGame.Extended/issues/510#issuecomment-398434410).

**Comment by jamieyello** [comment]
I understand the idea behind keeping all three, ultimately it's not my decision, but I get why it's argued about so much.

It's not so much an inconvenience to me as it gets me right in the OCD.

Looking at master, it looks like implicit operators already exist, I must have an outdated build.

**Comment by lithiumtoast** [comment]
Hello @jamieyello 

I will consider removing `Point2` in v4.
