### ISSUE TITLE
Can't install the Install-Package Monogame.Extended

### ISSUE THREAD

**Issue by elguoshiy** [craftworkgames/MonoGame.Extended#663]
![2020-04-22 (2)](https://user-images.githubusercontent.com/61806028/80020396-dcc23300-84d0-11ea-9ed6-0576927b5f2c.png)
I don't know what it means please help.

**Comment by TarranWalker** [comment]
Upgrade your project to .NET Framework 4.6.1 or greater and should work.

**Comment by elguoshiy** [comment]
I tried to upgrade but it says that I already installed it into my PC

**Comment by TarranWalker** [comment]
You need to upgrade your Project in Visual Studio. In Visual Studio, right click the Project name and go to Properties; then under Target Framework, change this drop down from ".NET Framework 4.5" to ".NET Framework 4.6.1" or greater.

If you look at the NuGet package for Monogame.Extended (https://www.nuget.org/packages/MonoGame.Extended/), it's compiled to .NET Standard 2.0 which is equivalent of .NET Framework 4.6.1 or greater.

**Comment by elguoshiy** [comment]
Thank you so much! It worked.

**Comment by TarranWalker** [comment]
Great - Happy coding!
