### ISSUE TITLE
Unnload objects from the ContentManager after the scene was deleted? 

### ISSUE THREAD

**Issue by Donaut** [craftworkgames/MonoGame.Extended#665]
Whats the best way to unload unused resources from the content manager after the scene was deleted? I think the simplest way is to creating a separate ContentManager for every scene then just delet them after the scene is no longer needed.

**Comment by lithiumtoast** [comment]
Hello @Donaut,

Yes if you want to control unloading certain assets, it is recommended to create a new `ContentManager` for those assets and then call `ContentManager.Unload()`. Note that disposing of a `ContentManager` by calling `ContentManager.Dispose()` will [also call `ContentManager.Unload()`](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Content/ContentManager.cs#L193).
