### ISSUE TITLE
MonoGame.Extended.Animations is empty on dev?

### ISSUE THREAD

**Issue by tobischw** [craftworkgames/MonoGame.Extended#667]
Appears as if the sources for MonoGame.Extended.Animations is simply empty on the `develop` branch. 

Naturally, this occurs after painstakingly trying to puzzle together how to use the Animations extension. The current one in `3.7.0` seems to lack any coherent documentation, and after some googling, I was told to try the preview NuGet branch (the server seems to have shut down). Finally, I tried to compile the `dev` branch from source, to find out that there's no code. The `spritesheets` branch appears to be outdated, so I am a bit lost here.

(Sorry if I seem frustrated, I understand this isn't super well-maintained anymore and only by a few people, just really wanted to get the animations to work!)

**Comment by dylanwilson80** [comment]
To be honest, I don't remember how this happened. I probably started working on animations and then got busy with life.

Your best bet would be to start by trying to compile and run the demos. This demo here looks like it's probably working to some degree:
https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Tutorials/Demos/AnimationsDemo.cs

In terms of the project being maintained, it's true that I haven't been able to give it my full attention  recently. However, I have been actively trying to put together a team of people to continue development and bring the project back to life. I wrote a [quick post about it](https://www.patreon.com/posts/meet-new-team-37688719) a few days ago.

**Comment by tobischw** [comment]
That's great to hear about the team! I am very excited about this.

Regarding the demo: Yes, I did end up getting most of my code from there, but the problem remains that since `develop ` does not contain the Animations namespace, I can't compile them. Do you know where I could find the "newest" version of Animations (the one that includes `SpriteSheet.cs`)?

**Comment by dylanwilson80** [comment]
I think the original intention was to move the animations stuff into the "core" library.

There's [a folder called Sprites](https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended/Sprites) that appears to contain the `AnimatedSprite`, `SpriteSheet` and other related bits. I'm a bit surprised the demo doesn't already compile but I doubt it will take much to get them going again.

**Comment by tobischw** [comment]
Ah, my apologies - I don't know what was wrong but they are compiling. Thanks for pointing out the `Sprites` folder.

**Comment by jypjypjypjyp** [comment]
I found that SpriteSheetAnimationFactory is missing, How can I use the new SpriteSheet?

**Comment by tobischw** [comment]
Literally the last 2 comments above you tell you where it’s located.

**Comment by jypjypjypjyp** [comment]
> Literally the last 2 comments above you tell you where it’s located.

But there is no SpriteSheetAnimationFactory, I put the old version code into the Animation folder for this.

**Comment by lithiumtoast** [comment]
The animations code has moved somehow from a NuGet package to being part of the core library: https://github.com/craftworkgames/MonoGame.Extended/tree/develop/Source/MonoGame.Extended/Sprites
