### ISSUE TITLE
Fix For Monogame 3.8 (develop)

### ISSUE THREAD

**Issue by Emersont1** [craftworkgames/MonoGame.Extended#668]
I've just compiled MonoGame.Extended for the current MonoGame `3.8.0.1375-develop` release on NuGet with DotNetCore3.1. I've Only compiled the libraries and tests so far (not the demos or games), but so Far, I've only noticed one thing that will need fixing. I could not add the demos/games, due to the content builder NuGet not wanting to install

+ **Ambiguity between `Microsoft.Xna.Framework.Content.ContentReaderExtensions` and `MonoGame.Extended.Content.ContentReaderExtensions` in `Monogame.Extended/TextureAtlases.cs`**. I think MonoGame added/is adding the class in with 3.8, but a simple  change to `MonoGame.Extended.Content.ContentReaderExtensions` `ContentReaderExtensions` on Line 36 Fixes this. Ideally, if the functionality is replicated in MonoGame 3.8, then the code should use the class in `Microsoft.Xna.Framework` but at present, it does not contain any methods in its static class for adding/removing extensions

**Comment by lithiumtoast** [comment]
I will look at this on Monday, June 15th

**Comment by lithiumtoast** [comment]
I tested and ran all projects with .NET Core 3.1 and MonoGame 3.8 pre-release `3.8.0.1375-develop`. I could not re-produce this.

@Emersont1 Can you try to re-produce with a clone of #673?
