### ISSUE TITLE
[Gui] Trying to get a simple context menu to display on right click

### ISSUE THREAD

**Issue by mxmissile** [craftworkgames/MonoGame.Extended#679]
Trying to get a small context menu to display on right click:

```
public class UserInterface
{
        public UserInterface()
        {
            var button = new Button {Content = "Build Something"};

            ContextMenu = new StackPanel
            {
                //Orientation = Orientation.Horizontal,
                //Spacing = 5,
                Items = {button},
                BackgroundColor = Color.Gray,
                Margin = 10,
                IsVisible = false
            };

            Screen = new Screen {Content = ContextMenu };
        }
    
        public LayoutControl ContextMenu { get; private set; }
        public Screen Screen { get; private set; }
      
        public void ShowContextMenu(Point position)
        {
           // Screen.Layout(GuiSystem, new Rectangle(100, 100, 120, 100));
            ContextMenu.Position = position;
            ContextMenu.IsVisible = true;
        }        
    }
```

Called in my Game's Update() like this:

```
if (Input.IsNewRightMouseClick(out var mouse))
{
  _ui.ShowContextMenu(mouse.Position);
}
```

It shows up in the correct position, but its huge (current window size) unless I call `ScreenLayout()`. I've tried setting the StackPanel.Width and Height properties but they do nothing. 

I feel like I'm going about this completely wrong. Is calling `ScreenLayout` the best way? Is StackPanel the wrong control for this?

**Comment by lithiumtoast** [comment]
Hello @mxmissile. Sorry for the delay. I'm not sure if it's the wrong control or not. I'm not familiar with the GUI system. I can take look at this soon.

**Comment by lithiumtoast** [comment]
@mxmissile Hey finally has some time to look into this. Could you provide a zipped csproj/solution I can test this with VisualStudio?

**Comment by AristurtleDev** [comment]
Moving forward, MonoGame.Extended will be supporting GUM as the Gui component.  Please see https://www.monogameextended.net/blog/monogame-extended-gum/ for more information.
