### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by WardBenjamin** [craftworkgames/MonoGame.Extended#68]
Looking at the front page of the repository, there's no clear indication of what our features actually are. Should we either add a list to the readme or add some kind of FEATURES.md file with a similar list?

**Comment by craftworkgames** [comment]
Yep sounds good. I think it should go in the main readme file somewhere near the top.

You can grab the current feature list from the release notes of [version 0.2](http://dylanwilson.net/monogame-extended-v0-2-release-notes) and [version 0.3](http://dylanwilson.net/monogame-extended-v0-3-release-notes).

I think it should be a short bullet point list. Don't describe each feature in too much detail but you can link to relevant blog posts and tools if that makes sense.
