### ISSUE TITLE
[Tiled] Unable to build tiled map

### ISSUE THREAD

**Issue by sudo-make** [craftworkgames/MonoGame.Extended#680]
Hello guys.
*this was originally posted on the monogame forum, but was told it may be best to create an issue here*
I am trying to use a Tiled map in my project, but have run into an issue preventing me from building.
I’ve been able to get the Tiled Map Importer/Processor referenced etc. But, when I add my map and attempt to build the game, I am presented with an exception being thrown: “Unable to read beyond the end of the stream”.

I have attempted re-loading and string to re-import the asset but to no avail.

Monogame version: 3.8.0.1375-develop
![This is very annoyying ngl](https://user-images.githubusercontent.com/20684751/87885826-383c8800-ca10-11ea-8e59-b5aab0c31b59.png)

Monogame Extended Tiled Version: 3.7.0
^— Content Pipeline version: 3.7.0

I would greatly appreciate any help or guidance you guys can give 🙂
I have attached a screenshot of the issue (hopefully it provides some help)

**Comment by lithiumtoast** [comment]
Never seen or encountered this before.

Could you try opening up the .tmx file, adding a space to the last line and then adding a new line?

**Comment by sudo-make** [comment]
> Never seen or encountered this before.
> 
> Could you try opening up the .tmx file, adding a space to the last line and then adding a new line?

Did as you suggested, but it, unfortunately, made no difference. I appreciate the help though.

**Comment by lithiumtoast** [comment]
Could you share your project or the minimum amount to reproduce the problem?

**Comment by sudo-make** [comment]
> Could you share your project or the minimum amount to reproduce the problem?

It's just the basic Visual Studio "Monogame Windows Desktop (DirectX)" template. With monogame extended tiled, and pipeline installed. This problems occurs in new projects and my existing ones.

**Comment by lithiumtoast** [comment]
OK, could you share your .tmx?

**Comment by sudo-make** [comment]
> OK, could you share your .tmx?

Here ya go:
```
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.4" tiledversion="1.4.1" orientation="isometric" renderorder="right-down" width="64" height="32" tilewidth="64" tileheight="32" infinite="0" nextlayerid="6" nextobjectid="1">
 <tileset firstgid="1" source="Tilesets/Medievil.tsx"/>
 <layer id="1" name="BaseLayer" width="64" height="32">
  <data encoding="base64" compression="zstd">
   KLUv/WAAH30LADJEBQfQARAKcvT3t213W/et7sjtNNB/V4DaqJBvAAMbcR4SoBKYBA1I0LEEAAYSIAhHaJigCZ3ACRiaKqkDxUu+4kD0/DcI39jCUL2Fvo0midIqFaw1UGvn9nuL2gQ4B3Bcbtzx+sqn/Nul7gBwE02uIetnYr24m8UG9pAqTssN6YbNcjIYHskp/7F7m9G92i7gIW5qIEr8qc4XMTudletHVa+RO0cbnzQ+wNO4eOs0sXLYntx6/99lXrjUtR/K50fjjMaclh7JQ/tzGEtym1+OOXQRBl0pu87sUMfizwXs8pF/Xgvq/C6+w3aPfw3n1lDWGe953qfv+zjq+j8alB5I/oqH/JsAHyimwECpO1ZvPzoQUBvF+MPm9dbkHBj9vJ0f6rQZ3xAOealLbmuxeaiSwgUw222rQl+e5/RKEvkdBIGdv4DeZ/F7q+1QtYWYIISKWh9EDiSbOYhfCzPGmcYZyX3DIL7wyAX/xunFL1I=
  </data>
 </layer>
 <layer id="4" name="Roof" width="64" height="32">
  <data encoding="base64" compression="zstd">
   KLUv/WAAH1UOAJJFCQyQCwE/9poxNKnOuvZ9ra+t/r/uhgAqZFdWqqOaRlUEQjK8Xw2BL6ghswIaIQbYUK0BEsATuAQAQBI0KEEDEiqQEEEBMEgAlGAADY3RAHEY5IPvsqsGZET+MCs+e/ZxPaClmn5icaTBCBwYs41hgaNzH+woHFYMYI8414+4Szb4xuExkL9r8HTfBKzSk4PBU/huqfMl6TlpYLNy2inebNAb6fX9UNk45I3Ek3MTwLI5N2V5kLiPm3wZ7MVZ/bHSnnIi+9F9a9yC3w6/LOIi1JL3I4RZWhoC2B7nPvE9WHRaw6PggSovm6c15MZQyt9uppEzHoGf5ozb5fDZ0DgFIBz/0cEvptM/SMt9c0GXllkfJ8y17wSW0gzar+Q3gF7wuVN8fg3wFXsFp2K4unQqt+jAjzl1G8Q4Rf9UeRWITPdN9/xQJrmQkYppOitFhIpaA0N+BdRRRbWawSz9A1+3+EJQUIo4QSZVYUf3fdtJk2Rr8S/OugYvv+7e8JUuD91jHHZq6TIjLZfrVpLfkDW5k3U0rjJgbBI9KCDvuSi8UQu1/r0PyDHJI0wGAr1VLZ3HB39hw91dg59k8/hLwp/9BYsLmGUuD4x/
  </data>
 </layer>
 <layer id="5" name="collision" width="64" height="32">
  <data encoding="base64" compression="zstd">
   KLUv/WAAHz0PAMQDAAAMAAwMAAwAAAAADAwMADQAAAA1AAA2OQAADAwADAAADAAMDAAMAAAAAAAAAAwMDAwMAAAMAAAAAAAMgTKoUTcJ4QUWWfYSgBO4BAFJEIEEAAMTGkhoqBAoIROUgIrIOIPDnBPpEY9U8SzLyiY+Z/xtaWziUgkcuVQN13scMUxtcdnZr5sJPETjvBQ8G3QI6d4TpoUFMA/PGrv1XoZtsfQrYh+c923kMlUbAB3sHqe2I42PSXiFyesHdr0sAB++WcurGvJXHP+uYny9hjGuUzwKjwIa1ecUhnuF2sePcv+RI3YcofpvS7VMDp8OO9TanhuyGqMHiffjl6s/SrEkWxU5Wf3a/M8D+/Vpyl6MURCfG1eYnMD84hx23RT8qe8YGMd1y34jRdCmBE1St0mZHVCR1nqGFWi0bVxd3njjK37oqYR6ANfpzq16NUP8o0bL5jnPwSXloRGHBeywoWzumpHe5jej7ei41BP32jKxm1IupPrTwnyL+SxE027igS/+8jSboBhny2J3brmLdHtNZ78cFPU9CBg5suDkl8W/QfTDDMnnd/thNcOB4FYYDrDoNXC8CIfyE38bICafkONzjRoyjY/gaQwCEfajFjNlPyhv+uO+Ft9/djlmUIxr9TNYy6bRYv8=
  </data>
 </layer>
</map> 
```

**Comment by itsreallyhim** [comment]
I've encountered the same issue in the past. Try changing the compression from zstd to gzip.

**Comment by sudo-make** [comment]
> I've encountered the same issue in the past. Try changing the compression from zstd to gzip.

Thanks so much for this; worked perfectly.

To anyone looking at this: go back into the Tiled editor, and when you open the map, make sure to change the compression to gzip.
