### ISSUE TITLE
Was ScreenGameComponent renamed?

### ISSUE THREAD

**Issue by dazinator** [craftworkgames/MonoGame.Extended#681]
I discovered ScreenGameComponent from the docs, but couldn't find this class anywhere: http://docs.monogameextended.net/Features/Screens/#screen-management

Was this component renamed to ScreenManager? Is ScreenManager used in the same way?

**Comment by lithiumtoast** [comment]
Hello @dazinator. I believe that documentation is out of date. You should use the `GuiSystem` class and set the [`ActiveScreen`](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Gui/GuiSystem.cs#L55).
