### ISSUE TITLE
Crash in source built version of Tutorials->Animation (has fix)

### ISSUE THREAD

**Issue by danieloff** [craftworkgames/MonoGame.Extended#683]
Howdy, I was/am just starting to try to learn some monogame/monogame extended because I think I can use it to make my project idea!

Anyway I was going through the tutorial projects trying things and the animation tutorial crashed due to the Newtonsoft.Json dll being version 11 something in one place and 12 something being requested at runtime. Anyway it seems that I was able to make the crash go away by replacing the Newtonsoft.Json.dll (looks like version 11) in the Source\MonoGame.Extended.Content.Pipeline folder with the dll that the other projects in the solution are using (version 12), and rebuilding.

It is not clear to me what is pulling in this dll but I thought I would mention the fix, in case it helps someone.

Thanks for a cool library! If this is already fixed no worries.

**Comment by lithiumtoast** [comment]
https://github.com/craftworkgames/MonoGame.Extended/pull/685
