### ISSUE TITLE
Update to MonoGame 3.8

### ISSUE THREAD

**Issue by janfokke** [craftworkgames/MonoGame.Extended#687]
https://community.monogame.net/t/monogame-3-8/13312

**Comment by lithiumtoast** [comment]
I do not have access to the NuGet.org account. I will try to contact @dylanwilson80 to get access. 

In the mean time the packages are uploaded to my personal feed: `https://www.myget.org/F/lithiumtoast/api/v3/index.json`. If you include pre-releases when searching my feed you can access MonoGame.Exntended by individual pull requests in progress and all commits made to the `develop` branch.

**Comment by lithiumtoast** [comment]
Merged PR but re-opening until I can access NuGet.org

**Comment by AngelMunoz** [comment]
Hey there
I tested with the myget feed and I got an error

I will push these changes to the Repro repository let me know if there's something I've missed
```
C:/Users/scyth/source/repos/Repro/Content/Plazas/sample.tmx : error : Failed to create importer 'TiledMapImporter' [C:\Users\scyth\source\repos\Repro\Repro.csproj]
C:\Users\scyth\.nuget\packages\monogame.content.builder.task\3.8.0.1641\build\MonoGame.Content.Builder.Task.targets(138,5): error MSB3073: The command "dotnet C:\Users\scyth\.nuget\packages\monogame.content.builder.task\3.8.0.1641\build\\..\tools\netcoreapp3.1\any\mgcb.dll /quiet /@:"C:\Users\scyth\source\repos\Repro\Content\Content.mgcb" /platform:DesktopGL /outputDir:"C:/Users/scyth/source/repos/Repro/Content/bin/DesktopGL/Content" /intermediateDir:"C:/Users/scyth/source/repos/Repro/Content/obj/DesktopGL/Content" /workingDir:"C:/Users/scyth/source/repos/Repro/Content/"" exited with code 1. [C:\Users\scyth\source\repos\Repro\Repro.csproj]
```
![image](https://user-images.githubusercontent.com/8684875/90615506-77a1f400-e1c9-11ea-90b5-936e5d6249ba.png)
![image](https://user-images.githubusercontent.com/8684875/90615581-92746880-e1c9-11ea-9a1b-16a004938fc8.png)

**Comment by dylanwilson80** [comment]
@lithiumtoast I have just looked into giving you access to the NuGet.org account. Seems straightforward enough.
I've converted the account to an Organisation just like we did on GitHub and I will be able to add you as an Admin.

![image](https://user-images.githubusercontent.com/1871955/90621639-538cf400-e257-11ea-9df5-2d7e5b1fc7b3.png)

I just need to confirm your NuGet.org username. I don't want to accidentally give it to the wrong person 😬

**Comment by lithiumtoast** [comment]
@AngelMunoz Check our the samples https://github.com/craftworkgames/MonoGame.Extended-samples
There you can see how the content pipeline is set up with NuGet paths. The samples are confirmed to "just work".

**Comment by lithiumtoast** [comment]
@dylanwilson80 Yup my account is `lithiumtoast`

**Comment by AngelMunoz** [comment]
@lithiumtoast got it working thanks!

**Comment by OedipusRexed** [comment]
I managed to get past the same error of "Failed to import TiledMapImporter" by bunching pipeline, tiled, extended, and newtonsoft.json dll's in a package lib, then *only* referencing the pipeline dll in content.mgcb.

However now i am back to the only error being the original one posted above, still related to TileMapRenderer:
`System.Exception: 'This MGFX effect is for an older release of MonoGame and needs to be rebuilt.'
`

**Comment by lithiumtoast** [comment]
@OedipusRexed see https://github.com/craftworkgames/MonoGame.Extended/issues/686
