### ISSUE TITLE
Using animations from a Tiled tsx file

### ISSUE THREAD

**Issue by kerams** [craftworkgames/MonoGame.Extended#688]
Hello, I'm using the `AddAnimationCycle` method from the Platformer demo to define animations for a moving entity. It works great, but I was wondering if it's possible to use animations in a tsx file. The data loads fine with `Content.Load<TiledMapTileset>`, but then I don't see a way to populate `AnimatedSprite` with it.

In other words, I'm looking for a counterpart to `TiledMapRenderer`, which can seamlessly load and update map animations from tmx and tsx files. that would work on individual entities, not the entire level/terrain.

**Comment by lithiumtoast** [comment]
@kerams Could you post an example project with the files?

**Comment by kerams** [comment]
[Content.zip](https://github.com/craftworkgames/MonoGame.Extended/files/5150833/Content.zip)
Thinking about it a bit more, stuffing animated character sheets into a tsx tileset probably isn't the intended use...
