### ISSUE TITLE
Rendering object layers on a Tiled map

### ISSUE THREAD

**Issue by kerams** [craftworkgames/MonoGame.Extended#693]
Looking at https://github.com/craftworkgames/MonoGame.Extended/issues/125, this seems to have been implemented, but the API mentioned (`MapRendererConfig`) no longer exists.

I was hoping commenting out the early return here
https://github.com/craftworkgames/MonoGame.Extended/blob/382aa0abb12b05570f510fd6a42c9a609321e558/Source/MonoGame.Extended.Tiled/Renderers/TiledMapRenderer.cs#L123-L135
would help, but it does not, possibly because there is no implementation for object layers here
https://github.com/craftworkgames/MonoGame.Extended/blob/382aa0abb12b05570f510fd6a42c9a609321e558/Source/MonoGame.Extended.Tiled/Renderers/TiledMapModelBuilder.cs#L17-L29

**Comment by janfokke** [comment]
Do you want to use this for debugging?
Correct me if I'm wrong, but don't object layers just contain data?

**Comment by kerams** [comment]
Adding an object layer in Tiled allows me to place tiles/objects in a much more fine grained fashion. They don't have to be aligned in a grid, can be scaled and rotated. Therefore I figured it was a great way to add static props and whatnot to the map, hoping I'd have everything (except for any moving objects of course) in the picture below defined in a single tmx file.

https://www.kenney.nl/content/3-assets/72-racing-pack/sample.png

Admittedly I am new to Tiled and MonoGame too, so this might not be the best approach.

**Comment by lithiumtoast** [comment]
@kerams There is no built in renderer for Tiled objects. What were you expecting to be rendered?

**Comment by kerams** [comment]
Whatever I define in Tiled :). If I place a rotated texture somewhere on the object layer, Tiled will display it there. Hoped the tiled map renderer would do the same. Apparently, it used to work - #301.

**Comment by lithiumtoast** [comment]
OK; so it is possible in Tiled so select an object, right-click it, and click the menu item "Replace Tile". This will take whatever you have selected in the tileset and use that for an image of the object. I can only seem to select one tile to do this though; it doesn't seem possible to select multiple tiles. Is this what you are doing? I can't seem to find a way to use an image for an object any other way, maybe I'm not aware of a way.

**Comment by kerams** [comment]
This is what I did [Content.zip](https://github.com/craftworkgames/MonoGame.Extended/files/5150767/Content.zip)
Create an object layer on top of the tile layer, select the Insert Tile "tool" and choose some tile (from the current or another tileset) and place it somewhere. Then press Select Objects and click on the tile/object so that you can scale and rotate it however you wish.

**Comment by lithiumtoast** [comment]
OK; so basically you are using the tile as a sprite; it can be rotated, positioned, stretched, etc off the tile grid. This kind of thing is not the purpose of the `TiledMapRenderer`. The purpose of the `TiledMapRenderer` is render tiles not sprites. I would recommend a workaround for this problem by: parse the objects you want to render after loading the map in game and then using `SpriteBatch` which does support off grid positioning, rotation, etc.

**Comment by kerams** [comment]
Thanks, I'll look into it. It would have been cool to have this out of the box in the renderer in any case though ;)
