### ISSUE TITLE
MeasureString doesn't seem to measure a space character at the end of a string.

### ISSUE THREAD

**Issue by SenpaiSharp** [craftworkgames/MonoGame.Extended#695]
MeasureString doesn't seem to measure a space character at the end of a string.

For example:

.MeasureString("Hello World ").X 
.MeasureString(" Hello World").X

The latter will measure longer, while the former will result equally to just measuring without the space at all ("Hello World").

**Comment by Raader** [comment]
seems odd. but which way should it behave. should it measure spaces or not

**Comment by lithiumtoast** [comment]
I just tested with with `BitmapFont` and could not reproduce. Could you share a zipped csproj/solution reproducing the problem?

**Comment by AristurtleDev** [comment]
@SenpaiSharp I am unable to reproduce this issue as well.  I added a unit test to ensure that it doesn't occur or slip through in the future as a bug.

If you are still having this issue, please open a new issue request.

Reference: 
- https://github.com/craftworkgames/MonoGame.Extended/pull/876
