### ISSUE TITLE
[Particle] `VortexModifier` ignores `MaxSpeed`

### ISSUE THREAD

**Issue by janfokke** [craftworkgames/MonoGame.Extended#698]
The `VortexModifier` does not use the `MaxSpeed` Property
This causes the particles to be propeled of at high speed.

https://github.com/craftworkgames/MonoGame.Extended/blob/6e32d1f3229ef00ea11619666bd92b6ffd3896d0/Source/MonoGame.Extended.Particles/Modifiers/VortexModifier.cs#L12

The mercury-particle engine uses it in the following way
https://github.com/Matthew-Davey/mercury-particle-engine/blob/2bfc567a466e3d3bcbc17b972c830898d3c996d6/Mercury.ParticleEngine.Core/Modifiers/VortexModifier.cs#L11-L25

**Comment by lithiumtoast** [comment]
Hmm, wonder what happened here.
