### ISSUE TITLE
Why is EllipseF a class?

### ISSUE THREAD

**Issue by LokiMidgard** [craftworkgames/MonoGame.Extended#703]
I stumbled upon `EllipseF` unlike the other shapes this is a `class` and not a `struct`.

It also does not implement `IShapeF`.

**Comment by lithiumtoast** [comment]
Hmm that's strange. It should definitely be a `struct`. You can open a PR if you want :)

**Comment by simonantonio** [comment]
Strange that the build for this fails on GH, i'm not super familiar with the tooling

**Comment by simonantonio** [comment]
I've converted the class to a struct, added some DataContract attributes (similar to CircleF) and added various overloads and overrides, so the struct is inline with CircleF.

However its failing the windows build step, in the Tiled project (via GitHub)
MonoGame.Extended.Tiled.csproj : error NU1102: Unable to find package NETStandard.Library with version (>= 2.0.3)
