### ISSUE TITLE
ComponentManager.Destroy can throw an NRE

### ISSUE THREAD

**Issue by Jeff425** [craftworkgames/MonoGame.Extended#707]
https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Entities/ComponentManager.cs#L83

This line can throw an NRE if a component is Referenced in an aspect builder, but never attached to an entity. Could check if the componentMapper is not null before trying to call componentMapper.Delete(entityId)

**Comment by lithiumtoast** [comment]
Thanks for the information.
