### ISSUE TITLE
Tiled Importer failing in both MGCB-editor and build.

### ISSUE THREAD

**Issue by mephitisdeux** [craftworkgames/MonoGame.Extended#714]
I'm looking to use the TiledMap Importer in my DesktopGL project, but the TIled Map and Tileset importers fail to load, despite being referenced in the mgcb file as such:
`/reference:../../../../home/mooi/.nuget/packages/monogame.extended.content.pipeline/3.8.0/tools/MonoGame.Extended.Content.Pipeline.dll` All other assets build fine.

MGCB doesn't report anything beyond `Failed to load Importer` for both maps and tilsets, and an attempt to build results in:
`[fail]: OmniSharp.MSBuild.ProjectLoader
        Failed to create importer 'TiledMapTilesetImporter'`

I am using Linux, and the version of mgcb that dotnet downloads, which is `3.8.0.1641`

Any ideas here would be wonderful. Hopefully it's just me doing something wrong.

**Comment by lithiumtoast** [comment]
Hello 😃 

First thing is to ensure everything is working or not working via terminal: https://docs.monogame.net/articles/tools/mgcb.html

Building content via terminal has in my experience shown more enlightening error messages.

**Comment by mephitisdeux** [comment]
This is what I get running `dotnet run mgcb /build` or anything else.
```
/mnt/aux/MATM/assets/Maps/map_test.tmx : error : Failed to create importer 'TiledMapImporter' [/mnt/aux/MATM/src-mgx/Mooi.csproj]
/mnt/aux/MATM/assets/Maps/map_testTiles.tsx : error : Failed to create importer 'TiledMapTilesetImporter' [/mnt/aux/MATM/src-mgx/Mooi.csproj]
/home/atsuko/.nuget/packages/monogame.content.builder.task/3.8.0.1641/build/MonoGame.Content.Builder.Task.targets(138,5): error MSB3073: The command "dotnet /home/atsuko/.nuget/packages/monogame.content.builder.task/3.8.0.1641/build/../tools/netcoreapp3.1/any/mgcb.dll /quiet /@:"/mnt/aux/MATM/src-mgx/Content/Content.mgcb" /platform:DesktopGL /outputDir:"/mnt/aux/MATM/src-mgx/Content/bin/DesktopGL/Content" /intermediateDir:"/mnt/aux/MATM/src-mgx/Content/obj/DesktopGL/Content" /workingDir:"/mnt/aux/MATM/src-mgx/Content/"" exited with code 3. [/mnt/aux/MATM/src-mgx/Mooi.csproj]

The build failed. Fix the build errors and run again.
```
Hope this helps. Thank you.

**Comment by lithiumtoast** [comment]
Did you install the tool? `dotnet tool install -g dotnet-mgcb`

From there you should be able to do: `mgcb /PATH/TO/Content.mgcb`

**Comment by mephitisdeux** [comment]
> Did you install the tool? `dotnet tool install -g dotnet-mgcb`
> 
> From there you should be able to do: `mgcb /PATH/TO/Content.mgcb`

Yes, MGCB is installed. This was run from the project root.
Referring directly to the `Content.mgcb` produced the same output.

Though it did spit this out:
`/build=/build=/reference:../../../../home/atsuko/.nuget/packages/monogame.extended.content.pipeline/3.8.0/tools/MonoGame.Extended.Content.Pipeline.dll: error: Couldn't find a default importer for '/build=/build=/reference:../../../../home/atsuko/.nuget/packages/monogame.extended.content.pipeline/3.8.0/tools/MonoGame.Extended.Content.Pipeline.dll'!`

**Comment by lithiumtoast** [comment]
Can you post your `.mgcb`? Likely an issue where the paths don't match in the reference.

**Comment by mephitisdeux** [comment]
Sure thing. First, the path to the dlls
`/home/atsuko/.nuget/packages/monogame.extended.content.pipeline/3.8.0/tools`
...and the absolute path of the game's project file:
`/mnt/aux/MATM/assets`
Now, the mgcb itself
`
#----------------------------- Global Properties ----------------------------#

/outputDir:.export/bin/$(Platform)
/intermediateDir:.export/obj/$(Platform)
/platform:DesktopGL
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#

/reference:../../../../home/atsuko/.nuget/packages/monogame.extended.content.pipeline/3.8.0/tools/MonoGame.Extended.Content.Pipeline.dll

#---------------------------------- Content ---------------------------------#

#begin Maps/map_test.tmx
/importer:TiledMapImporter
/processor:TiledMapProcessor
/build:Maps/map_test.tmx

#begin Maps/map_testTiles.tsx
/importer:TiledMapTilesetImporter
/processor:TiledMapTilesetProcessor
/build:Maps/map_testTiles.tsx

#begin SpriteSheets/Items/Weapons/wand.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:SpriteSheets/Items/Weapons/wand.png

#begin SpriteSheets/Temp/ball.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:SpriteSheets/Temp/ball.png

#begin Tilesets/bg/bgtest1.jpg
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:Tilesets/bg/bgtest1.jpg

#begin Tilesets/bg/bgtest2.jpg
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:Tilesets/bg/bgtest2.jpg`

**Comment by lithiumtoast** [comment]
Things look at a glance; could you provide a minimal project zipped that reproduces the problem?
Alternatively, you can take a look at how this was addressed for the samples: https://github.com/craftworkgames/MonoGame.Extended/issues/626#issuecomment-720449736

**Comment by mephitisdeux** [comment]
> Things look okay at a glance; could you provide a minimal project zipped that reproduces the problem?
> Alternatively, you can take a look at how this was addressed for the samples: [#626 (comment)](https://github.com/craftworkgames/MonoGame.Extended/issues/626#issuecomment-720449736)

Curiously, the samples build perfectly. Though it isn't 100% clear what's different here, since the `.mgcb` looks the same. I'll test a fresh project and see if its some weird thing with my current one.

**Comment by mephitisdeux** [comment]
Well, we can marked this as closed, and hopefully this odd insight can help.|
It was the slashes used in the reference line. Every slash after `/reference:` _must_ be a backslash. That was it. Tried it on my original project, and yeah it worked.

So:  `/reference:..\..\..\..\..\home\atsuko\.nuget\packages\monogame.extended.content.pipeline\3.8.0\tools\MonoGame.Extended.Content.Pipeline.dll` works, but the Linux version at least, will use forward slashes, instead.

Not at all annoying. Thank you for your help.

**Comment by lithiumtoast** [comment]
Likely a problem with MGCB itself. Glad you figure it out!

**Comment by slanger** [comment]
Note: Forward slashes in the MGCB reference path *do* work on Windows (tested with MonoGame version 3.8.0.1641). For example, see https://github.com/slanger/zelda-online/commit/f060f71994ba266163fd71277dc3fe03dacc9311. I noticed that in [this comment](https://github.com/craftworkgames/MonoGame.Extended/issues/714#issuecomment-749081919), the reference file path begins with 4 `..`s, but in [this comment](https://github.com/craftworkgames/MonoGame.Extended/issues/714#issuecomment-749902388),  the path begins with 5 `..`s. This might be why you were having issues instead of the forward slashes vs. back slashes in the file path.
