### ISSUE TITLE
GUI Package

### ISSUE THREAD

**Issue by J23t** [craftworkgames/MonoGame.Extended#716]
When I tried out the GUI I couldn't get skinning to work. #646 
Seems like a lot of the GUI package is in disarray and with GUI code being removed/commented out from the samples. (Skinning, Screens from XML, View from a MGEML file?) _I'm not a fan of hardcoding._

What is the status of MonoGame.Extended.GUI?

**Comment by lithiumtoast** [comment]
Yup, there are other libraries that are dedicated to UI in MonoGame which I recommend such as Myra: https://github.com/rds1983/Myra. Right now I only have so much time to work on Extended and GUI is not on the priority list.

**Comment by lithiumtoast** [comment]
Also, highly recommend ImGUI for basic needs such as editors: https://github.com/mellinoe/ImGui.NET

**Comment by J23t** [comment]
I'm using EmptyKeys.UI. It's going to have to stay until I have something better. 

CocosSharp _was_ built from MonoGame and used Xamarin.Forms but it seems dead.

[Maui](https://github.com/dotnet/maui) evolution of xamarin.forms is coming to dotnet6.

I'll look into ImGUI. Thanks.

**Comment by vchelaru** [comment]
For MonoGame.Extended 4.0 and later the recommended UI library is Gum:

https://www.monogameextended.net/docs/features/ui/gum/gum-forms/
