### ISSUE TITLE
More basic shapes for collision detection

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#72]
We currently have one shape (a circle) in the MonoGame.Extended.Shapes namespace. There's room for a few more. Given that one of the use cases will be collision detection I think it makes sense to look at the shapes found in a typical physics engine.

Farseer Physics [has a few](http://farseerphysics.codeplex.com/SourceControl/latest#SourceFiles/Collision/Shapes/PolygonShape.cs) including Polygon, Chain and Edge. Although, these are not all technically "shapes" they can be used to make shapes.

Even though a typical use case for the the shapes will be collision detection, we need to be careful not to leak the responsibility of the physics engine into our shape classes. The idea would be to keep our shapes similar to MonoGame's [Rectangle](https://github.com/mono/MonoGame/blob/5f4b70005804891ee6e819ffcf26c396a307a3ca/MonoGame.Framework/Rectangle.cs).

We may provide another enhancement in the future consisting of extension methods to convert them to and from physics shapes in the future. However, this shouldn't live in the core library as it will take a dependency on Farseer (or whatever) physics engine.

**Comment by LithiumToast** [comment]
> We may provide another enhancement in the future consisting of extension methods to convert them to and from physics shapes in the future.

If you mean collision geometry I could do that without too much effort. They are all 2D shapes right?

**Comment by craftworkgames** [comment]
> They are all 2D shapes right?

Yeah, let's focus on 2D for now. I'd rather have a good 2D focused library than a kind of okay 2D/3D library.

**Comment by craftworkgames** [comment]
I'm pretty happy with the shapes we have now.

    CircleF
    PolygonF
    RectangleF
    RectangleExtensions

I'll close this issue..

@LithiumToast When it comes to collision geometry, we'll deal with that when we get to it. Probably don't need to discuss it any further on this issue.
