### ISSUE TITLE
Tiled Tiles are rendering at roughly a half pixel offset for some reason.

### ISSUE THREAD

**Issue by kryzp** [craftworkgames/MonoGame.Extended#720]
Hello! I've been trying out the monogame.extended.tiled package and so far most things work great! Apart from the tiles that is.
It might just be a problem in my settings, but the tiles are strangely offset by about half a pixel in the final render:
  
![image](https://user-images.githubusercontent.com/48471657/106298576-f2c50700-624b-11eb-9819-858c8ba66d5d.png)
![image](https://user-images.githubusercontent.com/48471657/106298647-0cfee500-624c-11eb-932c-9953b2b423fd.png)

In tiled, everything seems completely fine, I've even tried giving/removing padding from the tiles, to no avail.

And it isn't an issue with my camera either, I've tried scaling it up, down and moving its position but nothing seems to fix the issue.

Any help would be appreciated, thank you in advance!

EDIT: After looking into it seems like someone else had the same problem as me in #476 but it seems like the issue has resurfaced...

**Comment by kryzp** [comment]
Alright, so I've found the source of the issue:
In TiledMapLayerModelBuilder.cs the
```var texelLeft = (sourceRectangle.X + 0.5f) * reciprocalWidth```
 and
 ```var texelTop = (sourceRectangle.Y + 0.5f) * reciprocalHeight```
Just need to get the '+ 0.5f' removed, and then the tiles work just fine!

**Comment by lithiumtoast** [comment]
What OS+arch+graphicsAPI you have the problem and fix on?

**Comment by kryzp** [comment]
Apologies for not updating this post, I've created a pull request which fixed the issue for me.

**Comment by lithiumtoast** [comment]
❓
