### ISSUE TITLE
Values of autoTrigger and autoTriggerDelay are ignored

### ISSUE THREAD

**Issue by SjaakAlvarez** [craftworkgames/MonoGame.Extended#722]
https://github.com/craftworkgames/MonoGame.Extended/blob/fce644e62f58542c77e0f7151261d514811cb026/src/dotnet/MonoGame.Extended.Particles/ParticleEffect.cs#L14

**Comment by AristurtleDev** [comment]
The `AutoTrigger` and `AutoTriggerDelay` functionality of the `ParticleEffect` class was moved to the `ParticleEmitter` in commit https://github.com/craftworkgames/MonoGame.Extended/commit/92600bc5b82d01b047c91440a1ed37d8912384d5.

They were later removed from the constructor in commit https://github.com/craftworkgames/MonoGame.Extended/commit/04a563680162debc217a0791374d76b898cac497
