### ISSUE TITLE
Entity.Detach() method doesn't invoke EntityChanged until next Update of EntityManager

### ISSUE THREAD

**Issue by SjaakAlvarez** [craftworkgames/MonoGame.Extended#723]
When calling Detach() to remove a component, the entity is not updated until the next Update of the EntityManager.

For example:

When I Detach a component in a EntityProcessingSystem, the component bit is still set in the next EntityDrawSystem Update and the entity is still part of the ActiveEntities which might crash the code.

A quick and dirty solution is to modify EntityManager.OnComponentsChanged to:

```
private void OnComponentsChanged(int entityId)
{
    _changedEntities.Add(entityId);
    _entityToComponentBits[entityId] = _componentManager.CreateComponentBits(entityId);
    EntityChanged?.Invoke(entityId);
}
```

**Comment by AristurtleDev** [comment]
This was resolved in #724
