### ISSUE TITLE
PrimitivesHelper.IntersectSlab is not properly swapping two values

### ISSUE THREAD

**Issue by mattj1** [craftworkgames/MonoGame.Extended#726]
https://github.com/craftworkgames/MonoGame.Extended/blob/fce644e62f58542c77e0f7151261d514811cb026/src/dotnet/MonoGame.Extended/Math/PrimitivesHelper.cs#L26

Line 26 should actually say 
```var temp = rayNearDistance;```

**Comment by lithiumtoast** [comment]
Hmm, this is an actual bug.
