### ISSUE TITLE
[BitmapFont] Invalid text offset on consecutive lines in multi-line text when using `StringBuilder`

### ISSUE THREAD

**Issue by qivio** [craftworkgames/MonoGame.Extended#729]
When using `DrawString` extension method with `BitmapFont` and `StringBuilder` parameter on a multi-line text, the offset of subsequent lines becomes corrupted. This is due to offset not being reset properly after line feed (LF) character at [BitmapFont.cs:322](https://github.com/craftworkgames/MonoGame.Extended/blob/239fa04ca12908683f1cdf699b63066c33ba57b7/src/dotnet/MonoGame.Extended/BitmapFonts/BitmapFont.cs#L322). Compare to how it's done for `String` input at [BitmapFont.cs:204](https://github.com/craftworkgames/MonoGame.Extended/blob/239fa04ca12908683f1cdf699b63066c33ba57b7/src/dotnet/MonoGame.Extended/BitmapFonts/BitmapFont.cs#L204).

**Comment by AristurtleDev** [comment]
I am unable to reproduce this issue based on the information provided.  It may have been resolved prior and included in the v4.0.0 release?  If you are still experiencing this problem, please open a new issue with minimum reproduction steps or a minimum reproduction example.



![Image](https://github.com/user-attachments/assets/282f3568-dc68-4c1f-b4b1-f5abf281bdf5)
