### ISSUE TITLE
Support for the Overlap2D level editor

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#73]
I just came across this awesome looking level editor. It's written in Java but the website says it's not tied to any specific game engine. This [youtube video](https://www.youtube.com/watch?v=I0g-t0nZ-qE) shows the things it can do.

I haven't managed to get it working on my machine but it could be worth watching.

**Comment by LithiumToast** [comment]
Please disregard my commit reference :sweat:

**Comment by InfiniteProductions** [comment]
@craftworkgames: for what it worth, it works on my win 7 64b computer with the latest java package (build 1.8.0_73-b02).

Regarding the tool itself: demo is nice but the important matter is what exactly was exported, in which format and how much usable it is in MG(.Ext), as lights and UI things won't work as-is out-of-the-box like magic I guess (it would be far too easy).

**Comment by craftworkgames** [comment]
I've had a play with it since I originally wrote this issue. The tool has some good ideas but still felt very buggy and prototypey. I'm still interested in considering it for the future but probably not anytime soon.
