### ISSUE TITLE
[Tiled] Tiled Tiles are rendering at roughly a half pixel offse

### ISSUE THREAD

**Issue by MoJongleur** [craftworkgames/MonoGame.Extended#736]
![lines](https://user-images.githubusercontent.com/41997306/121356012-e8c5ba00-c949-11eb-9c69-eca198a5525a.PNG)

I took an example from the Tiles documentation and am getting tiles like this(screenshot). How can I fix this? i already install 3.9v but it did not help.

**Comment by lithiumtoast** [comment]
DirectX or OpenGL?

**Comment by MoJongleur** [comment]
> DirectX or OpenGL?

OpenGL

**Comment by lithiumtoast** [comment]
Could checkout the commit before this PR #721 was merged and see if the problem still exists?

**Comment by MoJongleur** [comment]
Do I understand correctly that the merged is missing in version 3.8?

if so, yes, the problem is there too

**Comment by lithiumtoast** [comment]
Could you share a minimal project with the problem?

**Comment by MoJongleur** [comment]
[test.zip](https://github.com/craftworkgames/MonoGame.Extended/files/6628231/test.zip)

Here is only the code from the example in the documentation

**Comment by MoJongleur** [comment]
I've tried generating and using my own .dll with and without changes from [720](https://github.com/craftworkgames/MonoGame.Extended/issues/720), [476](https://github.com/craftworkgames/MonoGame.Extended/issues/476), nothing helped. Updating .NET / .NET Core/ DirectX also didn't help.

I did not write above, but I am using win 10

**Comment by lithiumtoast** [comment]
Issue is you need to set the how the texture is filtered before you render the map.

```
GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
```
