### ISSUE TITLE
Flaging of monogame.extended specific posts on SO.

### ISSUE THREAD

**Issue by stromkos** [craftworkgames/MonoGame.Extended#737]
I have created a new tag on stackoverflow for questions specific to monogame.extended .

I have no clue as to reason why it was not defined before, but I am asking for you and everybody to go though the "monogame" tagged questions specifically and edit the questions specific to MonoGame.Extended to include the "MonoGame.Extended" tag,

I have attempted to answer questions on SO about sprites/screens without knowing the base class of the source of the code(thinking that the unknown code was locally generated).

I am asking everyone that reads this to fix this situation by editing questions(or purposing edits on SO) for every question specific to MonoGame.Extended.

@craftworkgames, Why did this SO change take my effort? You have been active longer than me.(your project is worthy of a catagory)

**Comment by dylanwilson80** [comment]
There's been a [`monogame-extended`](https://gamedev.stackexchange.com/questions/tagged/monogame-extended) tag on the GameDev Stack Exchange for some years now. This is where most of the questions are asked and if you ask a game dev question on SO you're often directed to the GameDev Stack Exchange site.

**Comment by stromkos** [comment]
While that is true, many posts related to  Monogame.Extended still end up on SO. It is worthy of a distinct tag.   All I am asking is for help with the existing posts on SO are reclassified with the appropriate tag."

"If you ask a game dev question on SO you're often directed to the GameDev Stack Exchange site." I have not seen this at all with MonoGame questions. They may be transferred more often than I visit the site.

Some posts still end up persisting on SO, and need to be differentiated from Monogame(the only existent tag until now.)

**Comment by dylanwilson80** [comment]
> I have not seen this at all with MonoGame questions.

Keep in mind that I haven't been using MonoGame or answering questions on SO for a probably a couple of years now. I was just trying to explain why things are the way they are. Things are always changing and I think it's awesome if you're taking the initiative to make improvements. Every small change adds up.

**Comment by stromkos** [comment]
Thank you.  I understand about the break, I needed and took one myself. When I returned, the first question I encountered was monogame.extended specific. I was surprised there was not a tag existent.  So I created one. 

Many of the single question tags get deleted, and most first timers ask on SO.  Hence the request.  

I will close close issue this if you want.

**Comment by AristurtleDev** [comment]
Closing as this is not an issue with the project.
