### ISSUE TITLE
[ECS] Add the ability to subscribe to put/delete in component mapper

### ISSUE THREAD

**Issue by GrizzlyEnglish** [craftworkgames/MonoGame.Extended#743]
This is just a thought: Similar to what is already in place where you can subscribe a system to entity changes, if mappers were to have change subscriptions this would allow for processing entities that got new components one time.

event OnPut
event OnDelete

For Example:

I am working a "fatigue" system that when an entity moves before their turn it generates fatigue on the character. I only want to process this when the entity gets a movement component attached once.

There are current ways to handle this yes, just thought this would be a simpler solution.

**Comment by AristurtleDev** [comment]
Closing issue, this was merged in #744
