### ISSUE TITLE
Tiled: unable to render to specific location

### ISSUE THREAD

**Issue by AndrewCS149** [craftworkgames/MonoGame.Extended#750]
I am creating a 2D RPG style game. I am using the Comora package to have a camera that follows the player. With this, the camera should always project the player in the very center of the screen and I can move around the map freely (just like Stardew Valley). My issue is that I can't seem to render the TMX map in a way that allows me to move around the map. It seems to always be projected as the game windows background so the result is that it looks like the player is not moving. Here is my simplified code for rendering the TMX map. 

```csharp

protected override void LoadContent() 
{
  tiledMap = Content.Load<TiledMap>("Path/to/map");
  mapRenderer = new TiledMapRenderer(GraphicsDevice);
  bottomLayer = tiledMap.GetLayer("bottomLayer");
  topLayer = tiledMap.GetLayer("topLayer");
  mapRenderer.LoadMap(tiledMap);
}

protected override void Update(GameTime gameTime) 
{
    mapRenderer.Update(gameTime);
}

protected override void Draw(GameTime gameTime)
{
  _spriteBatch.Begin(Camera);
  mapRenderer.Draw(bottomLayer);
  mapRenderer.Draw(topLayer);
  _spriteBatch.End();
}
```

Please let me know if I need to elaborate on my issue and thank you in advance for any help.

**Comment by lithiumtoast** [comment]
https://www.monogameextended.net/docs/features/tiled/tiled#adding-a-camera
