### ISSUE TITLE
Orthographic Camera not directly looking at moving sprite.

### ISSUE THREAD

**Issue by AndrewCS149** [craftworkgames/MonoGame.Extended#751]
I am trying to get an orthographic camera to follow a moving sprite. I should be able to move the player around freely on the map with the player always directly centered on the screen with the camera. For some reason, the player seems to move a bit faster than the camera, which will then result in the player moving completely off screen at some point. The sprite is also not positioned center mass from the start which I also cannot figure out as to why. Pictures below.

On startup:
![image](https://user-images.githubusercontent.com/52691521/147859746-a9c45006-483a-4965-818c-c14f8f1ffaf6.png)

Moving player to the right:
![image](https://user-images.githubusercontent.com/52691521/147859754-0ecfa571-a9e3-4cfe-821e-5a21a8094fb8.png)

Moving player to bottom: 
![image](https://user-images.githubusercontent.com/52691521/147859761-fc4b534c-7274-4379-86e7-a502852b35c9.png)

Also here is a short video demonstrating what I talking about.
https://user-images.githubusercontent.com/52691521/147859966-8afc2784-7975-4a22-a578-f0b15a94f746.mp4

As shown above, you can see that the sprite is moving a little bit faster than the camera. I'm wanting the player to always be in the camera's center mass. I followed these [docs ](https://www.monogameextended.net/docs/features/tiled/tiled) as best I could. Here is some simplified code from my project:

```csharp

public override void Initialize()
{
    var viewportAdapter = new BoxingViewportAdapter(_gameWindow, _graphics, 960, 540);
    
    _player = new Player()
    {
        Position = new Vector2(1000, 300),
        Camera = new OrthographicCamera(viewportAdapter),
    };
}

public override void Update(GameTime gameTime)
{
    float delta = (float)gameTime.ElapsedGameTime.TotalMilliseconds * .25f;
    var kState = Keyboard.GetState();

    // up
    if (kState.IsKeyDown(Keys.W))
        _player.Position.Y -= _player.Speed * delta;

    // down
    if (kState.IsKeyDown(Keys.S))
        _player.Position.Y += _player.Speed * delta;
    
    // left
    if (kState.IsKeyDown(Keys.A))
        _player.Position.X -= _player.Speed * delta;
    
    // right
    if (kState.IsKeyDown(Keys.D))
        _player.Position.X += _player.Speed * delta;

    // update camera position
    _player.Camera.LookAt(_player.Position);
}

public override void Draw(GameTime gameTime)
{
   _spriteBatch.Begin();

    map.MapRenderer.Draw(player.Camera.GetViewMatrix());
    player.AnimationManager.Draw(_spriteBatch, player.Position.X, player.Position.Y, 
    player.Width, player.Height);  

    _spriteBatch.End();
}
```

Thank you for any help!

**Comment by lithiumtoast** [comment]
First thing to try:

You need to normalize the movement vector after adding it with 4 directions.

**Comment by AndrewCS149** [comment]
Thanks @lithiumtoast.  I believe I did try that initially and didn't get a successful result. I'll give it a try again and update the thread

**Comment by janfokke** [comment]
Your spritebatch doesn't use the camera matrix

`_spriteBatch.Begin(transformMatrix: player.Camera.GetViewMatrix());`

**Comment by AndrewCS149** [comment]
@janfokke WORKED. Thank you!

@lithiumtoast I tried normalizing the vector and it caused the character to not be able to move at all.

**Comment by lithiumtoast** [comment]
Normalize the movement direction, not the position itself.
