### ISSUE TITLE
ContentFiles from Nuget package ending up directly in Visual Studio project

### ISSUE THREAD

**Issue by AntonLuning** [craftworkgames/MonoGame.Extended#752]
My Visual studio project is being filled up by the ContentFiles attached to the nuget package. I have ever encountered this before with different Nuget packages and find it a bit annoying scrolling through my project tree when it is filled with an imported packages files.
![image](https://user-images.githubusercontent.com/74569454/148126987-590006f1-b04b-401c-8e77-997bc63a71f5.png)

**Comment by lithiumtoast** [comment]
That's `MonoGame`, not `MonoGame.Extended`. If you remove the `MonoGame.Extended` package, the problem will presist.

The issue is the `.props` and `.targets` file: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/MonoGame.Content.Builder.targets#L98
