### ISSUE TITLE
how long does approval of pullrequests usually take?

### ISSUE THREAD

**Issue by codymanix** [craftworkgames/MonoGame.Extended#757]
I created a PR for adding a small feature to monogame.extended.particles a few days ago, but I got no feedback yet.

The change is a few lines only. it enabled paricular z-layerdepths for created particles, which defaulted to 0.0f in the version before.

**Comment by lithiumtoast** [comment]
I can take a look when I can this weekend.

**Comment by codymanix** [comment]
I answered to your comment in the PR.
