### ISSUE TITLE
Inconsistency between KeyboardStateExtended.WasKeyJustDown and MouseStateExtended.WasButtonJustDown

### ISSUE THREAD

**Issue by williamhCode** [craftworkgames/MonoGame.Extended#760]
### The Problem
```KeyboardStateExtended.WasKeyJustDown``` checks if the previous keyboard state was down, and if the current keyboard state is Up.
https://github.com/craftworkgames/MonoGame.Extended/blob/c90365211eaae3ed092d748230f4cbebe490d1b9/src/cs/MonoGame.Extended.Input/KeyboardStateExtended.cs#L26

However, ```MouseStateExtended.WasButtonJustDown```,
https://github.com/craftworkgames/MonoGame.Extended/blob/c90365211eaae3ed092d748230f4cbebe490d1b9/src/cs/MonoGame.Extended.Input/MouseStateExtended.cs#L66
which calls the ```WasJustPressed``` method, checks if the previous mouse state was up, and if the current mouse state is down.
https://github.com/craftworkgames/MonoGame.Extended/blob/c90365211eaae3ed092d748230f4cbebe490d1b9/src/cs/MonoGame.Extended.Input/MouseStateExtended.cs#L98

This inconsistency makes it confusing especially when using the keyboard and mouse extended functions alongside, because ```Was__JustDown``` has the opposite meaning when comparing the keyboard and mouse.

### The Solution
If we look at the literal meaning of the function, then it makes sense to reverse the ```MouseStateExtended.WasJustPressed``` method with ```WasJustReleased```.

If we want to go for clarity however, I suggest changing the names of both the ```KeyboardStateExtended``` and ```MouseStateExtended``` functions from ```Was__JustDown``` and ```Was__JustUp``` to something like ```Is__Released``` and ```Is__Pressed``` because when most people use, for example ```WasButtonJustDown```, they actually mean did they just release the button, and having the word "down" is counter-intuitive.

Furthermore, since the naming of ```Is__Released``` and ```Is__Pressed``` overlaps with Monogame's ```ButtonState.Pressed``` and ```ButtonState.Released``` and may pose to be confusing, they can be named to something like ```Is__ReleasedOnce``` and ```Is__PressedOnce```.

### Proposed Changes
Proposed Changes for Least Effort:
Rename -
```MouseStateExtended.WasJustPressed``` to ```MouseStateExtended.WasJustReleased```,
```MouseStateExtended.WasJustReleased``` to ```MouseStateExtended.WasJustPressed```.

Proposed Changes for Clarity:
Rename -
```MouseStateExtended.WasJustPressed``` to ```MouseStateExtended.WasJustReleased```,
```MouseStateExtended.WasJustReleased``` to ```MouseStateExtended.WasJustPressed```,
```MouseStateExtended.WasButtonJustDown``` to ```MouseStateExtended.IsButtonReleased``` or ```MouseStateExtended.IsButtonReleasedOnce```,
```MouseStateExtended.WasButtonJustUp``` to ```MouseStateExtended.IsButtonPressed``` or ```MouseStateExtended.IsButtonPressedOnce```,

```KeyboardStateExtended.WasKeyJustDown``` to ```KeyboardStateExtended.IsKeyReleased``` or ```KeyboardStateExtended.IsKeyReleasedOnce```,
```KeyboardStateExtended.WasKeyJustUp``` to ```KeyboardStateExtended.IsKeyPressed``` or ```KeyboardStateExtended.IsKeyPressedOnce```.

**Comment by damian-666** [comment]
if you look at Nez that have all this in a standard way and it might me in monogame core as well.  I poll the  state on a bk thread at up to 900hz.. so i dont miss any.    also it maps the controllers to keys.. and thre is some touch logic.. onkeypressed, onkeyreleased..  ( happens once)  thas it.  and ther is iskeydown to chekc the state...theres a click cound and timer as well.         anyways prs are not getting mreged.   i have other issues where i cant fork because of that.  i will have ot take a snapshot.. im not suing this but i hit the sponsport button.. it takes likje an hour to merge the tow prs or it wont work in net6.. not everyone is using that..  toom me 6 weeks ..so  might need to keep old branch with 4.8 and netstandard i dont...
