### ISSUE TITLE
requirement needed?

### ISSUE THREAD

**Issue by ghost** [craftworkgames/MonoGame.Extended#761]
Hi

In the installation docs is written .NET Core 3.1 SDK is needed.
If I want to use.NET 6.0 or 5.0, do I need to install this SDK too?

If yes, should I install it through visual studio installer or by manually downloading it from microsoft website?

**Comment by damian-666** [comment]
i think i did it through the microsoft website.. and sadly the order in
your path might give you trouble so i hope it works.   i think i installed
the olderones last.     i just got lucky and didnt have to mess wit the
path,   yes it sucks ...but its worth it to have net 6..

**Comment by lithiumtoast** [comment]
You can have multiple SDKs installed at once. Use the `dotnet --list-sdks` in terminal to list which ones are installed along with their installation directories on disk.

My macOS machine:
```
3.1.413 [/usr/local/share/dotnet/sdk]
5.0.401 [/usr/local/share/dotnet/sdk]
6.0.100-rc.2.21505.57 [/usr/local/share/dotnet/sdk]
6.0.100 [/usr/local/share/dotnet/sdk]
```

**Comment by lithiumtoast** [comment]
You should be able to use a .NET Core project in .NET 5 or .NET 6. Let me know if it's not possible and I'll update it.

**Comment by Shpendicus** [comment]
@lithiumtoast  it absolutely works fine for me ! I am using even .net 7 prev 1 with current Monogame :)

**Comment by monogamefan** [comment]
Yes i can confirm. It works on each .net
