### ISSUE TITLE
visual studio project weird files

### ISSUE THREAD

**Issue by ghost** [craftworkgames/MonoGame.Extended#762]
Hi

I have the same problem as https://github.com/craftworkgames/MonoGame.Extended/issues/752

When installing MonoGame.Extended 3.8.0 I get those weird files in my visual studio project

![afbeelding](https://user-images.githubusercontent.com/101529915/162016979-ccef854e-629e-4ee2-af0b-4bc363a7e488.png)

Please don't say it has nothing to do with MonoGame.Extended because when uninstalling MonoGame.Extended the files are gone.
So when only using MonoGame without MonoGame.Extended package, the files are not there.

Can it be fixed please?

**Comment by lonely-unicorn** [comment]
Here you can see it are the content files of MonoGame.Extended

![afbeelding](https://user-images.githubusercontent.com/101529915/162017566-88913f2c-7387-49fc-9971-13c2b2198a81.png)

**Comment by monogamefan** [comment]
Hello

I have the same problem.
Is there a fix already?

**Comment by damian-666** [comment]
you should erase all that and put Nuget dependency instead then build, diff
the project files and such and submit a PR if you use it... i thik its kind
of unmaintained as a whole....pieces are used here and there so people just
take parts out.

**Comment by monogamefan** [comment]
I'm a beginner and can't do this at all.
I'm looking for somebody who can fix the nuget package so I can use it correctly.
Do you want to do it?

I'm also wondering what Tiled version is supported in the package since I can't find any information.

**Comment by lithiumtoast** [comment]
Looks like extra files are in that NuGet package specifically.

You can simply edit your `.csproj` file to exclude those files:
```xml
    <ItemGroup>
      <PackageReference Include="MonoGame.Extended" Version="3.8.0">
          <ExcludeAssets>contentFiles</ExcludeAssets>
      </PackageReference>
    </ItemGroup>
```

**Comment by monogamefan** [comment]
Can't you release a fixed nuget package? I can't edit each time for each of my projects this file again...

What Tiled version number is supported in MonoGame.Extended?

**Comment by lithiumtoast** [comment]
> I can't edit each time for each of my projects this file again...

It's really not that hard. You open up your `.csproj` file and edit it by hand. Using a find and replace can make it even faster.

> Can't you release a fixed nuget package? 

No. All time and effort is put towards Katabasis.

> What Tiled version number is supported in MonoGame.Extended?

I don't remember.

**Comment by monogamefan** [comment]
Euhm you don't give any information I can use. Is this project abandoned?

What is Katabasis?!?

**Comment by monogamefan** [comment]
Will MonoGame.Extended nuget package be updated when there is a new MonoGame so it's compatible with latest MonoGame?
I'm depending on it for my game.

**Comment by lithiumtoast** [comment]
>  Is this project abandoned?

No. It's in maintenance phase of the software development life cycle.

> What is Katabasis?

The next version of MonoGame.Extended

> Will MonoGame.Extended nuget package be updated when there is a new MonoGame so it's compatible with latest MonoGame?

Yes.

**Comment by monogamefan** [comment]
Ah ok!
So Katabasis will be updated along with MonoGame releases?

Is there a repository already of Katabasis?

thx
