### ISSUE TITLE
Windows 10 UWP project/ use different version of sharpdx/can not compile

### ISSUE THREAD

**Issue by songshizhao** [craftworkgames/MonoGame.Extended#767]
Windows 10 UWP project/ use different version of sharpdx/can not compile
1.build a prj with Monogame template[UWP]
2.install package monogame.extend
3.can not compile

Error The payload contains two or more files with the same target path "SharpDX.dll", but they are of different sizes. Source File:
C:\Users\Administrator\.nuget\packages\sharpdx\4.0.1\lib\uap10.0\SharpDX.dll
C:\Users\Administrator\.nuget\packages\monogame.extended\3.8.0\contentFiles\any\netstandard2.0\SharpDX.dll	MyPlatformGame

**Comment by AristurtleDev** [comment]
Closing this issue since MonoGame is dropping the UWP template
