### ISSUE TITLE
monogame update

### ISSUE THREAD

**Issue by ghost** [craftworkgames/MonoGame.Extended#779]
Hello

Monogame 3.8.1 is released recently.
Would it be possible to update monogame extended so it works with 3.8.1?

Thank you

**Comment by Apostolique** [comment]
What doesn't work for you? I tried on some of my projects with no issues so far.

**Comment by lithiumtoast** [comment]
Hello @rocketpowergirl

> Would it be possible to update monogame extended so it works with 3.8.1?

 Thanks for pointing this out, I will do it this weekend when I have the time to do it justice.

**Comment by rocketpowergirl** [comment]
> What doesn't work for you? I tried on some of my projects with no issues so far.

Because MonoGame 3.8.1 is using .NET 6.0 exclusively, I thought it would be good to update monogame extended because this is not using .NET 6.0 yet. Who knows what hidden problems otherwise could occur. But as you said, it seems to keep working.

**Comment by NikolasDN** [comment]
I recently updated my project to .NET 6.0, monogame 3.8.1, and the TiledMapProcessor doesn't work any more.
`Processor 'TiledMapProcessor' had unexpected failture!`

**Comment by CodeRabbit957** [comment]
Is this change part of the current stable release? 
I'm currently having issues with TiledMapProcessor expecting an older release of Monogame.

**Comment by lithiumtoast** [comment]
@CodeRabbit957 you can try the packages `https://www.myget.org/feed/lithiumtoast/package/nuget/MonoGame.Extended` using the NuGet source feed `https://www.myget.org/F/lithiumtoast/api/v3/index.json`

**Comment by CodeRabbit957** [comment]
Tried it, but it doesn't appear to be resolving the error. Maybe the issue I'm having is with the Tiled package rather than Extended?

**Comment by ancientpharaoh** [comment]
Whe are you going to update monogame extended to 3.8.1?
In the year 2030, 2040 or 2050?
There are probleme everywhere!
Can you please update it and fix it so we can use as it should be?

**Comment by lithiumtoast** [comment]
Hey @ancientpharaoh

I have plans to rehaul MonoGame.Extended and keep it somewhat on track with the FNA work which is [Katabasis](https://github.com/bottlenoselabs/katabasis).

To do so I need to upgrade the [C2CS](https://github.com/bottlenoselabs/c2cs) project which generates bindings for the all the C library dependencies of FNA automatically and other C dependencies I wish to bring in like [Flecs](https://github.com/SanderMertens/flecs). Having a solid foundation with C libraries with automation of generating bindings is critical for future paths of MonoGame/FNA/Katabasis and, in my opinion, is more worthy of my time than updating the NuGet package.

Your options:
1. Fork/clone the MonoGame.Extended repository and build it from source; everything is reported to be working.
2. Sponsor me by paying me money to fix the NuGet package and have it working correctly when it is uploaded to MyGet.org.
3. Contribute with a fork which demonstrates how to fix the problem with a free NuGet feed like myget.org. I will gladly update the NuGet.org feed when I know everything works correctly first on a feed which can be deleted for development purposes. Once a package is pushed to MyGet.org it can't be deleted. It can be delisted but it still pollutes their servers with data.
4. Wait until I'm ready to dump my time into this project when I'm already dumping my time outside of my 40 hours of week and my regular life into multiple projects.

Have a good day!

**Comment by damian-666** [comment]
Those are all amazing projects that you pointed  out ..
re: C2Cs does Silk .net have anything you can use?    I monitor it along wi 20 other vaults and 100s of research papers,  but it's slowing down a bit lately.  They commit tons of generated code, it's not part of the build process to generate code, but seems like the way to bind these c and c++apis.

 I think it's ok you have  unmerged PRs.. combining  those, peoplecan solve their own forks, as I could for wpf host.

  Theres just too many options, trying to future proof it's overwhelming.  but I think I have good enough tools and graphics  tech now, w net7 mg 3.8.1 even if some parts are archived or  legacy or fading.away, or could be 100x.faster ,  if I don't  ship some. art  physics game soon or I won't have a future lol

**Comment by AristurtleDev** [comment]
MonoGame.Extended has been updated in the `develop` branch for MonoGame 3.8.1.303.

Until the MonoGame.Extended v4.0.0 release you can use one of the following workaround
1. Use the source code of MonoGame.Extended directly and reference it in your project
2. Use the most recent (at the time of writing this) prerelease NuGet https://www.nuget.org/packages/MonoGame.Extended/3.9.0-prerelease.4
