### ISSUE TITLE
Couldn't MonoGame.Extended in NuGet in VS2015

### ISSUE THREAD

**Issue by lionelthomas** [craftworkgames/MonoGame.Extended#78]
This is not a major issue but would be nice to keep up-to-date through VS2015

**Comment by craftworkgames** [comment]
I'm using VS2015. I don't understand the problem? Are you saying the NuGet package is out of date? 

Version 0.4 is still a work in progress so it hasn't been published on NuGet.org yet. 

If you want to try the latest unstable build through NuGet we do publish them on our own build server.

http://build.craftworkgames.com/guestAuth/app/nuget/v1/FeedService.svc/

**Comment by lionelthomas** [comment]
When I search for MonoGame.Extended in the NuGet Launcher Windows it gives no items found. Never used NuGet before so I am unsure of how it is supposed to work.

**Comment by craftworkgames** [comment]
Try setting the include pre-release flag. 

I was planning on keeping it pre release until version 1.0 but I don't think it's providing any benefit. I might turn it off in the next release.

**Comment by craftworkgames** [comment]
I've turned off pre-prelease from version 0.4 onward.

The incremental CI builds produced by our build system are marked pre-release, but each official release will be normal.

For example, the last official release was 0.4.64.

The build system is currently producing 0.5.11-beta (pre-release). When version 0.5 is officially released the `-beta` will be removed from the NuGet package.
