### ISSUE TITLE
Couldn't install Samples.Extended.Windows

### ISSUE THREAD

**Issue by lionelthomas** [craftworkgames/MonoGame.Extended#79]
Downloaded zip file and copied extracted file Samples.Extended-master to vs2015 projects folder.
Opened windows solution with VS2015. Did a Build.
Started debugging, stopped at this statement
 _bitmapFont = Content.Load<BitmapFont>("montserrat-32"); in Game1
Could not load montserrat-32 asset as a non-content file!
Was I supposed to create content  before running sample?
Thanks.

**Comment by craftworkgames** [comment]
There's an open issue about this.

https://github.com/craftworkgames/Samples.Extended/issues/5

The recommended workaround is to install the MonoGame for Visual Studio 3.5 development build.

http://www.monogame.net/downloads/

This issue is really starting to bother me, since it's blocking people with MonoGame 3.4. I think I'll get it moving again.

**Comment by lionelthomas** [comment]
I downloaded MonoGame 3.5 and installed it but this did not fix the problem in Samples.Extended. It did however cause the build of my game project to hang during, so I reinstalled 3.4 and my project now builds again. Not sure what this means.

**Comment by craftworkgames** [comment]
That is truly a mystery.

One last thing to try. Remove the reference to MonoGame.Framework.dll 3.5 from the samples project and add a reference to your 3.4 version.

The only reason we use 3.5 is multi platform compatibility (i.e  Linux)

**Comment by lionelthomas** [comment]
I'm a bit confused on which MonoGame dll to reference so I reference the Windows version and now I get these compile errors:
Severity	Code	Description	Project	File	Line
Error	CS1061	'GameWindow' does not contain a definition for 'Icon' and no extension method 'Icon' accepting a first argument of type 'GameWindow' could be found (are you missing a using directive or an assembly reference?)	Samples.Extended	C:\Users\Lionel\Documents\Visual Studio 2015\Projects\Samples.Extended-master\Samples.Extended-master\Source\Samples.Extended\Game1.cs	38
Error	CS1061	'GameWindow' does not contain a definition for 'Position' and no extension method 'Position' accepting a first argument of type 'GameWindow' could be found (are you missing a using directive or an assembly reference?)	Samples.Extended	C:\Users\Lionel\Documents\Visual Studio 2015\Projects\Samples.Extended-master\Samples.Extended-master\Source\Samples.Extended\Samples\ViewportAdaptersSample.cs	33
Error		Metadata file 'C:\Users\Lionel\Documents\Visual Studio 2015\Projects\Samples.Extended-master\Samples.Extended-master\Source\Samples.Extended\bin\Debug\Samples.Extended.dll' could not be found	Launcher.Windows	C:\Users\Lionel\Documents\Visual Studio 2015\Projects\Samples.Extended-master\Samples.Extended-master\Source\Launcher\CSC	

?????

**Comment by craftworkgames** [comment]
Delete [line 38](https://github.com/craftworkgames/Samples.Extended/blob/master/Source/Samples.Extended/Game1.cs#L38) from `Game1.cs`

    Window.Icon = new System.Drawing.Icon("Icon.ico");

Apparently they changed or removed the Icon property in MonoGame v3.5.

**Comment by lionelthomas** [comment]
Well, what an infernal waste of time. When I set the references from the list it gave me windows8 no matter what I selected. Now I selected explicitly windows version and everything works.
Issue closed.
