### ISSUE TITLE
HslColor.cs Simple Lerp Bug

### ISSUE THREAD

**Issue by TriggerJock** [craftworkgames/MonoGame.Extended#809]
In HslColor.cs there is a bug preventing Lerp from interpolating the Lightness parameter.  Looks like a simple typo:

        public static HslColor Lerp(HslColor c1, HslColor c2, float t)
        {
            // loop around if c2.H < c1.H
            var h2 = c2.H >= c1.H ? c2.H : c2.H + 360;
            return new HslColor(
                c1.H + t*(h2 - c1.H),
                c1.S + t*(c2.S - c1.S),
                c1.L + t*(c2.L - c2.L));
        }

The line:

                c1.L + t*(c2.L - c2.L));

Should be:

                c1.L + t*(c2.L - c1.L));

I've never done a pull request before, I'll look into it and see if I can start the process for this change.

**Comment by toore** [comment]
This is merged, shouldn't we close this ticket?

**Comment by AristurtleDev** [comment]
> This is merged, shouldn't we close this ticket?

Yep, if issue was resolved in merge, ticket should have been closed.
