### ISSUE TITLE
Camera center

### ISSUE THREAD

**Issue by Sejsel** [craftworkgames/MonoGame.Extended#81]
I would love to have the ability to set the center of the camera.
This would allow simple implementation of a variable game resolution.

If the center was at the real center, increasing the game window would reveal content on all sides at the same rate, staying centered.

An example of what I mean I quickly put together (I apologize for poor quality):
http://gfycat.com/FaroffShrillDeviltasmanian

**Comment by craftworkgames** [comment]
Good idea.

**Comment by craftworkgames** [comment]
How would you imagine the API working for this?

**Comment by Sejsel** [comment]
I have been thinking about this for some time and still haven't figured out what the best way to do this would be.

What seems most sensible for me right now is to have a Center Vector2 property which would default to (0, 0). (0.5, 0.5) would act like the example I have linked above. (1, 1) would expand from the other corner.

This would not even have to be limited to the range [0, 1], having the center off-camera would work just fine.

The only way I can imagine this working is by transforming the camera by Center*ViewportSize.

This might not be the best way to do this, I just wasn't able to come up with anything better.
