### ISSUE TITLE
(question) vb.net

### ISSUE THREAD

**Issue by kiruhasas22** [craftworkgames/MonoGame.Extended#813]
MonoGame.Extended Works woth Visual Basic.net (vb.net)?

**Comment by Gandifil** [comment]
Yes.

Right now I have tried to build this [project ](https://github.com/AristurtleDev/monogame-visual-basic-example), then added Monogame.Extended in references and checked the camera features. All works correct.

I don't see reason the library doesn't work. It's usually .Net library, all .net languages must be supported.
