### ISSUE TITLE
WindowViewportAdapter

### ISSUE THREAD

**Issue by cupstudio** [craftworkgames/MonoGame.Extended#86]
I wanted to have a viewport adapter that would be based on the GameWindow so that as the window is resized you simply get more content instead of scaling the content.  I've [posted a video demo here](https://youtu.be/fNtnY-uymLI), let me know what you think.

WindowViewportAdapter:

    using Microsoft.Xna.Framework;
    using Microsoft.Xna.Framework.Graphics;
    using System;

    namespace MonoGame.Extended.ViewportAdapters
    {
    public class WindowViewportAdapter : ViewportAdapter
    {
        public WindowViewportAdapter(GameWindow window, GraphicsDevice graphicsDevice)
        {
            GraphicsDevice = graphicsDevice;
            Window = window;
            window.ClientSizeChanged += OnClientSizeChanged;
        }

        protected readonly GameWindow Window;
        protected GraphicsDevice GraphicsDevice;

        public override int ViewportWidth
        {
            get { return Window.ClientBounds.Width; }
        }
        public override int ViewportHeight
        {
            get { return Window.ClientBounds.Height; }
        }

        public override int VirtualWidth
        {
            get { return Window.ClientBounds.Width; }
        }

        public override int VirtualHeight
        {
            get { return Window.ClientBounds.Height; }
        }

        public override Matrix GetScaleMatrix()
        {
            return Matrix.Identity;
        }

        private void OnClientSizeChanged(object sender, EventArgs eventArgs)
        {
            var x = Window.ClientBounds.Width;
            var y = Window.ClientBounds.Height;

            GraphicsDevice.Viewport = new Viewport(0, 0, x, y);
        }

    }
}

**Comment by craftworkgames** [comment]
Isn't this the same behavior as the `DefaultViewportAdapter`?

Are you using MonoGame DX or GL? I do recall an issue with the DX version causing some issues with the viewport adapters. Maybe the `DefaultViewportAdapter` is not working for you as intended?

**Comment by cupstudio** [comment]
Ah sorry, not sure how I missed that.  That is literally the only one I didn't look at but I'm not sure why.  Sorry about that!  One of the things I try to keep in mind is not to add extra work for people by messing things up.  :smile:

**Comment by craftworkgames** [comment]
No problem. It's an easy enough mistake.
