### ISSUE TITLE
NullpointerException in TiledMapProperties

### ISSUE THREAD

**Issue by Lutz89** [craftworkgames/MonoGame.Extended#901]
Hey @AristurtleDev 👋 

There is an error in the implementation of the TryGetValue method in the TiledMapProperties class, which leads to a NullpointerException.

The assignment of the return value must be changed from
`value = result ? null : tmpVal.Value;`
To 
`value = result ? tmpVal.Value : null;`

Cheers,
Lutz

**Comment by AristurtleDev** [comment]
Thanks @Lutz89

**Comment by AristurtleDev** [comment]
Resolved in #903
