### ISSUE TITLE
Main page link to docs leads to a Page Not Found

### ISSUE THREAD

**Issue by vchelaru** [craftworkgames/MonoGame.Extended#902]
![image](https://github.com/craftworkgames/MonoGame.Extended/assets/729631/b9b2a5b0-6271-4001-a7e8-2e372a3b969e)

leads to...

![image](https://github.com/craftworkgames/MonoGame.Extended/assets/729631/7b3a8840-4544-479a-bfc8-6c7e7957596f)

It should go to the Docs link

**Comment by DecidedlyHuman** [comment]
The same happens with the link to the old documentation. Specifically [this link](http://craftworkgames.github.io/MonoGame.Extended/) from [https://github.com/craftworkgames/MonoGame.Extended/wiki](https://github.com/craftworkgames/MonoGame.Extended/wiki).
