### ISSUE TITLE
Update README to include v0.4 features

### ISSUE THREAD

**Issue by WardBenjamin** [craftworkgames/MonoGame.Extended#91]
I actually don't know the complete list of what's been added, but none of it is documented in the readme along with the stuff from v.2 and v.3.

**Comment by craftworkgames** [comment]
Good point. I did write a short [blog post](http://dylanwilson.net/monogame-extended-v0-4-release-notes) about the 0.4 release.

To be honest I kind of lost track of what make it into 0.4, so there might be a few other things. I guess we could check the commits.

**Comment by craftworkgames** [comment]
Done.
