### ISSUE TITLE
BitmapFont - "This does not appear to be a valid BMFont file!"

### ISSUE THREAD

**Issue by tigurx** [craftworkgames/MonoGame.Extended#910]
I pulled the latest changes for the development branch earlier which included the recent changes for the Bitmap Fonts. I am running into an issue with my XML exported BitmapFont not loading correctly. This font file was exported from 64bit Angelcode BMFont 1.14a.

**I created two test projects:**
https://github.com/tigurx/TestBitmapFont -- This project targets MonoGame.Extended (3.9.0-prerelease.7) -- This works as expected. You may need to change the reference for the content pipeline in MGCB to not point to my local .nuget directory.

https://github.com/tigurx/TestBitmapFontDevelop -- Targeting the current develop build cloned from GIT. I added the DLL's built into the main directory of this project. This version gets the error "This does not appear to be a valid BMFont file". 

**BitmapFont Cascadia 27pt:**
[BitmapFont.zip](https://github.com/user-attachments/files/16121113/BitmapFont.zip)

![bitmap_font_error_1](https://github.com/craftworkgames/MonoGame.Extended/assets/16768537/424ee9cd-003b-4f76-84d6-4ec2db4a295b)
![bitmap_font_error_2](https://github.com/craftworkgames/MonoGame.Extended/assets/16768537/b8b2647f-8910-46e3-a4ee-a4da039aaace)
![bitmap_font_error_3](https://github.com/craftworkgames/MonoGame.Extended/assets/16768537/af9c4fc8-01b4-469b-be96-4e6a34d7228a)

**Comment by tigurx** [comment]
This seems to be resolved in the v4.0 release as well as in the develop branch.

**Comment by AristurtleDev** [comment]
Thanks for confirming @tigurx
