### ISSUE TITLE
Let's use C# 6.0 (any complaints?)

### ISSUE THREAD

**Issue by craftworkgames** [craftworkgames/MonoGame.Extended#93]
How does everyone feel about upgrading the project to C# 6.0 syntax?

I've kept the project in C# 5.0 syntax so that people using Visual Studio 2013 are about to build it from 
source.

Basically, I have my Resharper settings configured so that the project is forced to C# 5.0 syntax and fails to build if someone merges C# 6.0 syntax code. This is kind of annoying because there's no way to enforce it with vanilla VS. 

Also, we are obviously missing out on many of the nice C# 6.0 syntax features. That makes the code a lot more verbose.

If there's no complaints about this in the next week or so, I'd like to start using C# 6.0.

**Comment by WardBenjamin** [comment]
Sounds good to me!

**Comment by cupstudio** [comment]
Yay!

**Comment by craftworkgames** [comment]
Cool. I've started doing this.
