### ISSUE TITLE
ParticleSystem Loading with FromFile StackOverflowException 

### ISSUE THREAD

**Issue by jeffgamedev** [craftworkgames/MonoGame.Extended#936]
Calling the `ParticleEffect.FromFile` method results in a StackOverflowException.

Code: 

`ParticleEffect.FromFile(_textureRegionService, "Content/particles/myparticle.particles");`

Result:

`Exception has occurred: CLR/System.StackOverflowException
An unhandled exception of type 'System.StackOverflowException' occurred in System.Text.Json.dll`

I wrote a small unit test and was able to recreate the issue in MonoGameExtended project, and then I rolled back to before the commit where Newtonsoft.Json was removed from the project.

https://github.com/craftworkgames/MonoGame.Extended/commit/d008b1bd4104be237a156a15a46e5e11353bc262

The particle began loading properly again at before this refactor.

Here is the body of a simple particle effect for testing:

```
{
  "autoTrigger": true,
  "autoTriggerDelay": 0.0,
  "emitters": [
    {
      "name": "emitter2",
      "offset": "0 0",
      "modifiers": [],
      "profile": {
        "type": "Point"
      },
      "parameters": {
        "quantity": [1,1],
        "speed": [89.0,155.0],
        "color": ["#556b2fff","#936fdbff"],
        "opacity": [0.0,0.1],
        "scale": [1.0,6.0],
        "rotation": [-1.57079637,1.57079637],
        "mass": [1.0,1.0]
      },
      "textureRegion": "square03",
      "modifierExecutionStrategy": "Serial",
      "capacity": 1000,
      "lifeSpan": 1.0
    }
  ],
  "position": "468.5 381.5",
  "rotation": 0.0,
  "scale": "1 1"
}

**Comment by AristurtleDev** [comment]
Resolved in #938
