### ISSUE TITLE
Setup errors, failed to find the file specified, no importer/processor

### ISSUE THREAD

**Issue by NickFall** [craftworkgames/MonoGame.Extended#956]
Hi
I'm following the setup guide [here](https://www.monogameextended.net/docs/getting-started/installation-monogame/#optional-setup-mgcb-editor) setting up 4.0.3 in VS2022 installed from NuGet, with MonoGame 3.8.2.1105 on .NET 8.0.
If I follow the instructions to a T, the MGCB Editor crashes the moment I click OK in the final step. 
Here's the full vomit (sorry there's a lot of it):

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MonoGame.Tools.Pipeline.PipelineTypes.ResolveAssemblies(IEnumerable`1 assemblyPaths) in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Common\PipelineTypes.cs:line 436
   at MonoGame.Tools.Pipeline.PipelineTypes.Load(PipelineProject project) in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Common\PipelineTypes.cs:line 253
   at MonoGame.Tools.Pipeline.PipelineController.ResolveTypes() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Common\PipelineController.cs:line 927
   at MonoGame.Tools.Pipeline.PipelineController.OnReferencesModified() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Common\PipelineController.cs:line 136
   at MonoGame.Tools.Pipeline.CellRefs.Edit(PixelLayout control) in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Controls\PropertyCells\CellRefs.cs:line 40
   at MonoGame.Tools.Pipeline.PropertyGridTable.<Drawable_MouseUp>b__29_0() in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Controls\PropertyGridTable.cs:line 238
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Eto.Wpf.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at MonoGame.Tools.Pipeline.Program.Main(String[] args) in D:\a\MonoGame\MonoGame\Tools\MonoGame.Content.Builder.Editor\Program.cs:line 71
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoGame.Framework.Content.Pipeline, Version=3.8.2.1105, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

If I instead select the dll installed to the .nuget directory (of course MGCB Editor decides to derive a relative path within Content.mgcb, though looking at past issues this should (?) no longer be an issue) then it doesn't crash immediately but doesn't show any MonoGame.Extended entries in the Importer or Processor dropdowns for things like .tmx files.
I realise this may well be more a MonoGame problem than a MonoGame.Extended problem, but any light you could shed on the issue would be much appreciated.

**Comment by NickFall** [comment]
Downgrading to 4.0.0 (also installed through Nuget) appears to resolve the above issue. Should've said "except I changed the version" rather than "to a T" 😅

**Comment by AristurtleDev** [comment]
@NickFall Can you check which version of the MGCB Editor is/was being used when you were on the 4.0.3? I ask becuase the current MonoGame setup guide for Visual Studio 2022 has the users install the VS2022 MonoGame Extension.  Currently this extension installs the MonoGame 3.8.1.303 templates, which means when creating a new project the dotnet-tools.json manifest file will have the 3.8.1.303 tools listed and not the current 3.8.2.1105.


So if you could check
1. What version of the MGCB Editor is being used by clicking Help > About in the MGCB Editor
2. Alternatively, in your project directory open the `.config/dotnet-tools.json` manifest file and see which version of the tools it ahs listed.

**Comment by NickFall** [comment]
@AristurtleDev .config/dotnet-tools.json does indeed have 3.8.1.303 listed! When looking at the error output I saw it was going after 3.8.2.1105 so thought updating through Nuget would update whatever I was using, not the case apparently. 
Thanks for taking a look 👍

**Comment by AristurtleDev** [comment]
Assuming this was resolved from updating the tools. Going to close the issue. If still not resolve, please reopen @NickFall .
