### ISSUE TITLE
I purpose a change to IMoveable

### ISSUE THREAD

**Issue by stromkos** [craftworkgames/MonoGame.Extended#99]
I purpose that:
IMoveable  should be renamed IPosition and IMovable should derive from IPosition and contain a Vector2 Velocity.

Rational:
Any drawable or collidable object has a position. A movable object must have a velocity(even if it can be zero).

**Comment by craftworkgames** [comment]
Technically to be consistent with `IRotatable` and `IScalable` it should probably be called `IPositionable`. That's a [real word](http://www.thefreedictionary.com/positionable) right?

```
    public interface IPositionable
    {
        Vector2 Position { get; set; }
    }

    public interface IMovable : IPositionable
    {
        Vector2 Velocity { get; set; } // public setter? maybe not?
    }
```

Interesting idea. Not sure how I feel about it yet. I'll think about it.

**Comment by LithiumToast** [comment]
Also be nice if `IDraw` was renamed to `IDrawable` and `IUpdate` was renamed to `IUpdatable` to remain consistent with the naming of the interfaces. I understand that this would mean they have the same name as the interfaces `Microsoft.Xna.Framework.IUpdateable` and `Microsoft.Xna.Framework.IDrawable` but that's what namespaces are for :)

**Comment by LithiumToast** [comment]
I think just `IPosition` would be OK. Is there any cases where `IMovable` is useful?

**Comment by craftworkgames** [comment]
> Is there any cases where IMovable is useful?

Not within the library itself.

**Comment by cupstudio** [comment]
:+1:  for NOT public setters unless there is something in the framework that requires it.

**Comment by LithiumToast** [comment]
I think that interfaces should use adjectives as their names and classes should use nouns. Perhaps there is a better adjective to abstract the `Velocity` property than `Movable`? If not, maybe drop support for abstracting velocity with an interface all together.

**Comment by craftworkgames** [comment]
Okay. So I had a quick look. The only thing in MonoGame.Extended that has a `Velocity` property is the `IActorTarget` in the Collisions feature.

    public interface IActorTarget : IMovable, ICollidable
    {
        Vector2 Velocity { get; set; }
        void OnCollision(CollisionInfo collisionInfo);
    }

To be honest, I'm really not happy with how the whole Collisions feature is working. In light of the work being done in #74 and #105 I'm going to close this issue. If we have a need for this change in the future we'll do it then.
